### ISSUE TITLE
CSS clash of class "tree"

### ISSUE THREAD

**Issue by opitz** [maths/moodle-qtype_stack#1000]
The current CSS implementation of the "tree" class is very generic and clashes with another plugin (block_sharing_cart) thereby destroying the list view there (see example below).
Please consider a less generic class name or CSS implementation.

<img width="298" alt="Screenshot 2023-07-28 at 11 00 52" src="https://github.com/maths/moodle-qtype_stack/assets/5082491/b83e337a-fa4a-45eb-8d1c-baf0615ee59a">

**Comment by sangwinc** [comment]
Oh dear - I did wonder about that at the time!

I assume you'll raise the issue with (block_sharing_cart) as well?!  There is a symmetry to the problem.... ;-)

**Comment by opitz** [comment]
Hi Chris,
Thanks for the quick response.
block_sharing_cart does already a good job in hedging the "tree" class inside a "block_sharing_cart" class so it should not show side effects elsewhere (https://github.com/donhinkelman/moodle-block_sharing_cart/blob/master/custom.css).

**Comment by sangwinc** [comment]
Thanks for replying to issue #1016  pointing out the duplicate.  I'm happy to change the CSS style name to something else than "algebratree" is people make suggestions.  However, I'd like this style to be available outside the qtype_stack plugin components. I can easily see teacher who use this style within questions also using this style elsewhere, such as blog posts and materials.  I'm planning to use these within description questions (where we often put materials).

**Comment by berardin** [comment]
Hi everybody,

thanks you for the prompt fix.
May I ask when will the patch release?
I don't see right now in the tags a version with the Patch merged.

Thanks you

**Comment by sangwinc** [comment]
It's about half a days work to release STACK. I'd like to finish off a couple of other things before I make an official release if that's ok?

**Comment by berardin** [comment]
for sue, I was just wondering if I missed the right tag since there was already a fix for the Layout.

Thank you for your great work!
