### ISSUE TITLE
extra packages/libraries

### ISSUE THREAD

**Issue by sdirnboeck** [maths/moodle-qtype_stack#1002]
Hello everyone!

I was wondering if it is possible to make self written libraries accessible in all of STACK? ie. if it possible to have access to a set of (self-written) functions no matter which course or question one is currently in/editing? 

One way we would like to use it is to randomly generate matrices with certain properties. We are currently already doing this with a maple based system and are wondering if this is also possible in STACK. 

Thank you very much in advance!

**Comment by sangwinc** [comment]
Yes, please see
https://docs.stack-assessment.org/en/Authoring/Inclusions/#inclusions-within-cas-logic

If you create a useful library please contribute it back!  Also, if you are interested in randomly generated matrices this paper might be useful.
[SteeleLinAlg.pdf](https://github.com/maths/moodle-qtype_stack/files/12227496/SteeleLinAlg.pdf)

**Comment by aharjula** [comment]
Yes, there even exist two different ways with different types of problems and usage issues. For those that have not thought about this, the primary issue with all inclusions of code that is not part of the question or the system is that when exporting questions, that code will not travel with the question and importing becomes a hassle if that code is missing. Assuming that this is something that does not matter, then there are two options:

 1. For inclusion into every single STACK material on the site, one can add Maxima code into the [`local.mac`](https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/local.mac) file. This is a relatively efficient way of doing things, but it will most definitely be difficult to update and transfer. This route is not recommended, but there are certain use cases where one might want to use this.
 2. The newer and simpler-to-use way is the one that Chris linked above. That allows one to pick exactly what to load and load it only into specific questions. However, it is less efficient, and one should avoid loading extra stuff into a question as every bit loaded will use resources and slows things down. It is recommended that should one use this method, one would segment one's libraries into small files and load only the bits one needs.
 
One example of a shared library that uses that latter method for inclusion is [Meclib](https://github.com/mkraska/meclib). It uses inclusions in both the logic portion and the presentation (CASText) side of the question.

**Comment by sdirnboeck** [comment]
Thank you both for your quick and very helpful answers!
