### ISSUE TITLE
Feature request: Delete all selected variants

### ISSUE THREAD

**Issue by LukeLongworth** [maths/moodle-qtype_stack#1003]
My apologies if this is in another issue that I didn't spot when searching. 

I frequently want to delete several variants at once (e.g. just now I wanted to delete every variant of a question that had a 3-digit constant term in a polynomial) and the refresh - followed by the very slow MathJax rendering - after every delete action makes the process take a very long time. Ideally we could put a checkbox by each seed and then just select the ones we want. This could be used for a "delete all selected" but could also be used for other things like "run question tests on all selected" if that was useful at all. 

In general I want to avoid the constant moodle page-refreshes as much as possible, but I understand that we probably don't have any say in this. Similar examples would be "Add n nodes to PRT" or "Delete selected PRT nodes", or a "Save changes, preview, and keep editing" button.

**Comment by sangwinc** [comment]
Luke,
This is a very sensible suggestion.  To achieve this with the current system (relatively recent version) you can "Remove variants and redeploy from a list".  See the attached image.  In this example I've removed all seeds where the number in the sqrt is odd.  

This feature was added to enable "variant matching"
https://docs.stack-assessment.org/en/Moodle/Variant_matching/
but it will also solve your problem.

If you want to add a checkbox to each line in the notes table, then the code _starts_ here
https://github.com/maths/moodle-qtype_stack/blob/master/questiontestrun.php#L292

Then you could do something with the selection.  That all requires more logic in the questiontestrun.php page which is already very complicated!  I'm not planning to add this logic so I'll close the issue.   Please talk with colleagues in the Professionals Network, and if you agree on a design we can ask Edmund to work on this (once the export questions to git) is completed.

Chris
<img width="697" alt="redeploy" src="https://github.com/maths/moodle-qtype_stack/assets/781615/a92321cc-b10f-4d37-abcf-a08b03b683ab">
