### ISSUE TITLE
Bringing Datasets into STACK

### ISSUE THREAD

**Issue by fowal44p** [maths/moodle-qtype_stack#1005]
Hi STACK community, 

I am a statistics lecturer at a university in New Zealand, and we are looking to migrate all our statistics questions from our own learning management system into STACK. 

Many of our assignment questions require students to download datasets that are randomly assigned to each student, and then do statistical analysis (e.g. hypothesis tests, regression analysis, etc) on the data they’re given in R.

I have read https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/Serving_out_data.md for the documented approaches for how to do this. But all seem to require the data to be generated in STACK.
What I was wondering was
Q1: Whether it is possible to bring datasets created outside STACK into STACK questions, and then randomly assign a dataset to students from within STACK?
The main reason for wanting to do this that we have already created and validated suitable data files for our assignment questions, that we use on our own current learning management system. Needing to recreate the files in STACK would require us to recreate the data files and revalidate that the datasets we create meet our requirements (e.g. that the data is approximately normally distributed). It also has the massive advantage of meaning real-world applied datasets can be brought into STACK. Or
Q2: Is there a way of bringing real-world data files in from STACK, but then randomly allocating different versions of that data to students? From reading Maxima documentation, I understand that the descriptive Maxima package (which is supported by STACK) can extract subsamples from particular datasets, but have no idea how to implement this as yet.
 
A couple of side questions that relate to Q1 above:
Q3: What could be quite handy would be to be able to compute the values of variables relating to each dataset (e.g. test statistics, regression slope parameters, etc) outside of STACK, and then bring these pre-computed values into the question variables field in STACK, and then use these pre-computed values to validate that student answers are correct for the specific dataset they were given. This is how our current learning management system works. 
Could this be done? 
The advantages to this are that it would save having to bring each dataset into STACK for student's answers to be evaluated, and it would also mean we could compute variable values (e.g. test statistics, regression slope parameters, etc) in a more powerful language than Maxima (e.g. for writing statistics questions as we are, R would be much preferred).
Q4: If we need to bring the files into STACK to evaluate student answers (as opposed to evaluating everything outside STACK, as proposed in Q3), from reading Maxima documentation I understand that the numericalio package can read in text file datasets into STACK, but that this package is not currently supported in STACK. When I spoke to Chris (Sangwin) about this, he mentioned that numericalio could be added as a supported package if there was enough demand for it. So, does anyone else think that this functionality that numericalio provides (reading in external .txt files) could be helpful for them? Given the ability it could allow to bring in real-world datasets I'm thinking it would be helpful.

Looking forward to discussing.
Alex

**Comment by smborio** [comment]
Hi Alex,

Firstly, I would recommend you post this type of questions in the [STACK Community forum](https://stack-assessment.zulipchat.com).

Secondly, I am currently working on questions very similar to what you are describing. I would be happy to discuss your questions through a call (smborio@idems.international) or through the community chat. We have a few sample questions of using external data sets in interesting ways, carefully generating data sets within STACK, and presenting visualisations of existing or generated data sets for analysis, within others.

All the best,

Santiago

**Comment by aharjula** [comment]
Making STACK itself read any dataset from the outside world into the CAS is not going to work. We do not allow such external connections from the CAS and never will. Whether you modify your own installation to allow them is naturally your own choice, but I can already say that for security reasons such capabilities will not become a part of the release version. You can always copy data into the question variables, but it is not meant for large datasets and may become quite slow if one does not use some form of procedural generation logic. But the following will work and should match most people's first ideas, including what you described:

```
/* In question variables:*/
/* Each set defines the tans values and the set id, could include plenty of other things as well. */
datasets: [
 ["set0", 2.33, 0.98],
 ["set1", 2.13, 0.98],
 ["set2", 2.23, 0.38],
 ["set3", -2.33, 0.78]
];

/* Pick one set for this student. */
[setname, tans1, tans2] : rand(datasets);
```

Then in the question text, depending on the set name, link to wherever that data is and to anything else related to the dataset:

```
....
[[if test='setname="set0"']]
<a href="https://whereever.nz/coursedata/set0/data.csv">Get your data from here.</a>
[[elif test='setname="set1"']]
....
[[/if]]
....
```

Naturally, with suitable naming, you do not need such an if-structure and can simply have:
```
<a href="https://whereever.nz/coursedata/{#setname#}/data.csv">Get your data from here.</a>
```

All the problems related to maintaining questions with externally linked resources naturally apply here. But if one really wants and the number of sets is small one can actually attach the files into the question and use that if-structure to show only the bits that are relevant.
