### ISSUE TITLE
Deleting and adding PRTs in the same question version still grades assuming original PRT not deleted

### ISSUE THREAD

**Issue by LukeLongworth** [maths/moodle-qtype_stack#1006]
We are running STACK 2022082900.

If I have an existing question (v1) with one PRT, prt1, and I decide that I want to split this into two PRTs, prtA and prtB, then upon the _first_ instance of saving this updated question (v2), STACK thinks that prtA and prtB both contribute 1/3 of the total question marks, meaning that the maximum mark for (v2) is 0.67/1.00, even though prt1 no longer exists. If I then change absolutely nothing, but click save a second time, the new version (v3) will mark correctly, assuming that both prtA and prtB are worth 1/2 of the total question marks. 

This causes problems at the quiz level because students cannot get 100%. This is difficult to catch when checking a question because it shows up as all correct at a glance, with the only hint that something is wrong appearing when you see that you have only been awarded 0.67/1.00. This is also in the quiz itself; if you preview the question it will show as 1.00/1.00 and the only clue is in the PRT feedback! Question tests don't help here, because all existing question tests break in this instance (the PRT they are referencing no longer exists), and if you update the question tests it shows as totally fine because they only check the PRT results, not the total grade for the question. 

Here is a lot of screenshots. Hopefully they are follow-able!
![Missing PRT 6](https://github.com/maths/moodle-qtype_stack/assets/34358809/0a8e175f-dbda-4f0d-91c8-6d23f49f73bd)
![Missing PRT 7](https://github.com/maths/moodle-qtype_stack/assets/34358809/d76cf143-5778-4f5b-85a2-e5b55409ed76)
![Missing PRT 8](https://github.com/maths/moodle-qtype_stack/assets/34358809/2351b8b0-a160-4288-963b-9c87da93b4c0)
![Missing PRT 9](https://github.com/maths/moodle-qtype_stack/assets/34358809/ed03fe01-82be-4871-a5f4-ddc24010fad5)
![Missing PRT 10](https://github.com/maths/moodle-qtype_stack/assets/34358809/a8fb1d24-da73-44bb-891e-1734f416f48a)
![Missing PRT 11](https://github.com/maths/moodle-qtype_stack/assets/34358809/7f12c287-a59b-4e1f-a09f-799d534776f5)
![Missing PRT 12](https://github.com/maths/moodle-qtype_stack/assets/34358809/6b8ec6f2-7b9e-4e70-a7bd-b193427ff3c7)
![Missing PRT 13](https://github.com/maths/moodle-qtype_stack/assets/34358809/d40aacd4-4f2f-4c0d-830a-fc9a290e117a)
![Missing PRT 14](https://github.com/maths/moodle-qtype_stack/assets/34358809/f6fa7fb5-adf9-4612-b994-4a2805f37e43)
![Missing PRT 15](https://github.com/maths/moodle-qtype_stack/assets/34358809/726c786f-64ff-408d-948c-6ccacbeee75c)
![Missing PRT 16](https://github.com/maths/moodle-qtype_stack/assets/34358809/c1e2adeb-09f8-471b-8f68-991ca70240f9)
![Missing PRT 17](https://github.com/maths/moodle-qtype_stack/assets/34358809/f4c7197b-e882-477c-8ca3-b22b52e0319a)
![Missing PRT 18](https://github.com/maths/moodle-qtype_stack/assets/34358809/7a949292-907c-4aec-aa9f-9474b857a3c4)
![Missing PRT 19](https://github.com/maths/moodle-qtype_stack/assets/34358809/21d00392-6552-483d-8c52-f3862af32ec8)

**Comment by sangwinc** [comment]
Thanks for reporting this Luke, and sorry about this edge case!

Just to be clear: saving the question again (v3) means the later version works correctly?

**Comment by LukeLongworth** [comment]
Hi Chris,

Yes, saving a new version seems to fix it, even when no changes have been made. 

Cheers,
Luke

**Comment by LukeLongworth** [comment]
It looks like this is fixed by 4.4.6, as I cannot recreate it on our test site that runs 4.4.6.
