### ISSUE TITLE
Docu Update

### ISSUE THREAD

**Issue by nisaDoc** [maths/moodle-qtype_stack#1009]
Hello,
since the [[jsxgraph]] was replaced, I am not sure that the docu for jsxgraph is still uptodate. In this docu you are still using the jsxgraph block: https://docs.stack-assessment.org/en/Authoring/JSXGraph/
and is the any info, what is the replacement for jsxgraph?
Thx

Cheers,
Nisa

**Comment by sangwinc** [comment]
The jsxgraph block still works, and I think the docs are correct!
