### ISSUE TITLE
Expected score test: round-off mismatch

### ISSUE THREAD

**Issue by chigle** [maths/moodle-qtype_stack#1015]
Apologies for a possible duplication or misinterpretation. After a recent upgrade (to STACK 4.4.4/2023060500; Moodle 4.1.4; Maxima 5.41.0), some questions with fine-grained PRT sub-scoring fail to produce accurate net scores and report errors in question tests. I believe the issue originates from rounding individual PRT scores to 3 significant figures, while requiring 5 figures to match the expected score and 7 decimal points for internal calculations. Please see the code extracts below. 

Many thanks in advance for looking into this.

_/db/install.xml_
```
DECIMALS="7" COMMENT="The maximum score this PRT can contribute to the question."
```

_/stack/questiontestresult.php_
``` 
// Single PRTs only work to three decimal places, so we only expect that level.
$state->expectedscore = round($state->expectedscore + 0, 3);
```
```
if ( is_null($state->expectedscore) != is_null($state->score) || abs($state->expectedscore - $state->score) > 10E-6 ) {
  $state->testoutcome = false; $reason[] = stack_string('score');
}
```
Example:
![image](https://github.com/maths/moodle-qtype_stack/assets/16074082/6c383163-81a1-4b3a-92f9-49389fc8cc90)

**Comment by sangwinc** [comment]
That's now fixed.  Sorry for the delay in fixing this, but thanks for reporting it.

**Comment by chigle** [comment]
Thanks a lot!
