### ISSUE TITLE
The CSS Style of .tree ul breaks down other plugin's layout

### ISSUE THREAD

**Issue by berardin** [maths/moodle-qtype_stack#1016]
Hi everyone!

As soon as I installed the qtype_stack plugin, other plugin's layout were corrupted.
As I saw in the style.css there is the block about the class .tree which is used from other plugin as well.

Is here maybe better to create a new class which will be used just from the qtype_stack plugin?

Thanks.

**Comment by sangwinc** [comment]
I decided not to use "qtype_stack" in the name as this part of the CSS is something more generally useful outside STACK, and something which could be very useful in blog posts, discussions etc.  I wanted something a human can type.
