### ISSUE TITLE
Timeout errors not reported very nicely.

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#1024]
You can reproduce this by creating a qusetion like this (everything else default).

* Question name: Timeout test
* Question variables: `for i: 1 while i > 0 do s: s+i;` /* This is the key bit */
* Input ans1 -> Model answer 1
* PRT1 -> Note 1 -> SAns: ans1
* PRT1 -> Note 2 -> Tans: 1

Click Save changes.

On our live server, using goemaxima, we get
![a5b03fed-f009-4e69-a14d-8460468f8a84](https://github.com/maths/moodle-qtype_stack/assets/138653/8b2d9c99-96a2-4e65-833a-127fa96394e7)

Using the the older MaximaPool, we get
![image](https://github.com/maths/moodle-qtype_stack/assets/138653/28425094-4e1f-4d03-a966-c7daef2fd367)

(I have not tried stand-alone Linux or Windows yet.

In any case, none of this looks very pretty, so I was wondering if we could, or should, improve it?

**Comment by sangwinc** [comment]
Yes, the original idea was to give as much information back to the user as possible to help track down the error.  However, I agree that's really ugly and should be replaced with a basic error message.  Thanks for the suggestion.
