### ISSUE TITLE
Ans-test and "a correct answer is" with UnitsStrictSigFigs

### ISSUE THREAD

**Issue by Bjoern-Ge** [maths/moodle-qtype_stack#1028]
When I use UnitsStrictSigFigs like this:

tans1: stackunits(1.60*10^-19,C) ;

tested like this
ATUnitsStrict(ans1,tans1,ev(3,simp),stackmap_get_ifexists(_INPUT_STRING,"ans1")) |  

The correct answer is shown like:
1.6*10^-19*C
and the "typed in as" is:
(1.6*10^-19)*C

Is there a possibility that it is shown as
the correct answer is 
1.60x10^-19 C 
and the "can be typed in as follows:" 
(1.60*10^-19)*C

**Comment by sangwinc** [comment]
Yes, you need to protect the decimal places in the numerical part.  For example, define two variables.

tans1: stackunits(dispsf(1.60,3)*10^-19,C);
tansv1: stackunits(1.60*10^-19,C);

Use "tans1" when you want to show the students the answer.  The "dispsf(1.60,3)" means treat this as a number with three significant figures.  Without this maxima will just simplify 1.60 to 1.6, which is the problem you reported.

Then use "tansv1" in the PRT.

There is a bug in the code which automatically removed dispsf within the answer test, so you need two variables for now.  I'll fix this bug, (sorry!).
