### ISSUE TITLE
Problem with extra option `rationalnum` for Numerical input type

### ISSUE THREAD

**Issue by jonaslache** [maths/moodle-qtype_stack#1029]
Hi there,

I have a problem in my STACK question where I am using the numeric input type with the extra option `rationalnum`. Basically, the extra option does not do what the [docs](https://docs.stack-assessment.org/en/Authoring/Numerical_input/#options) suggest: When using the option, any input that is not a rational number as judged by the `rational_numberp` function should be flagged as invalid. However, when I type in expressions like `1.1`, `-1`, or `%pi` (numbers that `rational_numberp` says are not rational), the input is still considered valid.

I got around this problem by writing a simple validator function:

```
validate_rationalnum(ex) := if rational_numberp(ex) then "" else "Your answer must be a rational number.";
```

Is this a bug or am I doing something wrong?

Many thanks,
Jonas

**Comment by sangwinc** [comment]
Jonas,
That's an embarrassingly obvious bug which has been there for 4 years!
https://github.com/maths/moodle-qtype_stack/blame/dev/stack/input/inputbase.class.php#L1021
Sorry about that. I'm glad there is an immediate work around.  I'll fix this for the next release.  Thanks for reporting it.  Clearly this is not a popular feature!
Chris

**Comment by jonaslache** [comment]
Alright, thank you!
