### ISSUE TITLE
A question mark is not permitted in a string answer

### ISSUE THREAD

**Issue by impemic** [maths/moodle-qtype_stack#1030]
I am working with cryptography and I am writing a question whose answer is a string with characters in ASCII 32 -> ASCII 126.
Then sometimes a question mark is in the answer. I get the error:
"This answer is invalid. Your answer contains question mark characters, ?, which are not permitted in answers. You should replace these with a specific value."
But I need the question mark in text: how can I resolve the issue? Thanks
![2023-09-29_100539](https://github.com/maths/moodle-qtype_stack/assets/56223576/167f855c-9ce2-4d51-bbce-2619c61fffc5)

**Comment by aharjula** [comment]
@sangwinc could we just remove the old string tests from the [inputbase](https://github.com/maths/moodle-qtype_stack/blob/4737dc541f635df5889c5c566e794aff1b161cc1/stack/input/inputbase.class.php#L815-L819) after all the context-aware check that knows when it is used as an operator has happened in the security filter for quite some time now...

After all this nor any other character-based checks should affect anything inside strings.

**Comment by sangwinc** [comment]
Yes, @aharjula, this "todo" is long overdue resolving...
https://github.com/maths/moodle-qtype_stack/blob/dev/stack/input/inputbase.class.php#L814
Leave this with me and I'll fix it.
