### ISSUE TITLE
Language issue, "a correct answer" vs. "the correct answer" and how we really cannot figure out which applies

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#1034]
People on a field/subject where most questions only have one correct answer noted a localisation issue of a particular message related to the display of the teacher's answer, tracing that I found out that the original string translates perfectly correctly to the equivalent string in that other language but that form in that language is more explicit in its meaning and makes one think that there really are multiple correct answers even to the question that surely does not have many answers.

While in our world we often accept many answers, even equivalent answers in various forms, it is pretty common to have questions where there really is only one correct answer even when it could possibly be inputted in many ways it still is the only answer.

We (as in STACK, the system) cannot really identify when this is the case we may need to add an option for selecting between "a correct answer" and "the correct answer" alternatively we need to start using language that does not bring this up, e.g. say that this is the teacher's answer and skip noting whether it is one of many possible ones.

Basically, these strings cause issues:
```
$string['teacheranswershow']      = 'A correct answer is \( {$a->display} \), which can be typed in as follows: {$a->value}';
$string['teacheranswershow_disp'] = 'A correct answer is {$a->display}.';
```
It leads to silly wording like here.
![Screenshot from 2023-10-04 11-51-50](https://github.com/maths/moodle-qtype_stack/assets/980957/451d56c4-29af-4880-a3a2-602a3e433856)
Were we to ask for something with more real answer options like an odd function going through a given set of points, then that wording would make more sense. Similarly, if the wording points to a singular correct answer then that text in those types of questions would start looking silly.

If we were to separate these two cases so that on input by input basis we would declare if it is a case of "a singular correct answer" or not we could then apply different wording accordingly and the translations could better tone their wording to these versions. Translating the meaning here is difficult as the meaning might not be the meaning that the student expects, i.e. the student does not think about permutations of terms in equivalent answers instead they would think about actually different values. On the other hand who wants to declare that and who remebmers to do so is another matter and having yet another bit of settings in play for such a detail is questionable, so maybe we could consider wording it so that it cannot be interpereted to mean anything about the number of possible answers?

**Comment by christianp** [comment]
"The answer $3$, which can be typed as `3`, would be correct."

**Comment by aharjula** [comment]
Much better thank you, but I wonder if it works for the other end of the spectrum. Well, trying it is the best way to test that:
![Screenshot from 2023-10-04 13-49-12](https://github.com/maths/moodle-qtype_stack/assets/980957/f27051ad-1f49-49f7-ae0a-a3d89d78a73f)
It seems fine, even though now I get a feeling that this is "the answer", but that is not what the grammar says and grammatical correctness is enough. Will be interesting to see how that translates though.

**Comment by sangwinc** [comment]
Thanks @christianp, that's a really helpful improvement.
