### ISSUE TITLE
JSXGraph not loading for some students

### ISSUE THREAD

**Issue by georgekinnear** [maths/moodle-qtype_stack#1035]
I've had reports from three students (out of ~200 completing the latest quiz) that they could not see the graph in one question where I used JSXGraph.

From screenshots they have shared, all three students seem to be using Safari (two on MacBook Pro and one on an iPad).

Two students (one iPad one macbook) shared screenshots showing the space for the graph taken up with HTML code:
![image](https://github.com/maths/moodle-qtype_stack/assets/30723394/91e9756e-0ad7-49a7-8774-79808d85e5c2)

The other student simply had a blank space where the graph should be.

I'm wondering if this could be an issue with the new iframe implementation. I'm not sure what further information would be helpful to diagnose the issue.

**Comment by aharjula** [comment]
For me this works with Safari 16.6, so we need to figure out what Safari could be different. Alternatively, we should consider the possibility of Safari being more sensitive to something inside the plot. Could the plot itself contain some HTML fragments or such that could cause issues for parsing? Although those should not bubble up from within the JavaScript, but who knows....

**Comment by aharjula** [comment]
When you say that they could not see the graph in "one question", and that screenshot says that this broken one is "graph 2" then can I assume that it does otherwise work and the issue is somehow with this particular question?

**Comment by georgekinnear** [comment]
Thanks for the quick response. I've reached out to the students to ask for (1) their browser details and (2) which questions it's affecting.

One of the students had shared screenshots showing this issue in both JSXGraph questions in the test, so I'm leaning toward it not being an issue with particular questions.

**Comment by aharjula** [comment]
Just to make sure, this is a normal quiz without any safe exam browser-related extra limitation on top of it? It would be nice to know if these students can work around this by using some other browser.

Also are the students using their own machines and not some institutional/corporate machines with extreme security rules?

In any case, various browsers have various options that might cause issues:
 1. The case of a completely blank graph with only a blank space can easily be duplicated by disabling JavaScript. Given that these are **JS**Graphs that would obviously cause issues even without the new iframes.
 2. I have not been able to duplicate the screenshot though but I have a feeling that it might link to some form off an add-blocker or some other content filter, and thus knowing what the settings say at "Safari -> Settings -> Websites -> Content blockers" would be of some interest and maybe those having something there should add some exceptions for the university sites.

**Comment by georgekinnear** [comment]
Yes, it's a normal quiz with no safe exam browser setting.

I've heard back from two of the students now:

- The one with the blank space reports using version 13.1.2 (13609.3.5.1.5), and that the problem is with every graph - but reports other interactive applets do appear (I have some other embedded GeoGebra and H5P applets in this course). Mathjax is also rendering on the page - I can see from the "y=" in the question - so I think that rules out JavaScript being turned off, unless there is some way to selectively turn it off within iframes...
- The one with the HTML was using version 14.1.2 (14611.3.10.1.7) and has seen the problem in other quizzes so it's not just a particular quiz/question.

I have asked both students to check the content blocker settings, and to try another browser. I'll report back any updates!

**Comment by aharjula** [comment]
Ok. This is inconvenient but at least there is a solution, in the form of other browsers or updating their MacOs.

Now if we had access to a suitable number of Mac users who have not done the updates we could possibly find the exact point where Safari starts to work with these new iframes and give that as a requirement. But for now, we know it is between Safari 14.1.2 and 16.6. and being more accurate is pretty pointless.

14.1.2 is the MacOs Mojave era version for which Apple's support ended in 2021. 16.6.x which I have access to is the oldest one available on still supported MacOs releases, so I am pretty optimistic that anyone who can upgrade their MacOs to the currently supported versions can use their Safari.

**Comment by georgekinnear** [comment]
Just to complete the story here, the other student (using 13.1.2) had a content blocker turned on, and turning that off resolved the problem.

**Comment by sangwinc** [comment]
Thanks for following this up George, much appreciated.

**Comment by aharjula** [comment]
Thank you for the note about the content blocker note, that is really something that can happen now that the security logic separates the "potentially evil" from the page it really does not differ that much from advertisement systems separating the "more likely evil" adds from the page. Content blockers will therefore have a hard time detecting which is which.
