### ISSUE TITLE
MCQ (dropdown) with all options as correct answers

### ISSUE THREAD

**Issue by KZerva** [maths/moodle-qtype_stack#1039]
I have a STACK dropdown MCQ, in which all options are correct answers. The question is used for data collection reasons, asking the students which topic of the course they find more interesting, so there is no wrong answer really. This questions is used over 3 years now (with Moodle 3.9 and Moodle 4.1) and the latest STACK version, and I noticed that this question is failing to store the students answers. Is this because the question has no false option? The test cases don't indicate any issues. 

![image](https://github.com/maths/moodle-qtype_stack/assets/79198720/3f7d66a6-e054-41de-854e-463021f8e3ff)

**Comment by sangwinc** [comment]
I'm in JCMB - come and find me before 13:00 today and we'll track this down.

**Comment by sangwinc** [comment]
We've resolved this: it's an authoring issue when we run questions as surveys not a problem with STACK.
