### ISSUE TITLE
error message easy to miss when "tans" PRT node entry ends with semicolon

### ISSUE THREAD

**Issue by szegowitz** [maths/moodle-qtype_stack#1044]
Hi, I was wondering if it would be at all possible to display the error message more prominently in the case when a semicolon has (accidentally) been added to the "tans" PRT node? This would be really helpful :) At the moment it is easy to miss, and one might not notice that changes that were made to the question weren't saved. Thank you!

**Comment by sangwinc** [comment]
Good suggestion, thanks.
I'll add a general "please check below" error, but not with more specific location information which would be a lot of work.

**Comment by szegowitz** [comment]
Thank you. This will be very helpful.
