### ISSUE TITLE
[[lang]] works in question castext area but not in prt castext area

### ISSUE THREAD

**Issue by guidopinkernell** [maths/moodle-qtype_stack#1051]
[[lang]] block works nicely in question text area. In PRT castext it does not. It always shows the "en" tagged text whether the global language has been set to some other language or not.

**Comment by guidopinkernell** [comment]
Here is a test question:

question text:

`<p>
    This test needs next to the moodle English(en) language pack one of the German (de) or the Finnish (fi) language pack.
    <br><br>
</p>
<p>
    [[lang code="en,other"]] What is \(1 \cdot 1\) ? [[/lang]]<br>[[lang code='de']] Was ist \(1 \cdot 1\) ? [[/lang]]<br>
    [[lang code='fi']] Mikä on \(1 \cdot 1\) ? [[/lang]]
</p>

<p>[[input:ans1]] [[validation:ans1]]<br></p>`

prt1 text true

`[[lang code="en,other"]] true [[/lang]]<br>
[[lang code='de']] richtig [[/lang]]<br>
[[lang code='fi']] oikea [[/lang]]`

prt2 text wrong

`[[lang code="en,other"]] wrong [[/lang]]<br>
[[lang code='de']] falsch [[/lang]]<br>
[[lang code='fi']] väärä [[/lang]]`

**Comment by sangwinc** [comment]
I hope I've now fixed this, and issue #940.  I suspect we'll need to still do more work on STACK's [[lang]] block system, but I'm closing this issue for now.
