### ISSUE TITLE
AtAlgEquiv problem

### ISSUE THREAD

**Issue by lassikor** [maths/moodle-qtype_stack#1052]
Hi,
we encountered a problem where we weren't able to open a student's answer and a gateway timeout appeared. We found out that this problem was caused by the function ATAlgEquiv which was stalling and apparently it was waiting user's response. In this case TAns was inf and SAns was a complex number in an exponential form. There is a simple test case to reproduce the problem in the sandbox in the picture below.
![algequiv](https://github.com/maths/moodle-qtype_stack/assets/42375494/77be621c-d620-4fb3-9871-29a55be7666b)
The problem does not occur if the power is positive i.
The situation where student's answer is something as unexpected as in this case is unusual for sure, but not impossible as we just witnessed.  
BR
Lassi Korhonen

**Comment by sangwinc** [comment]
I'm going to start awarding prizes for people who break ATAlgEquiv in novel ways!   Sorry about this - the interactive mode of Maxima was an interesting innovation on the command line (try comparing int(x^n,x) on various CAS....) but it is confusing and problematic in general.  I'll try and sort this out...  Thanks for posting a clear test case to work against.

**Comment by lassikor** [comment]
Thank you for a very quick fix!
BR Lassi K.
