### ISSUE TITLE
Error in quiz task that runs in CRON. Task of Type: \quiz_statistics\task\recalculate

### ISSUE THREAD

**Issue by kirildevlion** [maths/moodle-qtype_stack#1053]
Error that we get:
```
Default exception handler: Unsupported operand types: float * string  הודעת שגיאה חריגה Debug:
Error code: generalexceptionmessage
* line 1064 of /question/type/stack/questiontype.php: TypeError thrown
* line 87 of /question/classes/statistics/responses/analyser.php: call to qtype_stack->get_possible_responses()
* line 802 of /mod/quiz/report/statistics/report.php: call to core_question\statistics\responses\analyser->__construct()
* line 772 of /mod/quiz/report/statistics/report.php: call to quiz_statistics_report->analyse_responses_for_questions()
* line 721 of /mod/quiz/report/statistics/report.php: call to quiz_statistics_report->analyse_responses_for_all_questions_and_subquestions()
* line 1003 of /mod/quiz/report/statistics/report.php: call to quiz_statistics_report->get_all_stats_and_analysis()
* line 94 of /mod/quiz/report/statistics/classes/task/recalculate.php: call to quiz_statistics_report->calculate_questions_stats_for_question_bank()
* line 8 of /test.php: call to quiz_statistics\task\recalculate->execute()

!!! Unsupported operand types: float * string  הודעת שגיאה חריגה !!!
!!
Error code: generalexceptionmessage !!
!! Stack trace: * line 1064 of /question/type/stack/questiontype.php: TypeError thrown
* line 87 of /question/classes/statistics/responses/analyser.php: call to qtype_stack-&gt;get_possible_responses()
* line 802 of /mod/quiz/report/statistics/report.php: call to core_question\statistics\responses\analyser-&gt;__construct()
* line 772 of /mod/quiz/report/statistics/report.php: call to quiz_statistics_report-&gt;analyse_responses_for_questions()
* line 721 of /mod/quiz/report/statistics/report.php: call to quiz_statistics_report-&gt;analyse_responses_for_all_questions_and_subquestions()
* line 1003 of /mod/quiz/report/statistics/report.php: call to quiz_statistics_report-&gt;get_all_stats_and_analysis()
* line 94 of /mod/quiz/report/statistics/classes/task/recalculate.php: call to quiz_statistics_report-&gt;calculate_questions_stats_for_question_bank()
* line 8 of /test.php: call to quiz_statistics\task\recalculate-&gt;execute()
 !!
```

The problem is in function  **get_possible_responses($questiondata)** 
When the question have strings parameters instead numbers:  falsescore and truescore have 'grade' instead numeric value 1 or 0

**Comment by sangwinc** [comment]
Sorry about this - can you please confirm which version of STACK and Moodle you are using?

**Comment by kirildevlion** [comment]
moodle 4.1.6

**Comment by sangwinc** [comment]
Thanks. can you please confirm which version of STACK you are using?  See below
https://docs.stack-assessment.org/en/Authoring/Author_FAQ/#which-version-of-stack-do-i-have

**Comment by kirildevlion** [comment]
$plugin->release   = '4.4.2 for Moodle 3.9+';
Sorry

**Comment by sangwinc** [comment]
Thanks for reporting this.  I wonder if you'd be willing to email me the question causing this problem.  I'm curious exactly what is going on here.

**Comment by lassnj** [comment]
Hi, 

thanks for the fix. We now get a different Error for the same Quiz/question. It seems to occur if there are some questions left unanswered:

```
Column 'credit' cannot be null
INSERT INTO oer_question_response_analysis (hashcode,whichtries,questionid,variant,subqid,aid,response,credit,timemodified) VALUES(?,?,?,?,?,?,?,?,?)
[array (
  0 => 'some hash value',
  1 => 'alltries',
  2 => '60797642',
  3 => 710265,
  4 => 'prt3-0',
  5 => NULL,
  6 => '[no answer]',
  7 => NULL,
  8 => 1703673939,
)]
```

Moodle 4.2.5 and STACK 4.5.0 for Moodle 3.9+ (2023121100)

Any idea how to fix this also? Thanks a lot.

Regards
Julia

**Comment by EJMFarrow** [comment]
Hi, does anyone still have a copy of the question they can send me? I'm so far unable to replicate the new issue.

Initial thought is to revert the fix and instead cast the strings to floats to return behaviour to pre-PHP8 and see if that fixes things. If not, this is a new issue.

**Comment by lassnj** [comment]
@EJMFarrow what should be stored in the column credit? Thanks!

**Comment by EJMFarrow** [comment]
Presumably it should be trying to store a score of 0 rather than NULL but without a copy of the question it's very hard to work out how this situation has arisen.

**Comment by EJMFarrow** [comment]
I couldn't recreate the exact issue with the CRON job but obtained the same DB error message via 'Show report' in 'Statistics calculation settings'. Reverting the fix and instead casting the strings to floats to return to pre-PHP8 behaviour does indeed fix things. I've also added a test which fails with the initial problem when run against the original code.
https://github.com/maths/moodle-qtype_stack/pull/1161
