### ISSUE TITLE
Bug in the syntax hint for a matrix input

### ISSUE THREAD

**Issue by tkokkone** [maths/moodle-qtype_stack#1057]
The syntax hint does not work for matrix inputs comprising more than one row. It works OK for the frist row, but not for the subsequent ones. E.g. if you have a 2x2 matrix input with the following syntax hint: matrix([1,2], [3,4]), the first row (1,2) will be filled in correctly, but the second one will remain empty. The cause for this appears to be the space character between  the rows. In the question editor in the preview mode providing the following syntax hint matrix([1,2],[3,4]) will result in desired behavior, but saving the question and exiting the question editor will re-insert the space character between the rows and hence when the students open the question the syntax hint will not work.

Applying an approriate trim here:

https://github.com/maths/moodle-qtype_stack/blob/f37adb831977898ef0877f5843e6ab954cd25b4e/stack/input/matrix/matrix.class.php#L162

might solve the problem.

**Comment by sangwinc** [comment]
That should be easy to fix.  Thanks for reporting it.  We can't use a parser here because we might deliberately want the syntax hint to be invalid!
