### ISSUE TITLE
Missing parentheses for negative factors when using "Only numbers" as multiplication sign

### ISSUE THREAD

**Issue by jknaut** [maths/moodle-qtype_stack#1060]
Hi,
when using "Only numbers" as multiplication sign, parentheses for negative factors are not displayed. This is confusing.
![grafik](https://github.com/maths/moodle-qtype_stack/assets/109731454/a93d519d-1948-495e-bbf2-6f831a2ec43d)

![grafik](https://github.com/maths/moodle-qtype_stack/assets/109731454/df82e1fd-ad36-4e53-aad7-99052a98ca06)

The same example using "None" as multiplication sign:
![grafik](https://github.com/maths/moodle-qtype_stack/assets/109731454/2151423a-ff20-42c6-959b-f56c48ec018a)

![grafik](https://github.com/maths/moodle-qtype_stack/assets/109731454/e67a4a82-72e2-4278-8eb7-09252e6ec0db)

#### Suggestion:
In the function `multsgnonlyfornumbers` (stackmaxima.mac): In the case of `safe_op(a)="-"` the subexpression `tex1(a)` should be wrapped in parentheses. Feedback is appreciated, I could contribute a pull request.

Best regards,
Johannes

**Comment by sangwinc** [comment]
That's very sensible, thanks for the suggestion. I also appreciate a reminder to the point in the code.
