### ISSUE TITLE
[[lang]] with STACK variables inside results in system error

### ISSUE THREAD

**Issue by guidopinkernell** [maths/moodle-qtype_stack#1065]
For validation, create this question first:

Question variables:

`var:rand(1);`

Question text:

`[[lang code="en,other"]] a random number [[/lang]]`

And after saving, replace "random number" with `{@var@}`.

Then save again. The system error "Call to a member function is_flat() on null" appears.

**Comment by sangwinc** [comment]
@guidopinkernell, sorry I can't reproduce that error in the "dev" branch of the code.  Can you email me your full question to Edinburgh and I'll check that as well?

**Comment by sangwinc** [comment]
Thanks for talking on Zoom today.  I think this issue is already fixed, and we'll reopen this again if needed when you've upgraded.
