### ISSUE TITLE
AlgEquiv problem with +- in equivalence reasoning

### ISSUE THREAD

**Issue by Mat-Ge** [maths/moodle-qtype_stack#1066]
ATAlgEquiv doesn't work if the arguments are lines of a ER-field and they contain #pm# respectively +-.
![grafik](https://github.com/maths/moodle-qtype_stack/assets/128398586/4088ffc2-475c-47eb-b82d-942fff14bf0c)

[AlgEquiv problem with +- in equivalence reasoning.xml.zip](https://github.com/maths/moodle-qtype_stack/files/13393100/AlgEquiv.problem.with.%2B-.in.equivalence.reasoning.xml.zip)

**Comment by sangwinc** [comment]
Thanks for reporting this, especially with such a clear example.  The fix will be in the next release which will come out before Christmas.  As an immediate work-around, try (untested by me) the following feedback variables

sa:map(pm_replace, ans1)

and use sa in the PRT.  This function replaces #pm#.  Beware, that if you have more than one #pm# then there is genuine ambiguity....
