### ISSUE TITLE
floor(): Argument #1 ($num) must be of type int|float, string given

### ISSUE THREAD

**Issue by daniil-berg** [maths/moodle-qtype_stack#1067]
I encountered the error message from the title of this issue, when trying to view a specific quiz attempt with the following stacktrace:

```
floor(): Argument #1 ($num) must be of type int|float, string given Debug:
Error code: generalexceptionmessage
* line 817 of /question/type/stack/stack/utils.class.php: TypeError thrown
* line 817 of /question/type/stack/stack/utils.class.php: call to floor()
* line 867 of /question/type/stack/stack/utils.class.php: call to stack_utils::rational_approximation()
* line 124 of /question/type/stack/stack/prt.evaluatable.class.php: call to stack_utils::fix_to_continued_fraction()
* line 167 of /question/type/stack/stack/prt.evaluatable.class.php: call to prt_evaluatable->unpack()
* line 204 of /question/type/stack/stack/prt.evaluatable.class.php: call to prt_evaluatable->get_path()
* line 711 of /question/type/stack/question.php: call to prt_evaluatable->get_answernotes()
* line 702 of /question/behaviour/behaviourbase.php: call to qtype_stack_question->summarise_response()
* line 96 of /question/behaviour/deferredfeedback/behaviour.php: call to questio...
```

It seems the following call to [`floor`](https://www.php.net/manual/en/function.floor.php) receives a string argument:

https://github.com/maths/moodle-qtype_stack/blob/131268a162dae212c98fd499b906e034ff474460/stack/utils.class.php#L817

And since PHP 8.0.0 
> **num** no longer accepts internal objects which support numeric conversion.

System:
- Moodle 4.1.6+
- qtype_stack 4.4.6
- PHP 8.1

I was not yet able to pinpoint, where/why exactly this happens. Other attempts in the same quiz did not produce this error. I am still trying to reproduce it and find the root of the issue, but I thought I would post the error itself for now. Maybe someone here will know what exactly goes wrong and how to fix it right away.

I suppose the naive idea might be to just prepend `(float)` to the argument passed to `floor`, but since I am not sure what exactly that string is that is causing the error, this may not solve the actual problem. If I find it, I'll try to fix it and open a PR.

**Comment by sangwinc** [comment]
Thanks for posting this - we need to fix it.  I'm caught between two opposing tensions. (1) PHP is getting more strict (which in general I approve of....), and (2) STACK is allowing more, e.g. allowing variable names for PRT values not just numbers.  I expect the string coming through here is either empty (which would have been quietly converted to 0 I think) or is a variable name which, for some reason, didn't get evaluated to a numerical value.  In any case we need better error trapping for users, (particularly students).  Could you email me the question to my ed.ac.uk email, and let me know the STACK version number you're using?

**Comment by daniil-berg** [comment]
## PS

The `$value[1]` passed to `stack_utils::fix_to_continued_fraction` here

https://github.com/maths/moodle-qtype_stack/blob/131268a162dae212c98fd499b906e034ff474460/stack/prt.evaluatable.class.php#L124

in this case was `0.001*'round(1000.0*max(0.0,min(1.0,0.5*sum_score+0.333333333333)))`. I.e. definitely not a numeric value. It seems something ended up not being evaluated properly.

The contents of `$this->evaluated` here

https://github.com/maths/moodle-qtype_stack/blob/131268a162dae212c98fd499b906e034ff474460/stack/prt.evaluatable.class.php#L118-L124

in this case was the following:

`[[[true,false,"ATSets_wrongentries. ATSets_missingentries. ","stack_trans('ATSets_wrongentries' , !quot!\[\left \{0 \right \}\]!quot! ); !NEWLINE!stack_trans('ATSets_missingentries' , !quot!\[\left \{1 \right \}\]!quot! ); !NEWLINE!"],[false,false,"ATSets_STACKERROR_SAns. ",""],[true,true,"",""]],0.001*'round(1000.0*max(0.0,min(1.0,0.5*sum_score+0.333333333333))),0.0,["%root","//CT2S1////CT2S4//",["smlt","\({\left \{0 \right \}}\)"],"//CT2S6//",["smlt","\({\left \{1 \right \}}\)"],"//CT2S7////CT2S8////CT2S1////CT2S14//",["smlt","\({{{\it sum}}_{{\it notwanted}}}\)"],"//CT2S16//",["smlt","\({{{\it sum}}_{{\it missing}}}\)"],"//CT2S17////CT2S18//"],["prt1-1-F","prt1-2-F","prt1-3-T"]]`

Does this help to narrow it down at all? 

If not, I'll see if I can extract the question causing this somehow. As of now, there is no obvious way for me to find out, which one it is because the quiz has many and this is a specific attempt causing this error, without showing which question exactly caused it.

Please let me know.

---

Yes, more type safety is better, but introducing it post-facto like in PHP now is bound to break things. Thanks for your efforts anyway!

**Comment by aharjula** [comment]
Well given that `sum_score` is not a variable present in STACKs own logic one could probably guess that it is a variable in the question itself.

**Comment by aharjula** [comment]
Based on this part of the expression `0.5*sum_score+0.333333333333` one could probably guess that one PRT-node has a score value that contains `sum_score` or probably `0.5*sum_score`. If one has access to the database (most people dont') one can search for PRT-nodes with `truescore` or `falsescore` fields containing that and then track those nodes back to the question identity.

More realistically, one could try reviewing just singular question attempts as opposed to the whole quiz attempt and maybe narrow the set down that way. In the quiz result list, one should be able to click the cells in the table to do that.

Or one could open each question in the quiz in the question editor and find which one has that variable in use in the PRTs. Naturally, many could have it if these come from the same source and the one that fails might simply be a copy-paste issue where something relevant was lost on the way.

**Comment by daniil-berg** [comment]
@aharjula Thanks for the tip. I do actually have access to the DB. I think I found the question causing the issue. @sangwinc I sent it to your Email address. Thanks for looking into this. Let me know, if there is anything else I can contribute.

**Comment by sangwinc** [comment]
Thanks, it was relatively easy to reproduce the the problem.  I'm testing a fix which will throw a runtime error (with an answer note) rather than a coding exception.  Thanks for reporting this.

**Comment by daniil-berg** [comment]
@sangwinc Sorry, I am not familiar enough with STACK myself (I am just administrating, not using it myself). Am I correct in understanding that this was ultimately still an error on the part of the person that wrote this question? If so, what must be changed to avoid the runtime error?

**Comment by sangwinc** [comment]
Basically yes!  They used a variable name to define the score.  For some reason that did not evaluate to a number at the end of the assessment process.  The new, strict, PHP threw a coding exception because we're trying to change a string (unevaluated variable name) to a float.  I've added a check so that we trap this error in a better way.  The problem remains with the question!

**Comment by daniil-berg** [comment]
Sorry to bother you again. This problem caused much broader issues that I have not figured out how to solve yet. The `mod_quiz\task\update_overdue_attempts` scheduled Task keeps failing because of this error, which (among other things) prevents a huge number of quiz attempts to be finished. (When a quiz has a deadline and the teacher set it up accordingly, that task should close overdue attempts automatically.)

Any help with this would be greatly appreciated. It seems impossible to fix this problem as a teacher. Fixing the question just sets up a new version of it. The attempt is tied to the old version. The only thing would be to re-grade the attempts, but since they have not been finished due to the error they cannot be re-graded. And I cannot submit/close the attempt because of the error. The snake biting its own tail here...

Thousands of students' quiz submissions are not being graded properly because of this. This is a serious problem.

**Comment by aharjula** [comment]
The easy but inconvenient way is to destroy the attempts that cause this. Naturally, this means that the points need to be restored to these students manually through other routes. If there are more than one, then this will be an iterative process.

Other than that, one would need to mess with the database so that the attempts actually target the fixed version of the question. If there are many failing attempts, then this is probably simpler to do in bulk, assuming that not too many versions are in play and don't differ in other ways.

One could also eliminate attempts to singular questions in the quiz through the database, but that is more risky. In any case, having a backup copy to try on would probably be nice when there are thousands of victims in play.

**Comment by sangwinc** [comment]
I believe I've fixed the issue.  This will be in the release which is due out on 11th Dec.

**Comment by daniil-berg** [comment]
OK, we just cherry-picked the b3633ef5b48111d46208166109ec8d7c2e4b4453 commit by @sangwinc into our production system and re-ran the task successfully. :partying_face: I did not expect this to affect the scheduled task. This is really a problem with Moodle and should not happen in principle IMO.

**Comment by sangwinc** [comment]
Thanks for confirming.  I'm glad to hear this is fixed.  I'll talk with the Moodle community (inc @timhunt) and see what we can do to improve the behaviour after an error.
