### ISSUE TITLE
NumSigFigs answer test not reliable

### ISSUE THREAD

**Issue by gustavdelius** [maths/moodle-qtype_stack#107]
Try a simple question, asking the student to enter the number 0.1667. Then use the NumSigFigs answer test with option 4 to compare the student's answer to 0.1667. The correct answer will be marked as incorrect with the claim that the answer has the wrong number of significant figures.

This is due to the fact that the NumSigFigs answer test code uses maxima's `floor()` function, which gives `floor(0.1667*10^4)` as `1666` not `1667` as expected.

I think the test should be made more robust by checking not only the student answer but also the student answer plus and minus a small number near the machine precision.

**Comment by sangwinc** [comment]
The way to fix this is to have an "ephemeral form" for representation of floating point numbers.  This is quite a big project, and was already mentioned in the docs.  E.g.it is the reason why there is no "decimal places" test yet.  I've put this into future plans, and so will close this issue here for now.

**Comment by gustavdelius** [comment]
However perhaps a warning should go into the user documentation of the NumSigFigs test.

**Comment by sangwinc** [comment]
Yes, that is a very sensible idea.  Do you have some examples to hand?  If so, could you add some (failing) unit tests to 
/question/type/stack/tests/answertestfixtures.class.php     
which illustrate the problems?  These can be given a code fail, expected failure or maths failure if you like.

**Comment by gustavdelius** [comment]
There is an example in the first post in this issue. Unfortunately I am not currently set up to contribute to the code and do not have any time at the moment. So we need to leave this open until someone has time.

**Comment by sangwinc** [comment]
https://github.com/maths/moodle-qtype_stack/commit/1967af3c7d416abebdcfe2c6e135a1c8674acc8e

**Comment by tamuratak** [comment]
Hi, I guess that converting students' answers into bigfloat literal and again converting them into rational numbers internally would solve this issue although I have not understand the intended action of NumSigFigs yet.

```
floor(rat(0.1667b0)*10^4); /* => 1667 */
```

By setting "fpprec" big enough and "ratepsilon" small enough,  we can convert bigfloat number to rational number precisely.

```
is(floor(rat(0.999999999999999b0)) = 0);  /*  => false */
ratepsilon : 1e-100$
fpprec: 110$
is(floor(rat(0.999999999999999b0)) = 0);  /*  => true */
```

**Comment by sangwinc** [comment]
I think this issue has been addressed in this commit, so I'm going to close it.  If you have further examples and problems, please reopen the issue.

https://github.com/maths/moodle-qtype_stack/commit/873f52fa0a4133fbb44268b5af05a2d3b7033184
