### ISSUE TITLE
Timeout issue using Int PRT

### ISSUE THREAD

**Issue by mrseanman** [maths/moodle-qtype_stack#1073]
Using the Int PRT test, there is a timeout issue when trying to detect incorrect answers for quite simple expressions.
It has something to do with large-ish exponents within trig functions.

Here are some examples where this timeout occurs
- `correct_ans: sin(x^12/%pi) + C`, `submitted_ans: 3*sin(x^12/%pi) + C`
- `correct_ans: cos(x^12/%pi) + C`, `submitted_ans: 3*cos(x^12/%pi) + C`

And some where the timeout does not occur (wrong answer correctly detected).
- `correct_ans: sin(x^12) + C`, `submitted_ans: 3*sin(x^12) + C`
- `correct_ans: cos(x^12) + C`, `submitted_ans: 3*cos(x^12) + C`
- `correct_ans: sin(x^11/%pi) + C`, `submitted_ans: 3*sin(x^11/%pi) + C`

Lower (than 11) values of exponents are also well behaved.
For all of the above the test option is set to `x`.

Correct answers are detected OK, answers without a constant are detected OK. Only these incorrect answers with a constant cause this issue.

**Comment by sangwinc** [comment]
Interesting edge case!  This is caused because, internally, the system was calling trigexpand of `sin(2^12/%pi)`.  This obviously causes a timeout!  For a non-timeout example, try `trigexpand(sin(2^3/%pi));` in Maxima to see why this leads to expression explosion.  Thanks for reporting it.
