### ISSUE TITLE
edge case [[validation:ans1]] with kids 10-13

### ISSUE THREAD

**Issue by Bjoern-Ge** [maths/moodle-qtype_stack#1077]
[[validation:ans1]] of the input "+1" tells "1".
1+(-3) is shown as 1-3
That is a totally understandable simplification.

Together with the answer-test CAS-equal, I ran into the problem that 1 and +1 is interpreted differently by the answer test.

I suggest that the validation should also tell "+1"

**Comment by sangwinc** [comment]
Gosh, this really is an edge case to end the week on!  For everyone else interested, you can reproduce the underlying issue in a castext session (with simp:false) as

{@disptree(1-3)@}
{@disptree(+1-3)@}

This will display the underlying expression trees for 1-3 and +1-3.

ATEqualComAss(+1-3,1-3);

returns "true" (as I'd expect) so which test are you using here?  CASEqual?

It's interesting that Maxima's tex command _does_ show the +1, so we must have switched this off somewhere in our parser.

**Comment by sangwinc** [comment]
Right, that was easy to find:
https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stackmaxima.mac#L770

**Comment by sangwinc** [comment]
I'm quite happy to revert the code which "sorts out" the unary plus.  For elementary use, I can see "simple" +1 should retain the visual +.  Maxima (not STACK) has some edge cases.  E.g. 

'1/sin(+x)' gives '\frac{1+}{\sin \left( x \right)}'. 

That is really very odd, and comes from Maxima's TeX function. I'm not going to fix this!  On reflection, I think the benefit of this to elementary users outweighs this edge case which is not likely anyway.  If this issue pops up again in the other direction @Mat-Ge then you owe me a pint!
