### ISSUE TITLE
input type 'Matrix of variable size' does not autosave correctly when using syntax without multiplication stars

### ISSUE THREAD

**Issue by FelixDiLenarda** [maths/moodle-qtype_stack#1082]
When using the 'Matrix of variable size' input type in a STACK question within a Moodle quiz, the user's input is not consistently displayed upon navigating between different question pages.

**Steps to Reproduce:**

1. Set up a quiz in Moodle that includes a STACK question with the input type set to 'Matrix of variable size', followed by either a description page or another question.
2. Attempt the quiz and enter an answer in the STACK question using syntax without asterisks, such as '2i 4'. The response will be shown correctly in the "Your last answer was interpreted as follows:" section.
3. Navigate to the next page (either a question or a description page) and then return to the STACK question.
4. Observe that the input textarea for the question is empty, even though the "Your last answer was interpreted as follows:" section still displays the previously entered answer correctly.

**Notable Issue:**

- This issue occurs regardless of the "insert stars" setting in the quiz configuration.
- This issue does not occur if you use 'Algebrai input' type for example.
- It appears that the 'Matrix of variable size' input type may have compatibility issues with Moodle's autosave functionality, leading to the loss of displayed user input upon page navigation.

**Comment by EJMFarrow** [comment]
Hi @FelixDiLenarda,

Is this still an issue and, if so, which versions of STACK and Moodle are you using? I've tried the current development version of STACK (soon to be v4.6) with Moodle 4.1 and 4.6 and can't replicate the problem. If you have XML for a sample question that would be great as well in case I'm missing a setting somewhere.

Thanks,

Edmund

**Comment by FelixDiLenarda** [comment]
Hi @EJMFarrow ,

thanks for checkin. In the meantime we also upgraded stack (v4.5.0) and moodle (4.3).

I checked aswell and it seems that the error does not occur anymore :)

Greetings Felix
