### ISSUE TITLE
Answer Test SubstEquiv no longer takes the optional input

### ISSUE THREAD

**Issue by LukeLongworth** [maths/moodle-qtype_stack#1083]
I think this is from #974, where test options were hidden when they are not needed. In 4.4.6 I cannot give the optional list of variables that are not allowed to be substituted. I tried setting it to an answer test that does take optional inputs, giving [x] as required, and then switching back to SubstEquiv, but upon saving the question, the options field seems to be cleared. I imagine that if there are other tests that take an _optional_ input but no compulsory input, these will be affected too.

**Comment by sangwinc** [comment]
Thanks for reporting this @LukeLongworth, sorry about this.  I already spotted and fixed this issue, and it will be in the next release.
Chris
