### ISSUE TITLE
input convention for column vector and row vector

### ISSUE THREAD

**Issue by tamuratak** [maths/moodle-qtype_stack#109]
## Feature request

Hi,

I have been teaching undergraduate students mathematics. 
Moodle/STACK has wonderfully worked well enough. Thanks
 very much for your great work.

My feature request is adding into STACK an input convention for
column vector and row vector.

I know I can set Matrix as Input type of the answer on STACK and
they can be used for vectors also. But when the number of vectors
in the answer itself is  also the part of the question, (e.g. questions on
the basis of linear subspace whose dimension is unknown), Matrix
seems inappropriate as Input type.

Summary

 * I want students to answer some questions with Algebraic input.
 * I also want students to be able to differentiate between column vector and row vector rigorously.
 * typing matrix([1], [2], [3]) for the column vector [1, 2, 3] would be difficult for students.

## Proposing input convention 

```
c(1, 2, 3)  /* => column vector [1, 2, 3]  */
r(2, 3, 5)   /* => row vector [2, 3, 5]       */
```
or 

```
col_v(1, 2, 3)  /* => column vector [1, 2, 3]  */
row_v(2, 3, 5)  /* => row vector [2, 3, 5]       */
```

Regards

**Comment by sangwinc** [comment]
This seems like a very sensible suggestion.

I agree the matrix input is unambiguous.

Underscore characters in col_v will be difficult and could be a problem. 

I think (without having tried this myself) that you can do this already.  E.g. "c" and "v" are undefined functions, so they do nothing.  A student can already type in c(1,2,3) and it will be left unevaluated.  We can convert this into a matrix internally for them, using code such as the following.

ta1:c(1,2,3);
ta2:v(1,2,3);
vec_convert(sa) := if op(sa)=c then transpose(matrix(args(sa))) 
                   elseif op(sa)=v then matrix(args(sa));
vec_convert(ta1);
vec_convert(ta2);

Of course, you don't need the vec_convert function here and could just apply these transforms in the feedback variables to transform the expression into a matrix type internally.

I agree, through, that some consistent mechanism within STACK might be a real help here.  What views do other people have on syntax?

**Comment by tamuratak** [comment]
Hi.

Thanks for your kind response very much. If these functions becomes built-in for STACK, I can expect c(1,2,3) and v(1,2,3) will be displayed as vectors with MathJax filters. That's the reason I opened this issue. I do not know how long it takes to implement that.  But this would help students greatly. 

Regards.
