### ISSUE TITLE
Add sample Parsons block, and GeoGebra block to the healtcheck scripts

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#1090]
Sal,

Following the very helpful example @aharjula posted earlier,
https://github.com/maths/moodle-qtype_stack/commit/b5678e4bb7a6a470e2d498ffc5195634948bc891
could you please add in two more blocks to the healthcheck script which confirm (1) Parsons blocks, and (2) GeoGebra blocks also work?  Having something interactive on the healthcheck will help us (i.e. me!) check all this pre-release.

Thanks,
Chris

**Comment by aharjula** [comment]
For anyone faking inputs that need to use STACK-JS all you need to do is to have the input and user wrapped in a `class="formulation"` `div` and have the input element have an id that ends with the referenced name and has an underscore before that name. Fake inputs inside questions work the same way but you do not need to add that div wrapper there.
