### ISSUE TITLE
Parsing exception breaks the workflow and the site rendering

### ISSUE THREAD

**Issue by XTRage** [maths/moodle-qtype_stack#1098]
If a user enters for example a superscript ² (\u00b2) instead of ^2 an exception is shown on resuming the attempt (as in screenshot) and the rendering of the site is broken.

![image](https://github.com/maths/moodle-qtype_stack/assets/78024887/7fe916ab-3458-4eb8-8c5b-8c2ba50bb2cb)

**Comment by sangwinc** [comment]
Yes, this is a duplicate of issue #1107 and is now fixed.
