### ISSUE TITLE
casstring->errors and the generation of duplicates

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#111]
While doing my wipcasblocks-merge I have encountered a problem with the validation unit tests, for some reason (reason being that I have to call a function that calls validate and I also need to call validate) my code returns dual copies of whatever errors casstring validation finds. So as an example I get:

'<span class="error">CASText failed validation. </span>'*' is an invalid final character in <span class="stacksyntaxexample">2*</span> '*' is an invalid final character in <span class="stacksyntaxexample">2*</span>'

Instead of:

'<span class="error">CASText failed validation. </span>'*' is an invalid final character in <span class="stacksyntaxexample">2*</span>'

As the validate function of casstring is coded so that it appends errors to the errors field on every call and as one can easily call it more than once with different parameters in various validation levels there will easily appear multiple copies of the same error. This leads to a situation where one must never call the validate function if one does not want duplicate errors, which is somewhat annoying when one would like to ensure validity in some deepper part of the code.

What makes this extra funny is that calling various functions like set_key causes validation using the default settings and if you need to use some other validation settings after that you'll get dual errors. This causes different output from the validation system depending on what code handles the strings which makes writing test cases somewhat difficult.

In the wipcasblocks version of the castext-class I have been using an array to store the various errors and running that through array_unique() before imploding it to a string in get_errors(), thus shortening the error messages and not drowning the author with the same error if they have repeated it multiple times. Maybe the casstring validation system could use a similar logic?

What do you think about casstring errors being an array and duplicate errors being eliminated using array_unique? Get_errors would still return a string, unless we would like to join the errors at upper levels to for example HTML-lists?

Array operations will naturally have a price, but maybe unique error messages would be worth it. On the other hand do we even care if the error message repeats itself couple of extra times? Only the unit test might break less often if adding extra validate somewhere would not cause error messages to change elsewhere...

-Matti

**Comment by timhunt** [comment]
I don't think you should be calling validate(). Instead you should call get_valid, which will ensure that validate is called if it has not already been. validate() is private for a reason.

**Comment by aharjula** [comment]
get_valid does indeed the same things as validate except if you have used set_key before the call. casstring->validate is public...

**Comment by aharjula** [comment]
Also why does almost every get/set function in that class call validate? And if validate and get_valid have parameters why is the get_valid function blocking validation using those parameters if something has caused validation before that call, thus forcing the validate call to make sure those parameters are actually used.

**Comment by aharjula** [comment]
Naturally, most of my problems here is that I am using the thing in the wrong way, but maybe the way I am using it could also be less wrong? Moving the same casstring object between security settings and thus requiring multiple validations is something that could be needed in the future.

**Comment by sangwinc** [comment]
Matti,

I'm responsible for this design I'm afraid.  The original goals were (1) to limit validation to only once (since this does a lot of checking).  I was worried about efficiency if we keep vaidating the casstring, but Tim said "PHP calls are basically free and state is Evil", so I've probably been worrying without good reason on this score.  We all learn!   (2) make sure validation security can't be changed easily.  Otherwise casstrings than get passed around the code could end up with the wrong setting.

You are right.  At some point validate got made public and it should not be.  So, I've changed it back to private and run all the unit tests.  Mostly changes needed to be made only in the test scripts, but so far I've not found any reason why it should be public.

I may not have got the design right here.  I can see why you end up with duplicate messages which should not happen.  Suggestions welcome on how to refactor this.  Do you have compelling reasons why it needs to be public?  Why does the security setting need to change?

**Comment by aharjula** [comment]
Chris,

The problem was that I thought validate to be public, so that is now fixed. But the bigger problem was that various functions like set_key will call validate if no validate has been called before and that call will use default security settings, which may be different than the setting where that casstring exists. Thus generating validation problems for things that do not apply and blocking the validation with the correct settings when calling get_valid as that notes that validation has been done and gives the previous results no matter which settings were used to generate them.

Basically, it is a minefield where you may get completely wrong validation results if you do not use the functions in correct order and as you wish to protect yourself against wrong order of invocation in some other part of code you must force validation with your own settings the moment you form the casstring. So the validation might as well be part of the constructor of the casstring as you must call it anyway to avoid wrong security settings later.

I have (hopefully) learned my lesson with the way the validation works but future developers might again break things and trace their problems to this. 

As to the duplicate elimination using array_unique, not realy necessary with private validate-function. But moving the rendering (as in return arrays instead of a string) of validation issues upper in the code might be a thing that would allow more control on the layout of the errors.

**Comment by aharjula** [comment]
Also, set_key is the biggest grievance as it seems so logical to set all the details of a casstring before calling the validation. But it is not the only function that may cause these problems.

**Comment by sangwinc** [comment]
I certainly agree with set_key and I have to confess I've also had this problem!  Please don't treat the design as a tablet of stone.  If you have a suggestion of how to refactor, and that might just be to allow set-key not to call validate, then please go ahead.  The validate is a "side effect" and while these are sometimes helpful they are sometimes a serious barrier.
