### ISSUE TITLE
"Send General Feedback to CAS" should use HTTP post not URIs

### ISSUE THREAD

**Issue by stuartmanderson** [maths/moodle-qtype_stack#1110]
The functionality of "Send General Feedback to CAS" (part of question tests) currently encodes the maximavars in the URI.  This can make some URIs exceptionally long and exceed the default apache LimitRequestLine setting of 8177 characters.  In the example that has led me to report this issue, the URI was 9132 characters long with most of that being encoded maximavars data.

In such cases, the better design choice if for data should be passed as HTTP post data rather than as a URL link.

**Comment by EJMFarrow** [comment]
I couldn't find a way of doing a straight change to POST when moving between pages within Moodle so I've altered things so only minimal information is passed in the URI from the STACK dashboard and the data is loaded from the DB on the target page. (Updates on the Send General Feedback page itself are already sent via POST.)

Ready for code review - https://github.com/maths/moodle-qtype_stack/pull/1115

**Comment by sangwinc** [comment]
Thanks @EJMFarrow.

**Comment by stuartmanderson** [comment]
Thanks @EJMFarrow for such a fast fix.  I'll pick this change up during our summer STACK upgrade.

**Comment by stuartmanderson** [comment]
Thanks!  I have no date set yet, but it is largely up to me.  However, with change freezes I think the latest date possible is W/C **4th August.**
As a side note on this, my move from MaximaPool to goemaxima has made upgrades so much less stressful and much quicker.  I'm pleased I made the jump.
