### ISSUE TITLE
Three issues for the dashboard

### ISSUE THREAD

**Issue by Mat-Ge** [maths/moodle-qtype_stack#1111]
1. The deployment of variants can be very helpful, e.g. for test cases. But after the deploying of variants, the seed is no longer chosen freely. Sometimes, I would prefer both: Deployed variants and a freely chosen seed. Can you add an option for this (choose the seed freely) in the dashboard if at least one variant is deployed?
2. Sometimes I have to develop a large number of variants. For example, my question involves six different types of functional equations, and I want to have exactly three variants in the question for each type. In this case, I develop numerous variants until I have at least three variants for all six types (requires maybe 45 variants). After that, I have to delete 27 variants individually, which is very time consuming. Can you add a checkbox in front of each variant so that numerous variants can be deleted with one click? Or is there already a much more efficient method? Using the option "Remove variants and re-deploy from list" isn't really an option, because it's very confusing with 45 variants. 
3. If the score in a PRT is written as a fraction,  clicking on "Tidy inputs and PRTs" leads to the following error:
![grafik](https://github.com/maths/moodle-qtype_stack/assets/128398586/f90766e0-345f-43fd-8638-1288cb4dc6ff)

**Comment by sangwinc** [comment]
Thanks for these suggestions.  With (1) and (2) I think there is just a cost-benefit question, i.e. how important relevant to other requests.

Really sorry about (3).  That's a separate and live bug.
