### ISSUE TITLE
Forbidden Maxima commands and NumDecPlaces test

### ISSUE THREAD

**Issue by kak23** [maths/moodle-qtype_stack#113]
Hi,

I'm trying to set up a question in linear programming, the 'maximize_lp' and 'minimize_lp' commands from Maxima are forbidden in STACK, though. I was wondering if there is an option for me to unlock the simplex package myself?

And since I'm here, I have a problem with NumDecPlaces answer test. It works fine until, for example, I set the test options to 4, but the correct answer is 1.05. Even if the student inputs '1.0500' their answer is validated as '1.05' and therefore it displays the negative feedback. Is there any way of going around it?

Thank you,
Klaudia

**Comment by sangwinc** [comment]
Thanks Klaudia,

(1) you can add the packages manually at the developer level.  Add an appropriate load command to stackmaxima.mac  See https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stackmaxima.mac   There is no option for question authors to load extra packages at the moment. 

(2) Yes, I'm sorry that the numerical tests are not solid at the moment.  This was already reported in issue 107.   https://github.com/maths/moodle-qtype_stack/issues/107 

Chris
