### ISSUE TITLE
textput

### ISSUE THREAD

**Issue by sdirnboeck** [maths/moodle-qtype_stack#1131]
Hello, 

I just found the function textput and would like it to have the e-function displayed with \mathrm{e}. I have gotten the textput function to work for the logarithm and the imaginary unit i, but somehow it doesn't work for the exponential function. 

How does the textput-function work for the exponential function?

**Comment by sangwinc** [comment]
The issue here is that student's input "e" is transformed into the Maxima constant %e.  Hence, you need

texput(%e, "\\mathrm{e}");
