### ISSUE TITLE
Allow configuring the MathJax URL

### ISSUE THREAD

**Issue by daniil-berg** [maths/moodle-qtype_stack#1160]
This was mentioned in #992, specifically in [this comment](https://github.com/maths/moodle-qtype_stack/issues/992#issuecomment-1659757219), so I want to focus on this specific issue.

Right now the MathJax URL is hard-coded to point to `cdn.jsdelivr.net`:
https://github.com/maths/moodle-qtype_stack/blob/dc19c913b6c4a8fc8b8ef20ae31ced699d23dd7b/vle_specific.php#L188-L194

I realize that a specific CORS Header is required to make this work, but it would still be nice, if we could change the URL without having to create our own fork and branch of this repository.

In fact, simply pointing to the `filter_mathjaxloader | httpsurl` Moodle setting should be fine. You could add some documentation to the plugin that explains that changing that setting without ensuring the correct CORS header will affect this.

Alternatively, a separate config option just for this plugin would also be fine. There you could add the info about the CORS issue right next to the setting.

In any case, a hard-coded URL is not ideal. We have a strict CSP for our Moodle instance that blocks almost all other domains and we use our own installation of MathJax that we point `filter_mathjaxloader | httpsurl` to.

**Comment by sangwinc** [comment]
Agreed, a hard-coded URL is not sensible!  Let's fix this.

**Comment by MuellerAle** [comment]
May I suggest we:
1. use filter_mathjaxloader | httpsurl that is already a core part of moodle.
2. add other cdn files locally to the plugin (if any). 
Optional: add qtype settings with fields to enter the cdn when users want to use cdn instead.
