### ISSUE TITLE
Equivalence Reasoning firstline option validation problem

### ISSUE THREAD

**Issue by bgailer** [maths/moodle-qtype_stack#1175]
Hello,

when using Equivalence Reasoning together with the input option `firstline`, the validation message says <pre>Class "stack_cas_casstring" not found</pre> when your first line starts with an equals sign. 
Maybe there needs to be a check if the first line starts with an equal sign, and then this could be shown as validation message to students like for example "Your first line should not start with an equals sign".

**Comment by sangwinc** [comment]
Thanks for reporting this and sorry for the bug. This has already been fixed in the "dev" branch, and will be in the next release.
