### ISSUE TITLE
Imaginary number i together with fraction causes problems with validation

### ISSUE THREAD

**Issue by bgailer** [maths/moodle-qtype_stack#1176]
Hello,

in one of our questions, we recently noticed a strange behavior with the validation when the input contains a fraction multiplied with the imaginary unit. For instance, something like `%i*pi/3` works fine but `(%pi/3)*%i` or `1/2*%i` does not. Below I included screenshots of the validation output from one of our questions on complex numbers.

![imagnumbers_working](https://github.com/maths/moodle-qtype_stack/assets/113438267/090d69e5-3ddd-41a7-81c7-89b651381ecb)
![imagnumbers_notworking](https://github.com/maths/moodle-qtype_stack/assets/113438267/d8e44887-03fd-4f28-b30c-9a3c75cf086e)

**Comment by bgailer** [comment]
This only seems to be the problem for this specific question, as other questions in our moodle do not show this when inputting something like <code>(%pi/3)*%i</code>. 
Here is the question that causes this issue:
[quiz-Komplexe Zahlen – Entwicklung-U2_A2 Rechenoperationen Zusatz-20240426-1608.txt](https://github.com/maths/moodle-qtype_stack/files/15131599/quiz-Komplexe.Zahlen.Entwicklung-U2_A2.Rechenoperationen.Zusatz-20240426-1608.txt)

**Comment by sangwinc** [comment]
Yes, sorry about that - the problem has already been fixed.
