### ISSUE TITLE
iframe covers area much larger than applet within

### ISSUE THREAD

**Issue by guidopinkernell** [maths/moodle-qtype_stack#1177]
A geogebra applet is displayed within an iframe. The attached example shows that the iframe covers an area that is much larger than the applet within hence creating empty spaces around the applet which put  other question information out of view. I have played around with applet size definitions, and it seems that these have no influence on the area that is occupied by the iframe.

[questions-authotry-iframe larger than applet-20240426-0744.zip](https://github.com/maths/moodle-qtype_stack/files/15125885/questions-authotry-iframe.larger.than.applet-20240426-0744.zip)

**Comment by sangwinc** [comment]
@smmercuri could you please look into this?  If it's just an update to the docs then could you follow @georgekinnear's suggestion and resolve this please?

**Comment by guidopinkernell** [comment]
Thanks for looking into this. Actually, George is right. The problem is solved by adding information about size of the iframe etc into the block's head. Inside the block, size information for the applet itself needs to stay, though. It seems that the documentation is not complete. I will add what is necessary.
