### ISSUE TITLE
Limit the requested number of variants to deloy,

### ISSUE THREAD

**Issue by timlowe** [maths/moodle-qtype_stack#118]
On the "deploy questions" page, could we please limit the number of variants that can be deployed in one go (the "Attempt to automatically deploy the following number of variants" box), to, say, 100?

This would prevent idiots like me typing a 9-digit variant number into this box, instead of the "Switch to arbitrary variant" box!

Thanks,
Tim

**Comment by sangwinc** [comment]
Good idea.

See https://github.com/maths/moodle-qtype_stack/commit/e11107312d2abeb7fc46525ad4af880e46a00185
