### ISSUE TITLE
Should we allow PRTs with weight 0?

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#119]
Someone told me that they had seen PRTs with Question value set to 0.0000001, because the form validation does not allow it to be 0.

However, I checked in our database, and actually, this does not seem to be true.

The alleged need for this was that you might want to add an extra PRT, just for the purpose of computing a certain bit of additional feedback, without it contributing to the score.

The context for this was a question with three parts, where they wanted to award a point only if all three parts were right, otherwise zero. We found a neat trick to do that, namely AlgEquiv( A*ans1 + B*ans2 + C*ans3, A*tans1 + B*tans2 + C*tans3 ), determining the score. Then wanted to give feedback for the specific parts after the feedback for the overall correctness. However, it is perfectly possible to do that within one PRT, so I don't know why I could not work that out on Friday.

So, actually, I am no longer convinced that this is a good idea. But I record it here anywhere, if case anyone else wants to comment.

**Comment by sangwinc** [comment]
Thanks Tim,

I can see why there might be good reasons why you'd want to do this.  For example, putting the PRT feedback next to each part, but then having a final PRT which requires all three parts to award any marks.  I've tried the change and this causes no unitests to break, so I've commited a change which only requires marks to be non-negative.

See https://github.com/maths/moodle-qtype_stack/commit/e9d198db3a9759f619663c1a3b06e1cb99ea4893

Chris
