### ISSUE TITLE
allowempty and "insert lots of stars" results in E*M*P*T*Y*A*N*S*W*E*R;

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#1205]
With an input, choose the options allowempty and "insert lots of stars".

Submitting an empty answer results in `E*M*P*T*Y*A*N*S*W*E*R`, not `EMPTYANSWER` which is a bug!

**Comment by aharjula** [comment]
Well... is `EMPTYANSWER` in the `security-map.json`? Some of those insert start logics tend to avoid splitting things that are there...

**Comment by sangwinc** [comment]
Indeed!  Thanks @aharjula.
