### ISSUE TITLE
Failing unit tests in master from the API

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#1217]
I've just noticed that the master branch in Moodle now has some failing unit tests for the code in the API branch. It looks like something has changes in PHP
https://github.com/maths/moodle-qtype_stack/actions/runs/9810665112/job/27091276827#step:17:92

Could you take a look please @EJMFarrow?  Thanks

**Comment by EJMFarrow** [comment]
OK, will do.

**Comment by EJMFarrow** [comment]
The above pull request fixes the PHP upgrade issues. There's still a failed test involving unencapsulated commas, though, which looks like it's to do with other changes.

**Comment by sangwinc** [comment]
Thanks for fixing this @EJMFarrow
