### ISSUE TITLE
Support for plot2d option adapt_depth with value 0

### ISSUE THREAD

**Issue by Bennett-Woolf** [maths/moodle-qtype_stack#1222]
Following on from #921, adapt_depth is now allowed within STACK, however the value of 0 is not currently allowed.

Using the exact same plot as David in the last post, we see that an adapt_depth of 1 looks like this

<img width="336" alt="Screenshot 2024-07-17 at 11 44 18" src="https://github.com/user-attachments/assets/6ebdb5d2-89b9-466e-a34c-08a0189defa8">

which, while definitely much better than the previous options, still does not nicely align as it does for the case of adapt_depth = 0. Specifically 0 is a special case for the adapt_depth function which says "A value of zero means that adaptive plotting will not be used and the resulting plot will have 1+4*nticks points".

Is it possible that 0 could be allowed,

Thank you,

Jacob

**Comment by sangwinc** [comment]
@Bennett-Woolf would you please post the Maxima code for the plot you want so we can use this as a test case?

**Comment by Bennett-Woolf** [comment]
Hi Chris,

See below, thank you for this,

`
[a, b, c, d]: rand_selection([1,2,3,4,5,6,7,8], 4);
e: rand(5) + 2;

currentFunctions: rand([[e*x^a, e*x^b,e*x^c, e*x^d], [e*x, e^x, x^e, x^(1/e)]]);
functionNames: ["f", "F", "g", "G"];

graphs: plot(currentFunctions, [x, -2.2, 2.2], [y, -e - 0.2, e + 0.2], [box, false], [yx_ratio, 1], [axes, solid], [xtics, -e, 1, e],[ytics, -e, 1, e], cons(legend, functionNames), [alt, "Graph Of Multiple Functions"], [style, [linespoints, 1, 1.5]], [nticks, 5], [color, "#785EF0", "#DC267F", "#FE6100", "#648FFF"], [adapt_depth, 0]);
`

**Comment by sangwinc** [comment]
Thanks @Bennett-Woolf ,  here is a minimal example (more suitable for a testcase).

```
graphs: plot([6*x,6^x,x^6,x^(1/6)], [x, -2.2, 2.2], [y, -5.2, 5.2], [box, false], [yx_ratio, 1], [axes, solid], [xtics, -5, 1, 5],[ytics, -5, 1, 5], cons(legend, ["f", "F", "g", "G"]), [alt, "Graph Of Multiple Functions"], [style, [linespoints, 1, 1.5]], [nticks, 5], [color, "#785EF0", "#DC267F", "#FE6100", "#648FFF"], [adapt_depth, 0]);
```

**Comment by sangwinc** [comment]
Trying the above option in Maxima, we get this screen shot.
![iss1222](https://github.com/user-attachments/assets/4485f383-1828-4e48-a3fa-ed2ab0eb2d85)

This image also does not seem to respect the `[adapt_depth, 0]` option as described above.  So, I think this is a "maxima issue" not a "stack issue"?

**Comment by Bennett-Woolf** [comment]
You are completely correct, I'm sorry I didn't check this on my own Maxima, thank you again Chris

**Comment by sangwinc** [comment]
No problem at all @Bennett-Woolf, this is an interesting example plot.  I'm really keen to find out how people are using STACK and add interesting examples to the docs/test cases so we can ensure things keep working!  Please keep in touch.
