### ISSUE TITLE
Question description not copied when using course import or restore

### ISSUE THREAD

**Issue by bgailer** [maths/moodle-qtype_stack#1224]
Hello,

we recently used the import option to import data from our "development course" to a course for the students. All the STACK questions are copied to the question bank of the new course but interestingly, the question description was not copied. The question in the new course don't contain the question description that is present in the questions from the development course from which we imported them. The same issue also occurred when exporting and then restoring the development course into the new course.
I'm not sure if this is related to STACK or maybe more of a Moodle issue, but maybe someone here has an idea why this could be.

**Comment by sangwinc** [comment]
The question description is a rather new feature.  It was introduced in v4.3.0 (May 2023).  If you import into an older version of STACK then you will certainly drop the descriptions.

I've just checked, and from our public demo server (https://stack-demo.maths.ed.ac.uk/demo/ ) I can export STACK questions with the description intact in the .xml, and then restore them without any problems into the same server.

This site was rebuilt this year, so I'm confident that descriptions are fine in the latest version.

Could you do the following? 

1. Export a single question with a description and double check the moodle .xml has the export correctly?
2. Try to re-import that?
3. Confirm which versions you are using (after v4.3.0)

There is a subtle difference between installing from new, and upgrade in place.  Did you install a fresh server, or upgrade STACK in-place?

**Comment by EJMFarrow** [comment]
This looks like a problem with backup/restore rather import/export.
I'm thinking we're missing questiondescription (and its format) from here:
https://github.com/maths/moodle-qtype_stack/blob/5d000435c61febe604a1446e7d52b5b91238a10d/backup/moodle2/backup_qtype_stack_plugin.class.php#L49
Hayden has checked and the description is definitely not being transferred on backup/restore.

**Comment by sangwinc** [comment]
Thanks for looking at this @EJMFarrow.  I wonder if the individual question mechanisms (which I was testing and seems to work) is different from the quiz/course backup/restore.  I've added those fields to the backup script.  These are on coulomb now.  Could @hayden-MB please test this and confirm if it's fixed?

Thanks,
Chris

**Comment by hayden-MB** [comment]
Seems to work, coppied from coulomb to coulomb and coulomb to prep and the questions description remained.

**Comment by sangwinc** [comment]
Thanks!
