### ISSUE TITLE
Weird Text Box Shrinking on iOS devices

### ISSUE THREAD

**Issue by jmbragg** [maths/moodle-qtype_stack#123]
![img_0004](https://cloud.githubusercontent.com/assets/4606870/7128655/62a113a2-e223-11e4-89f5-0da1c72852f5.PNG)

This image is from an iPad.  Notice that the coefficient of 2 entered into the text box in front of the H<sub>2</sub> is weirdly cutoff.  This occurs when the cursor is the text box but not when the cursor is elsewhere.

I've duplicated this on an iPad Air 2 and iPhone 5 in Chome and Safari.  It does not occur on my Windows 7 machine with Chrome no matter how I resize the window.  It does NOT occur on my HTC One M8 on Chrome.

The input box size is "1" because I only need one digit.  On the desktop and Android versions of Chrome this shows up as a box that I can enter at least 3 digits in before it starts to cut off numbers.  Only the iOS boxes are smaller sizes.  I guess this means that the other versions are padding the size more than iOS is... 

This happens in multiple themes (Clean, Elegance, Base)

Anyways, this is admittedly a trivial issue since I can increase the size of the boxes.  There are a few places this will get annoying since there are some two digit coefficients that will require a box size of "3".  That will make the desktop/Android boxes much too large to be elegant.  In any case, its just odd.

**Comment by timhunt** [comment]
What's annoying is that it looks like there is space to fit a 2 in there, but the 2 is shifted to the left where half of it is cut off.

Note that in standard Moodle qtypes, we use a fudge-factor to size the input box: https://github.com/moodle/moodle/blob/master/question/type/shortanswer/renderer.php#L72 but that was more about making large boxes match the size of a row of underscores in a range of browsers, mainly concentrating on the long end of the scale, not the few characters end (and I have no idea if the fudge-factor I picked years ago still works in Modern browsers.)

In contrast, STACK passing the question setting straight to the HTML: https://github.com/maths/moodle-qtype_stack/blob/master/stack/input/algebraic/algebraic.class.php#L31 That is logical and comprehensible, but as you point out, not necessarily what is wanted.

**Comment by timhunt** [comment]
The spec is clear http://www.w3.org/TR/html5/forms.html#attr-input-size - the input should be big enough to display the number of characters specified. Sadly browsers have never followed that exactly.

If you save this script as test.php in the root of your Moodle site, you can use it to see a range of input sizes filled with a range of characters.

The old fudge-factor of 1.1 seems to work quite well on this Mac laptop in Chrome, IE and Firefox, though is a tiny bit small as size gets large for numeric input. In most browsers, size=1 is big enough for about 4 chars, except chrome where fits about 1.

I have not tried on an iDevice yet.

```PHP
<?php

require_once('config.php');
$PAGE->set_context(context_system::instance());
$PAGE->set_url('/test.php');

echo $OUTPUT->header();
for ($desiredsize = 1; $desiredsize < 20; $desiredsize++) {
    $actualsize = $desiredsize * 1.1;
    echo $OUTPUT->heading('size="' . $desiredsize . '"');
    $inputs = array();
    foreach (array('I', 'M', 'i', 'm', '1', '2') as $char) {
        $inputs[] = html_writer::empty_tag('input', array('typr' => 'text',
            'size' => $actualsize, 'value' => str_repeat($char, $desiredsize)));
    }
    echo html_writer::div(implode(' ', $inputs));
}
echo $OUTPUT->footer();
```

**Comment by timhunt** [comment]
Better version, at least on this laptop. (Though if we are doing style=... we don;t really need to keep the size, or don't need apply a fudge-factor to it):

When I say better, this now works for the M. The boxes are to big for the digits.

```PHP
<?php

require_once('config.php');
$PAGE->set_context(context_system::instance());
$PAGE->set_url('/test.php');

echo $OUTPUT->header();
for ($desiredsize = 1; $desiredsize < 20; $desiredsize++) {
    $actualsize = $desiredsize * 1.1;
    $width = (0.1 + 0.9 * $desiredsize) . 'em';
    echo $OUTPUT->heading('Desired size: ' . $desiredsize . ', size="' . $actualsize .
            '", width: ' . $width);
    $inputs = array();
    foreach (array('I', 'M', 'i', 'm', '1', '2') as $char) {
        $inputs[] = html_writer::empty_tag('input', array('typr' => 'text',
            'size' => $actualsize, 'style' => 'width: ' . $width,
            'value' => str_repeat($char, $desiredsize)));
    }
    echo html_writer::div(implode(' ', $inputs));
}
echo $OUTPUT->footer();
```

**Comment by timhunt** [comment]
I have now tested that last version on the three browsers on Windows, and the default browsers on iPhone, iPad and Android phone, and the input sizing is remarkably consistent, though not exactly the same.

So, style="width: ..." seems to be the reliable way to control the size.

And width = 0.9 * chars + 0.1 seems to be a good heuristic for Ms.

I will try to shut up now.

**Comment by sangwinc** [comment]
Thanks for pursing this Tim, very tiresome.  I'd have thought that width=# characters.  But there we go.

Are we proposing a change in the code as a result.   E.g. in the input code sections.  I'm happy to implement a change but don't want to work at cross purposes with anyone else doing this. Should I implement this and push changes?

**Comment by timhunt** [comment]
I am not planning to implement this.

Please do, if you agree with it.

**Comment by sangwinc** [comment]
Ok, I've gone ahead and implemented this.  
https://github.com/maths/moodle-qtype_stack/commit/3d1289ccefc3973e5d920ce31a63ee2f6da6b964

I've also written a question collections which tests some of the various options on the inputs.  This will be useful to test various browsers in the future, I'm sure.

I don't like the fact that we send a float instead of a non-negative integer, but there we are.  The rules seem to allow us to throw a float at the browser: http://www.w3.org/TR/html5/infrastructure.html#rules-for-parsing-integers

**Comment by timhunt** [comment]
Thanks Chris. I suppose we could always add a floor() to the code, to get rid of the non-integer size. Non-integer width in ems is not a problem.

**Comment by jmbragg** [comment]
For the record, you two rock.  I looked at this and thought... "Well that's a really minor issue with an easy workaround.  I'll report it but go in and change the input box sizes when I have the time."  Thanks for being so awesome and getting to this so quickly.
