### ISSUE TITLE
Adding "tags" to the [[todo]] block for better collaborative working.

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#1231]
Thanks to @anst-i yesterday for discussing how we can better support collaborative working in STACK authoring by adding "tags" to the `[[todo]]` block.

I think this is a very valuable suggestion, and one which could be implemented in a simple way.

The goal is to have question development workflow tied/documented _within_ a question itself.  Currently I know some teams are using email or spreadsheets to track question development workflow.  I think it's much better for the question itself to contain information about this workflow.  For that reason the `[[todo]]` block could be better used.

**Comment by sangwinc** [comment]
@smmercuri, could you please look at the docs in the above commit (https://github.com/maths/moodle-qtype_stack/commit/168c982c0a49ff678052463e906a588b5be8f834 ) which details the discussion @anst-i and I has yesterday.  Please could you talk with colleagues at IDEMS, and decide if this is a helpful way to proceed?  Once we agree what to do, we can decide on implementation (inc. who will sort this out).

**Comment by LukeLongworth** [comment]
My tuppence: I love the idea of a `stack-todo.php` page, as I often jump between various courses without finishing all the tasks as I get weekly quizzes ready to go. This would be a natural way for me to form my own to-do list across multiple courses. Tags wouldn't be that useful for me, as I'm really the only person actively working on STACK in my set of courses, but I recognise that its intended for other sorts of users.

This would also be useful for other teachers without STACK experience to drop into a question to add it to my todo list with minimal training. 

I also like the future idea of hooking into the Moodle question bank - this was going to be my main request until I spied it down the bottom. Would it be possible to also show it in the Moodle Quiz question page? That way, when I do my regular quiz checks I could just scan the quiz itself for anything new in the todo list.

**Comment by sangwinc** [comment]
@LukeLongworth if you already have the moodle capability "qtype/stack:usediagnostictools" then you can use the dependency checker to pull out a list of questions with [[todo]] blocks.  The goals of this issue are to (1) expose this functionality to any teacher, and (2) help people arrange their "todo" lists in more meaningful ways via tags.  This is to support _teams_ of question authors, checking processes and requests for support in individual situations.  

So, teachers can already "drop into a question to add it to my todo list with minimal training." if you have this capability.  I get fed up with emails saying little more than "can you fix my broken question in linear algebra!".  The reply today could be "Please put in [[todo]]Details of the symptoms of the problem.[[//todo]]" and I'll find it.

Not sure about the moodle quiz question page.  Let's see how well used the basic feature becomes and what demand there is for this feature.

**Comment by sangwinc** [comment]
This branch https://github.com/maths/moodle-qtype_stack/tree/iss1231 now adds support for "tags" in the `[[todo]]` blocks, as suggested here.  These tags are exposed on the _existing_ dependency checker page.  It's now a "mini project" to create a UI for teachers to access the tags.

**Comment by jumazevick** [comment]
This is a great idea, I haven't known much about this until recently. 
Thanks Chris!
