### ISSUE TITLE
Change of behaviour of insert stars?

### ISSUE THREAD

**Issue by timlowe** [maths/moodle-qtype_stack#1233]
If a student enters (eg, as part of an algebraic vector)  i(x+1)+j(2x+3) ,  with "insert stars" turned on (does not seem to matter which exact setting), then the first term is interpreted as i * (x+1) [great!], but the second seems to be treating j as a function. (Similarly for k!) [not so great]

I'm fairly sure this is a change of behaviour.

I have a workaround to overcome this, in the question variables define  j(x):=j*x;
but I suspect I have many unidentified questions where this may be an issue.

Minimal example attached.

Thanks,
Tim

[questions-MATHS-WS-OSEP-Algebraic vectors-20240726-1509.xml.txt](https://github.com/user-attachments/files/16392879/questions-MATHS-WS-OSEP-Algebraic.vectors-20240726-1509.xml.txt)

**Comment by sangwinc** [comment]
@timlowe I've been thinking about this - the real solution would be to add in an option to insert stars when we have "unknown functions".  While the bespoke validator options can forbid these, anything to insert * characters needs to be a core change to STACK.  We have no plans for bespoke syntax modification functions I'm afraid.  This has been asked for a lot over the years, and will be increasingly valuable as STACK gets used more with younger students (children) who have no idea what a function is, but want `x(t+1)` to be `x*(t+1)`.  Your example of `j(2x+1)` is the same really.
