### ISSUE TITLE
Randomisation does not work in Parson's block when ordinals are used as `proof_steps` tags

### ISSUE THREAD

**Issue by smmercuri** [maths/moodle-qtype_stack#1237]
When writing Parson's problems, using ordinals as the tags, and randomising in the Question Variables field as:
```
proof_steps: [
    ["1", "<proof step one>"],
    ["2", "<proof step two>"],
    ...
    ["n", "<proof step n>"]
];
proof_steps: random_permutation(proof_steps);
```
Proof steps are still displayed in order on the question page, so randomisation seems to have no effect. This is only an issue for ordinal tags; for any other tags randomisation still works.

**Comment by sangwinc** [comment]
This is now fixed.
