### ISSUE TITLE
Failing unit test for vendor\bin\phpunit --group qtype_stack

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#124]
I've just done a completely clean install on Moodle 2.8.5+ (Build: 20150417).

The install worked fine, and worked first time. I've also successfully imported the demo course, and this  seems to work.

We now get one failing unit test which we didn't have before on Moodle 2.7+ (Build: 20140626)

----------------------------------------------------------------------------------------
1) stack_maths_tex_test::test_tex_rendering
Failed asserting that 'Your answer needs to be a single fraction of the form <span class="MathJax_Preview"><a title="TeX" href="http://www.example.com/moodle/filter/tex/texdebug.php"><img class="texrender" title=" {a}\over{b} " alt=" {a}\over{b} " src="http://www.example.com/moodle/filter/tex/pix.php/b2539acaaba44bf7a1169e86b3c1b032.gif" /></a></span><script type="math/tex"> {a}\over{b} </script> . ' matches PCRE pattern "~^Your answer needs to be a single fraction of the form <a .*alt=" \{a\}\\over\{b\} ".*</a> \. $~".

/var/www/equiv/question/type/stack/tests/mathsoutputtex_test.php:47
/var/www/equiv/lib/phpunit/classes/advanced_testcase.php:80
----------------------------------------------------------------------------------------

Any idea why this had broken?

**Comment by timhunt** [comment]
This is probably to do with further changes to the Moodle default maths renderering, but I am guessing.

**Comment by timhunt** [comment]
I did a fix for this the other day. Commit 73631986ed83cf669298e35d4b4728420dd0c73c
