### ISSUE TITLE
ordergreat or orderless functions when used in Question variables are throwing errors

### ISSUE THREAD

**Issue by AnupamaSarjoshi** [maths/moodle-qtype_stack#1241]
Hi Chris, 

We have several questions that use ordergreat and orderless functions. But we are getting the error when we preview the question or run the bulk test. We have recently updated Stack to v4.6.0 version, and these used to work fine earlier. Have verified that the questions are using these functions only once in the question variables.

Env details:
Stack: v4.6.0
Maxima: 5.41.0
Stackmaxima: 2024060300
Goemaxima: 1.1.9

![image](https://github.com/user-attachments/assets/c26c718c-80e8-431c-a637-8c7af5eedcfe)

![image](https://github.com/user-attachments/assets/c61ad7d3-6bd2-4830-9879-e39f3b03a33a)

Please find attached the sample example question which is failing. (Attaching the file with txt extension as github didn't allow it to upload as xml)
[questions-A101-22B-Test Ordergreat function-20240802-1556.xml.txt](https://github.com/user-attachments/files/16472324/questions-A101-22B-Test.Ordergreat.function-20240802-1556.xml.txt)

We tried to have a look at it and still couldn't understand the right reason. Please let us know if you have seen it in any other case or if if you could provide with any suggestions to debug would be helpful.

(Though we are seeing this happening only on some of our servers and not all.)

Thanks,
Anupama

**Comment by sangwinc** [comment]
@AnupamaSarjoshi I'm really sorry you are still having problems with `ordergreat`.  

This was fixed as issue #1207  https://github.com/maths/moodle-qtype_stack/issues/1207
and I released the fix in v4.7.0 recently.  I tried your question on https://stack-demo.maths.ed.ac.uk/demo/ (which we updated to v4.7.0 this week) and it does not throw your error.  I think this is now fixed.

**Comment by AnupamaSarjoshi** [comment]
Thanks so much Chris for the quick reply. 

Apologies, I had tried searching for the issues related to ordergreat, but somehow missed this one. 

Thanks again for your help.

**Comment by sangwinc** [comment]
Any time @AnupamaSarjoshi, please raise issues here if you can't find the answer!
