### ISSUE TITLE
Plots not showing after Stack upgrade

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#125]
Good morning,

I just upgraded STACK to the latest version. I run the healthcheck scripts, but the plots don't show up there, even with the plain linux configuration setting, without optimization. Instead I get the text:

Errors
The CAS returned the following error(s):plot([sin(x),x,x^2,x^3],[x,-3,3],[y,-3,3]) caused the following error: plot2d: some values were clipped.plot2d: some values were clipped.

If I run the command in the automatically optimised maxima image, then I get the following result:

sudo -u apache maxima_opt_auto
plot([x^4/(1+x^4),diff(x^4/(1+x^4),x)],[x,-3,3]);
Cannot open load file '/var/wwwstackplot-3638677887-23393183.plt'
line 0: util.c: No such file or directory

rm: cannot remove `/var/wwwstackplot-3638677887-23393183.plt': No such file or directory

I am surprised by the path /var/wwwstackplot-3638677887-23393183.plt. The file exists, but it is placed in the current working directory /data/moodledata/stack. If I run gnuplot manually on this file, then (but only then) a png file with the plot is correctly created in /data/moodledata/stack/plots/stackplot-3638677887-23393183.png.

Some comnfiguration info: 

Maxima 5.28.0 http://maxima.sourceforge.net
using Lisp SBCL 1.0.50

Correct and expected STACK-Maxima library version being used (2015040102).

/* File generated on April 22, 2015, 7:50 am */

/* Add the location to Maxima's search path */
file_search_maxima:append( [sconcat("/var/www/html/moodle/question/type/stack/stack/maxima/###.{mac,mc}")] , file_search_maxima)$
file_search_lisp:append( [sconcat("/var/www/html/moodle/question/type/stack/stack/maxima/###.{lisp}")] , file_search_lisp)$
file_search_maxima:append( [sconcat("/data/moodledata/stack/logs/###.{mac,mc}")] , file_search_maxima)$
file_search_lisp:append( [sconcat("/data/moodledata/stack/logs/###.{lisp}")] , file_search_lisp)$

STACK_SETUP(ex):=block(
    MAXIMA_VERSION_NUM:28,
    MAXIMA_PLATFORM:"unix",
    maxima_tempdir:"/data/moodledata/stack/tmp/",
    IMAGE_DIR:"/data/moodledata/stack/plots/",
    PLOT_TERMINAL:"png",
    PLOT_TERM_OPT:"large transparent size 450,300",
    DEL_CMD:"rm",
    GNUPLOT_CMD:"/usr/bin/gnuplot",
    MAXIMA_VERSION:"5.28.0",
    URL_BASE:"!ploturl!",
    true)$
/* Load the main libraries */
load("stackmaxima.mac")$

Platform: unix
Maxima shell command: /usr/local/bin/maxima
Maxima initial command: load("/data/moodledata/stack/maximalocal.mac");

Friendly greetings,
Mikael

**Comment by sangwinc** [comment]
Well, I'm very sorry about this indeed.

This issue arose as a result of https://github.com/maths/moodle-qtype_stack/commit/b5c6f8a86fe816deb4be7990320809a1fc3c5ad7 which is to support a new version of Maxima on Windows.

I did test this on [Maxima branch_5_35_base_87_g454731b http://maxima.sourceforge.net using Lisp CLISP 2.49 (2010-07-07)] and it worked find on linux.

However, going back a few versions, to [Maxima 5.27.0 http://maxima.sourceforge.net
using Lisp GNU Common Lisp (GCL) GCL 2.6.7 (a.k.a. GCL)] on linux this does not work.  At least I could reproduce the problem.

Thank you for such a helpful and swift bug report.  Please see the latest commit.
https://github.com/maths/moodle-qtype_stack/commit/e2f0c4c4a0b9ad446eb5a81e1d6ec1b2c730cdce

Chris
