### ISSUE TITLE
STACK breaks if 'forceclean' is enabled

### ISSUE THREAD

**Issue by geichelberger** [maths/moodle-qtype_stack#1252]
If you enable `forceclean` for your Moodle instance, STACK is not working correctly because the stack-iframe-holder div id gets stripped, breaking the `create_iframe` javascript function.

`Uncaught TypeError: document.getElementById(...) is null`
```js
create_iframe(iframeid, content, targetdivid, title, scrolling, evil) {
          const frm = document.createElement('iframe');
          frm.id = iframeid,
          frm.style.width = '100%',
          frm.style.height = '100%',
          frm.style.border = 0,
          !1 === scrolling ? (frm.scrolling = 'no', frm.style.overflow = 'hidden') : frm.scrolling = 'yes',
          frm.title = title,
          frm.referrerpolicy = 'no-referrer',
          evil ||
          (frm.sandbox = 'allow-scripts allow-downloads'),
          frm.srcdoc = content,
          document.getElementById(targetdivid).replaceChildren(frm),
          IFRAMES[iframeid] = frm
        }
```

The cleanup happens in `$question->format_text` before that line `$questiontext` contains the div with an id.

https://github.com/maths/moodle-qtype_stack/blob/ab90b2a6d22d6343934f8ee0f8e5d793caf79ba8/renderer.php#L56-L72

**Comment by gergelyrakoczi** [comment]
This would be great to fix.

**Comment by EJMFarrow** [comment]
In principle, adding the div id as a class and searching for that if the id is missing seems to fix things.
https://github.com/maths/moodle-qtype_stack/commit/444019e149c04b4ee2ccf03cce8f225324d1b42d
(Includes an extra check in input.js for #743)
Any thoughts, @aharjula ?

**Comment by aharjula** [comment]
Well if it works... However, I do have to wonder what exactly is it with `id`-attributes that so troubles the cleaning logic? Are they somehow generally considered evil, or is this about cutting down scripting by making targeting by `id` difficult?

Would a data-attribute work or would it too be cleaned away? If so then maybe we could use e.g. `data-stack-iframe-id` instead so that we would not need to use `class` as that does have another role in the world in general. If that would work, then we could avoid having that fall-back in the logic.

**Comment by EJMFarrow** [comment]
Thanks, @aharjula . Yes the cleaning does seem... severe... but I'll give the data attribute a go. If it doesn't get wiped, l'll check for that in our code but I'll leave the id on the element as well in case anyone else is relying on it.

**Comment by EJMFarrow** [comment]
Data attributes also get wiped. 🤷‍♂️

**Comment by MalteHellwig** [comment]
Hello Everyone, now for a non technical guy... is there a fix coming or a workaround, without diabling the forceclean or manipulating the code of the plugin?
I can follow your thoughts just a little... Since we also have the problem, a fix would be fantastic.

Greetings,
Malte

**Comment by aharjula** [comment]
More complicated fix is coming, the one tried here worked but did not solve the underlying issue. I am sure more discussion will happen in https://github.com/maths/moodle-qtype_stack/pull/1272
