### ISSUE TITLE
Corrupt Files in download

### ISSUE THREAD

**Issue by stusmith32** [maths/moodle-qtype_stack#1255]
**input_algebraic_test.php** and **input_notes_test.php** seem to be corrupt in the download zip file for version **2024072400**
I have downloaded it on 2 different laptops with the same results.

**Comment by sangwinc** [comment]
That's odd!  I've just downloaded the .zip from github, and I can't reproduce the problem.

What form is the "corruption" taking, and where did you download this from?

**Comment by stusmith32** [comment]
![screenshot](https://github.com/user-attachments/assets/1101ecf8-98e5-4f09-b9a4-e40df6c15f25)
I have downloaded it again and attached a screenshot of opening it from the zip and also direct from the file

**Comment by sangwinc** [comment]
Well, that file is automatically created by pulling the code from github to create the .zip.  I've just downloaded that file and opened it.  I can't reproduce the problem there either!  Perhaps you could obtain the code via https://github.com/maths/moodle-qtype_stack
