### ISSUE TITLE
Multiplication Sign Option

### ISSUE THREAD

**Issue by georgeionutionita** [maths/moodle-qtype_stack#1256]
The Multiplication sign option controls how multiplication signs are displayed. There are 4 possibilities: Dot, Cross, Only numbers, and None.

I would like to have multiplication only between numbers, but choosing 'Only numbers' produces a cross not a dot.

![image](https://github.com/user-attachments/assets/b398c983-3aff-44e0-8502-e928ae39645d)

I am aware of the existence of the STACK function `make_multsgn(ex)`, but I would like to have the same behavior for the whole question.

Would it be possible to have two 'Only numbers' choices? One that uses the cross, and one that uses the dot?

**Comment by sangwinc** [comment]
Please add `texput(multsgnonlyfornumberssym, "\\cdot");` to the question variables.

See https://docs.stack-assessment.org/en/Authoring/Options/#multiplication
