### ISSUE TITLE
Quick start videos in the local documentation

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#1259]
STACK versions have been released at an impressive rate recently and we start to have more and more situations where people have different versions and it has become necessary to say that one should check "https://yourmoodle.whatever/question/type/stack/doc/doc.php/" if it mentions a particular feature there before trying to look for the newest and fanciest features too hard.

In general, it has been nice to instruct people to use the local docs if they want to be sure that the docs match their version as the project site does not have the option to display docs of an older version (would be nice to have a dropdown in the corner to select some recent ones). But now I heard about someone trying to go through the quick start and not finding the videos that are mentioned in it. As those videos ar nice, it would be nice if they would be available there as well.

**Comment by sangwinc** [comment]
Thanks @aharjula that's an oversite due to more vigorous cleaning of Moodle contents.
