### ISSUE TITLE
Short Math in moodle V4.4

### ISSUE THREAD

**Issue by EslamYoussif** [maths/moodle-qtype_stack#1261]
I have a concern about ShortMath I tried to use the plugin in Moodle 4.4 but it doesn't work .
Is there any version that works with moodle 4.4

**Comment by sangwinc** [comment]
Yes, if this is the plugin you are talking about https://moodle.org/plugins/qtype_shortmath then it's looking for new maintainers and doesn't work with moodle 4.  You are welcome to ask the STACK community to help https://stack-assessment.zulipchat.com/#  But, this isn't an issue with qtype_stack so I'm going to close the issue on this tracker.
