### ISSUE TITLE
texput? Wasn't this allowed back in the old stack?

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#127]
Hi,

I have been asked how to ensure that certain things get the correct layout, basically meters and other units and constants would not get outputted in italics. Many years ago I used the texput function to redefine the way various things were represented in the LaTeX code, basically I said texput(m,"\\texrm{m}").

But now stack did not allow that it just said "Unsupported keyword: texput."...

Could we maybe allow that function? It really does not cause too much damage. Now ff we could also make it so that those texputs would also apply in the validation system, that would be great, but I don't really expect that to happen...

http://maxima.sourceforge.net/docs/manual/maxima_13.html#texput

-Matti

**Comment by sangwinc** [comment]
Sorry Matti, this is fine with me.  I'll commit a change which fixes this in to master.

**Comment by aharjula** [comment]
Thank you, this helps my life. Yet another thing I would not need to remember to change myself after an update.
