### ISSUE TITLE
Validation not shown

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#1270]
Hi,

In the attached multi-language question, I see no validation on my system, neither in Swedish nor in other languages.

Best,
Mikael

[No validation shown.zip](https://github.com/user-attachments/files/17162539/No.validation.shown.zip)

**Comment by aharjula** [comment]
So if I understand correctly, the question is whether AJAX validation should be active if "Student must verify" = "No"? Might be nice as the validation is still being displayed after one presses "Check"...

**Comment by alcarola** [comment]
Thanks a lot for the speedy help! Indeed, I turned on "Student must verify", and now the validation is displayed.

I interpreted "Show the validation" as controlling whether the validation is shown, and "Student must verify" as something else.

Am I the only one finding the naming/functions of these options confusiong, or something be changed here?

**Comment by aharjula** [comment]
I doubt anything has changed related to this in the last five years, maybe even last ten years, but I did not look at the history for that.

Typically, "student must verify" is combined with no validation display at all and people do not notice a thing then. 

But as it controls whether the student must absolutely certainly have seen the validation message before the input can be graded, it does not necessarily immediately mean that validation could not also be displayed and thus the [AJAX validation setup code](https://github.com/maths/moodle-qtype_stack/blob/9b82f7fd0ef2160b44add4002073ecabe39913d3/renderer.php#L125-L138) should probably not rely on [this](https://github.com/maths/moodle-qtype_stack/blob/9b82f7fd0ef2160b44add4002073ecabe39913d3/stack/input/inputbase.class.php#L1348-L1350) but instead on whether there actually are any validation boxes...

**Comment by aharjula** [comment]
Do note that when you set "student must verify" = "no", your students very specifically do not need to wait for anything things will be graded on the check button press. By default that is "yes", and people tend to turn it to the other value only when they do not want to display validation or maybe when they want to run the thing at maximum speed/minimal clicks and don't ever want to wait for validation to display.

Red your last line a bit fast and though you were asking if something has changed, that is the reason for the history comment. You are perfectly free to suggest better terms and push them down to the localisation. To me, however, the key thing is that the former parameter is not really the thing that should control instant/AJAX validation, but that is something that needs some more thought and opinions on whether AJAX validation is even an option anymore, surely we could assume it to be there always...

**Comment by alcarola** [comment]
Okay, thanks a lot for your input, and for considering this!
