### ISSUE TITLE
Comma as decimal separator not working with DropDown fields

### ISSUE THREAD

**Issue by lassnj** [maths/moodle-qtype_stack#1277]
Hi, 
we are having the same issue as discussed in https://moodle.org/mod/forum/discuss.php?d=459949. When we use the comma as decimal separator in combination with a DropDown field, we get the error message
```
The input has generated the following runtime error which prevents you from answering. Please contact your teacher.

The model answer field for this input is malformed: [[1;false;"Draht A"];[2;false;"Draht B"];[3;true;"Beide Drähte erwärmen sich gleich stark."]]. The teacher did not indicate at least one correct answer.
```
![grafik](https://github.com/user-attachments/assets/e22ee9e9-ee41-4112-ae6f-a6276d5ce972)

When using the dot, the question works without problems. 

I'm enclosing the question so that you can reproduce the issue:
[quizStromdichte.ErwaermungKomma.zip](https://github.com/user-attachments/files/17288514/quizStromdichte.ErwaermungKomma.zip)

Thanks a lot for this great plugin!

**Comment by sangwinc** [comment]
Very sorry about that.  The above fix will be in the next release.

**Comment by lassnj** [comment]
wow that was fast. You just made someone very happy. Thanks a lot 😺 !
