### ISSUE TITLE
; in question variables, inside strings that is...

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#128]
Hi,

Typographically focused users found this little problem... 

Imagine question variables like these:

tmp: integrate(blaah(x),x);
tmp: tex1(tmp);
tmp: ssubst("{\\;\\textrm{d}x}","{\\;dx}",tmp);

The point obviously is to take the TeX-code and replace that cursive "d". But what you get is:

You are missing a quotation sign ". You have a missing right bracket ) in the expression: tmp: ssubst("{\\. You have a missing right bracket } in the expression: tmp: ssubst("{\\. Unknown operator: \.The brackets are incorrectly nested in the expression: \\textrm{d}x}","{\\. Unknown operator: \.You are missing a quotation sign ". You have a missing left bracket ( in the expression: dx}",tmp). You have a missing left bracket { in the expression: dx}",tmp). A comma in your expression appears in a strange way. Commas are used to separate items in lists, sets etc. You need to use a decimal point, not a comma, in floating point numbers.

The problem seems to be that the statements get splitted at semicolons no matter where those are, even inside strings.

In this case we can do with tmp: ssubst("\\textrm{d}x}","dx}",tmp); but I am not so sure that this problem can be skipped so easily in the future.

This is from 3.4 but probably the same in 3.3 as it also applies to equiv_input.

Would probably need logic to identify whether the semicolon is inside a string before splitting. Or maybe we already have that and I missed some sort of a escape system? 

-Matti

**Comment by sangwinc** [comment]
Thanks Matti,

Yes, I fully agree that STACK is currently sloppy in the way we treat the inside of strings.  Really we should not be looking inside the strings when we validate. This would be a relatively simple thing to add to the CAS string validation routines.

However, in this case I think we should address the underlying issue at the CAS level!  I've already done this for the diff operator around here.

https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stacktex.lisp#L161

So, the solution would be to add the following to 

https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stacktex.lisp

(defprop %integrate tex-int tex)
(defun tex-int (x l r)
  (let ((s1 (tex (cadr x) nil nil 'mparen 'mparen)) ;;integrand delims / & d
	(var (tex (caddr x) nil nil 'mparen rop))) ;; variable
    (cond((= (length x) 3)
	  (append l `("\\int {" ,@s1 "}{\\;\\mathrm{d}" ,@var "}") r))
	 (t ;; presumably length 5
	  (let ((low (tex (nth 3 x) nil nil 'mparen 'mparen))
		;; 1st item is 0
		(hi (tex (nth 4 x) nil nil 'mparen 'mparen)))
	    (append l `("\\int_{" ,@low "}^{" ,@hi "}{" ,@s1 "\\;\\mathrm{d}" ,@var "}") r))))))
 

The principal behind STACK has always been to solve things at a mathematical level where at all possible, not to "bolt together" strings if we can avoid it.....    

Do you agree here?  If so, I'll add it to the branch and add in some unit tests.

**Comment by aharjula** [comment]
Thank you professor,

Yes, obviously if we already have the correct diff we should have the matching int and removing the need for these kludges with the strings would always be the better solution. For now it would fix this problem perfectly.

But as to the strings, eventually, we really should get things through the validation and at the minimum through this splitting as there will always be those special cases with one of a kind layout "solutions". And I for one really like to generate code directly from Maxima with string operations...

**Comment by sangwinc** [comment]
Thank you Matti,

This turned out to be a rather subtle issue, not with removing and protecting strings, but with the key_vals interface.  The semicolon characters are treated as line breaks.  We "explode" over these when the key_vals are created.  Since you have some semicolons inside your strings this plays absolute havoc with everything else.....

I believe I've pushed changes which fix this bug.  Well spotted!

Also I've pushed changes which make the "d" in integrals Roman.

I've also noticed you will need to escape backslashes in Maxima strings, as per ususal, but I'll leave you to ponder that for now..... :-)

Chris

**Comment by aharjula** [comment]
Thank you,

I will need to setup a 3.3 installation for all these things that our summer workers come up and you fix, so that I can actually test if they work before they get merged to 3.4... but before that seems logical...

github also requires escaping so my escaped examples lost some backslashes... But in any case those escapes brought this little string to my mind "\\"", it will probably break this new code in new ways...

-Matti

**Comment by sangwinc** [comment]
Sure enough.... escaped strings break it.

**Comment by sangwinc** [comment]
Ok, I think my last commit should cope with escaped strings.
