### ISSUE TITLE
Document the proof samples, and add in a generic/sample Parsons question to the sample question library.

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#1283]
Please document the proof samples, in
https://github.com/maths/moodle-qtype_stack/tree/master/stack/maxima/contrib/proofsamples
and add in a generic/sample Parsons question to the sample question library.  This can be based on new "DAG" question
https://github.com/maths/moodle-qtype_stack/blob/dev/samplequestions/stacklibrary/Topics/Parsons-DAG.xml
but that would mean adding a graph for the assessment into each proof.  We have to decide if these proofs need interleaving.  Otherwise, just a simple question is fine.

**Comment by hayden-MB** [comment]
It may be useful to have some information about general feedback. If you have alternative proofs you will need some info in the GF. For example if we have two alternatives we have: 

>Notice this proof has two sub-proofs, which can occur in any order.  Therefore we have two >correct versions of this proof.
><table><tr>
><td><div class="proof">{@proof_display_para(tal[1], proof_steps)@}</div></td>
><td><div class="proof">{@proof_display_para(tal[2], proof_steps)@}</div></td>
></tr></table>
>Can you see the differences between these proofs?

Whereas this would be redundant in a proof with only one correct answer. We could either have GF in the contrib file or maybe a seperate contrib file with generic GF for 1 or multiple alternatives. Alternatively we leave this task to the question author, but it feels like half a job if its not complete.

**Comment by hayden-MB** [comment]
I think this may call for an [[if]] or [[for all]] block. This will be limited though, and I fear hard coding which will break for an esoteric example.

**Comment by hayden-MB** [comment]
This should work! 

[[if test='len1>1' ]]
Notice this proof has {#len1#} sub-proofs, which can occur in any order.  Therefore, we have {#len1#} correct versions of this proof.

<table><tr>
[[ foreach x="makelist (n,n, len1) " ]]
<td><div class="proof">{@proof_display_para(tal[x], proof_steps)@}</div></td>
[[/ foreach ]]
</tr></table>
Can you see the differences between these proofs?
[[/if]]

**Comment by sangwinc** [comment]
The example above with two proofs is a nice idea, and works well in this case. I think if we have more than two proofs it's really going to get cluttered and not look at all sensible.  Perhaps we can just show one proof in the worked solution of the generic proof question.  That example, with two proofs, could be an example in one question or in the docs.  

We have one example proof with a graph, and I don't expect we will have graphs for all the proofs.  Perhaps we could add that feedback to two of the proofs from this question.
https://github.com/maths/moodle-qtype_stack/blob/dev/samplequestions/stacklibrary/Topics/Parsons-DAG.xml
Again, we don't need to display all possible proofs!

**Comment by hayden-MB** [comment]
How do we feel re: organisation of these questions. We could do:

- stacklibrary
  - Topics
    - All questions based on topics docs

or

-stacklibrary
  - topics
    - docs
      - [Questions lifted directly from docs]
    - other examples
      - calculus
      - ...
  - templates
    - parsons' proof example
    - ODE 1st
    - ODE second
    - ...

The second is more organised but has rather a lot of file depth. Open to alternative suggestioins of course.

**Comment by sangwinc** [comment]
@hayden-MB good to start the discussion here.  I've already made a special top-level directory for "Doc-Examples" for examples which match up to "things" in the docs.  I had in mind these would be different from template type questions and "topic" examples.   See 
https://github.com/maths/moodle-qtype_stack/tree/iss1283/samplequestions/stacklibrary

Perhaps we could Zoom call to talk about the whole design?

**Comment by hayden-MB** [comment]
NOTE: we will need to back and edit question decriptions on these questions to point to the correct place in the docs
