### ISSUE TITLE
Allow student input like inverse_erf(x)

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#1292]
Currently the input inverse_erf(x) is rejected as "invalid" for student input.

This is a result of the 402 filter applied here.
https://github.com/maths/moodle-qtype_stack/blob/master/stack/input/inputbase.class.php#L955

To allow this input we need an option to disable this filter for a particular input (and users will also need to add inverse_erf(x) to the allowed words for the input).

This is a very useful filter, and needs to be there by default.  It could be considered a little over-zealous for more advanced users.

**Comment by aharjula** [comment]
One might want to think if 402 should, in addition to the static security-map identifiers, leave the allowed words alone. The filter does have access to those through the cas_security object.

**Comment by sangwinc** [comment]
Thanks @aharjula that's a very helpful suggestion, and means we need no further options.
