### ISSUE TITLE
healthcheck page images?

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#130]
&lt;div class="stack\_plot">
    &lt;img src="" alt="&lt;br">
    'https://server/question/type/stack/plot.php/stackplot-3643085822-57136044.png'&lt;br>

    alt=&lt;br>
    'STACK auto-generated plot of
    [x^4/(x^4+1),(4*x^3)/(x^4+1)-(4*x^7)/(x^4+1)^2] with parameters
    [[x,-3,3]]' /&gt;
  &lt;/div>

Just to let you know, probably only applies to 3.4... I spent some time trying to understand why I did not get plots until I finally understood that just the html-was broken. So watch what you put in the alt-text...

-Matti

**Comment by sangwinc** [comment]
Matti, thanks for the warning.  Do you have suggestions for checking the alt text? If so, please go ahead and add these to the code base!
