### ISSUE TITLE
"Send general feedback to the CAS" feature for "Equivalence reasoning" and "Text area" input types

### ISSUE THREAD

**Issue by jonaslache** [maths/moodle-qtype_stack#1311]
Hello everyone,

I've come across a strange behaviour with the "Send general feedback to the CAS" feature, which can be accessed via the Question Dashboard. This affects the input types "Equivalence reasoning" and "Text area". When using this feature, the variable `ans1` is not formatted as a list but instead has line breaks inserted (just as students would enter their answer in the input field). However, this leads to a syntax error. In my case, this wasn't a problem as I quickly realised what's happening and converted the value of `ans1` into a list. Nevertheless, I thought it was worth reporting. Here is a screenshot:

![Screenshot](https://github.com/user-attachments/assets/bbe4791c-4acc-4e6a-b7bd-e9d097606f79)

Best regards,
Jonas

**Comment by sangwinc** [comment]
Sorry about that!  Thanks for reporting this - it will be fixed in the next release.
