### ISSUE TITLE
Validation hangs and latex not rendered

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#132]
Hi!

We observed the following. Preview [this example](https://www.dropbox.com/s/h59wvgyer6ovzmz/timeout%20bug.xml?dl=1) in the question bank, try entering `N*2^(1/5.1*t)` to see the validation hang until the CAS times out. Press the Check button and wait until the CAS times out again to see that the answer is correct.

Preview the example again and now press Fill in correct responses. This goes instantly through the validation, but for some reason the latex code is not rendered, see the attached screenshot. Pressing Check immediately confirms that the answer is right, but still the latex is not rendered.

![screenshot from 2015-06-17 11 45 37](https://cloud.githubusercontent.com/assets/1645276/8205428/3aeda344-14f9-11e5-82fa-69fceb0f8bce.png)

Maxima 5.28.0 using Lisp SBCL 1.0.50

Stack:
$plugin->version   = 2015052000;
$plugin->requires  = 2013101800;
$plugin->cron      = 0;
$plugin->component = 'qtype_stack';
$plugin->maturity  = MATURITY_STABLE;
$plugin->release   = '3.3.3 for Moodle 2.6+';

Friendly greetings,
Mikael

**Comment by aharjula** [comment]
LaTeX rendering should be independent from all those maxima details. Is MathJax working with everything else?

-Matti

**Comment by alcarola** [comment]
Thanks for your quick and helpful response, as always! Yes, it works almost everywhere.

I write "almost", because surprisingly, in [this](https://www.dropbox.com/s/y0r3yl8v40tih0t/No%20validation.xml?dl=1) example, I get no validation at all, although validation is switched on. Only when I press Check, I see how my answer was interpreted, but the latex code is unrendered. In other questions the validation and rendering works just fine.

**Comment by aharjula** [comment]
Thank you for confirming my suspicion here. So basically, the JavaScript side of the AJAX-validation does not call MathJax update if the response takes too long or if it fails to return specific things?

I guess Chris and Tim will take it from here...

**Comment by sangwinc** [comment]
Yes, I can reproduce this bug.  Thanks for reporting it.  I don't think this is a timeout issue or a CAS problem.  I didn't get the LaTeX displayed with the answer "2".

To make the bug "go away" put the some LaTeX in your question stem to make sure the JavaScript is being called.

**Comment by aharjula** [comment]
Oh... so MathJax is not even loaded for pages that have no LaTeX content and as the content here is added to the page after the page loads there is no MathJax to process it. Good to know.

**Comment by sangwinc** [comment]
I've committed code which partially fixes this when a student has to manually validate their answer.  This does not work when there is no mathematics in the question text, and when the (Ajax) instant validation is being used.  The following can be inserted at line 79 of render.php to ensure the question stem always has some mathematics, and hence MathJax picks up the instant validation.

        // This hack ensures there is always some mathematics to be displayed.
        $questiontext .= '\(\,\)';

I'm sure the above is not the correct approach!  I'm sorry, but I don't understand enough about Moodle filters or the Ajax validation to make more progress, but I hope this is a sufficiently specific bug report that Tim can easily finish this job off.

**Comment by alcarola** [comment]
Thanks a lot for the clarification!

Did I understand correctly, that you could not reproduce the cas timeout?

**Comment by sangwinc** [comment]
No I didn't reproduce the CAS timeout.....

**Comment by timhunt** [comment]
The odd thing is that our validation JavaScript contains

```
        if (typeof MathJax !== 'undefined') {
            MathJax.Hub.Queue(["Typeset", MathJax.Hub, this.validationdiv.getDOMNode()]);
        }
```

OK, I think this is a general problem with how Moodle does MathJax, and I can't work out the answer on my own. I have created https://tracker.moodle.org/browse/MDL-50629. I will come back to this tomorrow.

**Comment by alcarola** [comment]
Strange that you cannot see the validation hang. I could reproduce it in Ubuntu/Firefox, OsX/Firefox, and OsX/Chrome. I re-imported the question I linked in the OP, and i cleared the stack cache. I even did a git pull on stack and moodle 2.8 half an hour ago.

**Comment by sangwinc** [comment]
Thank you very much indeed for posting this problem.

I've recreated and fixed what was actually a bug in the algebraic equivalence test.  Validation does quite a lot (e.g. establish "same type") which calls a range of functions you might not expect.....  

Sorry it has taken me so long to fix this.  It was an important bug.
