### ISSUE TITLE
text editor warning

### ISSUE THREAD

**Issue by hayden-MB** [maths/moodle-qtype_stack#1328]
Our prep server has plain text editor as the default, but if you are on this default you will still get the editor warning since it detects as 'default editor' rather than plaintext. Not a massive issue but possibly worth flagging as it could confuse users. 

![image](https://github.com/user-attachments/assets/9ee846fc-0946-4c6c-aa16-4c1b95c4b092)

**Comment by sangwinc** [comment]
Sorry about that!  My basic logic failed in looking at the user preference (default) rather than the editor currently being used....
