### ISSUE TITLE
Empty string should not have quotation marks printed

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#137]
If ans2 >= 0 then the following cas text correctly prints out a plus sign:
@ if(sign(ans2)=neg) then "" else "+" @
However, if ans2 <0, then the quotation marks are output, whereas in wxmaxima nothing is output.
Or is there a simpler way of avoiding expressions like "a - -3" if you want a-ans2 and ans2 happens to be negative?

**Comment by sangwinc** [comment]
Thank you.  I think the previous inconsistency should be considered a bug, which I've fixed.
