### ISSUE TITLE
Feature request: multiple choice input

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#138]
Would it be worthwhile to make a multiple choice input type for STACK? I want to ask for a particular solution to an ODE with given initial conditions, and a multiple choice part where the students choose the appropriate behaviour of this solution as the independent variable tends to infinity. (With randomized parameters as well.)

**Comment by sangwinc** [comment]
This is already on the feature request list!
https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Developer/Future_plans.md

I'm not going to have time to code this in the near future, but as you say it would be a very useful additional input.

**Comment by alcarola** [comment]
Ok, for now I solved it by asking for an integer corresponding to a particular description.
