### ISSUE TITLE
Not-equal-sign for input-box and turning off the automatic feedback

### ISSUE THREAD

**Issue by C0untC0unt** [maths/moodle-qtype_stack#139]
Hi!

We created some questions about fractions with variables as part of the denominator. Aside from the correct value of the variable, the students are asked to give the value(s) that are not allowed for it. Unfortunately, we did not find a way to type a “≠”-sign (or a combination of signs for it) into the input box. Are there any options for this?

Another question is:
Is it possible to avoid the automatic feedback about the right answer which appears under every question?
Example: https://www.dropbox.com/s/vulg0nykgkreztk/Stackproblem%20-%2001.jpg?dl=0
(The black box)

**Comment by sangwinc** [comment]
I've not received a request for a not equals sign!  Domain constraints are very much in my mind at the moment, so this question is very relevant indeed to some other things I'm working on.  

In Maxima we could define an operator for "not equal to" as something like <>.
infix("<>");
p:x<>y;

Then we can still display this in the following way with tex:

texput("<>","{\\neq}", infix);
tex(p);

So, adding a new operator would be no problem.  We can define it to be commutative and associative (if we wanted to).  I'm likely to add something like this in the very near future, so watch this space.

Automatic feedback about correct answers.  This should be controlled by the Moodle quiz options. Are you using Moodle or ILIAS?  I'm not sure of the options available in ILIAS for this.  It is a function of the quiz environment, not of STACK!
