### ISSUE TITLE
STACK demo server

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#144]
Hi!

I wanted to contact a few people about the possibility (and some advantages) of using STACK in teaching, but I cannot access the demo server at stack.bham.ac.uk/moodle/. I think I saw Chris use a demo server in his presentation yesterday, can someone please provide me with a link?

Mikael

**Comment by sangwinc** [comment]
Mikael,

That is odd!  Yes, I'll investigate.
Please also try http://matsrv6.bham.ac.uk/moodle/
This has a copy of the demo course.
Chris

**Comment by sangwinc** [comment]
Thanks for letting me know.  Some network level issue has now been resolved.
