### ISSUE TITLE
CAS timeouts, non checked answers and quiz-modules autosubmit feature and the fail of Moodle cron...

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#147]
Hi,

A new problem that might just be a problem with MaximaPool but I fear it is more. The situation is as follows:
1. There exists a question that asks for big things to be simplified to small things... and uses AlgEquiv to check, which is not that smart. Maybe verification has also been disabled.
2. There exists a student that instead of simplifying inputs even bigger things, that student does not press check for those things.
3. The quiz has been configured to auto submit open attempts at deadline.
4. Moodles cron job does just that and submits all things, even things that have not been checked or have failed checking, but then it meets this special answer that times out and crashes there. Blocking the evaluation of the cron-job and causing all sorts of problems.

Has anyone else had similar issues? Do we know what to do if this happens other than finding out who built that question and making it disappear? Is there anything that could be done to protect against this?

-Matti

**Comment by aharjula** [comment]
Never mind, this is probably just an issue with MaximaPool.

**Comment by sangwinc** [comment]
Can you be more specific Matti?  Some things "look big" but are not really... !

**Comment by aharjula** [comment]
In this case it is indeed a valid time out case: ATAlgEquiv(258552*x^7*(81*x^8+1)^398, x^3*(x^4+1)^399), the answer is either malicious or badly misunderstood. Naturally, the question itself is bad as it would basically time out every time the answer is wrong or presented in somewhat different form.

**Comment by timhunt** [comment]
This is not specific to MaximaPool. I remember something similar came up once before. I remember Chris mentioning it. I can't find the issue now. (I don't think it was #86.)

**Comment by aharjula** [comment]
Actually it is specific, to the current faulty MaximaPool the pool did not actually return valid time outs instead it returned servlet errors which caused exceptions as STACK side. And those exceptions broke the Moodle cron, with time outs the STACK would just have given zero points for the attempt and Moodle cron would not have noticed anything.

**Comment by sangwinc** [comment]
Thanks for reporting this Matti,

I'll look at the example from a CAS point of view.  We'd want everything to
degrade gracefully if the CAS timesout, so there may be something with the
MaximaPool as well.  I'll see what happens on the direct connection.

**Comment by aharjula** [comment]
The symptom i.e. the blocking of the cron-job was fixed by fixing the pool. Basically, the cron-job won't get blocked if there is a time out and STACK knows it is a time out, but now we threw an exception instead.

https://github.com/maths/stack_util_maximapool/commit/8c91506142e548eeef32bc5c32bf46b5a02ed08a and https://github.com/maths/stack_util_maximapool/commit/a9705d56594a35c2971f8b55ba5c8eaf509d8651 are the fixes for both variants of the pool.

**Comment by aharjula** [comment]
Everyone should have already upgraded their MaximaPool so no need to keep this open and visible.
