### ISSUE TITLE
Problem with scientistic notation

### ISSUE THREAD

**Issue by jcopado** [maths/moodle-qtype_stack#148]
In a question where you have to convert to scientistic notation 0.0000006306, the correct answer, 6.306*10^(-7) is said to be wrong, because the system expected 6.30699999999*10^(-7). I would like to attach the xml file of the question but it's not possible here, so please, anyone who can try to reproduce this bug, please contact me here and I cand send the XML file. This bug was found in the ILIAS version of the plugin but I could reproduce it in the Moodle version 3.3.

**Comment by sangwinc** [comment]
Please send me the .xml file to C.J.Sangwin@ed.ac.uk and I will look into this.  Floating point numbers are problematic on computers as rounding of one kind and another exist in many places.  We may have fixed this already. See the commit

https://github.com/maths/moodle-qtype_stack/commit/873f52fa0a4133fbb44268b5af05a2d3b7033184

**Comment by sangwinc** [comment]
Ok, I've tried your question on the latest (Maxima) code through Moodle of course. 

0.0000006306 is marked as correct and a rounding in the 4th significant digit is marked as incorrect.  

I notice you are using the EqualComAss test, not the numerical tests.  Is there a reason for this?
