### ISSUE TITLE
Error: STACK does not currently support the following plot2d options: \([[x,-4,4]]\)

### ISSUE THREAD

**Issue by azampa** [maths/moodle-qtype_stack#153]
Hi,

I get the very strange error *STACK does not currently support the following plot2d options: \([[x,-4,4]]\)* when saving the question in the following very straightforward situation:

**Question variables**
x1 : -rand(5);
y1 : rand(9)-4;
x2 : 1+rand(4);
y2 : rand(9)-4;
a : (y2-y1)/(x2-x1);
b : y1-a*x1;

**Question text**
... @plot(a*x+b,[x,-4,4],[y,-4,4]))@

If I change the plot command to

@plot(a*x+b,[y,-4,4])@

the error is not reported (and no error concerning [y,-4,4] is issued) but when previewing the question the CAS times out:

_qtype_stack_question : CAS error when instantiating the session: The CAS returned the following error(s):plot(a*x+b,[y,-4,4]) caused the following error: The CAS timed out. CAS failed to return any data. x1CAS failed to return any data. y1CAS failed to return any data. x2CAS failed to return any data. y2_

Observe that I'm using plot commands in other more complex questions without any problem, e.g. in a question I use

@plot(f[k],[x,-8,8],[y,-8,8])@

where f is a list of functions of different types defined by means of various random parameters, k is a random value, and I get no errors complaining [x,-8,8] is not supported, moreover no timeout arises.

The system runs STACK 3 with maxima 5.23.2 on SBCL lisp and a unix-optimised platform (no maximapool). The healthchek runs smoothly and the timing section reports a time of about 0.1.
Timeout is set to the default value 10 but if I increase it to 30 the problem continues to manifest itself. Please help me solving this issue. Thanks

Alessandro

**Comment by sangwinc** [comment]
Alessandro,

I have to say I'm rather at a loss what to suggest here since you report a working system with plots being produced in more complex situations.  Can you please send me an .xml of the whole question to C.J.Sangwin at ed.ac.uk and I will try to reproduce the problem myself.  

I suspect your random numbers are generating a floating point overflow, or calculations which time out. Does this fail for all random versions or just some?

Chris

**Comment by azampa** [comment]
Dear Chris,

the real problem is not that of timeout, but the fact that a supported option (i.e. *[x,-4,4]*) is not recognised by the system! I think that the time out issue is of secondary importance since, probably, the plot command is somehow compromised due to an unknown problem which arises along the way from the question editor to maxima. Let me explain: when I enter the complete command

@plot(a*x+b,[x,-4,4],[y,-4,4])@

and then click on *VERIFY THE QUESTION TEXT AND UPDATE THE FORM* no error is issued, but if I try to *SAVE CHANGES AND CONTINUE EDITING* or to *SAVE CHANGES* the question is not saved and the above mentioned error is issued. This behaviour should not be expected since, I guess, the verification should correspond to a syntax check of the question and any unsupported option would be spotted at this point. Instead, when saving maxima compels about an option which the CAS supports, saying that it is unsupported by STACK (i.e. by the plot command of STACK)!

I am not able to save the question unless I delete the option *[x,-4,4]* from the plot command. When I delete it and save the question I get the timeout problem: this issue does not allow me to test or deploy any random version! Wether I try to preview the question from the question editor or from the list of questions in the category, I always get a time out...

I sent you an email with the xml export of this question and of another one for comparison.
Thanks

Alessandro

**Comment by sangwinc** [comment]
Thanks very much indeed for reporting this, which is a bug.  The random numbers you have chosen result in the zero function.  So you are trying to plot something like @plot(0,[x,-2,2],[y,-3,2])@.  The STACK code tries to guess which variable you are using in your function.  Compare @plot(t,[t,-2,2],[y,-3,2])@ and @plot(x,[x,-2,2],[y,-3,2])@.  Where you have specified the variable as "x" but the expression you are plotting has no variables in it (i.e. is a constant expression) then the plot gets rejected.  This is a bug and I will post a fix.

**Comment by sangwinc** [comment]
A fix should now be in the master branch.  If you have further problems please re-open this.
