### ISSUE TITLE
Conflict with multilingual plugin

### ISSUE THREAD

**Issue by azampa** [maths/moodle-qtype_stack#154]
Hi,

I use STACK in a moodle bilingual site in conjunction with the multilingual content filter *filter_multilangsecond_moodle29_2014033100*. Almost all questions suffer of some bad behaviour concerning the selection of the language used to show content to the user. As you can see from the snapshots below, the multilingual filter is somehow blocked and all the content is displayed, the multilingual selectors {mlang} being ignored. This happens sometimes in the feedback only and sometimes both in the question and in the feedback.
Since I don't know if the problem originates in STACK, or in the multilingual filter, or in Moodle (which has some errors, e.g. in the title of blocks - that I managed to solve - and in the name of the grading categories), I'm taking a gradual approach to get a solution, starting with STACK. Could you please check if all text is correctly handled concerning any kind of filter?
Thanks

Alessandro

![question](https://cloud.githubusercontent.com/assets/15650840/10940273/c929fff2-8305-11e5-99c9-e73900312ca2.jpg)
![feedback](https://cloud.githubusercontent.com/assets/15650840/10940283/d0bdff98-8305-11e5-939a-b16f690f04dc.jpg)

**Comment by sangwinc** [comment]
Alessandro,

This is the first I've heard of the multi-language filter.  Thanks for pointing it out.  I've been asked by various colleagues over the years if we can produce some mechanism for multi-language questions and I've always suspected this was not a problem "STACK" should solve!  So, I'm glad to hear there is a more general moodle solution to the problem, but I'm sorry its not working.

STACK tries really hard to do things in the "correct Moodle way", indeed Tim Hunt has been very strict with me over the years!  

Can you recreate the problems with other question types in the quiz, or does this problem really look like it belongs to STACK?

I don't think we are doing anything which would break the later filtering, e.g. transforming the text in strange ways (e.g. protecting characters here and there).  Indeed, we rely on the MathJax filter to display mathematics, and so on.  

I'd like to get this feature working with STACK because other people have asked me for it, so if you are willing to try to produce a minimal question which does not work, and give me some instructions for how to use the multi-lingual filter I'll certainly look into it.  I'll also try to work with other STACK developers to clean up our code not to break the text you add.

One thought as I type: is the editor we use in the STACK forms adding special characters to your text?  This occasionally happens with pasting HTML tags your can't easily see which breaks the MathJax.  Just a thought.

Please give me some examples and I'll try to help.

Chris

**Comment by azampa** [comment]
Dear Chris,

I tried to see if other question types show the same problem. With matching questions and with calculated questions all works perfectly, while with the embedded answers (cloze) question I observe a similar problem.Therefore it should be a problem of the question type, not of moodle per se.
It seems that the editor is not adding any special character so I am really baffled.
The filter works as follows: you simply have to enclose the text written in some language inside the tags **{mlang** _code_**}** and **{mlang}**, where *code* is the code of the language: the filter shows this text only if the language selected by the user (e.g. the browser) is that corresponding to *code*. This is done at the text level, not at the HTML one, and works like MathJax substituting \\( and \\) with the above tags. The support documentation of the filter reports that it should be better to have a closure tag and a following opening tag on the same line, so an example of use is the following:

**{mlang en}** This text will be displayed only if the selected language is English...
**{mlang}{mlang it}** This text will be displayed only if the selected language is Italian...
**{mlang}** This text will be displayed whatever language is selected, even if it is turkish...

It is simply that. I sent you an email containing the export of three questions showing different behaviour. The simplest one works correctly, the others, which are more complex, not.
I hope you find these examples useful.
Thanks again

Alessandro

**Comment by sangwinc** [comment]
Thanks for sending me the questions.

I've installed the language filter (and another language!).  The language filter works when I use the old style <span> tags from the docs, e.g. 
        <span lang="XX" class="multilang">your_content_here</span><span lang="YY" class="multilang">your_content_other_lang</span>

However, when I use your style tags
{mlang en}English{mlang}
I don't get it to work anywhere!  Any hints on this?  

I've installed the following plugin:

/**
 * Version details
 *
 * @package    filter
 * @subpackage multilang
 * @copyright  1999 onwards Martin Dougiamas (http://dougiamas.com)
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$plugin->version   = 2014051200;        // The current plugin version (Date: YYYYMMDDXX)
$plugin->requires  = 2014050800;        // Requires this Moodle version
$plugin->component = 'filter_multilang'; // Full name of the plugin (used for diagnostics)

**Comment by azampa** [comment]
This is not the filter I'm referring to. Try to install the correct plugin from the page https://moodle.org/plugins/view/filter_multilangsecond

**Comment by sangwinc** [comment]
Ok, I've installed the plugin you've suggested with Moodle 2.9 (For various reasons I've set up a new machine this weekend from scratch).  

I wrote my own question with {mlang en}...{mlang} tags in every CASText field (except the question note which students don't see).  My question worked with the language filter no problem.  I also tried your question "{mlang en}Identify from graph{mlang}{mlang it}Identifica dal grafico{mlang}"  (Nice question by the way!).  This worked fine as well.  So, I'm sorry but I can't recreate your bug.

I really like this plugin for multi language support and so I hope we can get it to work for you.  If so, it solves a problem I've been worrying about for a while, as this functionality has been asked for before.  What should we try next?

**Comment by azampa** [comment]
Well, I don't know what to say... Do you confirm that the feedback of my question you tested displays correctly? On my site that question is displayed correctly for what concerns the question text, but not regarding the feedback, which is displayed in both languages with the {mlang} tags visible.
Have you tried my question "{mlang en}Direct cubic proportionality{mlang}{mlang it}Proporzionalità cubica diretta{mlang}" too? On my site both the question text and the feedback are not touched by the multilingual filter...
I upgraded to the latest version of Moodle (the site was already built with Moodle 2.9, but not with the latest subversion) and nothing changed... My other installed custom plugins are only joomdle to integrate moodle with joomla and the theme Klass: is it possible that the theme interfere with the filter? No, I think...

**Comment by sangwinc** [comment]
Hi there,
I've set up the mult-language filter you suggested (with non-HTML setting) on another server this evening, and imported your "Direct cubic proportionality" question.  The title doesn't get translated, but the rest does as with my other server last night. Below is a screen shot.  Do you get something different?

![multi-language](https://cloud.githubusercontent.com/assets/781615/11104809/dadd2978-88c2-11e5-8a51-aa55b5722857.png)

**Comment by azampa** [comment]
I have exactly the opposite situation: the title is translated (however it does not appear inside the preview window, I can see it only in the title bar of that window: is this related with the theme I'm using?) while the question text and the feedback not, see the screen shot.
![screenshot](https://cloud.githubusercontent.com/assets/15650840/11105508/9076c094-88cf-11e5-8c61-cb0f99193862.png)

**Comment by sangwinc** [comment]
Ok, very tedious if I can't reproduce it.  How should we proceed?

**Comment by azampa** [comment]
Hi Chris,

   for the moment I would like to put aside the problem of the multilingual filter to consider another issue explained by the screen shot you find below: in this question text the multilingual filter works (not on the feedback, though) **_BUT_** the MathJax filter fails. As you can see the text has the following structure:

*{mlang en}Some text and a latex formula correctly displayed*
*{mlang}{mlang it}The same text translated in italian and the same latex formula  correctly displayed*
*{mlang}*

*@plot command@*

*{mlang en}Some text and a latex formula not filtered with MathJax*
*{mlang}{mlang it}The same text translated in italian and the same latex formula not filtered with MathJax*
*{mlang}*

*Other plot commands within a numbered list*
*[[input:ans1]]*
*[[validation:ans1]]*

I hope you can replicate this issue. Now, the fact is that things go this way even if I cancel the {mlang} tags, i.e. it should no more be a problem of the multilingual filter, which should not be called into action by the system. **I observe that if I delete the first plot command from the question text then the second formula gets to the MathJax filter and is displayed correctly!** Therefore the issue should be (maybe :flushed:) ascribed to the way STACK elaborates CASText.
If this is the case then the issue I'm describing here may be connected to that concerning the multilingual filter.

I send you by email the XML export of this question (and of others of the same kind) and I really hope this can be helpful.

Regards

Alessandro
![screenshot-2](https://cloud.githubusercontent.com/assets/15650840/11211708/a3439cb8-8d31-11e5-9b86-c38216c9f75e.png)

**Comment by azampa** [comment]
Hi,

I forgot to say that I'm using the multi-language filter with Non-HTML setting as you do on your servers...

Alessandro

**Comment by sangwinc** [comment]
Ok, I can reproduce this issue and it is easy to fix.  Your question text has a lot of "span" tags and I believe these are interfering with MathJax (not the plot option in STACK).  This is nothing to do with the language filter.

![screenshot - 181115 - 09 27 48](https://cloud.githubusercontent.com/assets/781615/11237337/241a4a8a-8dd7-11e5-9ecd-d94deb3d0d3d.png)

To fix this problem

1. Select all in the editor.
2. Copy the text and paste it into a plain text editor (I used gedit on unix) to strip out all the HTML formatting elements.
3. Delete all the question text in STACK.
4. Copy back the cleaned up text from your plain text editor into STACK.

You can see the raw HTML in the editor if you press the buttons in the picture above.

Yes, I know the editor shouldn't let you create bad HTML, but it does.....  (This isn't my editor it is a Moodle component)

Below is the result of this cut and paste clean up operation.

![Uploading Screenshot - 181115 - 09:29:09.png…]()

**Comment by sangwinc** [comment]
Is it possible this kind of problem is also at the heart of your multilingual filter problems?

**Comment by aharjula** [comment]
Looking at the [code](https://github.com/vanyog/moodle-filter_multilangsecond/blob/master/filter.php) of that filter the spans should not be your problem especially if you are using the non html mode. Nor should those spans be a problem for MathJax either unless there is yet another filter doing something else to them before MathJax. 

It might be helpful to see the raw HTML code served when things fail, and by the raw code I mean code that has not gotten modified by the scripts. There might be additional symbols among the code coming from encoding or filter issues. Do not save an open page from a browser as that has already been processed by the scripts instead save a links target (or use Firefox web-consoles [network activity tab](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor) and save the raw response contents).

**Comment by azampa** [comment]
Excuse me for the length of this post, but I have some hopefully usefull things to say... :sweat_smile:

I agree with Matti: spans should not be a problem. Indeed, after playing a bit with that question I came to observe that it is exactly the presence of the span around the plot command that results in the second formula not to be parsed by MathJax: if I remove that **and only that** span (and move its style to the HTML paragraph \<p\> enclosing it) the formula is displayed correctly. Now, this is the only span containing CAS commands (the STACK plot function) and the other do not corrupt MathJax. With this I am not implying that the faulty behaviour is necessarily caused by STACK, I :innocent: merely observe the possible existence of some connections since all the other spans can remain there and all works fine. Until this problem is not solved (please tell me if you intend to look further into it) I will move the styles from spans to paragraphs and cancel the spans, however I would really need to fix this issue since the editor automatically puts style into the span and not into the paragraph! Since you can reproduce this issue maybe it is really due to STACK, but surely you can investigate in more detail...

Next. I have followed the suggestion of Matti concerning the raw code of the page: using the *web-console network activity tab* of Firefox I looked into the raw response of the first GET command of the question preview window, but I found no additional symbols. To be sure, I send you by email the HTML file **Question.html** that has no viruses. Of course check if it has, and then look by yourself if I missed something (if you don't find it in your messages please look at the spam filter).

My moodle site runs only three filters: MathJax, the multilingual filter and the multimedia plugins. I tried disabling one at a time and both issues continue to show: even if I disable the multimedia plugins and the MathJax filter I have problems with the multilingual filter. Even if I disable the multimedia plugin and the multilingual filter the issue with MathJax persists.

Coming to the issue with the multilingual filter, from the same file Question.html I observe that the page content has already passed this filter when the page is loaded, indeed I don't see the {mlang} tags and the text is already that corresponding to the language selected. However, if I give any answer to get the feedback, I see that in the new page the question text is already parsed by the filter as before (it displays only one language) while the feedback section shows both. I don't send you the corresponding raw HTML file, anyway among the network events triggered in order to build the content of the page I see calls to MathJax but not to the multilingual filter.

Moreover, I tried canceling all spans from all CASTexts and the issue with the multilingual filters persists: while the question text shows only the language selected, the feedback shows both. Do you confirm that this question shows the feedback correctly on your servers? I seem to understand from your screen shots that you are using moodle on some pc (probably where you have installed some server such as apache), while I'm working with a "real" server. Mine is running on unix: yours? Is it remotely possible that the different behaviours we get are to be ascribed to the type of server?

Finally, I remembered another issue I encountered before, so I added in the question text of this last question, just after the first formula and in the same line, the text '*with \\(x\in\mathbb{R}\\)*': the result is that the presence of *\mathbb{}* ruins the action of the multilingual filter in the question text too (it is exactly this command the cause, since if I remove it and leave just *\\(x in R\\)* then there are no problems). Are you able to reproduce this issue? This should imply some conflict between MathJax and the multilingual filter, but somehow this does not agree with the fact that the multilingual filter seems to be applied before MathJax (see the above comments). As I said in my first post, I don't know if all this is caused by STACK, but I need to know exactly that it is not its fault before turning to others.

For now that's all :wave:

Alessandro

**Comment by azampa** [comment]
Finally, a little breakthrough regarding the multilingual filter! :trophy:

Looking at other questions I made, I found an issue similar to the one regarding *\mathbb{}* I explained in my previous post: I have checked that whenever the CASText contains a latex formula with curly brackets *{* and *}* inside, as when you have *\frac{}{}*, or *\mathbb{}*, or *\sqrt{}*, the *{mlang}* tags do not work, and if I remove those brackets the multilingual filter does its job (but the latex formulae are obviously wrong). Can you reproduce this behaviour? Is STACK giving some special meaning / attention / elaboration to curly brackets? Notice that whenever the CAS returns a fraction, or a root, ... its result translated into latex needs curly brackets...

However :sob:, I also have other questions **without** curly brackets inside latex formulae that are not correctly translated by the multilingual filter...

**Comment by azampa** [comment]
I would like to add a little comment concerning the previous post: the faulty behaviour in presence of curly brackets is not to be ascribed to the multilingual filter since all calculated questions I have, which use constructs such as {a} to represent variable values randomly assigned, are correctly treated by the multilingual filter.

Alessandro

**Comment by aharjula** [comment]
I have not received any mail but I did look at the code of that filter again and if my reg-exp reading is any good this pattern [```'/(?:\{mlang\s+.+?\}[^{]*\{mlang\}){2,}/is'```](https://github.com/vanyog/moodle-filter_multilangsecond/blob/master/filter.php#L53) seems to be a bit problematic. If I understand it correctly one cannot place '{'-chars between ```{mlang XX}``` and ```{mlang}```.

So basically the filter is not compatible with LaTeX as it has curly braces, and as STACK outputs most things in LaTeX stuff breaks. As to your latest comment calculated questions replace the {a} with the value of a thus removing the curlies from the code before filter processes it.

I would recommend trying the HTML-mode of that filter as it does not seem to have this kind of an issue. 

But in any case I would think this issue is not caused by STACK it is just due to the design decisions of the filter and would think we should close this issue.

**Comment by azampa** [comment]
Ok, Matti: I made some more experiments on titles of activities and on calculated questions and I confirm that whenever '{'-chars are **between** {mlang XX} and {mlang} the filter breaks down, therefore this issue is not caused by STACK. I will write to Vanyo Georgiev asking for a more robust filter, since it is better if students use the Non-HTML mode instead of the HTML one.

It remains the problem of compatibility between STACK and MathJax I found in the last example concerning the plot command and spans: I would prefer to fix this issue too, and solving it would surely make STACK more robust. I sent the above mentioned file to Chris: I would like to send a copy to you so you can look at it, but I have not your email... This problem is independent of the multilingual filter, indeed if I remove the {mlang} stuff (and I did) it persists. Thus, I leave to you the choice to close this issue (maybe opening another concerning this last problem) or to keep it open in order to solve the span matter.

Alessandro

**Comment by azampa** [comment]
Hi, there are good news: not having been notified about an update, I used an older version of the multi-lingual filter. The last version of the filter works properly, so you can recommend to anyone who needs it.
Alessandro
