### ISSUE TITLE
Problems that occure while working with multiple input-boxes

### ISSUE THREAD

**Issue by C0untC0unt** [maths/moodle-qtype_stack#157]
Hello,

These are two problems that we have faced.

1)  We don’t find a proper way to check if an input-box is left empty by the student.
For example when a PRT is dealing with more than one student-answer and the first one isn’t answered, the following inputs don’t get a specific feedback even if they might have been filled (doesn’t matter if correct or not).

2)  When a question is constructed as combination of two answers and a positive score is given it is always the maximum of the reachable points. Even if the answer isn’t completely correct.
For example is “ans1” correct and “ans2” not, then the result should be 1 of 2 points. However there are always 2 of 2 points given. We checked every step in our tree and couldn’t find a mistake in the way the points are granted. That’s why we think this might be a bug.

Kind regards,
Alex

**Comment by aharjula** [comment]
Probably a quick answer for the second one, had probably the same today...

The marks defined in PRT-nodes are basically percentages of the total given by that PRT so if you are giving 2 points from that PRT and the nodes should give 1 point each, the nodes should have 0.5 as the modification of the mark. It caps the grade to 100% so giving 1+1 i.e. 200% does not get shown.

**Comment by sangwinc** [comment]
Thanks Matti,

To deal with (1), the idea in the design is to have multiple PRTs.  Each PRT is considered independently.    If you can assess ans2 independently of ans1 you should have a PRT that does just does this. So, in some situations you will end up with 3 PRTs for two inputs.  One PRT for each input separately, and then one PRT for both inputs together.  

This removes the problem of having complex code for letting the author specify when to ignore empty or invalid inputs.  

I hope this makes sense?  If you send me an example I can make more specific comments.
Chris

**Comment by sangwinc** [comment]
This issue is addressed by the "allowempty" option for inputs, and also the new formative PRT suggestions in issue #573
