### ISSUE TITLE
Problem with penalties and self-tests after questoins have been backed-up and restored

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#159]
1. In Moodle, in the past, md_question.penalty was stored in quite a sloppy way.
2. Then, at one point we tightened up, and made sure it was always stored to 7 decimal places. (So, 0.3333333).
3. As part of this change, we made it so that backing-up/restoring, or importing, old questions fixed up the data. https://github.com/moodle/moodle/blob/26653c8b5c69879e9ff166055d96c5b0b6fcaf17/backup/moodle2/restore_stepslib.php#L3976
4. STACK does not enforce that question.penalty must have 7 decimal places. It allows a penalty of 0.3333.
5. So, when you roll-forwards a course containing questions like that (that is OU jargon for making a copy of a course with backup and restore ready for a new presentation), then question.penalty is set to 0.3333333, but mdl_qtype_stack_qtest_expected.expectedpenalty is not changed.
6. As a result, in the rolled-forwards course, many question tests fail.

**Comment by timhunt** [comment]
My suggested fix is:

1. Add form validation, so you cannot create a STACK question with penalty 0.3333. It insists on 0.3333333. (And similarly for around 0.6666667)
2. Add a database upgrade step, to change any values in mdl_question.penalty or mdl_qtype_stack_qtest_expected.expectedpenalty that are close to 1/3 or 2/3 to the exact values.
3. Change the STACK restore code to do similar approximate -> exact penalty fixes (so that if someone backs up questions before this fix, then imports after this fix, the questions still work.)
4. Similarly for Moodle XML import.

With luck I will be able to implement this in January 2016.

**Comment by sangwinc** [comment]
Tim,

I'm in favour of tightening up these kinds of things, and fitting in with such decisions on Moodle unless there is a very good reason to do something different.  This might be a silly question, but will I be able to have a penalty of 0.3?  Will I have to type in 0.3000000?

Where will we cut off the rounding to 1/3?

Chris

**Comment by timhunt** [comment]
The backup/restore code I linked to before https://github.com/moodle/moodle/blob/26653c8b5c69879e9ff166055d96c5b0b6fcaf17/backup/moodle2/restore_stepslib.php#L3976 does

```php
        if ($data->penalty >= 0.33 && $data->penalty <= 0.34) {
            $data->penalty = 0.3333333;
        }
        if ($data->penalty >= 0.66 && $data->penalty <= 0.67) {
            $data->penalty = 0.6666667;
        }
```

I was proposing to use the same logic. So, 0.3 is safe.

**Comment by sangwinc** [comment]
Ok, fine with me.
Thanks Tim

**Comment by timhunt** [comment]
Proposed fix for this. Would anyone like to comment before I put this into Master? https://github.com/maths/moodle-qtype_stack/compare/wip159?expand=1

**Comment by sangwinc** [comment]
Tim,
I've read the code and have no objections.  Thanks for doing this.
Would you like to merge or should I?
Chris

**Comment by timhunt** [comment]
I'll merge this on Monday.

**Comment by timhunt** [comment]
Sorry. Pressed the wrong button!

**Comment by timhunt** [comment]
Fix now added to master.

**Comment by sangwinc** [comment]
Thanks very much Tim.

**Comment by timhunt** [comment]
Sorry, I missed one that that broke restore of backups. Extra fix pushed.
