### ISSUE TITLE
Using the same variable in the forbidden list and as tans

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#160]
Suppose you have a question variable 'ta' which is the correct answer to the question. Then, you probably want to put ta in as the Model answer for ans1.

However, you probably also want to add ta to the list of forbidden words, so students can't just type ta as their answer.

If you do that you get the PHP warning when you attempt the questoin (although apart from ths the question works fine).

```
Warning: strpos(): Empty needle in /fs1/www_root/tjh238/vle/question/type/stack/stack/cas/casstring.class.php on line 1039
Call Stack
#	Time	Memory	Function	Location
1	0.0014	362624	{main}( )	../questiontestrun.php:0
2	11.5440	39976648	question_usage_by_activity->start_question( )	../questiontestrun.php:172
3	11.5440	39976880	question_attempt->start( )	../questionusage.php:554
4	12.1110	39999304	qbehaviour_adaptive->get_right_answer_summary( )	../questionattempt.php:987
5	12.1110	39999304	question_graded_automatically->get_right_answer_summary( )	../behaviour.php:69
6	12.1111	40000120	qtype_stack_question->summarise_response( )	../questionbase.php:663
7	12.2028	40002280	qtype_stack_question->get_input_state( )	../question.php:414
8	12.2030	40006056	stack_input->validate_student_response( )	../question.php:481
9	12.2030	40006488	stack_input->validate_contents( )	../inputbase.class.php:284
10	12.2040	40007440	stack_cas_casstring->check_external_forbidden_words_literal( )	../inputbase.class.php:404
```

Here is a minimal test-case question. [questions-C100-13B-Forbidden example question-20151118-1805.txt](https://github.com/maths/moodle-qtype_stack/files/38179/questions-C100-13B-Forbidden.example.question-20151118-1805.txt)

Import it and preview it with Moodle deubgging turned on to see the problem.

(If you remove a from the forbidden list, you can type a into the answer box and get marked right.)

Thanks to my colleage Ray for finding this error in our server logs.

**Comment by timhunt** [comment]
Just to be clear, the attached file is a moodle .xml file. However, I had to rename it to .txt before I could upload it here. You should still be able to import it into Moodle.

**Comment by timhunt** [comment]
Also, for further clearness, this is not an issue I feel qualified to work on myself. I am hoping someone else can work it out.

**Comment by timhunt** [comment]
Great. Thanks Chris. I thought you would probably have ideas about this.

**Comment by sangwinc** [comment]
Tim,

The mechanism is in place and appears to be working.  See
https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/casstring.class.php#L991

We have unit tests of this. E.g.
https://github.com/maths/moodle-qtype_stack/blob/master/tests/walkthrough_adaptive_test.php#L365
It is important students can not enter question variables and so I made sure it was in place, so I was surprised (and rather worried) when you raised this issue!

Now, looking at the casstring checking method we have ignored single letter variable names.  So your example of "ta" should be trapped, and it appears to me to be trapped in my version of STACK.  Your minimal example uses a single letter variable.  These do *not* get rejected as invalid, even if the teacher has used them.  This must have been a design decision (not a bug) but I can't remember why.  Sorry, it is late and I'm on a very old and slow laptop (my raspberry pi has 4*the power....)  after my main one died a couple of weeks ago.

At this moment I can't see why I did this.  But I'd rather sleep on it, and hope someone else can remember why we did this....  But if you want to change the behaviour and run the unit tests, please do so.

**Comment by timhunt** [comment]
Sorry, Chris. The case I tested was with a one-letter variable 'a' as in the attached export file.

I only changed it to 'ta' in the issue description, to make the variable name stand out more from the surrounding text than 'a' did. I did not realise that the number of characters was significant!

I could guess that the reason not to block single-character variable names is because of the questions where you want students to write their own equations, without telling them the variable names to use.

Perhaps we just need a really strong recommendation in the documentation that question authors should always use multi-character question (and prt) variables? (I suspect enforcing this in the form validation could be a step to far, but it might be worth considering?)

**Comment by aharjula** [comment]
Tim beat me to it, the obvious reason is obviously that we wish to leave single char names free to the students.

I don't think forbidding single char variable names from the teacher would be a bad idea I think it is actually a brilliant idea. The way it fixes things that people do not even know are problems by simply renaming something irrelevant is just perfect. Naturally, adding this will cause some validation issues but the long term benefits from this could be very much worth it.

**Comment by sangwinc** [comment]
The validation only rejects variable names the teacher has used. I want to give some thought to not letting teachers use single variables. This change might create a huge amount of question editing!

Yes, we need to document this.

**Comment by timhunt** [comment]
We could try another complex two-step validation thing (like with deleting parts of the question) where it rejects single-var names when you try to save the form, but gives you a checkbox to say "save this question anyway". The validation message could link to the relevant docs.

That would probably stop people from creating new questions with single char var names, without making it impossible to edit existing questions.

I don't think it is easy to write a database query to find all the questions with single-char var names. It would be possible to write a PHP script to do it, if we wanted to get a handle on how many such questions are out there.

**Comment by sangwinc** [comment]
Perhaps we could check the "model answer" field in the input for a single variable name?  This would stop teachers from using single variables as the correct answer without stopping them putting single variables in the question variables.  So, we have at least four options.

(1) Do nothing (except document better).
(2) Forbid anything in the student's input which is used by the teacher (1 letter variables or more).
(3) Forbid the teacher using single letter variables in question variables.
(4) Forbid the teachers using model answers which are single letter variable.

My vote (currently) would be (2) or (4).  I'd object to (3).  I've been living with (1) [Indeed I probably coded it!], so this is fine for now.  Comments/votes?
