### ISSUE TITLE
Conflict between the plot command and MathJax

### ISSUE THREAD

**Issue by azampa** [maths/moodle-qtype_stack#161]
Hi,

following the discussion in issue #154, I confirm that the plot command of STACK breaks the functionality of the MathJax filter. Even if in the above mentioned discussion the problem seemed to arise from some \<span\> inside the HTML code of the CASText, I produced a question where the unwanted behaviour shows up without any \<span\>: the problem is that this occurs in the validation field, therefore students can't understand if their answer has been interpreted correctly by the CAS. Look at the screen shot below. After clicking on the CHECK button, when the feedback is shown, the formula gets displayed correctly.
Chris, I send you the export of this question so you can look with more detail into this issue.

Alessandro

![screenshot-5](https://cloud.githubusercontent.com/assets/15650840/11301481/c1661b4a-8f97-11e5-9eac-9966b1c361ef.png)

**Comment by sangwinc** [comment]
Alessandro,

Sorry about the delay in responding to this.  This is actually nothing to do with plots. I think this is because you are using instant validation in a question where there is no mathematics displayed with MathJax anywhere else on the page.  The Ajax does not trigger the MathJax scripts, so the instant validation does not get picked up!  This is a bug, obviously.  

Can you please confirm this is the case?

**Comment by azampa** [comment]
Hi Chris,

yes, I confirm that when there is no mathematics displayed the instant validation does not get picked up (other questions I recently produced, even without plots, show this behaviour).

**Comment by sangwinc** [comment]
Good!  We have reliably recreated the bug.  Sorry it took me so long to respond.  I've been more than 3 weeks without a computer (well apart from my trusty Raspberry pi of course....)

For now, put `\( \)` in the question text of any offending question and the problem should go away.  This will trigger the mathjax.  I'll sort out a better solution in due course and post a fix.

**Comment by sangwinc** [comment]
I think we have fixed this issue now, so I'm closing it.  Please reopen if the problem reoccurs.
