### ISSUE TITLE
Trouble with missing statistics packages

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#162]
Hello,

We just pulled the latest master branch and noticed that our probability and statistics exercises stopped working. I found [this commit](https://github.com/maths/moodle-qtype_stack/commit/75f4ea0abcd0bde46ead6da3f978b0fd5269f5a2) and uncommented the loading of the three stats packages. This temporarily fixed the problem for us, but are my changes not likely to be overwritten when I update STACK the next time?

One option would of course be to write in the documentation that Debian (and other) users need to make sure they have the statistics packages, but I don't know if this is any good.

Thanks!
Mikael

**Comment by sangwinc** [comment]
Thanks Mikael,

I'm sorry about this.  Commenting out the loads in the code are only intended as a temporary measure.  Without this, people couldn't install STACK at all. Thanks for opening an issue.

I can't figure out a way to autodetect this problem. I have tried.  I think we may have to add another option, which again makes install problematic.  Does anyone have suggestions about this?

Chris

**Comment by sangwinc** [comment]
Mikael,

I've added an additional option to let users load optional Maxima packages.  The default is to load the packages which are causing a problem, but to load them in such a way that failure does not bring STACK to a grinding halt.  This mechanism is extensible.  I've been asked before for support for various packages, and this will provide one mechanism to support this as well.  Comments on this approach are very welcome indeed.

Chris

**Comment by alcarola** [comment]
This sounds like a good solution to me! In a while we will probably 
switch from the master branch to the abacus branch. I assume the fix 
will eventually find its way into that branch too.

**Comment by aharjula** [comment]
Indeed, the abacus branch will get a merge of most of masters latest commits before christmas.

Now that we have installation specific configurations of packages we may need to think about adding metadata to questions about the packages they need and some sort of a way to tell the importer of questions that they will not work without extra packages... But there is obviously the issue of finding out what packages the questions need, maybe just add the list of packages configured on the installation exporting and comparing it to the situation at the importing side and warning if different.

Also I would like to point out that those specific packages now listed include some of the slowest loading packages and may require pre-loading and as the loading now happens on separate lines outside stackmaxima.mac this may cause some issues if people do not adapt the normal optimisation guides accordingly. Basically, these too will need to be included in the memory images. Anyway, it was good that you chose not to do this through live connections as that would made optimisation with memory-images very difficult.

**Comment by sangwinc** [comment]
Thank you Matti,

Yes, you are right.  These packages should be pre-loaded and not loaded again when we use unix-optimised mode. I've made some changes which I hope will have this effect.

Chris

**Comment by aharjula** [comment]
One little request related to this loading of libraries thing. Mainly from the point of view of the MaximaPool... especially the default configuration of it.

Traditionally, the maxima-output has included the string ```[ STACK-Maxima started, library version 20xxxxxxxx ]``` and the pool has assumed that the process is ready for use when that string appears. But now that string appears before the additional libraries start loading. So in theory if one were to load extra slowly loading libraries the pool would consider processes that are not actually ready to be ready. Not a problem as we can always configure the pool to look for the ```(%iN)``` rows but as the string ```STACK-Maxima started``` seems so obviously sensible string to look for it would be nice if it appeared after the loading is actually complete.

Truly not a major issue, but in theory this has a single technical problem with MaximaPool. The pool limits the number of simultaneously starting Maxima-processes to lessen the load for the file system. But as it could now think that the processes are out of the loading phase before the loading of the libraries is completed there could be cases where a suitable hiccup of the file system would collect abnormally high number of processes that would all be stuck in this loading-libraries phase and once that number get high enough things will break.

So any chance that you could move the printing of ```STACK-Maxima started``` from the end of the ```stackmaxima.mac``` to the end of ```maximalocal.mac```?

**Comment by sangwinc** [comment]
Matti,

I'm very sorry indeed about this.  I didn't test the changes on MaimaPools (due to current lack of hardware).  Please propose a fix and I'll accept it.  There was no good reason for this change.

Chris

**Comment by aharjula** [comment]
Simple fix but probably needs to be noted in the optimized-image documentation.
