### ISSUE TITLE
Option to display multiplication with cross still results in dot displayed

### ISSUE THREAD

**Issue by davidoj** [maths/moodle-qtype_stack#164]
I have selected the option to display multiplication as a cross, but it still displays as a dot in the example quizzes.

I also noticed a castext_test.php script which apparently tests the display of multiplication, but I'm unable to run it (I just tried pointing my browser at it)

**Comment by aharjula** [comment]
Setting that or other default options in the question type settings only applies to questions that do not override those settings and the old examples probably do, try checking the questions inside those quizzes and switching that setting inside them.

The _test.php scripts are for PHPunit unit-testing system and would need it to run. Even then they would not display anything useful for you as they will only tell you if they think the system works or not.

**Comment by sangwinc** [comment]
David,
If this is a genuine bug, please let me know.
