### ISSUE TITLE
Error with forbidden words

### ISSUE THREAD

**Issue by azampa** [maths/moodle-qtype_stack#171]
I observe the following behaviour which I think is a bug: suppose I define a CAS variable *t* with some value (e.g. the correct answer) and I don't want to allow the given answer to contain the variable *t*. Then I insert *t* into the field *Forbidden words* of the corresponding input and select the option *Insert stars for implied multiplication* (**but not the option** *Insert stars assuming single-character variable names* **!**). What I expect is that if one enters as answer *tan(1/2)* the syntax checker does not complain since *tan* should not be broken into the three letters *t*, *a*, and *n* and an occurence of the variable *t* should not be detected. Instead I get the error

`Your last answer was interpreted as follows: tan(1/2)`
`This answer is invalid.`
`The expression t is forbidden.`

Of course I can change the name of the variable (and I do), but I think this issue should be fixed, therefore I post it.
Thanks

**Comment by sangwinc** [comment]
You don't need to insert t into the field Forbidden words of the corresponding input.  The student cannot enter variable names used in the question variables as part of their answer. This is automatic and the teacher can't change this!  This is a design decision not a bug. It means the teacher does not have to remember to forbid things, or to worry about this kind of issue.  You might need to change your variable names if you want the student to use a variable like "t" which you have also used somewhere else in the question variables.

Try removing "t" from the forbidden words, then use the answer tan(t/2).  It should be rejected as invalid as well.  tan(s/2) should be ok (unless s is also a variable of course).

The forbidden words is a simple string match, for good reasons.  You might want to forbid characters such as "*". 

That said, I'm happy to consider alternative behaviors in STACK.

**Comment by azampa** [comment]
Then you have an error: if I don't put *t* in the *Forbidden words* then I can answer using *t* but STACK does not complain, it says I have given the correct answer and gives me the full mark!

**Comment by sangwinc** [comment]
Yes, I'm really sorry the docs are not clear about this.

Some time ago, I decided to allow single character variable names in student's expressions, whether or not they are used by the teacher. I don't want to change this behaviour now (as other things will break) but I have made the docs clearer.
