### ISSUE TITLE
Sample question AlgMap-7.1 is always marked as being wrong

### ISSUE THREAD

**Issue by drachels** [maths/moodle-qtype_stack#172]
I was playing around with the Stack Demo course the other day and I think that question AlgMap-7.1 has an error in it. As it is right now, both legs of the PRT are equal to zero. Shouldn't Node 1 when true have a score of 1 instead of 0?

**Comment by sangwinc** [comment]
Thanks for reporting this.  I've already fixed this problem in the sample materials which will be in the new release.

I'm a little behind updating demo servers etc!  I do appreciate you reporting this.

Chris
