### ISSUE TITLE
NumSigFigs judges correct answer as wrong

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#175]
In random variant 50 of the attached question the NumSigFigs answer test returns wrong in part c of the question, although the answer is right. There is also a PDF-printout of the question preview window in the attached .zip.
[NumSigFigs problem.zip](https://github.com/maths/moodle-qtype_stack/files/102421/NumSigFigs.problem.zip)

**Comment by alcarola** [comment]
Now I have narrowed down the attached question into a minimal example:

(%i1) ATNumSigFigs(0.498,[0.4985,3]);
(%o1) [true,false,"ATNumSigFigs_Inaccurate. ",
       "stack_trans('ATNumSigFigs_Inaccurate'); "]

(%i2)  ATNumSigFigs(0.499,[0.4985,3]);
(%o2) [true,false,"ATNumSigFigs_Inaccurate. ",
       "stack_trans('ATNumSigFigs_Inaccurate'); "]

Am I right when I think that the first of these two returns the wrong conclusion, whereas the second is correct?

Another Finnish STACK exercise developer seemingly also ran into the same problem.

**Comment by sangwinc** [comment]
Thanks for such a helpful error report.   I'll look into this.
Chris

**Comment by sangwinc** [comment]
I've tracked this down to a completely minimal example.  In Maxima, the command 
round(0.5)
returns 0, not 1 as you might expect.  This is the problematic case you have described above. I'm testing a proposed fix to this.

**Comment by alcarola** [comment]
I'm afraid it's not quite that simple. In my example, the first case would not return "inaccurate" if this is the only problem.

In school (in Finland), I learned to always round the number preceding a chopped-off five upwards, but some standard says that you should aways round that number to an even digit. (To avoid systematic errors e.g. in statistics, I guess.)

**Comment by sangwinc** [comment]
Ok, good point.  I've just had a look at this: https://en.wikipedia.org/wiki/Significant_figures#Rounding_and_decimal_places
There seems to be some room for manoeuvre here.  Maxima's round command takes the number to the nearest even digit.
round(0.5)=0
round(1.5)=2
Is this what you'd like?  It would be simpler to stick with Maxima.   Will this confuse users who always round 0.5 up. (as it confused me this evening?)  Round half up is a common rule I think.

Other comments?

**Comment by alcarola** [comment]
We had a discussion about this in the Finnish Abacus STACK project, so the participants there should know about it, in principle at least. I also thought that it is easiest to stick with the Maxima standard; the students should be able to round according to any given rules, anyway.

The problem I was trying to point out with the "minimal" report is that the answer is judged as wrong regardless of which of these two rounding conventions you follow.

**Comment by sangwinc** [comment]
Agreed, we should make sure it works, and also that the docs are clear as to the intended behaviour!  I have to confess, I didn't know about the "round to the nearest *even* number rule"....  !

Could I ask you to canvas the Abacus group and find out what they would like/expect?  If we hard wire this as the default behaviour for now, if other groups would like another option we can consider adding it in the future.

**Comment by alcarola** [comment]
OK, I'll ask if anyone objects to keeping the current Maxima behaviour and return to it here in a week or so.

I was also not aware of these rules before the discussion was initiated in the project.

**Comment by sangwinc** [comment]
Thanks,
Much better I think to have an agreed and documented test here!
Chris

**Comment by christianp** [comment]
We bumped into this a long time ago in Numbas - the "closest even number" rule is called "banker's rounding", and it's an attempt to avoid bias - see http://c2.com/cgi/wiki?BankersRounding. It only matters if you're performing a process which involves lots of rounding, like running a balance sheet. or being a computer algebra system :)
For humans, "round away from zero" is a much more sensible, and easily applied, rule, so that's what we went with. There should be options though - you never know when someone might write a banking question. (Ah! I've remembered why it first came up - the i-assess people got a contract to do e-assessment for the accountancy awarding bodies, so they had to implement banker's rounding in those questions)

**Comment by sangwinc** [comment]
Thanks Christian, that is a real help.
The point here is to choose a specific behaviour, make sure it works, and document it!  There was a bug, which should now be fixed......

Do people need bankers' rounding in STACK at this point?

Chris

**Comment by aharjula** [comment]
As to bankers' rounding, not now but there have been times where we have worked with the business people and they would probably have complained had STACK actually rounded in humane way. We will probably have to work again with those people in the future so ideally STACK should add a new question level option (like the sqrt(-1) display option) that would switch between these rounding methods, and surely the world has even more methods that we might need to handle in the future.

This could also simply be solved inside the sigfigs test by giving it yet another parameter to select the rounding method thus enabling the writing of questions where we use different rules for different things. But I would think that in most cases we want to apply the same rounding everywhere in the question and if someone wants to do something more complex they may just write a bit more of processing code to do so. The most extreme solution would obviously be that the new parameter for answer tests that need to know how to round would just be a function and everyone could write their own rounding rules, naturally the sane ones would already be provided.

I am sure the abacus people will come up with some ideas still but I vote for using the humane way of "rounding half up" i.e. not quite "round away from zero" that is the way I first understood rounding on second grade although I am not quite sure if I got it right...

**Comment by alcarola** [comment]
I asked the Abacus project and, agreeing with aharjula, there was a strong consensus that STACK should make it easy to always round halves up. It was commented that having a question-level switch to use bankers' rounding could be handy, but I got no impression that this was a priority.

**Comment by sangwinc** [comment]
Ok, well the Maxima default is Banker's rounding, and I had to work quite hard to switch it off.  Going back the other way will be easy!  For now I'll add this to the "to do" list.
