### ISSUE TITLE
Units: addition of SI units not reducing to a single value

### ISSUE THREAD

**Issue by whanrott** [maths/moodle-qtype_stack#176]
from stack/version.php: plugin->version   = 2016010901
I'm trying to add two values together with different units. For example:
2*km + 2*m
In WXMaxima these resolve to 
2002 m
In STACK the expression resolves to 
2×m+2×km
Am I authoring this question correctly?
I've tried a range of functions without success. I think that building in the convert function to the maxima LISP image might help. 
http://maxima.sourceforge.net/docs/manual/maxima_81.html#IDX2480

**Comment by sangwinc** [comment]
Sorry, but we are not using Maxima's "Units" package for STACK.  It is much too slow, and results in an unacceptable performance. See the docs at https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/Units.md 

The units code we are using is online at
https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stackunits.mac

We didn't support addition of quantities in mixed units yet.  The support for units is very new, and we assume only the form "number"*"units".  Let's see how much this gets used, what students need.  We can enhance the capabilities later.
