### ISSUE TITLE
Maths in input validation does not display if  the question contains no maths

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#178]

**Comment by timhunt** [comment]
OK, I think I found and fixed the problem that stopped this working in Moodle 2.7. Would anyone like to give this additional review or testing before I put this into master?

**Comment by timhunt** [comment]
Sorry, to be clear, the propose changes are here: https://github.com/maths/moodle-qtype_stack/compare/wip178?expand=1

**Comment by sangwinc** [comment]
Thanks Tim,
I've tested this on a Windows machine with Chrome and IE.  It works.  Great.  Do we need to do more testing?  If not, shall we merge this back into master and delete this branch?
Chris

**Comment by timhunt** [comment]
If you are happy, I am happy. I will merge this into master this afternoon.

**Comment by sangwinc** [comment]
Thanks Tim, please do.
C

**Comment by timhunt** [comment]
Fix pushed to master.
