### ISSUE TITLE
Incomplete documentation for Authoring/Author_FAQ.md

### ISSUE THREAD

**Issue by whanrott** [maths/moodle-qtype_stack#179]
The documentation for [Author_FAQ.md](https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/Author_FAQ.md) in the section "How can I change which Maxima functions STACK allows?" is incomplete:
The sentence "The most important of these for this purpose is" is truncated.

**Comment by sangwinc** [comment]
Thank you, I do appreciate suggestions for improvements.  This is now fixed.
Chris
