### ISSUE TITLE
MathJax + STACK + Chrome, black line

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#180]
Has anyone else seen a black line in the right edge of an MathJax rendered equation on a recent Chrome browser? It seems like we started seeing a single pixel wide black line, that is always present on all MathJax content that is part of a STACK question but maybe not present elsewhere, last week on updated Chromes...

Can anyone reproduce this? We are running on Moodle 2.9 with the normal MathJax filter.

**Comment by aharjula** [comment]
Update 1: Not just a STACK issue applies to the whole Moodle all MathJax content gets that artefact. The maybe in the original issue was a misunderstanding.

**Comment by timhunt** [comment]
Here is a related thread in the Moodle maths forum: https://moodle.org/mod/forum/discuss.php?d=327190

**Comment by aharjula** [comment]
Ok. Thank you for that link we can now close this issue.
