### ISSUE TITLE
PRT::evaluate_response should round a bit more

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#183]
We had an example question at the OU, with a PRT like this:

```
      1
=.33 ( ) =0
      2
+.33 ( ) +0
      3
+.33 / \ +0
```
The .33s were actually to 7 decimal places.

What was happening was that the final result was coming out as score = 0.9999999, penalty = 0.1.

We already have code https://github.com/maths/moodle-qtype_stack/blob/7ecf85b5c6c78f935fae09dd99dfeea5ee977fd4/stack/potentialresponsetree.class.php#L213 that catches scores very close to 1, and mostly treats them as 1, but this was not close enough.

I am proposing we change that to
```php
        if ($results->_score > 0.999999) {
            $results->_score = 1;
            $results->_penalty = 0;
        }
```

Any objections before I do? (I was even wondering about 0.999995.)

**Comment by timhunt** [comment]
Proposed fix on a separate wip183 branch for now. This change does not break any unit tests.

**Comment by christianp** [comment]
I would suggest a more correct option would be to take a continued fraction approximation of the score, stopping when you get within 1E-6 of the float value. The spirit of your proposal is that nobody's really going to specify scores to 7 decimal places, so you might as well apply this across the whole interval instead of just close to 1.

**Comment by timhunt** [comment]
That is, indeed, a beautiful idea. We should do that in future (separate issue) but for now, I think my patch represents a useful step forwards.

**Comment by sangwinc** [comment]
Tim, I'm happy with your suggestion and I'm sure this will conform with the intentions of the question author.  I.e. nobody will notice when you do the "right thing" here....

Christian, that is indeed a great idea.  Do you have code to do this already you are willing to contribute?   ;-)

**Comment by christianp** [comment]
Well, it's in JavaScript in Numbas at https://github.com/numbas/Numbas/blob/master/runtime/scripts/math.js#L1461. It's a simple algorithm, especially if you don't mind accumulating floating point errors, which you shouldn't do here if you're only looking to get within a few decimal places.

**Comment by timhunt** [comment]
Chris ahs merged this into master. Closing.
