### ISSUE TITLE
inverse hyperbolics and log forms

### ISSUE THREAD

**Issue by StackJeez** [maths/moodle-qtype_stack#184]
This may be a maxima issue. Stack does not recognise as correct the inverse hyperbolic forms of the integrals of 1/(x^2-a^2) (i.e. acoth(x/a)/a ) and 1/sqrt(x^2-a^2) (i.e. acosh(x/a)), which feature in the formula book; it only accepts the logarithmic form of the integrals.

**Comment by sangwinc** [comment]
Yes, you are quite right about this StackJeez.  The integration test is particularly complex, and this case was left out, which is a bug.  Thanks very much for reporting this bug.

**Comment by sangwinc** [comment]
I've added a number of test cases (including logs with and without absolute values signs....).  I sincerely hope this is now fixes, but if I've missed something please reopen this issue and let me know.
