### ISSUE TITLE
AlgEquiv failure

### ISSUE THREAD

**Issue by azampa** [maths/moodle-qtype_stack#186]
In some cases the AlgEquiv test fails to detect a correct answer, and this seems to be a Stack issue rather than a Maxima issue. In the attached screen shot (the question is here used in adaptive mode) you can see that Stack says the answer is wrong even if it is the expected one (see the bottom of the picture). In the specific feedback you can see the results of two tests I made: in the first one I compare **ans2** to the expected answer **ss** by means of a maxima command

ok1 : if (ans2 = ss) then 1 else 0;

while in the second I compare a maxima simplification of the answer with the expected answer

sa : map(ratsimp,ans2);
ok2 : if (sa = ss) then 1 else 0;

prt2 test is of type AlgEquiv and is designed to check if **sa** is equal to **ss**: it says _No_ but maxima says _Yes_ (see the value of **ok2**)!!!
prt2 test is set to quiet and if I let it be verbose, then it says that the second entry of the list is incorrect.
Of course, I can obtain a correct behaviour using the value of **ok2** to check if the student's answer is correct but, needless to say, Stack should itself behave correctly without help :wink:.
Chris, I send you the question by email.
Regards

Alessandro

![screenshot-6](https://cloud.githubusercontent.com/assets/15650840/13034051/f1c6ba20-d32a-11e5-9ba7-a37c9e008067.png)

**Comment by sangwinc** [comment]
Thanks for reporting this, I'll look into it further.  

Could you confirm which version of the STACK code you are using?  See the very bottom of the healthcheck script page for the number.  The latest is (2016021200).

The current code has no problems in deciding that -(2*k+6)/(k^2+4*k-12) is equivalent to itself using both ATAlgEquiv and ATEqualComAss.  

I'll look at your actual question and see if I can figure out what is going on.

I agree, STACK should be able to deal with this expression without a problem.

**Comment by azampa** [comment]
My version of STACK is not the last: it is (2015103000). Also, if this can help, due to restrictions on the server I'm running Maxima 5.23.2. As you can see from the image I attached, the question variant that gave me problems is the number 19, which corresponds to the deployed seed 111111000: I didn't check if other variants show the same problem...

**Comment by sangwinc** [comment]
Ok, thanks.
I've reproduced the problem.  It looks like a bug.  Thanks for reporting this.  I'll look into it.
Chris

**Comment by sangwinc** [comment]
I hope this fixes the bug.  Thanks again for such a clear and helpful bug report.
