### ISSUE TITLE
Modifying a question after it has been attempted in a quiz, should not cause fatal errors, e.g. in quiz overdue attempt cron

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#187]
Argh... as we know you can modify a question slightly even when it is being used in a quiz and even re-grade previous attempts using the modified question. But there is a limit to what you can do and I met it today.

Do not change the number of PRTs nor their names in a question while that question is in use. As this causes serious trouble with certain behaviours that handle multi-part questions, typically those problems arise when that question has attempts that reach the auto-submission part of the cron-jobs.

To reproduce:
1. Create a question with three PRTs
2. Get people to answer that question in a quiz (with adaptive mode and autosubmission). Not all submitting their attempts. Some not even answering anything, just opening the quiz.
3. Change the number of PRTs to two, maybe drop one or them all and create new ones.
4. Do a re-grade for the quiz.
5. Optionally add more attempts from more people.
6. Let there be deadline. And then run the cron-job that handles the autosubmission.

You should see errors like "Call to a member function get_required_variables() on a non-object", basically null references to PRTs that do not exist.

The way to fix your stuck Moodle cron is to try modifying that question even more by adding trees named just like the removed ones and/or previous names. And maybe regrading with that. The only sure way is to just delete the attempts.

**Comment by timhunt** [comment]
The code should be modifed so that this sort of thing does not cause fatal errors. Detecting the null, and throwing a moodle_exception instead of causing a fatal error should be an OK fix.

**Comment by aharjula** [comment]
Indeed, this might also be an issue for the behaviour side as if they assume the question parts to be the same between steps and the question gets edited to have different parts they too may explode. Maybe you know better how the adaptivemultipart would react to this.

**Comment by timhunt** [comment]
Well, as you say, the main thing is: people should not do this!

**Comment by aharjula** [comment]
Could ```edit_stack_form.php``` know if the question is in use in a open quiz and warn the people before this kind of an change gets done? Maybe suggest duplication instead...

**Comment by timhunt** [comment]
Yes, one could, but this should not be done in a STACK-specific way. Should be done in Moodle core so all question types benefit.

**Comment by aharjula** [comment]
Ok. So instead of STACK blocking its editor from creating this mess we shall wait for the Moodle to do that for the general case. Any estimates on how long that will take?

**Comment by sangwinc** [comment]
Thank you both for pursuing this.

Tim, are you happy to pursue this through Moodle, or should we try to get something into STACK before I release 3.5?

**Comment by timhunt** [comment]
This is not fixable in the STACK 3.5 time-frame.

https://tracker.moodle.org/browse/MDL-20584 is the issue for dealing with that in Moodle core.

Don't know when anyone will actually fix this.

**Comment by timhunt** [comment]
Hmm. It seems I am an idiot. That is an old Moodle core issue that got closed. We need a new one, with up-to-date description of what should be done.

**Comment by aharjula** [comment]
Just to ensure that you both understand the situation. When that question with changed PRT-identifiers and re-grade hits the auto submission cron job everything gets stuck in such a way that non admin user has basically no way of knowing what broke and the fail breaks the auto submission for the whole Moodle install and it may be that the admins and teachers of that install do not even notice it before the incomplete grades of the students have been pushed forward in the bureaucracy. Its a very bad situation in large scale installs and we can newer be certain that the question authors are aware of this unless we remind them specifically about this when they are doing it.

And by reminding I do not mean a generic warning message saying that you should not edit questions in use, as that is often done and can be done if the basics are understood, the warning should be excessively specific to this PRT situation and require confirmation.

This is even worse than the timeout/MaximaPool issue last autumn as in this case the answers that cause problems are more likely actually valid and deserve points.

**Comment by timhunt** [comment]
Sorry, yes. Will reopen.

**Comment by alcarola** [comment]
I got myself into this situation too. :/

**Comment by alcarola** [comment]
Thanks to aharjula's instructions it was easy to fix, though.
