### ISSUE TITLE
Time out in NumSigFigs...

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#200]
A student managed to answer slightly wrong (merely 960 million orders of magnitude) to a question that asked for an answer with specific number of significant figures. This caused the question and quiz get stuck for that student as Maxima cannot evaluate that test in that case during the normal time out limits. 

Maybe we could have some sort of safety filter in that test that would simply ignore answers that are multiple (maybe ten or just two) orders of magnitude wrong...

Quick testing tells me that just a couple of hundred thousand orders of magnitude tends to break things, which is comforting as that big of an error is rare, but as you can simply typo something and once the value is in your question/quiz is stuck this might require some sort of an fix.

**Comment by sangwinc** [comment]
Matti,

That is a good idea I think.  Perhaps you could suggest some code to test this, (log(n) or (log(log(n)) perhaps?)

Chris

**Comment by aharjula** [comment]
I would simply filter by ```is(sa*10000<ta) or is(sa/10000>ta)``` (with sign logic obviously on top of that) no need to evaluate any logs for this. The error case was basically ```ATNumSigFigs(0.111*10^-960000000,[0.111*10^-180,2])```.

But seems like I have jumped into conclusions here... It seems like the actual problem is with the syntax used by the user and we can't really do anything about it. Just see what happens when you give this instead of that previous sample ```ATNumSigFigs(0.111e-960000000,[0.111*10^-180,2])```. So basically it probably is not an issue in NumSigFigs instead it is an issue with the general handling of the expression ```A*10^B``` opposed to ```AeB```.

So we would probably need to filter those insane exponents in some other way, maybe Maxima has some filter of its own? Otherwise we would need to find that during input validation...

**Comment by aharjula** [comment]
Ok. The major problems in our case were due to the timeout-setting of STACK being high compared to the PHP-timeout setting and while the slowly completing evaluation of this test did not timeout the STACK-maxima-limit it was repeated often enough to timeout the PHP-limit of the Moodle installation thus leading to a crash and repeat as the value can't be changed. 

Lesson learned do not forget to reset your limit from 60s down to a reasonable 10s when you do load testings...

But we still have the problem of evaluation time difference between ```A*10^B``` and ```AeB``` and the little fact that in that ```AeB``` format we must have ```B<0``` or we get problems with start.
