### ISSUE TITLE
Work lost due to question editing form getting stuck with variable names containing digits

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#202]
I used the name c1l that has a digit in the middle for an input, because I forgot that this is not allowed. In the box where the model answer is entered I got the error message that I seem to be missing asterisks. 

After a little while I understood what the problem is and changed the input name to cl1 instead, so that the one is at the end. Upon saving the question, I checked the box that I want to remove the old input c1l from the question as requested and pressed _Save and continue editing_. However, the input was never removed, instead the error message about the missing asterisks kept showing up. 

Hence, once I introduced the problematic variable name, I could no longer save the question and I lost work. Expected behaviour would be that the input is removed when the confirmation box is checked, regardless if the model answer text field has a valid interpretation or not.

**Comment by sangwinc** [comment]
We now have a check for input names.  c1l is permitted in STACK v4.3.
