### ISSUE TITLE
Math and text in MCQ

### ISSUE THREAD

**Issue by lentzi90** [maths/moodle-qtype_stack#203]
I'm trying to make use of a [MCQ](https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/MCQ.md) as part of a question. The goal is to make sure the student chooses the right probability distribution for the rest of the question. So far I have something like this:
```
AnsList: [[1, false, "Normal distribution"], [2, true, \chi^2]];
```

The problem I run in to is that I can't combine math and text in the display field. I would like to have something like `[2, true, \chi^2\text{-distribution}]` or `[2, true, \(\chi^2\)-distribution]` but then I just get error messages like `CAS failed to return any evaluated expressions. Please check your connection with the CAS.`

Is it possible to combine text and math in the same field?

**Comment by sangwinc** [comment]
Len,

Argh yes, I thought this would become an issue very soon.  This is all about data types.  The 3rd argument must be a string.  If you'd like the LaTeX \chi^2 you will need to make this a *string*, e.g. 

    AnsList: [[1, false, "Normal distribution"], [2, true, "\(\chi^2\)-distribution"]];

But, you have identified a bug.  The single backslashes are lost.  Double backslashes are retained as double backslashes!

    AnsList: [[1, false, "Normal distribution"], [2, true, "\\(\\chi^2\\)-distribution"]];

I'll look into this and try to fix it.  I'm not sure which we will use.  I'd like to use the first, but the second might be needed.  Apologies.

**Comment by sangwinc** [comment]
Well, I do need some advice from more experience programmers about how to deal with slashes here.  Maxima is not helping, as slashes within strings seem to be removed.  The predictable problem with my naive search and replace code was nicely caught by an existing using test: https://github.com/maths/moodle-qtype_stack/blob/master/tests/castext_test.php#L526

Tim or Matti, or someone else, can you help please?

**Comment by aharjula** [comment]
https://github.com/aharjula/moodle-qtype_stack/blob/STACK_4.0_ALPHA2/stack/utils.class.php#L894-L904 this is from the state bit that pushes the users name through Maxima for cosmetic purposes...

You probably have an issue with the way you get that string from Maxima in the first place (unescaped vs. escaped strings and so on i.e., not grind output) and if you push it back there without noting the correct translation of those escapes between PHP and Maxima strings you will lose those slashes. Basically when you resend the strings to Maxima in the input class you need to handle the re-slashing there. As the slashes naturally do not exist in the string PHP would output... Also there are typically less slashes in a Maxima string than a PHP string but it should not be an issue here.

**Comment by lentzi90** [comment]
I guess this is related:

Commas terminate strings for some reason. For example this list of answers 
```AnsList: [[1, true, "Test, test 1"], [2, false, "Test 1,2"], [3, false, "Testing"], [4, false, "Testing 0.1"]];```
will show like this:
```
Tes
Test
Testing
Testing 0.1
```

Here is a file with the example code: [MCQ-test.xml.zip](https://github.com/maths/moodle-qtype_stack/files/243598/MCQ-test.xml.zip).

**Comment by aharjula** [comment]
Probably just doing the list splitting at the comma before string extraction, a common task that still has no utility function in STACK and tends to be forgotten often. That part of this problem should be simple to fix.

**Comment by aharjula** [comment]
Chris, shall we go with your branch or mine? Mine should also fix lentzi90's issue.

**Comment by aharjula** [comment]
Ohh, and single backslashes should be lost as backslashes need to be escaped in maxima code and we need to keep that behaviour for compatibility reasons. So it is `"\\chi^2"`.

**Comment by alcarola** [comment]
Is this issue already fixed in the abacus branch? If not, are there any ideas when it will be?

**Comment by aharjula** [comment]
Yep and I just upgraded abacus.aalto.fi.

**Comment by alcarola** [comment]
Wow, that's fast! :)

I'll pull the latest abacus stack right away then.
