### ISSUE TITLE
equation alignment in LaTex when displayed by MathJax

### ISSUE THREAD

**Issue by whanrott** [maths/moodle-qtype_stack#205]
I am authoring questions in STACK. I want to use LaTeX to typeset equations so that their equality signs align. This is useful when providing worked answers which use random input variables.
For example `\[\begin{align*}2x -12 &= 4\\2x &= 16\\x &= 8\end{align*}\]`

When the CAS returns the equation it doesn't appear possible to achieve this alignment
For example `\[\begin{align*}2x -12 &= 4\\@solve(2*x-12=4)[1];@\end{align*}\]`

Is it possible to amend the output of the CAS to enable alignment? I don't see this as a bug, but possibly a feature request or just some advice.

**Comment by sangwinc** [comment]
Yes, visual formatting like this is going to be a case-by case problem.  Here I'd use something like this (which I've not tested, but something like this will work.....)

In the question variables make a variable for the solution.  `sol:solve(2*x-12=4)[1];`

The use this variable as follows.
`\[\begin{align*}2x -12 &= 4\\@lhs(sol)@ &= @rhs(sol)@ \end{align*}\]`

**Comment by whanrott** [comment]
thanks. I'll use that method.
