### ISSUE TITLE
significantfigures problem

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#206]
Still related to issue [175](https://github.com/maths/moodle-qtype_stack/issues/175), now NumSigFigs seems to behave correctly, but random variant 50 of the question i submitted for issue 175 still doesn't work. The problem is now in significantfigures:

What happens in random variant 50:
(%i6) PrA:0.15;
(%o6) 0.15
(%i7) PrB:0.41;
(%o7) 0.41
(%i8) temp3 : PrA+PrB-PrA*PrB;
(%o8) 0.4985
(%i9) Tround3: significantfigures(temp3, 3);
(%o9) 0.498

For some strange reason banker's rounding is still used above (or is it a coincidence that we got banker's rounding?) Correct behaviour for this numerical data is returned for another example:
(%i11) a:0.4985;
(%o11) 0.4985
(%i12) significantfigures(a,3);
(%o12) 0.499

I do not get it, what is the difference between these two examples? The problem exists in today's abacus branch.

**Comment by aharjula** [comment]
temp3-a = -5.55111512313E-17...

Oh so much fun...

**Comment by sangwinc** [comment]
I'm sorry to have been quiet on this issue, I've been unwell this week and this has absorbed much of my time.  Not serious, but tedious.  I will look into this.
Chris

**Comment by alcarola** [comment]
Thanks for pinpointing the issue! We redid the question using rational numbers instead of floats where possible, and this seems to have fixed the problem. Our issue is resolved now, so this ticket can be closed, unless Chris still wants to investigate something.

**Comment by aharjula** [comment]
There really is not much that could be investigated as long as the calculations happen with different base than the presentation base and that is unlikely to change although it could be possible should someone want to invest plenty of time to lisp programming.

**Comment by sangwinc** [comment]
Thanks for confirming.  I think the most reliable way to get correct figures will be to use rational numbers with a denominator of 10^n and only render to floats at the last possible moment.  At least with Maxima (unlike many computer languages) we have that option.
