### ISSUE TITLE
Some questions make tests uneditable

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#208]
Some questions seem to break tests, so that questions can no longer be added or removed, and the automatical repagination does not work: 
![screenshot from 2016-05-16 10 33 34](https://cloud.githubusercontent.com/assets/1645276/15283440/4b3a9764-1b53-11e6-9c21-a694aeb3240b.png)

Steps to reproduce: Create a new test, and add the following question: 
[quiz-Stackverkstad-Mikael-20160516-1039.xml.zip](https://github.com/maths/moodle-qtype_stack/files/265754/quiz-Stackverkstad-Mikael-20160516-1039.xml.zip)

You can probably tell if this rather disturbing bug is a STACK or a Moodle issue.

**Comment by aharjula** [comment]
Try turning of the JSXGraph filter and see if thing work after that... You can turn it on after that. Maybe this is again #151. Basically more a problem with that filter combined with STACK.

**Comment by alcarola** [comment]
Indeed, that fixed the problem! So we just turn JSXGraph off while editing the test, and then we turn it on again. A more permanent fix at some point would of course be desirable.

**Comment by aharjula** [comment]
Indeed that is the way to go when you have JSXGraph filter using questions with STACK variables injected to the graph code. 

In issue #151 I suggested a possible fix about rearranging the storage of the question text, maybe you could note your opinion whatever it is about that idea in that issue.
