### ISSUE TITLE
Feature request: disapeering syntax hint

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#211]
I've received a request that the "syntax hint" should be removed when the student clicks in the input field. E.g. have the syntax hint display "Enter Number and Unit" as a reminder to the student to not forget the unit. In this case, the student has to delete the existing text before entering an answer. 

I would be useful to have a check-box option appear next to the syntax hint (authoring form) that would give the author the option to delete the hint text upon clicking in the field.

**Comment by christianp** [comment]
Can you not set the `placeholder` attribute on the input?

**Comment by sangwinc** [comment]
Thanks Christian, yes that is very probably what we will do at the HTML end.  A little more work is needed to store this as an option on STACK.  Sometimes it is useful to let the student edit the existing syntax hint option, so I don't simply want to change the current behaviour.

**Comment by aharjula** [comment]
Actually, here I would be the one that avoids extra options cluttering the system and would prefer to skip that option and the future task of having to explain what it does. So just using the `placeholder` attribute should be enough.

This is something that has annoyed us too so a welcome change indeed.

**Comment by sangwinc** [comment]
Ok, so are we proposing to just change the existing syntax hint?  Does anyone object to that?

**Comment by timhunt** [comment]
I think the current syntax hint behaviour is good. It is mostly useful to be able to edit your values into the template that is the syntax hint.

If you want a syntax hint out-side the box, then question authors can just put it as part of the question text.

I can see little benefit is a syntax hint that automatically vanishes.

Did the person requesting this explain why they thought this was a good idea?

**Comment by aharjula** [comment]
In set and list related inputs the option to write into the syntax hint is obviously handy, but really how often do you do that? The new problem is probably with the units and the syntax hint mentioned in the original posting, and when dealing with the units we tend to have plenty of inputs all saying similar things (thus making it somewhat pointless to add a syntax hint comment next to each box when the boxes are such an obvious place for it) and in the modern world the `placeholder` way seems to be the one that people expect, especially, with mobile devices...

**Comment by timhunt** [comment]
Placeholder is what people expect in input boxes where the hint is something like "Search" or "Email". I don't believe it is what anyone expects when the hint is [?, ?].

**Comment by aharjula** [comment]
What about "Mass" and "Length"?

**Comment by aharjula** [comment]
As in `Mass: <input placeholder="Enter Number and Unit" ...>`...

**Comment by sangwinc** [comment]
I think they are rather different behaviours, and that both are potentially useful.

Yes, the request comes because of units and wanting to make sure the input clearly signals that this is a "units" input type.  Currently, the input just looks like the algebra input.

Currently three options.
(1) Change syntax hint to use "placeholder".  (Not my preference)
(2) Add an option to all input types to allow "placeholder" text.
(3) Changing only the units to always have a placeholder saying "Units are required" for this input type?  The validation requires it anyway, so this would be sensible I think.

Chris

**Comment by aharjula** [comment]
In that case lets undo my first comment and go with an option i.e., option 2. Option 3 would limit this feature to units and that would not make sense to me.

**Comment by aharjula** [comment]
Obviously you can't have both the `placeholder` text and a syntax hint in a single input so you will only need to add a boolean to select between them...

**Comment by sangwinc** [comment]
Done.
