### ISSUE TITLE
Feature request: interpretation of 4.81e-5

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#215]
It would be nice if 4.81e-5 was interpreted as 4.81\cdot10^{-5}, but this is of course very low priority.

![screenshot from 2016-06-15 14 19 01](https://cloud.githubusercontent.com/assets/1645276/16077912/50b2e8c2-3304-11e6-844e-673d8989ac67.png)

**Comment by sangwinc** [comment]
I've just had a quick think about this.  It is a sensible suggestion, and we could add an option to each input to control the maxima variables which control display of numbers (see https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/CAS/Numbers.md) and the docs for

stackfltfmt:"~e";

I can't see an easy way in Maxima to display this.  E.g. there does not appear (at first reading) to be any option to printf to do this.

If some can programme this robustly in Maxima I'll give some thought to adding it in.

**Comment by aharjula** [comment]
But do remember #200 as we might not want to interpret them in that form for all powers of ten. Maxima does have problems with `x*10^y` vs. `xey` when `abs(y)` is large as in over couple of hundred. The exact powers of ten presentation and handling leads to Maxima doing all the calculation in that exact form and at some point things may get slow.

So watch out whether we are interpreting the input or just faking the output.

As a personal opinion, probably not shared by many, I find it problematic that you would want to convert that float notation that is inherently inaccurate to the infinitely accurate powers of ten presentation but maybe its just my digital tech background that says that those two notations mean different things while maths and science tend to think them equivalent.

**Comment by sangwinc** [comment]
Thanks Matti,

You raise a good point here.  I rather suspect that Maxima will be much better at dealing with exact representations a*10^n, (a an integer) rather than floats.  Actually float comes from the underlying lisp and there are subtle differences between SBCL and CLISP (try 1E-6 on both....).  This is a lisp issue and does not depend on the version of Maxima you are using.

Chris
