### ISSUE TITLE
Problem with MCQ and renaming of answers

### ISSUE THREAD

**Issue by lentzi90** [maths/moodle-qtype_stack#217]
Hello!

I had to rename/reorder some teacher answers today in order to add an input before the others. This is usually not a problem, but in this case I had already created some question tests and at least one of the inputs was an MCQ.

When the teacher answer variable-name is changed it breaks the question tests, if there are MCQs, with the error `stack_dropdown_input: could not find a key for Tans1`. In order to be able to edit it you have to change the input type to something else or change back the variable names, and then delete all question tests before continuing.

Here is a minimal example of the problem: [AutomaticTestingBug.xml.zip](https://github.com/maths/moodle-qtype_stack/files/327933/AutomaticTestingBug.xml.zip).

**Comment by sangwinc** [comment]
This has now been fixed by the subsequent issue and refactoring of error messages for inputs.
