### ISSUE TITLE
Doc question

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#218]
Hi,

Again doing a merge from master to abacus and finding some things curious when reading the docs to be merged... What does this mean:

"To place an inputs into the question enclose the name of the Maxima variable to which the student's answer is assigned between hash symbols, e.g. #ans1#"

https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/CASText.md

And where did that appear to the docs from, for some reason I do not believe that has been there for a while? Has someone committed an old version at some point or switched between branches in some wild way?

-Matti

**Comment by aharjula** [comment]
What worries me is this https://github.com/maths/moodle-qtype_stack/commit/d7124da2b50c2f92a86e108b1b6ef2e9e7847276 commit that actually fixed that text in 2013...

**Comment by aharjula** [comment]
Most importantly if that has magically switched to an older version what else could have changed on the side? What I see is that almost all the branches have this version except abacus... but I do not remember seeing that version when I last did a merge some weeks ago...

**Comment by sangwinc** [comment]
Well spotted Matti,

I think what has happened is that I committed that fix to the docs in the *abacus* branch along with lots of other changes to the docs. These changes were not reflected in the master branch.  Most of them in  https://github.com/maths/moodle-qtype_stack/commit/d7124da2b50c2f92a86e108b1b6ef2e9e7847276 only refer to abacus specific things, like @..@ gets changed to {@..@}.  

Well spotted and thank you.  I've proposed an improved wording in "master" which should not conflict too much with your branch.

I don't think this is some serious and hideous confusion of branches....  If you agree can you please close the issue?

**Comment by aharjula** [comment]
Ahh indeed the commit from 2013 is to abacus. But what worries me is that previously when doing merges the conflicts have not contained that segment as the master version has been older but now it appeared although I can't see any commits that would have made that line newer. So something must have broken the history graph in this case. Anyway probably nothing got confused by the origin of that line in abacus branch and probably did something wrong myself when doing the merge so that those old bits came haunting or something...

**Comment by aharjula** [comment]
Cause confirmed, happened to do the merge on top of an incomplete git clone, basically `git clone --depth=1 --single-branch...`.
