### ISSUE TITLE
Travis CI?

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#221]
Chris, Tim...

About this [travis](https://travis-ci.org/maths/moodle-qtype_stack/builds/140778356) thing, which is nice and all and ensures another test on another environment after we have naturally tested everything elsewhere. But are we testing the correct things with it, shouldn't the master at least be able to pass it and if it does not pass it due to matters of taste maybe the tests are configured wrongly?

I spent couple of days to fix my latest abacus merge so that it would pass the tests and found out that there are three places that cause problems for the travis config:
1. The duplicate code test (phpcpd) seems to find duplicate code, which is all fine and nice to eliminate if it exists, but if that thing focuses on unit-test code it might be focusing on the wrong thing. The only real thing here is the similarity of the agebraic and units inputs, that might require some inheritance or something. But if that gets fixed maybe we could just decide that duplication should not be tested within the `/tests/`, as writing the tests in an open form eases understanding them and helps creating new tests and the duplicate code there most definitively causes no harm.
2. The coding style test (codechecker) seems to test with a different logic than the Moodle-plugin one as I have serious trouble fixing some indentation errors that require more indentation than the coding-style defines. Maybe Tim can check what are the real coding-style issues with `backup/moodle2/backup_qtype_stack_plugin.class.php` as I can't see them similarly `settings.php` seems to be a problem for it.
3. The JS-tests (jshint) might be a problem as that `eval` may prove problematic to remove, but maybe the constructor names could be changed.

Also maybe that mess detector has some actually important findings so maybe at some point we should go though it...

-Matti

**Comment by sangwinc** [comment]
I have the same concerns Matti,

But at the same time I found a lot of the report very useful.  I'd like to get the auto-testing of the Maxima parts working.  The goal is to set up a system where it runs all the tests with multiple versions of Maxima, and Moodle.  This parallelism will save me a lot of time.

I think we can probably not worry too much about some of these.  The code checker in Moodle had an "ignore" environment!  Used in one or two places as really needed, I think we can make this a useful addition.

Finishing this off is on my list....

**Comment by timhunt** [comment]
Note that, in the Travis config, we now have

```
  allow_failures:
    - php: 7.1
      env: TASK=CODEKNOWNFAILS MOODLE_BRANCH=MOODLE_35_STABLE   DB=mysqli
```

The affect fo that is to say that, when we run some of the coding style checks, we don't care if they fail (but the results are still there to look at).

I think that is a good solution to this. So marking this close.

(That bits was commented out just now, but I am about to un-comment it along-side my Behat tests fixes.)

**Comment by timhunt** [comment]
Yay! https://travis-ci.org/maths/moodle-qtype_stack/builds/458063360
