### ISSUE TITLE
Inconsistent response with Units and SigFIgs

### ISSUE THREAD

**Issue by villehavu** [maths/moodle-qtype_stack#227]
While testing a problem with units and significant figures I came up with the following inconsistency:

The correct answer to the problem is 18000.0*J rounded to two significant figures.

A student input 18100.0*J gives the correct feedback about the answer being incorrect and the number of significant figures being wrong.

The input 18*kJ is accepted as a correct answer as it should. However, the input 18.1*kJ only produces the feedback 'Incorrect answer.' without giving a reason (i.e. a wrong number of significant figures as in the case above).

From the student's point of view the answers 18100.0*J and 18.1*kJ should of course be equivalent so I suspect there is something going on with the evaluation of the prefixes.

- Ville

**Comment by sangwinc** [comment]
Many thanks for reporting this bug.
