### ISSUE TITLE
If you change question penalty, it is then very fiddly to update all the question tests

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#229]
This was pointed out by Tim Lowe. My suggestion for fixing it is, when a question is being saved after the penalty has been changed, update any question test where expected penalty = the old penalty, to expect the new penalty instead. Does that seem safe?

**Comment by aharjula** [comment]
Seems odd to auto-magically shift the manually defined expectations to match new behaviour. And would this not require you to evaluate the penalties bot for the previous values and new ones to see which shifted from the correct positions.

Probably not asking from me but I do not believe anyone should change any declared expectations (tests) just because we know they would not be met after the author changes the parameters of the behaviour i.e., it is the authors task to ensure that he meets his own expectations even when he breaks some of them by tuning some scoring and it is only he that has the right to change those expectations.

**Comment by christianp** [comment]
Would it be possible to show an intermediate page containing a list of tests to potentially change, with a checkbox for each to say you want the change to be made?

**Comment by timhunt** [comment]
Christain, not easy within the Moodle code flow.

Matti, the full scenario Tim Lowe gave me was this:

1. Take some questions from Course A, which were created with penalty 1/3.
2. Copy them to Course B where you want to re-use them.
3. In Course B, you decide you want all the questions to have penalty 0.
4. The real issue is that if you have several question tests, it is a lot of mouse clicks to edit them all.

An alternative option would be to have a special variable you could used in your tests, e.g. __question_penalty. That way the tests would continue to work even if the penalty is changed. That is probably a better option. Does not solve the problem for existing questions (thought that could be done with a DB query.)

**Comment by aharjula** [comment]
The case you describe is naturally inconvenient but tests potentially changing without authors knowledge is quite a lot more inconvenient. Having the penalty as a variable would solve a lot, same with the actual points, it would even allow us to calculate the scores more directly, but I think this has already been thought of many times before and as it has not gotten done yet there obviously are some other issues.

Should you create such fixing logic to do things and can't do what Christian suggested make it so that you have to tick a check-box in the question editor to automatically update tests, like you would to automatically fix the math-delimiters.

**Comment by sangwinc** [comment]
I'm with Matti here folks,

My experience authoring questions is that the fails in the tests forces me to re-read all the tests carefully before I update them.  That is part of the whole point....

Chris

**Comment by timhunt** [comment]
OK, but if you have 6 tests, 1 right, and 5 for different possible wrong answers, then changing the penalty in each of the 5 wrong answers by clicking a lot of is not a good use of your time.

I agree human review would be good, but also, we do provide the button to "Fill in the rest of the form to make a passing test-case" when creating question tests.

We could make a page which, for each test, does this:
* Works out what "Fill in the rest of the form to make a passing test-case" would do for any of the test cases that have failures.
* Displays what expected values would be changed as a result.
* Runs those updated tests against all deployed variants, and shows the results.
* If eveything is green, gives you a button to save the updated tests.

**Comment by aharjula** [comment]
Just to point out one obvious solution to that example you described... if you only want to drop the penalties the Adaptive mode behaviour has a no penalty variant and other behaviours probably have the same ones... No need to edit questions or tests in that case.

**Comment by sangwinc** [comment]
Ok then Tim, you have a fair point here.

How difficult would it be to add the button "Fill in the rest of the form to make a passing test-case" next to each slot in the failing test page?  This just provides another interface to an existing functionality and it still requires active user input to each failing test without some of the tedium.  

Chris

**Comment by sangwinc** [comment]
Ok, I've just had a quick look at this.  The following will be useful around line 363 of questiontestrun.php but sorting out the data isn't something I can do today.  Tagging the release is more important, so this feature won't make 3.5.5.

```
        if (!$result->passed()) {
            echo $OUTPUT->single_button(new moodle_url('/question/type/stack/questiontestrun.php',
            $urlparams + array('inputs' => 'stuff')),
            stack_string('completetestcase', 'qtype_stack'), 'get');
        }


```

**Comment by timhunt** [comment]
I agree this is somethng for the future.

**Comment by timhunt** [comment]
By they way, Did you see my suggestion about having a variable for the default question penalty? (Might also be useful in PRTs, as well as in question tests.)

**Comment by sangwinc** [comment]
Yes Tim, I think having a variable for the question penalty would be very easy.

**Comment by sangwinc** [comment]
Tim, I looked at implementing this today... 
The expected penalty field in the DB is a number.  Had it been more flexible, we could have typed in "default" (or something else) and used this.  We already use the empty value to indicate the PRT did not fire...

The easiest thing (!) to do would be
1. Use an empty score to indicate the PRT did not fire. (in which case an empty penalty is expected as well, see below).
2. If the PRT fires, use an empty penalty to indicate we expected the question default - which is what we do when you write a PRT.

Any comments?

**Comment by aharjula** [comment]
Is it a nullable field? Surely NULL is the best thing ever? For some reason, our database schema has quite a lot of "NOT NULL" statements. This is a case where the NULL is the solution i.e. your empty values... Should not be a major problem to drop the NOT NULL constraint in a DB-upgrade.

**Comment by sangwinc** [comment]
It can be NULL.  We currently use NULL to indicate the PRT does not fire.  See the suggestion above.

**Comment by timhunt** [comment]
I agree with your suggestion 3 comments above.
