### ISSUE TITLE
Automatically run question tests when a question is edited

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#230]
As a software developer, I am used to having a Continuous Integration server to save me from mistakes. When I submit a code change, an automated process will re-run all the tests, and then email me if I have broken something.

STACK questions also have automated tests, we should offer the same facility to question authors:
1. add a new database table qtype_stack_qtests_results with columns questionid, testcase, seed, timerun, stackversion, stackmaximaversion, result
2. create a new scheduled task, which queries the question table, joined with the qtype_stack_qtests_results etc, and finds the top N questions where not all test results are present and up-to-date.
3. for those questions, run the question tests, and save the results.
4. if a question has been edited within the last H hours, and a test fails, then email the question.lastmodifiedby user to tell them a test has broken, and with a link to the question test page, and the edit question page.
5. update pages like bulktestindex.php, to use the new DB table to display more information about the current state of the questions in each area, without the slowness of re-running the tests. (E.g. Course M101 - 123 questions - 12 tests waitin to be run - 100 all tests pass - 11 with failing tests.)

**Comment by sangwinc** [comment]
Tim,
That all sounds like a very good idea.  This would be great.  I'd like to see Travis working first, as I think this is more likely to catch major problems. Then we should work on this.
Chris

**Comment by sangwinc** [comment]
I've been trialing this, and it creates quite an unacceptable performance hit when you have a question with many variants.  This doesn't work well on either the edit form or the question test form. So, I've added a button to "test all variants" on the form.  This will be in 4.0.1.

https://github.com/maths/moodle-qtype_stack/blob/master/questiontestrun.php#L240

**Comment by timhunt** [comment]
Thanks for trying this Chris. I was not thinking of running the question tests synchronously as part of the validation, when the question is edited.

Rather, I was thinking of a scheduled task, which ran the tests asynchronously, and then sent an email if any failed. But, I don't have time to implement something like that at the moment.
