### ISSUE TITLE
Lambdas broken...

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#231]
Hi,

A new issue appeared as people start to go through less common stuff with the upgraded abacus-branch that includes this commit: https://github.com/maths/moodle-qtype_stack/commit/d58c8fbea00eb590f2ad3d6ca5f7f0180a356da3

It seems like that subscript logic has trouble with unevaluated things that exist in lambdas? Maybe even elsewhere... Seems to want to evaluate things that can not be evaluated i.e., the recursion runs too deep and probably needs more complex termination rules.

Any idea what is happening and if there is a workaround that does not require switching lambdas to something else?

This may prove to be a major issue and I am trying to track down examples, but we have major authors that like lambdas... and have liked them from STACK 1 times.

Snip from a cas-chat debug:
```
], key = [ 
testLambda 
] 
, value = [ 
lambda([a],block([out],out:[],for i thru length(a) do out:append(out,[first(listify(setdifference(setify(a),setify(out))))]),out))
  
], display = [ 
length: argument cannot be a symbol; found a
#0: stack_disp_strip_number(ex=length(a))(stackmaxima.mac line 321)
#1: stack_disp_strip_number(ex=for i thru length(a) do out:append(out,[first(listify(setdifference(setify(a),setify(out))))]))
#2: stack_disp_strip_number(ex=block([out],out:[],for i thru length(a) do out:append(out,[first(listify(setdifference(setify(a),set...)
```

**Comment by aharjula** [comment]
Not just lambdas, the minimum case is this:
 1. Have ``f(x):=length(x)`` in your question variables.
 2. Then put ``@f(x)@`` in your question text.

Previously that would have generated the output of ``\(f(x)\)`` now you will only get blank space and broken cassession and question.

**Comment by aharjula** [comment]
Ok. Tried to add an end condition to the recursion like this ``if safe_op(ex) = "length" and symbolp(first(args(ex))) then return(ex),`` but then we get to the next error:
```
(%i1) testLambda: lambda([a],block([out], out:[],for i: 1 thru length(a) do out:append(out,[first(listify(setdifference(setify(a),setify(out))))]), out));
(%o1) lambda([a],
             block([out],out:[],
                   for i thru length(a) do
                       out:append(out,
                                  [first(
                                    listify(
                                     setdifference(setify(a),setify(out))))]),
                   out))
(%i2) stack_disp(testLambda,"");
"$setify": argument must be a list; found: a
#0: stack_disp_strip_number(ex=setify(a))(stackmaxima.mac line 322)
#1: stack_disp_strip_number(ex=setdifference(setify(a),setify(out)))
#2: stack_disp_strip_number(ex=listify(setdifference(setify(a),setify(out))))
 -- an error. To debug this try: debugmode(true);
```

So obviously we need to put some error catching into that recursion, but how?

Also this issue will cause trouble with our discrete maths course beginning very soon, while we are obviously not asking the students to answer with lambdas we most certainly use them to evaluate the answers and now this display logic applied to things that are never displayed makes things difficult.

**Comment by sangwinc** [comment]
Matti, 

Subscripts following Greek letters in LaTeX is only for display of expressions to students.  We don't need this display functionality in functions or lambda expressions.

If you are happy with this please close the issue.

**Comment by aharjula** [comment]
Chris,

Testing still but looks good. 

Was seriously trying to apply those subscripts inside presentations of lambda and doing that would have required identification of things that break with undefined values.

**Comment by aharjula** [comment]
Test seems good.

**Comment by aharjula** [comment]
Argh... for loops acting on lists/matrices have this same problem and they can exist outside lambdas. But they often exist inside blocks... In their case the issues is almost always with accessing a symbol index of a list.

**Comment by aharjula** [comment]
Probably needs to opt out of this subscript logic if any control structures are present. So ``if, for, do, in, unless, while, map...``, basically everything in the categories [Function application](http://maxima.sourceforge.net/docs/manual/maxima_105.html#Category_003a-Function-application) and [Programming](http://maxima.sourceforge.net/docs/manual/maxima_105.html#Category_003a-Programming) of the Maxima manual.

**Comment by sangwinc** [comment]
Yes Matti,
Would you be willing to propose a change?

**Comment by aharjula** [comment]
Would need to do the same as with lambda but can ``freeof()`` or some other see the control structures or does one need to search for them from the expression some other way. Maybe a new predicate that checks all of those? Naturally, the current recursion should be able to just terminate the moment it sees one of those control structures, so the search can be mixed in that instead of the top level filter that you now have for ``lambda``.

**Comment by sangwinc** [comment]
This is now fixed.

**Comment by aharjula** [comment]
This might have resurfaced...do test a function with length() in it...

**Comment by sangwinc** [comment]
Sorry about this Matti,

Certainly this case breaks:
1. Have f(x):=length(x) in your question variables.
2. Then put @f(x)@ in your question text.

But, it you type this into Maxima (without STACK) then it also throws an error:
f(x):=length(x);
f(x);
"length: argument cannot be a symbol; found x"

Did this really previously return f(x)?  I'm not sure how it would have done so, as any attempt to evaluate f should have thrown this error I think?

**Comment by aharjula** [comment]
Chris, it is largely irrelevant whether I can print @f(x)@... that is probably a bad recollection of how things were and not that important, probably safe to ignore. The thing that matters is can you write:
```
f(x):=length(x)
b:[1,2,3]
c:f(b)

and  @f(b)@
```
And obviously in a case where that f(x) is a bit more complex. I'll send you a sample that has history going back around 8 years... and worked last spring but now does not.

**Comment by aharjula** [comment]
Fun stuff: 
`sf: lambda([x,n],significantfigures(x,n));`

**Comment by sangwinc** [comment]
Matti,
I've just pushed two unit tests which are based on your examples.  Both currently pass!  Can you give me a failing unit test?

I know f(x):=length(x) appears to fail.  Did it ever pass? (That might have been a bug...)
Chris
