### ISSUE TITLE
Identical arctan expressions not recognized

### ISSUE THREAD

**Issue by AndersSkj** [maths/moodle-qtype_stack#237]
Hello,

The expression atan(7/-3)+pi is not identified as equal to atan(3/7)+pi/2.
ATAlgEquiv does not seem to use the identity
atan(1/x) = pi/2 - atan(x), when x > 0.

From the sandbox:
(%i13) ATAlgEquiv(atan(1/2),%pi/2-atan(2));
(%o13) [true,false,"",""]

**Comment by sangwinc** [comment]
Thanks for this, yes I'd say this is a mathematical bug in STACK.

Apologies for this.  I'll look into it.

**Comment by sangwinc** [comment]
This is an interesting mathematical problem.  I think the general problem is going to be quite hard to solve.  Also, the domain constraint x>0 really begs the question what it means to be "the same".  

This is as far as I can get today.

We can make some progress by doing a manual "invert" then solving.
```
i1:rhs(first(solve(y=atan(1/x),x)));
l1:rat(exponentialize(i1));
i2:rhs(first(solve(y=pi/2 - atan(x),x)));
l2:rat(exponentialize(i2));

```
Then
```
ATAlgEquiv(l1,l2);
[true,true,"",""]
```
So, for your particular question you may be able to use the feedback variables.  However, this may not be robust in other directions, especially if the "solve" in here fails as it must do for some mal-formed student input....

If you only want atan(7/-3)+pi to be identified as equal to atan(3/7)+pi/2 then you could use "float", but that does go against the whole idea of using a CAS!  [sigh....]

Not sure how to proceed.  Any suggestions?

**Comment by AndersSkj** [comment]
I'm happy that I didn't overlook something obvious. If it isn't easily achieved, I can state the questions (arguments of complex numbers) differently.

**Comment by sangwinc** [comment]
This example is now on the "todo" list in the unit tests, so I'll close this as an open issue.  Interesting example, thank you!
