### ISSUE TITLE
Add molarity as a unit and hr as an alias to h.

### ISSUE THREAD

**Issue by jmbragg** [maths/moodle-qtype_stack#238]
Molarity needs to be added as a unit.  I think that would be adding

`array('M', 'mol/(m^3/1000)', 'M', 'Molar'),`
under `private static $supportedunits`

Also, it would be really nice to have hr as an allowed variation of hours.  I had lots of students recently who put in hr for it which required lots of manual grading.  I think that's adding
`'h' => array('hr'),`
under `private static $unitsynonyms`

**Comment by sangwinc** [comment]
Thank you, that is very helpful.

Please don't underestimate the value of this kind of real, hard won, experience with students.

Chris
