### ISSUE TITLE
Additional Scientific Units needed in STACK

### ISSUE THREAD

**Issue by dhilsen** [maths/moodle-qtype_stack#244]
The scientific units listed below are not presently supported in STACK. These are units which we use in our physics questions and I believe others would benefit from having these units supported. The units listed in 1) through 4) are often displayed with a dash (-) appearing in the unit as shown. It would be ideal if the unit could be entered in this way, however, I understand this may potentially create a problem within STACK. 

1) kgm/s  and  kg-m/s   (kg(star)m/s is presently accepted)
2) N-m  (Nm is presently accepted)
3) ft-lb  (ft(star)lb is presently accepted)
4) kgm^2 and kg-m^2 (kg(star)m^2 is presently accepted)

5) rev ; rev/s ; rev/s^2 ; rev/min ; rpm
6) deg and deg/s 
7) torr  (Torr presently accepted, torr is often used)
8) cal  ; Cal ;  kcal
9) Btu
10) kWh
11) Bq
12) day ; days
13) year  ;  years
14) gal
15) mole (mol is presently accepted)
16) GeV ; MeV ; keV
17) kWh ; Wh
18) rem

**Comment by aharjula** [comment]
3) have to assume that you have configured the unit support for that yourself or only compare with strictly matching units, you can do that for all of these without the dash.

16) electron volts sure would be handy to have.

1-4,10,17) are not going to happen. The dash is impossible and the ones without dash are inconsistent with the normal operating principles and were we to allow those inconsistencies we would need them to work everywhere, which would create contradictions in the system and complicate the system both for students and in technical sense. One conflict is with the validation systems output and that is already enough of an conflict.

5,6) which base SI units do these even match.

8,9,14) could exist as aliases and conversion rules, but which calories would they be and what definition of Btu or gallon should we use... Simpler to leave these as things for the author to define as needed instead of by default choosing something everybody disagrees with. We will rather stick to unit systems that actually mean the same everywhere and leave the rest for authors to handle.

11) Bq is and has always been part of the unit support.

7,12,13,15,18) sure why not, the mechanism for adding them is present.

**Comment by sangwinc** [comment]
Thank you very much indeed for completing this list of units.  Very helpful indeed and I will certainly implement as many of these as I can.

I share Matti's initial reservation with "kg-m/s".  This will mean subtraction, and I'll give some thought to how we can actually help students who type this in, but mean kg*m/s.  We shall see!

**Comment by aharjula** [comment]
Honestly, if someone goes and inputs "kg-m/s" and expects it to mean "kg*m/s" they have issues on such an level that we can't help them nor should we even try. Dash is not an multiplication symbol and never will be. We must walk away slowly and just accept that this is an issue that should not be solved.

Just to guide you to the thought track of least chaos, if the input field contains an expression with terms using incompatible units then this is the probable cause for it, maybe add a test for inputs like "5.00*kg+0.5*cm", i.e., add an validation phase that tries to convert the input to base units and sees if it then has just one term after simplifcation.

**Comment by sangwinc** [comment]
Matti,

Spiritually I'm inclined to agree Matti but on a practical level there are serious differences between countries and subjects.  In physics this might be standard textbook notation, and so students will use this.  They may reasonably expect to type in what they see in a textbook....

I'm not suggesting we accept this, or try to accept it.  I am suggesting there are good reasons why a student may come to believe that km-m/s is a legitimate thing.  

Chris

**Comment by dhilsen** [comment]
The list which I provided is most definitely a wish list and I fully understand that using a dash within a unit is wishful thinking. As Chris stated, some students will try and enter certain units using a dash as they have been accustomed to seeing units expressed this way, at least in the US. We will simply make it clear to students that this will not be accepted.

Items 5) and 6) on the list are not SI units. When dealing with angular displacement and angular velocity we sometimes ask the student to convert radians into the familiar units of revolutions (rev) and degrees (deg). This is done at the introductory level to help students gain an intuitive sense for their answer. This raises the question of whether or not STACK should support non SI units, there may indeed be a good reason not to do this.  

I'm not familiar with the process by which an author can define a unit. Can I ask how this might be accomplished?

**Comment by sangwinc** [comment]
I've committed some changes to add the following in here: https://github.com/maths/moodle-qtype_stack/commit/0a1683ed9fb2ab1d78bdef279f4e2d90d3bb4a28

I'm going to leave these ones for now, and give some thought to overloading the syntax to spot them.  I think the computer science people call this kind of thing "Syntactic sugar".  If these are likely, the teacher already has the option to have "single letter variable names" which deal with all except (3)

1) kgm/s and kg-m/s (kg(star)m/s is presently accepted)
2) N-m (Nm is presently accepted)
3) ft-lb (ft(star)lb is presently accepted)
4) kgm^2 and kg-m^2 (kg(star)m^2 is presently accepted)

5) rev ; rev/s ; rev/s^2 ; rev/min ; rpm

'rev' added as "revolutions" base unit is angle, so rev:2*pi*rad.
'rpm' added.

We don't need to add rev/s; rev/s^2, the units system will incorporate these anyway.

6) deg and deg/s

Added "deg", so deg/s will automatically be added.

7) torr (Torr presently accepted, torr is often used)

"Torr" is in the $unitsynonyms (see https://github.com/maths/moodle-qtype_stack/blob/ATUnitsNum/stack/cas/casstring.units.class.php#L131) so the student will be asked to use "Torr".  I think this is cleaner than accepting both.

15) mole (mol is presently accepted)

"Mole" is in the $unitsynonyms so the student will be asked to use "mol".  I think this is cleaner than accepting both.

8) cal ; Cal ; kcal

According to wikipedia, Cal=kcal=1000*cal.  Is that correct and is that what you'd like?
https://en.wikipedia.org/wiki/Calorie
Having case sensitive "cal" and "Cal" is likely to be confusing!

9) Btu

Added this as 1055*J.

10) kWh; Wh

We don't need to add these, as they are literally k*W*h and all these units exist already!

11) Bq

This is already on the list.

12) day ; days

Happy to add "day" as 24*60*60*s.  Then I'll add days to the synonym list.

13) year ; years

What value should a year take in seconds?

14) gal

What value should a gal take in l?

16) GeV ; MeV ; keV

To do this we only need to add "ev" to the $supportedunits list.  GeV, MeV and keV will then automatically be supported as well.
https://github.com/maths/moodle-qtype_stack/blob/ATUnitsNum/stack/cas/casstring.units.class.php#L81

18) rem

Sorry, what are "rem"?  (!)  Is it 0.01 sivert?
https://en.wikipedia.org/wiki/Roentgen_equivalent_man

**Comment by dhilsen** [comment]
Thank you Chris for all your work on adding the new units. With regard to your questions:

8) cal ; Cal ; kcal
Cal=kcal=1000*cal is indeed correct. It may be best to utilize "cal" and prevent confusion by not using "Cal".

12) Please note: 1 day = 86400 seconds

13) 1 year = 3.156e7 seconds   (365.25 days)

14) 1 gal = 3.785 L 
This is for a US gallon, the British gallon is different of course. Gallons are commonly used in the US so it might make sense to use the US conversion. Can someone comment if gallons are commonly used in the UK?

18) rem is a commonly used unit for equivalent dose of absorbed radiation. The SI unit for equivalent dose is the sievert (Sv), however, it would be useful to also support the unit rem. 
1 rem = 0.01 Sv

**Comment by timhunt** [comment]
1 day != 86400 seconds.. Ditto year.

http://infiniteundo.com/post/25326999628/falsehoods-programmers-believe-about-time - if you have never read this, it is quite amusing, as well as educational.

**Comment by sangwinc** [comment]
Yes Tim, This is great: https://www.amazon.co.uk/Calendar-Struggle-Heavens-Happened-Missing/dp/1857029798

But, I think for our purposes we can define and document it that way.  

I'll add in gal for US gallon.  We are steadily and firmly inching towards the metric system, so I don't think any physics teachers here will want gallons in a serious way.  I think we should probably let teachers define their own odd units at some point.
