### ISSUE TITLE
Error on Creating New Optimized Version

### ISSUE THREAD

**Issue by jmbragg** [maths/moodle-qtype_stack#246]
Installed latest code from ATNumUnits.

Went to recreate the optimized version of maxima (CentOS, Maxima 5.36.1)

Got this:
(%i1) load("maximalocal.mac");
STYLE-WARNING: redefining TEX-MQUOTIENT in DEFUN
STYLE-WARNING: redefining TEX-PREFIX in DEFUN
STYLE-WARNING: redefining TEX-STRING in DEFUN
STYLE-WARNING: redefining TEX-DERIVATIVE in DEFUN
STYLE-WARNING: redefining TEX-D in DEFUN
STYLE-WARNING: redefining TEX-DABBREV in DEFUN
STYLE-WARNING: redefining TEX-INT in DEFUN
STYLE-WARNING: redefining TEX-MEXPT in DEFUN
define: warning: redefining the built-in function texnumformat
STYLE-WARNING: redefining TEXNUMFORMAT in DEFUN
;
; compilation unit aborted
;   caught 1 fatal ERROR condition
;
; compilation unit aborted
;   caught 1 fatal ERROR condition
loadfile: failed to load /usr/share/maxima/5.36.1/share/draw/draw.lisp
 -- an error. To debug this try: debugmode(true);

Got the same last few lines when I tried to load(stats);

Went through the rest of the process and the rest seemed fine.  Got the healthcheck script working also.  Don't know if this is expected or not.

**Comment by aharjula** [comment]
Oh I hope this is not the issue #149 again. Typically these kind of an issues are caused by the user running the Maxima not having rights to write the cached compiled versions of various libraries to their home-directory (~/.maxima is the normal place). Which is rather common for the www-data users and their read-only home directories. But draw.lisp sure has other issues also...

**Comment by jmbragg** [comment]
I created the image as apache so that would probably explain it.  I'll recreate the image soon and confirm.

**Comment by sangwinc** [comment]
Is this issue still open?

**Comment by jmbragg** [comment]
Thanks for the reminder on this.  I had forgotten about it.   It was as Matti suspected.  This is not an issue.
