### ISSUE TITLE
rand_with_step bug

### ISSUE THREAD

**Issue by dhilsen** [maths/moodle-qtype_stack#247]
The **rand_with_step(a,b,c)** function displays an operation rather than a randomly selected value when Question-Level Simplify is set to No. For example, if using rand_with_step(10,20,1) the question text will display 10 + 1  7 for the variable, which would appear to be values generated by the function in non-simplified form. 

Chris, I believe we encountered a bug with Question-Level Simplify a couple months back when we were addressing an issue involving an answer of zero along with a unit, and perhaps also the dispdp(a,b) function.

**Comment by sangwinc** [comment]
This isn't a bug!

simp:false is a very blunt tool.  We can't have it both ways, either we do or don't simplify.  In this case I think you need to use

`ev(rand_with_step(10,20,1),simp)`

to simplify the rand_with_step function.
