### ISSUE TITLE
ATNum_OutofRange Issue

### ISSUE THREAD

**Issue by jmbragg** [maths/moodle-qtype_stack#249]
A student put in a wrong answer recently on a quiz that was very wrong (10^24 instead of 10^-24).   They got a message that I hadn't noticed before that led me to the ATNum_OutofRange answer note which lead me to these lines (924-927) in moodle-qtype_stack/stack/maxima/stackmaxima.mac.  

    if SA>5e22 then
        return([false, false, StackAddNote("", "ATNumSigFigs_SA_OutofRange"), StackAddFeedback("", "ATNum_OutofRange")]),
    if SB>5e22 then
        return([false, false, StackAddNote("", "ATNumSigFigs_TA_OutofRange"), StackAddFeedback("", "ATNum_OutofRange")]),

I don't really understand what is going on here with these.  I'm concerned that it might mean that I can't use questions that have answers larger than 5e22.  That's a huge problem for a chemist as the mole is 6.022e23.  Just need some clarification...

**Comment by sangwinc** [comment]
Thank you for raising this as a public issue.

I very recently added in these lines of code, as you point out.   They are very easy to remove, but then we might well have situations where a teacher (unwittingly, and despite our flawless documentation ;-)  ) uses values out of range, which are not supported.  I've created a branch and added in some physics constants as test cases.  So far so good.

I think perhaps we should remove this test.  But things will fail...

Any other comments.

**Comment by sangwinc** [comment]
Ok, I've removed these lines and run all the question tests.  Nothing breaks, so I've committed this back into master.  We will get numerical problems, but perhaps this is better to deal with one by one.

**Comment by aharjula** [comment]
Wasn't this one about some set of Maxima installations with some specific LISP implementations being unable to deal with that large numbers? Most people have working LISPs and have no trouble having that limit around 1e100 but there was some set where 1e~22 was important? Could we find out what that issue is and add it to the health check as a warning?

**Comment by aharjula** [comment]
The original issue related to this from Aalto was probably about someone answering hundreds of orders of magnitude wrong and the system timing out due to the exact evaluation of the error. For that reason we added a limit and we could not make the limit simply be for |SA-TA| as evaluation time of that depended on the way the powers of ten were represented.

**Comment by jmbragg** [comment]
So just trying to make sure I understand the issue here... I haven't noticed that there was an upper limit on the size of numbers that work before. What is that limit? Is that a maxima limit? I missed it in the documentation. ;)

It is not uncommon to have students who make a mistake with Avogadro's number enter answers in the neighborhood of 10^46 = (10^23)^2.

**Comment by aharjula** [comment]
I don't know what the issue actually is as my installations of Maxima on CLISP have newer had trouble dealing with numbers of relevant scales, but supposedly there are some LISP implementations where the floating point operations have limits that collide with for example Avogadro's number. To see the problem try inputting `1e320` to your Maxima (or `1e64000` if you are luckier than me, although you might have limitless exponents) and imagine if you get errors for numbers around `1e24`, note that the test actually has to do arithmetic with smaller numbers but the operations can produce results that go over that limit. Also note that you can input `1*10^9000` just as well and those will not fail but certain functions on the value might evaluate at wildly different speeds depending on which way you represent the number.

The limit exists to stop those few Maxima installations from failing, although they will fail elsewhere anyway so might as well live without the limit.

**Comment by sangwinc** [comment]
I have to confess that I have not been able to track down the precise cause of the problem either.

Users reported problems with numbers just (only just) outside the above limits on one version of LISP. I'm probably being too cautious and so have revoked that check.  I've put in more tests, and if there is a genuine problem we can add more tests to reveal it as and when.
