### ISSUE TITLE
mis-spelling of path in lang file

### ISSUE THREAD

**Issue by marcusgreen** [maths/moodle-qtype_stack#251]
line 360 of 	
lang/en/qtype_stack.php

Has a mis-spelling where it says plath instead of path
It reads

$string['settingplatformplotcommand_desc'] = 'Normally this can be left blank, but if graph plotting is not working, you may need to supply the full plath to the gnuplot command here.';

**Comment by sangwinc** [comment]
Thank you very much for reporting this.
