### ISSUE TITLE
Answer Test Failure

### ISSUE THREAD

**Issue by jmbragg** [maths/moodle-qtype_stack#257]
![odd units issue](https://cloud.githubusercontent.com/assets/4606870/20996399/509086e6-bccb-11e6-9c13-af0127517bff.PNG)

I have no idea what might have caused this...

This student has the units on the answer wrong for quite typical reasons for this type of problem.  Its a reaction rate constant that has units that vary depending on the rate law for the reaction.  

I'm attaching the question also.
[questions-APChem-Rate Constant Calculations-20161207-2220.zip](https://github.com/maths/moodle-qtype_stack/files/638339/questions-APChem-Rate.Constant.Calculations-20161207-2220.zip)

**Comment by sangwinc** [comment]
Sorry, I can't reproduce this bug.  Is it possible it was a spike in server demand which caused a timeout?  Or, can you always reproduce this?

**Comment by aharjula** [comment]
Chris, when I this also has plenty of the same as #255 and if I try to build a question with `ta:7.54e-5/(M*s)` and answer like that I get that my input was interpreted as "0.00 1/s * M" which is somewhat odd... #255 is the one about "1/(s * M) != 1/s * M".

**Comment by jmbragg** [comment]
Hmm.  I can always duplicate it for this variant and any combination of incorrect units that I've tried so far.  I'll work on getting you a stripped down question that will duplicate this on my end.

**Comment by jmbragg** [comment]
Aha... I'm attaching a file.  For some reason, GitHub is saying it won't accept a .zip file as a file type even though it is in the list of acceptable file types....  So I renamed this to be a .docx file just to get around that.  It is a .zip file.  Rename it to .zip yourself.

In short, there are two questions here that are identical except for the answer test.  The answer test in one is has a `Tans` of `stackunits(k,kunits)`  while the other is just `k*kunits`.  The one with `stackunits()` fails and the one without passes.

[questions-APChem-Bug Testing-20161208-1326.docx](https://github.com/maths/moodle-qtype_stack/files/640260/questions-APChem-Bug.Testing-20161208-1326.docx)

**Comment by sangwinc** [comment]
Ok, I think this might be related to issue #255.  That is, the extra "1" which was shunted into the numerical part. 

I can't reproduce the bug on the new code......

**Comment by jmbragg** [comment]
I'll trust that this is fixed if you can't reproduce it on the new code.  Thanks again Chris.
