### ISSUE TITLE
Multi line input field in a question with Moodle auto-format question text.

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#264]
If a question has a multi line input i.e. give a system of equations and the question text uses Moodle auto-format, which it often does when authors use some WYSIWYG editor. Then if a student gives multiple lines of input and the page gets redrawn the line changes within that input inside the textarea get turned to br-tags. Those br-tags naturally cause havok on the Maxima side.

To reproduce create a multi-line input and give it multiple lines of teachers-answer, then preview and fill in the correct answers (pressing the button is enough). Just make sure you have Moodle auto-format on. To see the formatting options you may need to switch the WYSIWYG editor to plain text area.

This is primarily a Moodle formatting and filtering issue, obviously Moodle should not filter the contents of a textarea-tag in its output. So maybe Tim should bring this up at the relevant forum and test this himself.

However while that gets fixed (if ever) STACK will probably need to identify br-tags in inputs and react in some sensible way to them. For now the few cases where we have met this issue have been fixed by turning Moodle auto-format to HTML-format so no hurry from our side but this will probably cause problems for people unable to track and understand the issue.

**Comment by timhunt** [comment]
Please can you give exact setps to reproduce this?

**Comment by aharjula** [comment]
Switch to plain text editor so that you see the format option of the question text field, in 3.2 it seems to default to HTML-format which does not cause this but before it defaulted to Moodle auto-format which you will need to have on. Create a question with a textarea type input and set its model answer to for example `[a=b,b=c,c=a]` put anything you want to the PRTs. Now preview this question and press fill in correct answers, also try filling it in a quiz and returning to the same page later.

**Comment by aharjula** [comment]
Or just try with this: 
[multi-line.xml.txt](https://github.com/maths/moodle-qtype_stack/files/777013/multi-line.xml.txt)

**Comment by sangwinc** [comment]
Matti, is this still an issue?

**Comment by aharjula** [comment]
Seems to still be broken if you happen to have 'Moodle auto-format' active in your question-text, but as that only happens if you set it so or have an old Moodle with that as the default it is not really a major issue. This issue exists mostly to inform those suffering from this.

The sample above leads to this in the current master code.

Basically the issue is that each time you click check it adds `<br />` to the end of each line.

**Comment by sangwinc** [comment]
Ok, this is still a live issue!
