### ISSUE TITLE
Question tests failing sometimes when test inputs have the same name as feedback variables.

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#267]
We have some questions where the question tests used to pass, but with STACK 3.5.6 they now fail.

The problem seems to be with whether the sample input is evaluated before it is used. In almost all cases, wrapping the inputs of the failing test with ev(..., simp) makes the test pass. However, my understanding is that should not be necesssary.

We have lots of examples of this, but a simple one is attached below (Converting from Cartesian). Test case 1 fails.

The linearity example is even weirder. There seems to be minial differences between some of the test-cases that pass, and number 2 that fails.

Can you work out what is going on here Chris? If you can point me in the right direction, then I can develop the fix. Thanks.

[questions-MST124-16J-12.08 Converting from Cartesian form to polar form-20170202-1757.xml.txt](https://github.com/maths/moodle-qtype_stack/files/748587/questions-MST124-16J-12.08.Converting.from.Cartesian.form.to.polar.form-20170202-1757.xml.txt) (File renamed to .txt to make Github happy. It is really a Moodle XML export.)

[questions-STACK-DEMO-CR-Diff-02-linearity-3.c-20170202-1815.xml.txt](https://github.com/maths/moodle-qtype_stack/files/748620/questions-STACK-DEMO-CR-Diff-02-linearity-3.c-20170202-1815.xml.txt)

**Comment by sangwinc** [comment]
Tim,

At some point in the past I changed the test mechanism (I can't find the commit today, sorry) so that test inputs are entirely unsimplified.  This means you normally do need an "ev(...,simp)" to evaluate the tests.  I went through my copy of the "demo course" and checked which cases do and do not fail.  Where necessary I added in this wrapper.  I have noticed some minor differences between maxima versions with simp:false, which may be causing apparently inconsistent results here.

How many cases do you have?

**Comment by timhunt** [comment]
I don't think that quite explains what I am seeing:

![image](https://cloud.githubusercontent.com/assets/138653/22882594/d92bcdce-f1e3-11e6-9ae4-ed9e8dfd536f.png)

The input seems to have been simiplified perfectly well. The problem is where that is used in the answer test, that has not been simplified, and that is coming from the feedback variables. Note that, the Simplify option for the PRT is on.

![image](https://cloud.githubusercontent.com/assets/138653/22882701/453e9262-f1e4-11e6-81be-e953eeded320.png)

I wonder if the problem is caused by re-defining ans2?

I will continue to investigate and debug.

**Comment by timhunt** [comment]
OK, changing the bit of the feedback variables to `ansdown2:exdowncase(ans2)` and also updating the node where it is used makes the test pass.

Note that, even before editing, the question works if you preview it, it is just the test that fails.

I see. Now that I try to edit the feedback variables code back, now I see "You many not redefine the value of an input within the feedback variables, but you have redefined 'ans2'." That must be somewhat new.

OK, so this is a problem with our questions. Let me see how many like this we have.

**Comment by aharjula** [comment]
Wasn't the redefining the value of input only forbidden due to the new SigFigs tests requiring the raw input value and should still work for others? But as it now is blocked we might as well keep it blocked as one could say it is bad form to modify the input, better keep those as read-only for consistency and readability.

**Comment by timhunt** [comment]
It does not seem like a silly rule to me. Much cleaner to force people to use a different variable names for their feedback variables and their inputs.

However, we now have 376 questions with failing answer tests. (Or, rather, multiple copies of 48 distinct quesitions.)

That is a lot to fix by hand, and I can't think of a good way to automate it.

If anyone is interested, here is my query for finding the problems: (probably using Postgres-specific syntax)

```
SELECT DISTINCT
    c.shortname AS Website,
    qc.name AS Question_category,
    q.name AS Question,
    prt.name,
    prt.feedbackvariables,
    'http' || CHR(58) || '//learn2.open.ac.uk/question/question.php' || CHR(63) || 'id=' || q.id || '&' ||
        CASE WHEN cm.id IS NULL THEN 'courseid=' || c.id ELSE 'cmid=' || cm.id END
        AS Edit_link,
    'http' || CHR(58) || '//learn2.open.ac.uk/question/edit.php' || CHR(63) ||
        CASE WHEN cm.id IS NULL THEN 'courseid=' || c.id ELSE 'cmid=' || cm.id END ||
        '&category=' || qc.id || '%2C' || ctx.id ||
        '&qperpage=1000&lastchanged=' || q.id
        AS Question_bank_link,
    'http' || CHR(58) || '//learn2.open.ac.uk/question/preview.php' || CHR(63) || 'id=' || q.id || '&' ||
        CASE WHEN cm.id IS NULL THEN 'courseid=' || c.id ELSE 'cmid=' || cm.id END
        AS Preview_link,
    'http' || CHR(58) || '//learn2.open.ac.uk/question/type/stack/questiontestrun.php' || CHR(63) || 'questionid=' ||
        q.id || '&' || CASE WHEN cm.id IS NULL THEN 'courseid=' || c.id ELSE 'cmid=' || cm.id END
        AS Question_tests_link

FROM mdl_question q
JOIN mdl_qtype_stack_inputs i ON i.questionid = q.id
JOIN mdl_qtype_stack_prts prt ON prt.questionid = q.id
LEFT JOIN mdl_question_categories qc ON qc.id = q.category
LEFT JOIN mdl_context ctx ON ctx.id = qc.contextid
LEFT JOIN mdl_course_modules cm ON cm.id = ctx.instanceid AND ctx.contextlevel = 70
LEFT JOIN mdl_course c ON (ctx.contextlevel = 50 AND c.id = ctx.instanceid)
                            OR (ctx.contextlevel = 70 AND c.id = cm.course)

WHERE feedbackvariables ~ ('\m' || i.name || ':')

ORDER BY c.shortname, qc.name, q.name
```

**Comment by timhunt** [comment]
Note that, in the past, one of the question in STACK-demo did this. CR-Diff-05-quotient-2.c did ans1:trigsimp(ans1)

So, understandable that other people would copy that.

**Comment by sangwinc** [comment]
Sorry about this Tim,
Changes cause problems.  Matti has also suffered with this kind of thing recently.
We have made some substantial improvements recently, but I appreciate there is some cost here.   If you can make suggestions of how we can fit this I'll certainly help.

**Comment by timhunt** [comment]
The thing is, if you preview the question, it seems to work, even though the question tests fail. There may be a solution where we make the question test code also pass in this case. I will look into it tomorrow.

**Comment by timhunt** [comment]
OK, now I look into this again, I see that these questions really are failing, and the Question tests are clearly reflecting that.

So, no issue here, and really we have not choice but to manually fix the affected quesitons (at least the ones that students will still be interacting with.)
