### ISSUE TITLE
CAS text validation rules seem to have changed

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#268]
We have a question with the question text below: It used to work. Now, when you try to save the editing form, or preview the question, you get a validation error:

CASText failed validation. CAS commands not valid. 
The characters @, $ and \ are not allowed in CAS input.

Any clues? (We are on latest master, a few commits ahead of 3.5.6). Thanks.

--------------

The  triangle \(ABC\) has angle \(@angle1@  = @vangle1@^\circ\), angle \(@angle2@ = @\vangle2@^\circ\) and side \(@side2@\) of length  @vside2@, where the angles \(A\), \(B\) and \(C\) and sides \(a\), \(b\) and \(c\) are labelled as shown below.

A triangle with vertices capital A, capital B and capital C and sides lower case ay, lower case b and lower case c. The side opposite the vertex A is labelled lower case ay, the side opposite the vertex B is labelled lower case b and the side opposite the vertex C is labelled lower case c.

Find the length of side \(@side1@\). Give your answer as a decimal number to one decimal place.

\(@side1@\) = [[input:ans1]]   

[[validation:ans1]]

**Comment by aharjula** [comment]
@\vangle2@

**Comment by sangwinc** [comment]
Yes Tim, we stopped adding in "\"s here:
https://github.com/maths/moodle-qtype_stack/commit/57d36c34558ac529f3aaf9f1f2dd9d76b958010e

I think this is a bug in your question perhaps?   If so, can we close this?
Chris

**Comment by timhunt** [comment]
Confirmed, these were buggy questions, and are now fixed at our end.
