### ISSUE TITLE
Insert stars code breaking question variables

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#269]
This is another question that used to work fine, and which is now failing in 3.5.6.

The question varibles contain this bit:

```
/* SNIP define Wvec etc. */

eqn1gen: coeff(Wvec+Svec+Tvec, ii ) =0
eqn2gen: coeff(Wvec+Svec+Tvec, jj ) =0

Generalanswers: solve([eqn1gen,eqn2gen], [S,T])
```

Now, when you try to save the editing form, or preview the question, you get

"You seem to be missing * characters. Perhaps you meant to type solve([eqn1\*gen,eqn2\*gen], [S,T])."

Is that supposed to have changed?

**Comment by aharjula** [comment]
I don't know it was supposed to change but the rules of automagic star insertion pretty much force that and I do believe this was changed years ago.

**Comment by sangwinc** [comment]
Tim,

I think this is a very odd artefact only affecting the letters "g" and "f".
https://github.com/maths/moodle-qtype_stack/commit/fc9397982fb19430b38f9709f715ff481f67935f

I'm very sorry if this has caused you problems.  Do you have many of these flagging up?

Chris

**Comment by timhunt** [comment]
The good news here is that all the affected questions are using variable names eqn1gen or eqn2gen.

And, none of our questions currently use the variable names eqngen1 or eqngen2.

Therefore, a straight search-replace eqn1gen -> eqngen1 (and same for 2) will fix it. I'll do that in our database. Closing this.
