### ISSUE TITLE
0 point PRT -> yellow, remove PRT?

### ISSUE THREAD

**Issue by AndersSkj** [maths/moodle-qtype_stack#271]
A question was implemented with a (fifth) PRT to give a hint if there was anything wrong in the answers. The PRT gives 0 points, and the question is marked with yellow ("unfinished"?) in the grades overview.

From https://stack.maths.ed.ac.uk/demo/question/type/stack/doc/doc.php/Developer/Future_plans.md
"A button to remove a given PRT or input, without having to guess that the way to do it is to delete the placeholders from the question text."

Are the placeholders the input or validations tags? I can't remove them since the other PRTs use one each of the answers. I tried removing all content from the fifth PRT but it remains after saving. What do I try next?

**Comment by aharjula** [comment]
Removing the prt-placeholders i.e. `[[feedback:prt5]]` removes the PRT... In abacus you could keep the PRT but place the PRT-placeholder inside `[[if test='false']] [[feedback:prt1]] [[/if]]`, to hide the feedback. Note that the placeholders might not be in question text they might be in the specific feedback instead...

**Comment by AndersSkj** [comment]
Thank you, fixed! My local support also pointed to "specific feedback". :)

Not sure if the answers marked in yellow in the overview are an issue or not. When I gave the PRT a nonzero point value the answers are marked with green.

**Comment by aharjula** [comment]
Maybe the other PRTs give some fancy broken floating point combination of points that when scaled to the question total points leads to only 99.99% of points being given and therefore it leads to "yellow"? How are the points distributed between the PRTs and what is the total value given to the question?

**Comment by AndersSkj** [comment]
Default mark: 1 (not quite sure what that is used for)
Four PRTs with Question value: 1
Maximum mark for that question (all questions) in the quiz: 1.00

It sounds like it would be exactly representable by floats.

**Comment by aharjula** [comment]
Indeed should be able to represent, Does the "yellow" happen with new tries to this question after all these changes i.e. four PRTs giving 100% and one PRT giving none? The adaptive multi-part behaviour handling the grading of those parts for a question that has changed the number of parts or their parameters has been know to fail so this should only fix future attempts not existing ones. For existing attempts one needs to do the full regrade to update those part specific details, although removing PRTs might cause problems.

**Comment by AndersSkj** [comment]
The before case was as you described, 4x1 + 1x0, and gave "yellow".
I removed the 0 point PRT and regraded, now all submitted solutions in the overview are "green".

**Comment by sangwinc** [comment]
Is this an authoring issue rather than a code issue or are you proposing some changes to the code?

**Comment by aharjula** [comment]
Probably an issue arising from changing the structure of a question with previous attempts... I don't think there is anything to do here.

**Comment by AndersSkj** [comment]
Probably not the best implementation of a hint. (I suppose it was made since the same hint goes for all four answers and the creator did not want it repeated four times.)
Is there a forum for inquiries about creating/editing questions, without necessarily implying bugs? :)
