### ISSUE TITLE
Shading in PRT

### ISSUE THREAD

**Issue by dhilsen** [maths/moodle-qtype_stack#272]
When using STACK with Moodle 3.2 (with Boost theme), the colored shading is stripped out of the PRTs. This is a very minor issue, however, the shading is very useful as it helps to quickly visualize the different sections of a node. Is there a way to bring back the shading in Moodle 3.2?

**Comment by sangwinc** [comment]
Tim,
I wonder if you'd be willing to look at this please?  I'm a bit helpless with the Moodle style aspects... (Sorry!)

**Comment by timhunt** [comment]
Willing: yes. Have time: not sure when that will be. Sorry.

**Comment by sangwinc** [comment]
David, is this still a live issue?

**Comment by dhilsen** [comment]
Thanks Chris for checking in on this issue. This is no longer an issue for us.
