### ISSUE TITLE
casstring->check_underscores() and the contents of strings...

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#273]
Annoying little detail with that function, as you are now running it for the raw casstring it ignores all the logic that protects the contents of strings for evil word detection. Can we please stop adding tests on top of tests ignoring the fact that we have strings?

We had a massive set of physics and probability materials with old texputs defining nice subscripts with raw latex `var_{....}` syntax and now those broke again. I was 95% happy with my newest merge until I met this problem and now my day is ruined :[

**Comment by aharjula** [comment]
Maybe the casstring-class needs a new property/field called "stringlesscasstring" and all those tests that do not need to check string contents would always use it rather than that "rawcasstring" which contains strings.

**Comment by aharjula** [comment]
https://github.com/aharjula/moodle-qtype_stack/commit/1a4e0cd825b45d474f06e0431e46b34ee1bafbcc

**Comment by aharjula** [comment]
In case the age questions that got broken by this is unclear, that attacked pretty badly against multiple choice questions that had verbosely written options using multiple subscripts. As well as physics materials from quite a long time ago. In addition to the labels of multiple choice questions it blocked texputs handling similar things.

**Comment by sangwinc** [comment]
Does 1a4e0cd fix all your questions Matti?  I'd consider pulling this one change into master now.

**Comment by aharjula** [comment]
Seems to and it should naturally allow us to again build multi term subscripts with LaTeX strings. Obviously, it does not fix all my questions just the ones that stopped working due to the errors given by that check.

**Comment by aharjula** [comment]
Oh and while you are there, please combine those patterns to a single array instead of building it one at a time every time that is called... Not that it is a major performance issue but it wastes cycles anyway unless someone actually compiles that code...

**Comment by aharjula** [comment]
This is fixed in the current dev branch.
