### ISSUE TITLE
Many STACK unit tests failing if you use a non-standard CAS configuration (e.g. MaximaPool)

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#276]
So, Matti and me have been having this problem. Almost all the unit tests fails.

**Comment by timhunt** [comment]
After some serious debugging, I have found the cause: In stack_answertest_fixtures_cas_test we have

```php
    /**
     * @dataProvider answertest_fixtures
     */
    public function test_answertest($testrep, $passed, $ansnote, $expectednote) {
            $this->assertTrue($passed);
            $this->assertEquals($expectednote, $ansnote);
    }

    public function answertest_fixtures() {

        $testdata = array();
        // Get the list of available tests.
        $tests = stack_answertest_test_data::get_all();

        foreach ($tests as $test) {
            $testrep = 'AT' . $test->name . "( " . $test->studentanswer . ", " .$test->teacheranswer. ")";
            if ($test->options != '') {
                $testrep .= ' Options: ' . $test->options;
            }

            list($passed, $error, $rawmark, $feedback, $ansnote, $anomalynote) = stack_answertest_test_data::run_test($test);
            $testdata[] = array($testrep, $passed, $ansnote, $test->ansnote);
        }
        return $testdata;
    }
```

It turns out that the @dataProvider answertest_fixtures is called before any tests are run, and here, incorrectly, the actual work of executing the test stack_answertest_test_data::run_test is being done in the data provider. It must be in the test method.

This is bad, becuase this happens before setUp is called, and that is where we set up the configuraiton for talking to the CAS.

Worse, in stack_connection_helper, the configuration is only read from the database once, and then cached. So, the wrong CAS settings are used for all tests.

Now I know this, I will re-write.

**Comment by timhunt** [comment]
This works for me.

**Comment by aharjula** [comment]
Yes it also works for me.

**Comment by sangwinc** [comment]
Thanks for tracking this down and fixing it Tim.
