### ISSUE TITLE
Only show the links in STACK questions to users who have the permission entitled "Edit all Questions".

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#277]
From a user:

> For our finalized STACK questions which various teachers will be accessing, it is our plan to not allow teachers to edit these questions due to the myriad of potential support issues that could arise from users not well versed with STACK. I'm wondering if there is a way to suppress the link "Question tests and deployed versions" that appears at the top of every question when a teacher is creating a quiz (we certainly want our question authors to have access to this feature when creating a question, but not the teachers using the questions). I'm wondering if there is a Moodle permission setting that might accomplish this. Teachers presently have permission to "use all questions" and "view all questions", they DO NOT have permission to "add new questions", "edit all questions", or "edit your own questions". With these settings, the "Question tests and deployed versions" link is appearing when a teacher creates a quiz.
> 
> I've carefully looked over all the permissions for the role of Teacher and it would seem to make the most sense to target the permission entitled "Edit all Questions", which determines whether or not a Teacher can edit a question. When this permission is denied, a teacher has no access to the STACK question authoring screen or any STACK tools, so it would seem to make sense to also remove the "Question tests and deployed versions" link which is essentially an authoring tool. With the link removed the teacher would see the question exactly as seen by a student, and not be confused by the function of the link as someone who is most likely not well-versed in STACK. 

**Proposal**: only show the links in STACK questions to users who have the permission entitled "Edit all Questions".

**Comment by timhunt** [comment]
Currently, the logic is (https://github.com/maths/moodle-qtype_stack/blob/master/renderer.php#L113) that users can access the diagnostic tools for a question if they have moodle/question:use(mine/all). That is, if they can add the question to a quiz, they can run the question tests.

To access the Tidy question script (https://github.com/maths/moodle-qtype_stack/blob/master/renderer.php#L144) or to deploy variants (https://github.com/maths/moodle-qtype_stack/blob/master/questiontestrun.php#L53, https://github.com/maths/moodle-qtype_stack/blob/master/questiontestrun.php#L160, https://github.com/maths/moodle-qtype_stack/blob/master/questiontestrun.php#L189, https://github.com/maths/moodle-qtype_stack/blob/master/questiontestrun.php#L219), or alter the test cases (https://github.com/maths/moodle-qtype_stack/blob/master/questiontestrun.php#L250, https://github.com/maths/moodle-qtype_stack/blob/master/questiontestrun.php#L351) they need the moodle/question:edit(mine/all).

So, it seems to me that we have already done this! :-)

**Comment by dhilsen** [comment]
I can certainly understand that for some environments it makes sense that if a teacher has the permission to "use all questions" then he/she can run the question tests. In our particular environment, as a publisher, we are creating questions which are thoroughly tested by the question authors, with the questions then used by teachers who have no familiarity with STACK or it's conceptual design. In this environment the question users have no meaningful understanding of the question tests and their appearance only adds an element of confusion.

Could I propose that an option appear on the STACK config page (or perhaps elsewhere) which would give the administrator the ability to display or suppress the link "Question tests and deployed versions" when a user does not have permission to edit questions. The default setting could be set to "display", this would allow the current functionality of STACK to remain unchanged.

**Comment by christianp** [comment]
Sounds to me like the most straightforward solution is to add a "can run question tests" permission.

**Comment by timhunt** [comment]
But, the question tests also serve as very good documention for someone using the question in the question in their quiz. It shows what different wrong answers have been captured, and with what specific feedback. It also shows which variants have been deployed.

You will have to work very hard to convince me that it is a good idea to hide this.

It would be poissible to add a new capability just for this. This is open source, if you really want it, make a patch (including automated tests), and we will review it.

**Comment by sangwinc** [comment]
I'm inclined to agree with Tim, that non-editing teachers should be able to view the question tests.  This really is a valuable thing.

Actually what we probably need to do is to add some code to stop them adding, deleting and modifying tests!

**Comment by dhilsen** [comment]
Chris, the additional code you proposed would be a wise idea.

**Comment by timhunt** [comment]
Chris, as I explained above (with links!) that code is already in place.

**Comment by aharjula** [comment]
And I will disagree with you all. Instead of tying this to some new rights lets just add an option to the question type so that those that do not want those links never see them and those of us that tolerate them can leave them to behave like now. The links are after all pretty much optional and should anyhow be available through the actual question editor from which they are missing for whatever reason. I for one find the current placement of those links somewhat odd and inconsistent and would rather see them accessible through the editor not through the preview...

And in my opinion if we are fearing that the inexperienced users would cause trouble having access to these, they are probably also unable to find any use for the "documentation" Tim mentioned.

Deploying variants however is an entirely different problem here... as the variants will apply to all uses of that question and therefore changing the variants is something that should indeed be limited.

**Comment by timhunt** [comment]
If you don't want those links in your particuarl Moodle install, the easiest option is to add a display: none rule to your CSS, or override the renderer in your custom theme.
