### ISSUE TITLE
SingleFraction answer test fails with negative fraction and brackets

### ISSUE THREAD

**Issue by timlowe** [maths/moodle-qtype_stack#282]
Thought it might be worth pointing this out, which has been noticed by one of our courses.

-(3/4)  fails the SingleFraction test, as I guess it is interpreted as the negation of a fraction
-3/4   passes fine.

(I've overcome this issue by forbidding the entry of brackets in this simple question - which was numerical fraction subtraction).

Tim

**Comment by sangwinc** [comment]
Thanks for the report Tim, and sorry if this caused you problems.
Chris
