### ISSUE TITLE
Issues with scientific_notation(x,n) function in STACK

### ISSUE THREAD

**Issue by dhilsen** [maths/moodle-qtype_stack#283]
We have experienced a number of issues when using the scientific_notation(x,n) function. We tend to use this function on a regular basis as we often deal with very large or very small numbers. Please accept my apology as the list below is quite extensive. It was compiled over a period of time and I felt it was best to gather the various issues together in a single report. 

All of the findings below are based upon using the input type "Units", and scientific_notation(x,2):

1. For positive numbers involving scientific_notation, the display looks to be somewhat incomplete as the multiplication sign is not present. For example, `1.55 x 10^8` is displayed as `1.55 10^8`. 

2. For negative values less than -0.0001, the scientific_notation function appears to be completely ignored as the number is displayed without using scientific notation. For example:
-0.001, -0.01, -0.1, -1, -10, -100, -1000 . . . are displayed without using scientific notation. 

3. For negative values which are displayed using scientific_notation, the exponential display 
(ex.  `-1.0E-7`) is used rather than the form which resembles scientific notation (as used for positive numbers).

4. For negative values which are displayed using scientific_notation, a long string of numbers is displayed after the decimal point. The scientific_notation parameter specifying the number of decimal places seems to be ignored.

5. The number 100 is displayed as 10.00 x 10^1; 1000 is displayed as 10.00 x 10^2; 10,000 is displayed as 10.00 x 10^3 (non-standard form for scientific notation).

6. There appears to be rounding issues associated with scientific_notation. Here are some examples:
a) 155.5 is displayed as 1.55 x 10^2 (expected result 1.56 x 10^2)
b) 15.55 is displayed as 1.56 x 10^1 (as expected)
c) 777.7 is displayed as 7.78 x 10^2 (as expected)
d) 775.5 is displayed as 7.75 x 10^2 (expected result 7.76 x 10^2)
e) 775.55 is displayed as 7.76 x 10^2 (as expected)
f) 0.5555 is displayed as 5.55 x 10^-1 (expected result 5.56 x 10^-1)
g) 0.05555 is displayed as 5.56 x 10^-2 (as expected)

7. When using the scientific_notation function with units, the correct answer shown to the student displays misleading formatting. The display will show the following: "A correct answer is 7.77 10^2 m/s, which can be typed in as follows:  `(7.77*10^2)*(m/s)`". If a student was to follow this input format, with brackets around the number, it will cause the NumSigFigs test to automatically fail.

8. When trig functions are involved in the calculation, a CAS error will often occur when using scientific_notation. Some interesting observations:
a) `cos(23*pi/180)` will result in a CAS error. However, substituting `pi` with 3.1416 will work fine.
b) `cos(30*pi/180)` will work fine.

**Comment by timhunt** [comment]
It would be helpful to know exactly which version of Maxima you are using, and also which version of Lisp you are using. If you can run Maxima from the command-line on your server, please copy and paste the output of the build_info(); function.

**Comment by dhilsen** [comment]
Thank you Tim for investigating this issue. We are running Maxima version 5.36.1. I'll have our Lisp version and Maxima build info to you shortly.

**Comment by dhilsen** [comment]
Here is the information obtained from the Maxima build_info function on our server:

Maxima version: "5.36.1"
Maxima build date: "2017-01-21 15:51:53"
Host type: "x86_64-unknown-linux-gnu"
Lisp implementation type: "CLISP"
Lisp implementation version: "2.49 (2010-07-07) (built 3605602979) (memory 3694024315)"

I hope this is helpful. It will be interesting to learn if there is something unique to our system which is causing the problems with the scientific_notation function. I believe this is the only issue we are presently experiencing with STACK.

**Comment by sangwinc** [comment]
Thanks for this very helpful and comprehensive list of test cases.  I've been thinking about how to address these tonight.  Leave it with me.
Chris

**Comment by sangwinc** [comment]
David,

The commit fe0eda7 has, I hope, fixed almost all of the issues you have highlighted above. 

Could I ask you to look carefully at all the test cases here: https://github.com/maths/moodle-qtype_stack/commit/fe0eda7afc14bf3945e913530ca55803f23517d6#diff-e5c585e1f763a0280c920a07830ab236R877

Please add more test cases, especially numbers in the extremes you are likely to use in physics.  

Point by point.

1. The multiplication symbol is a global setting.  In the proposed changes I've added another "ephemeral form" which deals with scientific notation.  It is of the form displaysci(n,dp,exp).  This is displayed by tex as n*10^exp where n is written to dp decimal places. 

2., 3., 4. deal with negative numbers.  The old code only worked for positive numbers and this is now fixed.

5. is an edge case I've hard-wired.

6. rounding was previously dealt with by the underlying lisp display function "format".  I've added in a call to the STACK "significantfigures" function here to control rounding explicitly.
https://github.com/maths/moodle-qtype_stack/commit/fe0eda7afc14bf3945e913530ca55803f23517d6#diff-c8bf47f3f4e78bbaf12ba8bc5fa1f8e6R340

7. On hold for today (let's fix the others first).

8. is added as a test case.

In addressing 1. we have added a new ephemeral form.  If a user has expected scientific_notation(ex) to return a *value* of a*10^b then the displaysci function will break this.  This will be a significant change in behaviour, which may break many questions for other people.  Can the other developers comment on this?

Votes for 
(A) change scientific_notation(ex,d) to return the displaysci form, fixing the display in existing questions but breaking the value.
(B) keep scientific_notation(ex,d) to return a value, and introduce a new function to fix the display?

Chris

**Comment by dhilsen** [comment]
Thank you Chris. I reviewed all the test cases and they all look good. I will add additional test cases as requested.

**Comment by sangwinc** [comment]
Thank you David for these additional test cases.  All the test cases in the latest commit to this branch now pass.  (I'll run the unit tests on the whole project this afternoon to conform we've no side effects).

So, we have two issues to resolve.

(A) should we change the behaviour of scientific_notation(ex,d) to return the displaysci form, fixing the display in existing questions but breaking the value, or should we introduce a new function to return a displayed form.

(B) What should we do about the teacher's answer?  I think this is a different issue, not to do with the tex, but to do with the string output of the value.  The fixes to the displayed form won't help with the extra brackets.  Actually, I think this is very sensitive to the version of Maxima.  There are some changes to associativity between versions!

**Comment by dhilsen** [comment]
Great to hear all test cases pass. I'll give my humble opinion on the remaining issues (and hope that I am correctly understanding the issues). 

I would vote for changing the behavior of scientific_notation(ex,d) to return the displaysci form, as opposed to introducing a new function. The central question appears to be whether or not users have been using scientific_notation for anything other than display purposes.
