### ISSUE TITLE
CASText failed validation. CAS commands not valid. when preview all test results on one page 

### ISSUE THREAD

**Issue by knedlyk** [maths/moodle-qtype_stack#287]
I got this when trying to review quiz results. It happen when results are all on one page. When "showall=0" everything is ok. Below is trace:

Error rendering the general feedback text: CASText failed validation. CAS commands not valid. The characters @, $ and \ are not allowed in CAS input.The characters @, $ and \ are not allowed in CAS input.The characters @, $ and \ are not allowed in CAS input.The characters @, $ and \ are not allowed in CAS input.

Debug info:
Error code: exceptionmessage
Stack trace:
    line 376 of /question/type/stack/question.php: stack_exception thrown
    line 463 of /question/type/stack/renderer.php: call to qtype_stack_question->get_generalfeedback_castext()
    line 120 of /question/type/rendererbase.php: call to qtype_stack_renderer->general_feedback()
    line 170 of /question/type/stack/renderer.php: call to qtype_renderer->feedback()
    line 411 of /question/engine/renderer.php: call to qtype_stack_renderer->feedback()
    line 113 of /question/engine/renderer.php: call to core_question_renderer->outcome()
    line 113 of /question/behaviour/behaviourbase.php: call to core_question_renderer->question()
    line 829 of /question/engine/questionattempt.php: call to question_behaviour->render()
    line 449 of /question/engine/questionusage.php: call to question_attempt->render()
    line 1537 of /mod/quiz/attemptlib.php: call to question_usage_by_activity->render_question()
    line 1500 of /mod/quiz/attemptlib.php: call to quiz_attempt->render_question_helper()
    line 187 of /mod/quiz/renderer.php: call to quiz_attempt->render_question()
    line 56 of /mod/quiz/renderer.php: call to mod_quiz_renderer->questions()
    line 259 of /mod/quiz/review.php: call to mod_quiz_renderer->review_page()

PHP version 7.0.14

**Comment by knedlyk** [comment]
Please close this issue, the problem was in illegal characters in question.

**Comment by sangwinc** [comment]
Thanks for reporting the issue.  Glad you fixed it!
