### ISSUE TITLE
Stack 3.5.6 compatibility with PHP 7.1.*

### ISSUE THREAD

**Issue by nmouillet** [maths/moodle-qtype_stack#291]
Hello,

Stack don't work here with PHP 7.1, here is my fix:

Config:
Linux CentOS 7
PHP 7.1.*
Moodle 3.2.2 (Build: 20170313)

Error page:
/question/type/stack/healthcheck.php

Error:
Warning: Illegal string offset
On connector.class.php, in unpack_helper function
line 267: $unparsed[$var] = $val;

Fix:
$unparsed must be an array.
line 250: $unparsed = [];

**Comment by aharjula** [comment]
Thank you for the reminder on this, we really should start testing more aggressively on various PHP versions as things that were merely warnings in older ones tend to come and bite us now. 

This sounds very much like #266, and I thought that this was already fixed, maybe you are using a version of STACK that is from before February?

**Comment by nmouillet** [comment]
You're right, my bad.
I've took the code on https://moodle.org/plugins/qtype_stack, seems not up to date.

**Comment by aharjula** [comment]
No problem. The releases there do indeed lag a bit and there has not been a new release containing this fix. Anyway closing as it seems like it has been fixed.

**Comment by sangwinc** [comment]
Thank you very much for contacting us.  Please don't hesitate to let us know of any difficulties.
