### ISSUE TITLE
Ajax validation of textarea (and equiv inputs)

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#293]
Ajax sends the student's response from the browser to STACK as a Maxima list.   For example, the input
```
x+1
x+2

```
will be packaged up and sent to STACK as `[x+1,x+2]`.

This is all very well for everything except missing brackets errors.  If we have

```
x+1
x+2]
x+3
```
then this will be packaged up and sent to STACK as `[x+1,x+2],x+3]`.  Then this is unpacked by ajax_to_response_array($in) (in input base class, modified by the textarea/equiv) then everything breaks.

The solution will be to modify the way ajax packages up expressions to make clear line breaks, so we can validate each line individually.

This error only shows up with instant validation.

**Comment by sangwinc** [comment]
Tim, Matti, 
Could I ask you to please look at my proposed fix to this issue?  I'm not all that confident with the ajax validation part of the code.
Cheers,
Chris

**Comment by timhunt** [comment]
I just wonder if preg_replace would be better than explode/impolote. E.g. it would let you match <br /> too (not sure if any browsers actually sent that.)
