### ISSUE TITLE
Question test failures in a fraction question

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#294]
I am not sure if this is a bug with STACK, or a problem with our question (tests). See this question:

[questions-T193-17D-T193 MRQ 1 Fractions A Numerical fraction add-20170523-1157.xml.txt](https://github.com/maths/moodle-qtype_stack/files/1021879/questions-T193-17D-T193.MRQ.1.Fractions.A.Numerical.fraction.add-20170523-1157.xml.txt)

Test case 4 fails, at least in our slightly elderly version of STACK.

![image](https://cloud.githubusercontent.com/assets/138653/26351335/29dbcb66-3faf-11e7-9dac-b41b69623dbb.png)

![image](https://cloud.githubusercontent.com/assets/138653/26351355/3b4a4db4-3faf-11e7-8878-9a924e571580.png)

Is this sort of question test supposed to pass? Should we add an extra ev() call, or something like that?

**Comment by timlowe** [comment]
To clarify.  I think the general issue here is whether "Forbidden words" should be forbidden in the (authors) input to question tests. (My view is that they should not).

The specific case here arose as follows. Student input of, for example,   -(1/3) was not being interpreted as a single fraction. I raised this with Chris and the answer test has now been fixed, by not yet adopted at the OU. In the meantime, my workaround was to forbid entry of brackets. I forgot that the use of "ev" in the question test input required brackets for its syntax.

I realise I could overcome this by re-writing the question tests and/or waiting for us to adopt the system fix, but I think there is a general issue: should the question test input be subject to the forbidden words?

Tim

**Comment by sangwinc** [comment]
Tim,

I'd like the question tests to behave like the question!  That means, my instinct is that forbidden words should be forbidden.  If you want to forbid something like "+" in an answer, but need to use "+" to create the test case then the test case can be wrapped in ev( ... , simp) to evaluate the addition.

Maxima has started to add a lot more brackets, which is annoying.  This is causing the problem in this case I think. We now have brackets in (-14)/12. I'd like this to be 14/12.  I'll try to look into this problem.

[Also, I find it useful to include the correct answer in the question note.  Just a tip!]

**Comment by timlowe** [comment]
Thanks Chris.  I take your point about tests replicating input.

However in this case, since I forbade the input of brackets, I cannot used the ev command either!

(Hopefully the OU systems will shortly catch up with the update of the SingleFrac test to overcome this, in which case I can remove the forbidding of brackets).

**Comment by sangwinc** [comment]
Yes Tim,
This is a catch 22 type situation.  Unless we start getting into escaping values which we should allow/forbid....!
