### ISSUE TITLE
Change in syntax checking?

### ISSUE THREAD

**Issue by timlowe** [maths/moodle-qtype_stack#295]
I believe there has been a (backwards) change in the input syntax checking rules?

In the (recent past), input such as sin^2(x) was caught with feedback asking whether they meant to enter sin(x)^2.

In the current version used at the OU, this is no longer happening?

**Comment by sangwinc** [comment]
That is odd Tim,

The check is certainly in the latest master branch
https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/casstring.class.php#L705
This functionality has been re-factored into a special function in the current development code:
https://github.com/maths/moodle-qtype_stack/blob/equiv_input/stack/cas/casstring.class.php#L786

There is a test case:
https://github.com/maths/moodle-qtype_stack/blob/equiv_input/tests/fixtures/inputfixtures.class.php#L357

I think this is a non-issue for the current master, and development code.  Which version are you using?
Chris

**Comment by timhunt** [comment]
I am afraid we are running the rather old 2016122100.

**Comment by timlowe** [comment]
Thanks Chris. You inspired me to check further and I think it is  "insert stars assuming single character variable names" that is breaking it.

It works as expected with most "insert stars" options,  but when using these including "assuming single character variable names", STACK now seems to interpret "sin" as "s*i*n" before applying the syntax check

I'm pretty sure it didn't do that in previous versions we used.

Unfortunately (perhaps typically!) that's the option most of our questions use!

Tim
