### ISSUE TITLE
Typo in English language string ?

### ISSUE THREAD

**Issue by germanvaleroelizondo** [maths/moodle-qtype_stack#301]
While translating ATAlgEquiv_SA_not_logic | qtype_stack , I found the following string odd-looking:

Your answer should be an equation, inequality of a logical combination of many of these, but is not.

I wonder if 'of a logical combination' should really be 'or a logical combination'

Or maybe I just forgot my undergraduate math.

Thanks in advance for your help.

**Comment by sangwinc** [comment]
Yes, it should be "or a ..."  

Thank you very much for reporting this.
Chris
