### ISSUE TITLE
Image generation

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#302]
This commit 5fb8f1b70525e3044b18b66221e886eeb04c89a changed the way we generate image URLs in STACK for Moodle 3.3.  However, this now throws an error in Moodle 3.2.2.

> Call to undefined method theme_clean_core_renderer::image_url()

**Comment by sangwinc** [comment]
I'm surprised this change appears to break back compatibility with Moodle 3.2.2.  Am I doing something wrong here?  Is the proposed fix above the "right moodle" thing to fix this problem?

**Comment by timhunt** [comment]
I'm confused: why did you change pix_url to image_url? I can't see any explanation for that.

**Comment by timhunt** [comment]
Sorry, ignore my last comment. I was looking at the 3.2 code, so obviously changes for 3.3 were not apparent.

It seems that the only option is to add a helper function like

**Comment by timhunt** [comment]
OK, so there are two solutions:

1. Implement a helper method like this: https://github.com/danpoltawski/moodle-repository_github/blob/master/lib.php#L279 which sniffs the version and calls the right function. 

2. Probably better: Swtich to using pix_icon (which generates the whole <img> tag - or an <i> tag using FontAwesome in 3.3) rather than assembling the HTML yourself.

**Comment by sangwinc** [comment]
Thanks for responding Tim,
This is where I show my ignorance of the differences between pix_icon, pix_url and the rest of it! 
I assume that if a helper function was really needed then Moodle core should have provided it, so I'll take your advice on (2) and switch to pix_icon.
Any objection to the above commit?  If not, please just close this.

**Comment by timhunt** [comment]
That looks right Chris. Thanks.

The reason they did not add a helper function to Moodle is that really you would need it in all versions from Moodle 3.2.0 onwards to be useful, but this work was being done after 3.2.0 had been released.
