### ISSUE TITLE
Upgrading crashes

### ISSUE THREAD

**Issue by kkiiskin** [maths/moodle-qtype_stack#305]
-->qtype_stack
!!! Can not downgrade qtype_stack from version 2017080800 to version 2017060501. !!!
!!
Error code: cannotdowngrade !!
!! Stack trace: * line 347 of /lib/upgradelib.php: downgrade_exception thrown
* line 729 of /question/type/stack/db/upgrade.php: call to upgrade_plugin_savepoint()
* line 558 of /lib/upgradelib.php: call to xmldb_qtype_stack_upgrade()
* line 1748 of /lib/upgradelib.php: call to upgrade_plugins()
* line 181 of /admin/cli/upgrade.php: call to upgrade_noncore()
 !!

**Comment by sangwinc** [comment]
Kimmo,
I'm really sorry you are having this problem.  I have lots (!) of servers on the go, with various test machines so before releasing we tested this.  It is a policy of Moodle not to let people downgrade.   

What exactly are you trying to do?  I.e which version did you have, and what did you try to upgrade to?

Perhaps we could pick this up by email as it sounds like an individual issue? But,  I'll keep this issue open in case it is a general problem.

**Comment by aharjula** [comment]
Chris, it seems like there are two upgrades in the upgrade.php that are not in order. Probably assume positive has been merged to the wrong place... Anyway probably stops the question note from being upgraded. Should you fix it please redo the question note upgrade with a bigger version number and make a new release...

Odd that this has not given errors on our installations.

**Comment by kkiiskin** [comment]
Hi,

sorry I didn't have time to give details before as I was in middle of an update.

Stack question type version was being upgraded from 2016022900 to 2017081600.
Seems it added the 'assumereal'-field AND managed to upgrade 'questionnote' before crashing.
If this seems right?
| questionnote              | longtext     | NO   |     | NULL    |                |

After starting Moodle's upgrade prcocess again, it went through.

**Comment by sangwinc** [comment]
I'm really very sorry and embarrassed about this!  I don't know why this didn't show up when I installed or upgraded any of my servers.  I do both upgrades, and fresh installs, regularly.  Well there we are.  If the latest code in master does not fix the problem please re-open this issue.

**Comment by aharjula** [comment]
Chris, unfortunately the ordering of those versions in the upgrade.php has led to a situation where we have a subset of Abacus branch upgrades that had a suitable original version and thus managed to ignore the question note upgrade after the version had been changed by the assume positive upgrade. It should not be an problem for people that did not upgrade before that fix but will require intervention for people that did. Unless we release a new version which shifts the question note upgrade to yet another newer version number...

**Comment by aharjula** [comment]
The problem with testing upgrades is that you would need to test upgrades from each possible previous version and that is something that we obviously can't do if people are installing from live development branches.

**Comment by sangwinc** [comment]
Matti,
I'd really like all users to have a very smooth upgrade experience, through the normal Moodle process if at all possible.
If we have to release a new version which shifts the question note upgrade to yet another newer version number then I'm very happy to do that today.  Should I do this?
Chris

**Comment by aharjula** [comment]
Chris,
Yes please, the manual trickery to fix this is way too complex to explain to multiple people of very varying skill levels. 

Luckily the question note upgrade will not cause issues when we re-run it for those that may have gotten it already from last nights version.

**Comment by timhunt** [comment]
Since chaging the size of question_note is idempotent, then there is no problem repeating the step.

So, yes, if you add a repeat of that step at the end of the process with a new version number, and do a 4.0.1 release, then that will ensure everyone's STACK install ends up in the right state.

**Comment by sangwinc** [comment]
Tim,
I've added in this upgrade again and get this message:

XMLDB has detected one TEXT/BINARY column (questionnote) with some DEFAULT defined. This type of columns cannot have any default value. Please fix it in source (XML and/or upgrade script) to avoid this message to be displayed.
line 1853 of /lib/datalib.php: call to debugging()
line 352 of /lib/xmldb/xmldb_object.php: call to xmldb_debug()
line 261 of /lib/xmldb/xmldb_field.php: call to xmldb_object->debug()
line 131 of /lib/xmldb/xmldb_field.php: call to xmldb_field->setDefault()
line 103 of /lib/xmldb/xmldb_field.php: call to xmldb_field->set_attributes()
line 735 of /question/type/stack/db/upgrade.php: call to xmldb_field->__construct()
line 545 of /lib/upgradelib.php: call to xmldb_qtype_stack_upgrade()
line 1647 of /lib/upgradelib.php: call to upgrade_plugins()
line 683 of /admin/index.php: call to upgrade_noncore()

I'm not sure what to do about this.  Is this simply an artifact of the existence of this field already?

**Comment by aharjula** [comment]
That when you moved these lines to the end and upped the numbers: https://github.com/maths/moodle-qtype_stack/blob/b23551cf934b9bd0adb8f232bcbe2f44eceaeb7d/db/upgrade.php#L706-L717

Or did you do anything else?

**Comment by timhunt** [comment]
This seems to be happening when we call the xmldb_field->__construct(), which is just setting up information about what might need to change, not actually changing anything in the database.

I assume we are not trying to set a default.

Probably, some argument to that constructor call is wrong. Should be NULL, not ‘’, for the default (last argument) - in both places if necessary.

**Comment by aharjula** [comment]
I think there was something about those defaults when we did that conversion from varchar to text and now it seems that those values for defaults cause trouble for the no-op between text and text. Maybe there is a way of asking the XMLDB if the field is already text to avoid this?

**Comment by sangwinc** [comment]
Ok, so should I leave the command as

`$field = new xmldb_field('questionnote', XMLDB_TYPE_TEXT, 'medium', null, XMLDB_NOTNULL, null, '');`

I've basically just moved this
https://github.com/maths/moodle-qtype_stack/blob/master/db/upgrade.php#L706-L717

to just above
https://github.com/maths/moodle-qtype_stack/blob/master/db/upgrade.php#L732
and updated the dates.

I've not changed the DB code at all...  Do you both agree this is what should be pushed?

**Comment by aharjula** [comment]
Difficult to say, it fixes the cases where that update has not been executed. But gives that message for people that have installed after the 16th or upgraded after last night, that group is probably minimal.

**Comment by sangwinc** [comment]
The warning does not appear to be a symptom of a genuine problem.  Tim, any comment?

**Comment by timhunt** [comment]
You shoud change that '' to NULL in both places, so the warning does not appear, but that is all that is required.

**Comment by aharjula** [comment]
Before pushing the NULLs do test if it actually works when upgrading a version with varchar question note. I have a very distinct memory that that caused trouble when I was in Edinburgh.

**Comment by sangwinc** [comment]
Tim, 
I hope the following commit accurately encapsulates your suggested changes above?
https://github.com/maths/moodle-qtype_stack/commit/1b47d2ce819943f4dabe26e7a5725c5ff32f4981

No problems with the upgrade script on a server which already has this change implemented.

I've installed a fresh Moodle with the demo materials (i.e. non-empty notes) and an old version of STACK (v3.4) which is well before the answer note change.  Then I fast forwarded with this change

No problem upgrading from the legacy materials, but that does not mean people using the abacus branch won't have problems!  Matti, did you check an only abacus branch?

I'm treating the "svg" branch https://github.com/maths/moodle-qtype_stack/tree/svg as a release candidate for v4.0.1 which I'll unit test over night.

**Comment by timhunt** [comment]
Yes, that change looks right, and the testing you did also looks right. Thanks.

**Comment by aharjula** [comment]
Red through the code and as it seemed ok I installed it (the svg branch) directly on live abacus which had the version from 16th and thus no question note update. Question note upgraded just fine no errors. SVG plots look good everywhere but on the healthcheck where I get time-outs from MaximaPool. Now to hunt for the reason for that as the Pool should not care one bit on which type of files the Maxima process wants to output.
