### ISSUE TITLE
CAS "Too many arguments supplied to" errors in answer tests

### ISSUE THREAD

**Issue by turtaniumx** [maths/moodle-qtype_stack#307]
I am getting the following errors in the answer tests for STACK 4.0.1 (after updating from STACK 4.0.0). Any answer test not listed below is working fine.

The errors below are taken from the "Feedback" category of the answer tests

- _Expected failure cases with division by zero_
The answer test failed to execute correctly: please alert your teacher. Division by zero.

- **FacForm**
The answer test failed to execute correctly: please alert your teacher. Too many arguments supplied to ATFacForm(SA,SBL); found: [2,2,STACKOP]

- **CompSquare**
The answer test failed to execute correctly: please alert your teacher. Too many arguments supplied to ATCompSquare(SA,SBL); found: [1,(x-1)^2+1,STACKOP]

- **Equiv** and **EquivFirst**
The answer test failed to execute correctly: please alert your teacher. CAS failed to return any data. STACKSA:x

- **PartFrac**
The answer test failed to execute correctly: please alert your teacher. Too many arguments supplied to ATPartFrac(SA,SBL); found: [1/n = 0,1/n,STACKOP]

- **Diff**
The answer test failed to execute correctly: please alert your teacher. Too many arguments supplied to ATDiff(sa,sbl); found: [1/0,3*x^2,STACKOP]

- **Int**
The answer test failed to execute correctly: please alert your teacher. Too many arguments supplied to ATInt(sa,sbl); found: [1/0,1,STACKOP]

- **NumRelative**, **NumAbsolute**, **NumSigFigs**
The answer test failed to execute correctly: please alert your teacher. Too many arguments supplied to ATNumRelative(SA,SB); found: [1.5,1.5,STACKOP]

- **Units**, **UnitsStrict**, **UnitsRelative**, **UnitsStrictRelative**, **UnitsAbsolute**
The answer test failed to execute correctly: please alert your teacher. Too many arguments supplied to ATUnitsSigFigs(SA,SBL); found: [1/0,1,STACKOP]

I am using Maxima 5.36.1 on Ubuntu 16.04.

**Comment by sangwinc** [comment]
Thanks for reporting this, and sorry you are having problems.

Can you confirm that you have re-generated the optimised maxima image?  

Can you clarify that these are internally generated errors?  Or are these from instances where the question author has written this code in the question?

The answer test code is internal and not designed to be accessed directly by question authors.  I have refactored the code as follows. Old behaviour all answer tests took two arguments.

```
ATnooption(SA,SB) had two arguments
ATwithoption(SA,[SL,opt])
```
The advantage was every answer test had two options.  But the code had to unpack a "list" as the second argument which was very problematic if the teacher's answer was a list, but no option was supplied...

The new behaviour is to have 
```
ATnooption(SA,SB) had two arguments (as before)
ATwithoption(SA,,SL,opt) now takes three arguments.
```
Now functions take the correct number of arguments.

This will affect users who have called these (internal) functions explicitly in their question code...

I suspect you need to create a new maxima image in the optimised version.  The old optimused image will contain the old code, which will complain you now have too many arguments.

This should *not* be a difference between 4.0.0 and 4.0.1.

**Comment by turtaniumx** [comment]
Your suggestion to regenerate the optimized image fixed the errors up. Thank you!

I believe I may have been using the "Linux" version when I tested in 4.0.0 and then switched to the "Linux (optimized)" sometime after the 4.0.1 update, which is why I may have suspected the version change to have triggered something.
