### ISSUE TITLE
if statement blocks having weird behavior with multiple elif

### ISSUE THREAD

**Issue by turtaniumx** [maths/moodle-qtype_stack#309]
Question variables
```
a : 2
b : 3
c : 2


a_mul : if a=b or a=c then 2 else 1;
b_mul : if b=a or b=c then 2 else 1;
c_mul : if c=a or c=b then 2 else 1;
```

CAS text
```
There is a zero at \(x={@a@}\)

[[ if test="is(a_mul=2) and is(a=b)" ]]
with a multiplicity of 2 and a zero at \(x={@c@}\) with a multiplicity of 1.   
[[ elif test="is(a_mul=2) and is(a=c)"]]
with a multiplicity of 2 and a zero at \(x={@b@}\) with a multiplicity of 1.
[[ elif test="is(b_mul=2) and is(b=c)"]]
with a multiplicity of 2 and a zero at \(x={@a@}\) with a multiplicity of 1.
[[ else ]]
, a zero \(x={@b@}\), and a zero at \(x={@c@}\), all of which have a multiplicity of 1.
[[/ if]]
```
Output (with strange addition)

> There is a zero at x=2 with a multiplicity of 2 and a zero at x=3 with a multiplicity of 1. , a zero x=3, and a zero at x=2, all of which have a multiplicity of 1.

I rewrote the above in Java to make sure I was interpreting this situation correctly.

I noticed that if b=c then the above code works fine without the strange addition at the end. This correlates to how the test of "is(b=c)" is next to the else statement. So if you move another elif blocks around to be nearest to the [[ else ]], then the equality that elif contains will also work correctly.

STACK 4.0.1; Maxima 5.36.1

**Comment by aharjula** [comment]
Thank you for spotting this, apparently no one has used the "elif" enough in our testing. The compiler for castext pre-processes that to simple if-blocks, this because we do not want the conditions to be able to change by definitions inside the branches:

```
 [​[ define stackparsecond5="(is(a_mul=2) and is(a=b))" stackparsecond6="not (stackparsecond5) and ((is(a_mul=2) and is(a=c)))" stackparsecond7="not (stackparsecond6) and ((is(b_mul=2) and is(b=c)))" stackparsecond8="not (stackparsecond7)" /]​][​[ if test="stackparsecond5" ]​]

 with a multiplicity of 2 and a zero at \(x={@c@}\) with a multiplicity of 1.   

 [​[/ if ]​][​[ if test="stackparsecond6" ]​]

 with a multiplicity of 2 and a zero at \(x={@b@}\) with a multiplicity of 1.

 [​[/ if ]​][​[ if test="stackparsecond7" ]​]

 with a multiplicity of 2 and a zero at \(x={@a@}\) with a multiplicity of 1.

 [​[/ if ]​][​[ if test="stackparsecond8" ]​]

 , a zero \(x={@b@}\), and a zero at \(x={@c@}\), all of which have a multiplicity of 1.
 [​[/ if ]​]
```

And it is quite obvious that the condition (here stackparsecond8=not (stackparsecond7)) tor the "else" branch is wrong it should naturally only be true if none of the previous branches are true (i.e. stackparsecond8=not (stackparsecond5 or stackparsecond6 or stackparsecond7)). I shall fix this, and I should be able to push a fix very soon.

**Comment by aharjula** [comment]
A [fix](https://github.com/maths/moodle-qtype_stack/commit/38ccfeb7194a2846d2dc9756681dea41152b192a) exists in branch [iss309](https://github.com/maths/moodle-qtype_stack/tree/iss309) should you wish to test it you can simply replace `stack/cas/castext/castextparser.class.php` with the [one](https://raw.githubusercontent.com/maths/moodle-qtype_stack/38ccfeb7194a2846d2dc9756681dea41152b192a/stack/cas/castext/castextparser.class.php) from that branch.

I'll test this a bit more and maybe it will get to master in the next point release.
