### ISSUE TITLE
factorlist command broken when there is a factorable negative

### ISSUE THREAD

**Issue by turtaniumx** [maths/moodle-qtype_stack#310]
Negative leading coefficients/factors causes factorlist display a list with length 1

factorlist(x^2+x-6) has an output [x-1, x+2] (length of 2)

while factorlist(-x^2-x+6) > [-x-1 x+2] (length of 1)

This also happens with binomial form polynomials: factorlist(-(x+2)^2*(x-1) )

STACK 4.0.1; Maxima 5.36.1

**Comment by sangwinc** [comment]
Thank you very much indeed for reporting this bug & apologies.

The unary-minus is the bane of my life.....
