### ISSUE TITLE
New answer test - Decimal separator in the wrong place

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#314]
There is a not that uncommon need to note the cases where the end result has its decimal separator in the wrong place. I have done some sketching to formulate a test that identifies that case and only that case. This is what I have come up for now:

```
test_dec_sep(sa,ta):= block([tmp],
 if is(sa=ta) then return(false),
 if is(sa>0) and is(ta<0) then return(false),
 if is(sa<0) and is(ta>0) then return(false),
 if is(ta=0) then return(false),
 tmp: ATAlgEquiv(sa,ta),
 if is(tmp[2]=true) then return(false),
 tmp: ev(log(abs(float(sa/ta)))/log(10.0),simp),
 if is(tmp-floor(tmp)<STACK_NUM_TOL) then return(true),
 if is(ceil(tmp)-tmp<STACK_NUM_TOL) then return(true),
 return(false)
)$ 
```
Naturally, needs error reporting to identify non scalar inputs and maybe even a Unit wrapper.

Could we have this as an "Answer Test" or more suitably as a "Failure Test"? 

Can anyone come with any interesting options this test would need? For now I have been thinking that maybe one should be able to limit the scale of the error in the test to identify small just a few places and astronomical errors, but would it also be necessary to identify the direction of the error? Basically, I think that giving 100 g of aspirin is entirely different type of an error than giving just one nanogram.

**Comment by sangwinc** [comment]
Matti,

We were talking about something very similar in Edinburgh recently and this would be a very useful addition.  I worry about the numerical precision difficulties I'm having with significant figures.  I wonder if for the purposes of assessment this might be done at the PHP level looking only at the written form of the student's answer?  If we throw away decimal points, and leading zeros, how many of the digits match up?

**Comment by christianp** [comment]
From experience, looking at the written form of the student's answer, rather than trying to do arithmetic with it, is the safest option.

**Comment by aharjula** [comment]
I was wondering how to handle tolerances in conjunction with this test and indeed throwing away the decimal points might be the way to handle that issue. Basically if I expect the answer of 1234 and the student gives 1.234 it is simple to identify (with that test) that that decimal point has wandered a bit but if the answer is 1.23 some rounding has also happened and the test I have written there can't work unless we add some option to match N-digits.

However I do not think this needs to happen on PHP-side as long as the number is a number (or comes with units) and goes into the CAS as such we have all the tools we need. The only problem where we lack tools is the case of significant figures and that is a separate issue.

Here is a new and improved test version with options, the options are one integer and one float in any order. The integer defines the maximum offset acceptable with a direction without it all offsets are identified and the float defines how close a value needs to be if we ignore the decimal point.

```
test_dec_sep(sa,ta, to):= block([tmp,tol,offset,offlimit,sM,tM],
 if is(sa=ta) then return(false),
 if not is(sign(sa)=sign(ta)) then return(false),
 if is(ta=0) then return(false),
 tmp: ATAlgEquiv(sa,ta),
 if is(tmp[2]=true) then return(false),

 tol: 0,
 offlimit: 0,
 if integerp(to) then offlimit: to,
 if floatnump(to) then tol: to,
 if listp(to) then (
  map(lambda([t],if integerp(t) then offlimit:t),to),
  map(lambda([t],if floatnump(t) then tol:t),to)
 ),

 sM: ev(sa*10^-floor(float(log(sa)/log(10.0))),simp),
 tM: ev(ta*10^-floor(float(log(ta)/log(10.0))),simp),
 /* Should the values be too far when compared without decimal points end the test. */
 if is(abs(sM-tM)>tol) then return(false),

 tmp: ev(log(abs(float(sa/ta)))/log(10.0),simp),
 offset: false,
 if is((tmp-floor(tmp))<0.5) then offset: floor(tmp),
 if is((ceiling(tmp)-tmp)<0.5) then offset: ceiling(tmp),

 if is(offset=false) then return(false),
 /* offlimit=0 then all offsets are reportted */
 if is(offlimit=0) then return(true),

 /* The sign of the offset limit determines which side we track we ignore the other one. */
 if not is(sign(offset)=sign(offlimit)) then return(false),
 if is(abs(offlimit)>=abs(offset)) then return(true),

 return(false)
)$ 
```

And some examples:
```
(%i3) test_dec_sep(0.1230,1234,[0.1,0]);
(%o3) true
(%i4) test_dec_sep(0.1230,1234,[0.1,1]);
(%o4) false
(%i5) test_dec_sep(0.1230,1234,[0.1,-4]);
(%o5) true
(%i6) test_dec_sep(0.1230,1234,[0.1,-3]);
(%o6) false
(%i7) test_dec_sep(0.1230,1234,[0.0001,-5]);
(%o7) false
(%i8) test_dec_sep(0.1230,1234,[0.001,-5]);
(%o8) false
(%i9) test_dec_sep(0.1230,1234,[0.01,-5]);
(%o9) true
(%i10) test_dec_sep(0.1230,1234,0.01);
(%o10) true
(%i11) test_dec_sep(0.1230,1234,0);
(%o11) false
(%i12) test_dec_sep(0.1234,1234,0);
(%o12) true
```

**Comment by sangwinc** [comment]
Matti,
Do you have any thought where you'd like to connect this up to the main code base?
Should this be a new answer test, or should we use it to add feedback to the existing answer tests?
Chris

**Comment by aharjula** [comment]
Chris,
Personally, I think that adding this to all relevant current tests would give a bit too much information by default in the feedback to the students (and might duplicate feedback in older materials), but there are people that would prefer to have tests that handle "everything" in a single test. I am against such tests that do everything as it is typically difficult to toggle specific parts of the feedback off (the idea of silencing the whole test that would give multiple different useful types of feedback just to avoid the one type you do not want to give is annoying), on the other hand it is probably rare that one wants to not give a hint about this type of an error or that one would wish to adjust penalties differently for different types of errors, so as long as there is a separate test that does just this one can construct more customised logic from smaller tests in that case.

So at least a separate test for just this and maybe think about attaching this to the numeric/units tests, although exposing the options of this test in tests that already have options may be difficult. Although leaving the options to defaults will already provide sensible feedback...

**Comment by sangwinc** [comment]
Agreed Matti,
Let's add this as a separate answer test.

**Comment by sangwinc** [comment]
Answer test now in version 4.2 branch.
