### ISSUE TITLE
Add support for a "string" input.

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#315]
Can we have an input type which basically accepts anything and turns this automatically into a Maxima string?
This, of course, completely defeats the mathematical point of STACK, but there we are....  There will be uses for this in multi-part questions where we want a student to choose a method, or type in a word.

**Comment by aharjula** [comment]
We have had situations where we ask the student to explain their work and we have had to do that by adding a separate textual Moodle question under the STACK question. If we could simply include the input in the STACK question the explanation would be stored in the same question-attempt which would ease analysis especially in larger scale.

However we would need textareas for longer explanations. And typically those explanations would never reach the CAS as they are not part of PRTs anyway and PRTs do not send excess inputs to CAS. Although, it would be nice to somehow check if an input has been filled (requires that it is part of an PRT) without it having to be sent to CAS, I do not feel that it is an problem even if we need to send an essay answer through CAS.

For textarea input I would like to have an interactive length limit, to guide the student to keep it short.

As to actually using the string value for anything other than manual additional grading I am sceptical but in my stateful visions it may have uses... One thing coming to mind are algebra related questions where we have had to deal with variable name concatenations to do certain things, string values might actually help there even though I like concat more.

**Comment by sangwinc** [comment]
Matti,
The new "notes" input type (see https://github.com/maths/moodle-qtype_stack/tree/master/stack/input/notes) is exactly so that students can explain their work.  This is never passed to the CAS, it is just a survey input.  I think I already did what you wanted above!

I agree, I'm sceptical about the use.  I've added in one sample question, and we shall see what other people make of them...

**Comment by aharjula** [comment]
Chris,

Sorry had not notice the notes-input. Guess that solves that use case perfectly.

St to STRING input I don't realy see the point of this:
https://github.com/maths/moodle-qtype_stack/blob/9ac025a2f36210a5d7a42984a98445ab144a1e11/stack/input/string/string.class.php#L74-L75

If I were to write `".` to the string input field I would expect that on the Maxima side I would have a value of `"\"."` just like when I would write `abc` would lead to `"abc"` why should `"abc"` not produce `"\"abc\""`, Do we really need to cover the case where the student might write the quotes around the value? If we try to do that we lose the ability to input `"abc"`. And if we need to cover that special case you should probably cover it correctly, not assuming that if it starts with a quote it also ends with it.

Or are you using the sacrificial quotes to allow input of white-space? As the trim there blocks that possibility. If someone wants the student to input a string and then wants to act on that string we should probably give the choice of trimming or not to that someone and not do that automatically...

**Comment by sgparry** [comment]
I think there are valid mathematical uses for string type - for example, using the correct terminology for a feature on a graph, identifying a function or a series. Although these can be done with other question types, it makes clearer if you can include it in the question.

**Comment by sgparry** [comment]
I think there are valid mathematical uses for string type - for example, using the correct terminology for a feature on a graph, identifying a function or a series. Although these can be done with other question types, it makes clearer if you can include it in the question. Plus for my discipline, there's questions on cryptography that mix maths and text processing...
