### ISSUE TITLE
Error with student answer in the form a*10^b

### ISSUE THREAD

**Issue by dhilsen** [maths/moodle-qtype_stack#316]
For numerical answer tests, it has been noted that a student answer in the form `a*10^b` will produce the following validation error: "This answer is invalid. first: argument must be a non-atomic expression." This error occurs for those cases in which `a ` is a positive integer with no decimal. If `a` is a negative integer, or a number with a decimal, then the value is accepted.

For example, a student answer of `1*10^5` will produce the error. However, `-1*10^5` or `1.0*10^5` will be accepted. 

Students are encouraged to use the form `aEb` for answers involving scientific notation. However, the form  `a*10^b` may be more intuitive for some students, and perhaps should be considered as a perfectly valid form for inputting scientific notation.

**Comment by sangwinc** [comment]
My apologies David,
This is an error.  I have a proposed fix, just running the unit tests on it now to check nothing else breaks.
Chris

**Comment by sangwinc** [comment]
Fix now merged into master.
