### ISSUE TITLE
Regexp test broken

### ISSUE THREAD

**Issue by sgparry** [maths/moodle-qtype_stack#318]
The regexp test currently requires both teacher answer and options to be filled in (only one is necessary) and fails to pass either to this->atoption causing a TEST_FAILED every time.

**Comment by sangwinc** [comment]
Well this is a long-standing but and probably means nobody has used the regex answer test before!  I'm sorry about this. I've fixed the issue, but I need to use a machine I've got the STACK unit tests set up on before I merge this into master and release it.

**Comment by sgparry** [comment]
Thanks Chris,  that should help with some format specific questions.

On 5 November 2017 13:06:12 GMT+00:00, Chris Sangwin <notifications@github.com> wrote:
>Well this is a long-standing but and probably means nobody has used the
>regex answer test before!  I'm sorry about this. I've fixed the issue,
>but I need to use a machine I've got the STACK unit tests set up on
>before I merge this into master and release it.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/maths/moodle-qtype_stack/issues/318#issuecomment-341971815

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sangwinc** [comment]
Could I ask a favour please?

Would you please add some examples of the reg-ex patterns to a section in the docs:
https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/Answer_tests.md

and contribute some more test cases in this format
https://github.com/maths/moodle-qtype_stack/blob/master/tests/fixtures/answertestfixtures.class.php#L1429

I'm genuinely curious what you are using this for.  The basic principal is that STACK should check for mathematical properties, and if we need a dedicated answer test to let authors express some mathematical property, that would be better (in terms of a consistent design) than having authors write reg-exps.  If authors do need to write regular expressions then some relevant mathematical examples would be a great help to them.

Thanks for your interest in STACK.

**Comment by sgparry** [comment]
In Computer Science it is typically the case that binary answers are expected to be given to a specific number of binary digits, eg, "Convert the denary number 99 to 8 bits twos compliment binary". Often the leading zero indicates a positive number versus a negative. The format of the number is therefore as important as its raw numerical value. This is especially true of fixed or floating fractional parts (after the binary point) which in stack I have to handle as a separate field / input. The only way I have found of possibly dealing with these issues was using regexp on the input.
I will try and put together some examples but I am not 100% confident in the approaches I am using full stop...

On 6 November 2017 10:32:10 GMT+00:00, Chris Sangwin <notifications@github.com> wrote:
>Could I ask a favour please?
>
>Would you please add some examples of the reg-ex patterns to a section
>in the docs:
>https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/Answer_tests.md
>
>and contribute some more test cases in this format
>https://github.com/maths/moodle-qtype_stack/blob/master/tests/fixtures/answertestfixtures.class.php#L1429
>
>I'm genuinely curious what you are using this for.  The basic principal
>is that STACK should check for mathematical properties, and if we need
>a dedicated answer test to let authors express some mathematical
>property, that would be better (in terms of a consistent design) than
>having authors write reg-exps.  If authors do need to write regular
>expressions then some relevant mathematical examples would be a great
>help to them.
>
>Thanks for your interest in STACK.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/maths/moodle-qtype_stack/issues/318#issuecomment-342108568

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
