### ISSUE TITLE
CAS commands may not contain the following characters: \r.

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#321]
There are some characters that are not allowed in CAS commands (not including the strings inside those commands) and which may generate errors of form "CAS commands may not contain the following characters: a, b." that error however has a problem when the character is not  obviously visible e.g. `\n`, `\r`, and similar. With those we may simply get:

> CAS commands may not contain the following characters: 
> , 
> .

Which is inconvenient as those line changes are simply eliminated when displayed on HTML pages and the user has no idea what is the problem. Maybe we should handle those cases differently... maybe those `\n` like escape sequences would make sense to more technical people or maybe we need to write them open more verbosely:

> CAS commands may not contain the following characters: CARRIAGE RETURN, LINE FEED

> CAS commands may not contain the following characters: \r, \n

I personally have no opinion which would be better or should we have a special validation test to just handle line changes but what I am certain about is that the current error with list of invisible things is less than helpful as without access to the raw error logs I would not have found one mystically appeared `\r` from within CASText, especially as the error does not tell us too much on which part of the question it applies to.

**Comment by sangwinc** [comment]
Agreed Matti, thanks for raising this.  Could I suggest we have your "\r, \n" option which does not suffer from the need to translate the language strings?

Chris

**Comment by aharjula** [comment]
Chris, translation is a valid point. I'll try to build that version soonish.

**Comment by aharjula** [comment]
`\n\r\t\v\e\f` are now handled by rendering them as escape codes. Should cover this issue. However, found out that in WYSIWYG editors placing a line change in the middle of CASText embedded casstring also leads to "chained inequalities" which is even more bizarre an error, technically makes sense but for people not quite aware of the realities might be a bit of a mystery.
