### ISSUE TITLE
Math delimiters fix doesn't work for Quiz categories

### ISSUE THREAD

**Issue by Jarvil** [maths/moodle-qtype_stack#322]
Hello,

We cannot fix math delimiters on a course that has STACK-questions directly in/under Quiz categorybank. If they are in courses questionbank the fix works fine.

Stack version tested with; 4.0.1 (2017082400) & 3.5.7 (2017060600) & Moodle versions 3.1

When trying to fix delimites we get an error;

**Coding error detected, it must be fixed by a programmer: The course you passed to $PAGE->set_cm does not correspond to the $cm.**

`[:error] [pid 31117] [client 109.70.166.98:53474] Default exception handler: Koodivirhe havaittu, ohjelmoijan pit\xc3\xa4\xc3\xa4 korjata se: The course you passed to $PAGE-&gt;set_cm does not correspond to the $cm. 

Debug: \nError code: codingerror\n* line 1023 of /lib/pagelib.php: coding_exception thrown\n* 

line 4033 of /lib/navigationlib.php: call to moodle_page->set_cm()\n* 
line 3537 of /lib/navigationlib.php: call to settings_navigation->load_module_settings()\n* 
line 724 of /lib/pagelib.php: call to settings_navigation->initialise()\n* 
line 773 of /lib/pagelib.php: call to moodle_page->magic_get_settingsnav()\n* 
line 3145 of /lib/navigationlib.php: call to moodle_page->__get()\n* 
line 3189 of /lib/navigationlib.php: call to navbar->has_items()\n* 
line 55 of /theme/bootstrapbase/renderers/core_renderer.php: call to navbar->get_items()\n* 
line 42 of /theme/herald/layout/columns1.php: call to theme_bootstrapbase_core_renderer->navbar()\n* line 1028 of /lib/outputrenderers.php: call to include()\n* 
line 958 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()\n* 
line 1831 of /lib/setuplib.php: call to core_renderer->header()\n* 
line 56 of /question/type/stack/replacedollars.php: call to bootstrap_renderer->__call()\n, referer: https://xxxx/question/type/stack/replacedollarsindex.php

Images;

![stack111](https://user-images.githubusercontent.com/15193418/32266223-30b1723c-beef-11e7-8bb4-4b1c6a254dd0.png)

![stack2](https://user-images.githubusercontent.com/15193418/32266206-1e6e5a54-beef-11e7-843c-8e79abdf2129.PNG)

**Comment by Jarvil** [comment]
any idea @timhunt

**Comment by timhunt** [comment]
Not sure.

I imagine that this fix script was based on the replacedollars.php script that I wrote ages ago. Yes, it is the same script: https://github.com/maths/moodle-qtype_stack/blob/master/replacedollars.php. My memory is that worked for quiz contexts, but this is years ago, so I would not trust my recollection.

Please can you turn up Moodle's Debugging setting to DEVELOPER level, so we get a full stack trace?

**Comment by Jarvil** [comment]
Hello,

here is the error with Developer-level debuggin;

`Notice: Trying to get property of non-object in /var/www/moodle/31x/lib/navigationlib.php on line 1219

Debug info: 
Error code: codingerror
Stack trace:
line 1023 of /lib/pagelib.php: coding_exception thrown
line 4033 of /lib/navigationlib.php: call to moodle_page->set_cm()
line 3537 of /lib/navigationlib.php: call to settings_navigation->load_module_settings()
line 724 of /lib/pagelib.php: call to settings_navigation->initialise()
line 773 of /lib/pagelib.php: call to moodle_page->magic_get_settingsnav()
line 3145 of /lib/navigationlib.php: call to moodle_page->__get()
line 3189 of /lib/navigationlib.php: call to navbar->has_items()
line 55 of /theme/bootstrapbase/renderers/core_renderer.php: call to navbar->get_items()
line 4265 of /lib/outputrenderers.php: call to theme_bootstrapbase_core_renderer->navbar()
line 60 of /theme/clean/layout/columns1.php: call to core_renderer->full_header()
line 1028 of /lib/outputrenderers.php: call to include()
line 958 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line ? of unknownfile: call to core_renderer->header()
line 1831 of /lib/setuplib.php: call to call_user_func_array()
line 56 of /question/type/stack/replacedollars.php: call to bootstrap_renderer->__call()
line 56 of /question/type/stack/replacedollars.php: call to bootstrap_renderer->header()

`

**Comment by timhunt** [comment]
The strange thing is that this line: https://github.com/maths/moodle-qtype_stack/blob/master/replacedollars.php#L40 should have already set the right cm indirectly. 

Then, for some reason, this line: https://github.com/maths/moodle-qtype_stack/blob/master/replacedollars.php#L56 is interectly causing it to get set to something different. Will need some debugging to work out why, based on the stack trace, and I don't have time today.

**Comment by Jarvil** [comment]
Ok, thanks for the help.

**Comment by timhunt** [comment]
I finally got around to looking at this, and have done a pull request to add the same fix that was used in bulktest.php.
