### ISSUE TITLE
Create Maxima Image fails because of config caching.

### ISSUE THREAD

**Issue by sgparry** [maths/moodle-qtype_stack#327]
During the "Create Maxima Image" process, Stack changes between different Maxima configurations, first to remake the image, then to test the new image and, where needed, to revert to original settings.
This fails to work because the config is cached in the utils class.

**Comment by sgparry** [comment]
This is, I think, now fixed. Can someone please merge the pull request so that it can be closed? Thanks.

**Comment by sangwinc** [comment]
Thanks for pushing this.

Please let me apologize about the delay here.  I'm just back from Oxford.  Someone spilt coffee over my laptop on Monday, so I've been out of commission for a couple of days.  Things have backed up, and I'll certainly look at this over the next couple of days.

**Comment by sgparry** [comment]
Sorry to hear about the laptop. :-(
It's OK ; it gave me a chance to get the fix right. I only just realised something had screwed up some of the source line endings to CRLF (yuck).

**Comment by sangwinc** [comment]
Thank you very much indeed for this contribution.  Much appreciated.
