### ISSUE TITLE
Test fail with 1/2 power

### ISSUE THREAD

**Issue by dhilsen** [maths/moodle-qtype_stack#329]
We encountered an issue with the AlgEquiv answer test when dealing with expressions that involve square roots. 

As an example, if the TA is `(2*pi)/(k/m)^(1/2)` and the student answer is entered the exact same way the question will be marked as correct. However, if the student enters the equivalent expression `(2*pi)*(m/k)^(1/2)` then STACK returns a message of "Test Failed".

Of interest is the behavior of changing the TA to `2*pi/(k/m)^(1/3)`, a student answer entered the exact same way and `2*pi*(m/k)^(1/3)` are both marked as correct. There seems to be a pattern of odd number roots being handled correctly, with even number roots experiencing the issue.

**Comment by sangwinc** [comment]
Thank you for reporting this David.
