### ISSUE TITLE
Can you please add other languages to the STACK test server at https://stack2.maths.ed.ac.uk/demo/index.php 

### ISSUE THREAD

**Issue by germanvaleroelizondo** [maths/moodle-qtype_stack#336]
Hi,
I am the translator for the mexican Spanish language pack for Moodle.

Your qtype_stack plugin has been (completelly or partially) translated into several languages :)

I wonder if you could please add the following language packs for your demo STACK test server at https://stack2.maths.ed.ac.uk/demo/index.php 

Finland Swedish (sv_fi)
Finnish (fi) 
French (fr) 
Galego (gl) 
German (de) 
Japanese (ja) 
Romanian (ro) 
Spanish (International) (es) 
Spanish - Mexico (es_mx) 
Swedish (sv) 

So that we can check how the current translated strings perform in a real, properly installed and maintained server  with many stack-related activities and questions.

According to a post by Tim Hunt, installing many (20+) language packs has  [https://moodle.org/mod/forum/discuss.php?d=241098 almost 0 impact] on Moodle performance. 

Thanks in advance.

**Comment by sangwinc** [comment]
I'm very grateful indeed to all the colleagues who translate Moodle, and STACK, and create these language packs.  It is a very good idea to put them on the server and this is now completed.  I'd be very happy to host some demonstration quizzes in multiple languages as well...

Chris

**Comment by germanvaleroelizondo** [comment]
Thanks a lot Chris.

I will be posting when I have expanded/corrected the es_mx translations, so that you can make a language pack update (if it is not handled by cron) in your server.

I hope to expand the Spanish language documentation page at https://docs.moodle.org/all/es/Tipo_de_pregunta_STACK during the holidays.

**Comment by germanvaleroelizondo** [comment]
Hi Chris,

I have completed the es_mx translation of all plugin_stack language strings at AMOS one hour ago. 

Can you please do an upgrade of all installed languages (Site administration - Language - Language packs - Update all installed language packs) at your https://stack.maths.ed.ac.uk/demo server  ?

I think now would be a good time to ask a mathematician to have a look and check the mexican Spanish strings in action.

I will post in the mathematics forum of Moodle in order to find a Spanish-speaking mathematician.

**Comment by germanvaleroelizondo** [comment]
Hi Chris,

With the help of a Spanish maths teacher, I have updated the es_mx language strings for qtype_stack in AMOS. 

It would be very good if you can update all installed  language packs in your test server (if it is not automatically done by cron).

Thanks in advance.

**Comment by sangwinc** [comment]
We do run Cron, and this should have updated the language packs.
Thank you for your work on the translation!
Chris
