### ISSUE TITLE
But with the display of plots

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#340]
To reproduce, go to the CAS chat script, and enter

Question variables:
f:-(4*x^4-8*x^3+12*x^2-16*x)/40;
pf:plot(f,[x,-5,5],[y,-8,2],[xlabel,"x"],[ylabel,"y"],grid2d)     

CAS text:
\(f(x)\) is a polynomial function that has the following graph: @pf@

Send to the CAS, the look at the HTML source of the resulting page. Note that around the plot it looks like

`<div> … has the following graph: <div class="stack\_plot"><img src='https://learn2acct.open.ac.uk/question/type/stack/plot.php/stackplot-3725006832-57136044.png' alt='STACK auto-generated plot of ((-4*x^4)+8*x^3-12*x^2+16*x)/40 with parameters [[x,-5,5],[y,-8,2],[xlabel,"x"],[ylabel,"y"]]' /></div></html</div>`

Note the mangled close HTML tag.

This seems to be being caused by https://github.com/maths/moodle-qtype_stack/blob/4b082150ad85a1472d7158ec8bc58184ce936362/stack/cas/cassession.class.php#L474, which was added as part of commit 41dc6a8041c0ca9b8169f4d8b6b695d91f5e2e8d.

**Comment by sangwinc** [comment]
Thanks Tim.
