### ISSUE TITLE
Unsupported keyword: use_fast_arrays.

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#343]
Something to think about. Not that I would want this to be allowed although I do not have anything truly against it. Also this might be something that people might need to know about.

Basically, the situation is that newer versions of Maxima require that a variable has been initialised as a list/array before you can assign values to its indices.  This proved to be an issue when we found out that there is a significant amount of materials where the author had used the following types of code segments:
```
TAns[1]: ...;
TAns[2]: ...;
```
The situation is that that gives a CAS error on a newer Maxima and while the question is quickly fixable by simply writing:
```
TAns:[];
TAns[1]: ...;
TAns[2]: ...;
```
Generally, these could be written directly as `TAns1, TAns2...` as it is rare that one would actually use those as a list but as that needs to be checked in every case. That requires that we seek out all the questions to fix them individually. However, there exists a quick and dirty fix for allowing the old behaviour by setting `use_fast_arrays=false;`, which we could simply set in any question triggering this error by dumb prepending to the question variables. That would allow somewhat simple yet selective automatic fixing of old materials, but as that is an unsupported keyword...

Anyway, as this an issue with changing behaviour of Maxima and while we should always aim to make our code work with Maxima it might be nice to have some way of dealing with this change in this special case. That some way might be just allowing `use_fast_arrays`. However, I would prefer that we do not just set `use_fast_arrays=false;` globally as using uninitialised variables like that is bad and should be avoided everywhere.

**Comment by sangwinc** [comment]
Matti,
I think this is a prime candidate for the new "warnings" system we are working on which separates the validation of questions from the question editing system into a new method.  I'd like us to add a re-validation into the bulk-testing scripts so that as the software moves around us we will be able to spot problems before live questions are attempted by students.

**Comment by aharjula** [comment]
Chris,
Would be nice to validate, but requires a parser with type inference to identify when people assign values to unintialised variables like they were lists... So basically now we have to go for CAS errors to spot this.

**Comment by sangwinc** [comment]
Matti,
I can see no reason not to allow teachers to define `use_fast_arrays` on a per-question basis, but don't like the idea of fixing it on a site.
Thanks for tracking all this down.
