### ISSUE TITLE
Support for piecewise functions

### ISSUE THREAD

**Issue by georgekinnear** [maths/moodle-qtype_stack#348]
I would like for students to be able to enter a piecewise function as an answer. This would be useful in a number of contexts (I'm thinking particularly about introductory calculus).

Maxima does not support piecewise functions natively but there are a couple of packages available:

1. Pw.mac adds support for piecewise functions: https://sourceforge.net/projects/piecewisefunc/

2. abs_integrate enables Maxima to integrate certain piecewise functions, building on abs(x): http://maxima.sourceforge.net/docs/manual/de/maxima_31.html

Ultimately I think it would be good if students could enter piecewise functions using a "case"-like syntax (e.g. as in Maple: https://www.maplesoft.com/support/help/maple/view.aspx?path=piecewise)

I think something like this would be relatively easy to achieve if abs_integrate is turned on, as in this example:

```
load("abs_integrate.mac");
H(x):=(abs(x)/x+1)/2;
/* demo notation: [a,f1,f2] for f1 if x<a and f2 otherwise */
pw:[1,2*x,2*x-4];
fn:(1-H(x-pw[1]))*pw[2]+H(x-pw[1])*pw[3];
integrate(fn,x,0,1);
integrate(fn,x,0,2);
```

**Comment by sangwinc** [comment]
Thanks George,
We we discussed in person, I think this is an excellent idea.  The question is where does it sit in our list of priorities.

**Comment by sangwinc** [comment]
I've "plumbed" the pw.mac package into STACK and I'm rather impressed with the results.  The graphs plot really well, and the "simplification" and other manipulation routines seem to be very good.  I've pushed a branch and made some initial comments on what is needed as a first pass.

Anyone following this thread might also be interested in this paper on the subject: https://pdfs.semanticscholar.org/2197/c428e623320810d15077f5c1af1f9c48a35d.pdf

**Comment by sangwinc** [comment]
This issue is now part of #306.

**Comment by sangwinc** [comment]
For the record, here is some test data on times taken to repeatedly call the CAS using raw/optimised Maxima and with/without abs_integrate.  There is no significant change with the optimised image but is with raw.



** Without abs_integrate

Optimised:
Number of tests: 1375.
Tests took 267.47939 seconds.
Average per test: 0.19453 seconds.

(Raw)
Number of tests: 293.
Tests took 412.12978 seconds.
Average per test: 1.40659 seconds.

** With abs_integrate

Optimised:
Number of tests: 1375.
Tests took 269.46854 seconds.
Average per test: 0.19598 seconds.

(Raw)
Number of tests: 293.
Tests took 454.0286 seconds.
Average per test: 1.54959 seconds.
