### ISSUE TITLE
No re-evaluation of significant digits for trailing zeros

### ISSUE THREAD

**Issue by villehavu** [maths/moodle-qtype_stack#350]
There seems to be something odd in the way Stack deals with the case when the correct answer has a zero as the last significant digit. In the attached example if the student first gives an answer with too few significant digits (0.4 in the example) Stack reports correctly that the answer is incorrect and gives no credit. However if the student corrects his answer to have the right number of significant digits (0.40) the Stack reports that the answer is correct but doesn't give the credit. It looks like at some point 0.4 and 0.40 are interpreted being equal and the credit is never given while the answer is interpreted correct.

If there is another input in the question (with units in the example) the first input gets re-evaluated when the student fills in the second input. Also the problem doesn't concern inputs that require units (apparently 0.4*A and 0.40*A are not cached as equal?)

[Sigdig example-20180216-1435.xml.gz](https://github.com/maths/moodle-qtype_stack/files/1731309/Sigdig.example-20180216-1435.xml.gz)

**Comment by sangwinc** [comment]
Thank you very much indeed for reporting this, and my apologies.

The culprit is here:
https://github.com/maths/moodle-qtype_stack/blob/master/question.php#L187

and is caused because, in PHP, the _strings_ "0.4" and "0.40" are considered the same by the == operator.  I want to shriek....
