### ISSUE TITLE
Feature request: Automatic deployment should try a little bit harder

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#352]
If I understand correctly, automatic deployment fails immediately when a failed question test is encountered. This is not so practical, because deployment gives up immediately when a question with unsuitable random parameters appears.

I think deployments should give up only when it hits three failed tests, as it does with failures to generate new question notes.

**Comment by sangwinc** [comment]
As long as questions with failed tests don't actually get deployed, I'm open to suggestions here.  Would you like to implement these changes and send a pull request?

**Comment by alcarola** [comment]
I today noticed that my deployment problems are more due to [my still present problems with left-out last significant zeros](https://github.com/maths/moodle-qtype_stack/issues/351) than due to the deployment function giving up too easy. Hence, I will not propose any changes in the deployment function.
