### ISSUE TITLE
CAS connection

### ISSUE THREAD

**Issue by cyjack** [maths/moodle-qtype_stack#355]
I have installed moodle  and stack。However， when  prompted test cas at healthcheck .

It gives me wrong tips “stack_cas_connection:could not open CAS process”

There are maxima command configuration page, there is no explanation of how to configure it. Now I do not understand how to connect maxima,and has been installed maxima4.0.

**Comment by sangwinc** [comment]
I think we should correspond by email. I will help you fix this.  Please email me a little more information off Github to C.J.Sangwin@ed.ac.uk 
Chris
