### ISSUE TITLE
Feature request: Present penalties in a more sensitive way

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#356]
We practiced electronic exams in STACK in the course that I currently teach and a student mentioned that she finds it depressing to see the penalties eat her score while she's trying to focus on problem solving. Would it be difficult to add an option to show the calculation of the final score only after the test has been handed in?

(I don't think that I can implement the present request myself with a reasonable effort, but I will try to have a look at the deployment suggestion as you suggest.)

**EDIT:** Quiz is the correct English term, not test.

**Comment by aharjula** [comment]
Turning Marks of in the review options of the quiz does not work? What question behaviour are you using?

**Comment by sangwinc** [comment]
Thanks,
I agree we should be sensitive.  In this case I think this should be a quiz level option.  I do turn off marks during the exam.
Chris

**Comment by alcarola** [comment]
Ah, OK. I saw that you can turn off marking during the exam, but then when the quiz is handed in, I do not see the complete answer history, but only the last answer. Anyway this is probably a Moodle issue and not a STACK issue, or where is the quiz review view defined?

**Comment by sangwinc** [comment]
Have a look in
..../Course / ► Section / ► Quiz / ► Edit settings
then under "Review Options".

**Comment by timhunt** [comment]
I don't understand why this was closed.

In question/type/stack/renderer.php, in the prt_feedback_display method, I think it should check `$options->marks >= question_display_options::MARK_AND_MAX` before it adds anything to `$gradingdetails`.

https://github.com/maths/moodle-qtype_stack/blob/b820762afa778bb544e6ed97f6d79f551dd6180e/renderer.php#L349. Note the comment there ;-)

I think it is just a matter of adding that clause to the if statement (and then updating any necessary tests).

Should this be re-openend?

**Comment by sangwinc** [comment]
Tim, 
Is this what you had in mind?  There are plenty of bits of the Moodle quiz where I need your expertise!

**Comment by timhunt** [comment]
Oops! I commented in the commit, not here. Let me repeat:

That looks right to me. Would be nice to add a unit test (in question/type/stack/tests/walkthrough_adaptive_test.php). Should be possible to to change $this->displayoptions mid test, re-call $this->render(); the check the the presence or absence of the mark details. Probably sufficient to add that to just one testcase.
