### ISSUE TITLE
Choice where to put a checkbox-input

### ISSUE THREAD

**Issue by C0untC0unt** [maths/moodle-qtype_stack#359]
We developed some questions using single checkboxes as an addition to the actual input. (see below)

![aufgabe 6 3v1](https://user-images.githubusercontent.com/13086010/37386602-755c72e2-2759-11e8-9be9-81cfb1a573cd.png)

In some of these cases, we thought that it will look more clearly if the checkbox follows the input in the same line. But using the input-type "Checkbox" always causes a new paragraph. This does not necessarily happen in cases of other input-types, like dropdowns.

![aufgabe 6 3v1_2](https://user-images.githubusercontent.com/13086010/37387330-45977342-275c-11e8-9a0f-e211797c21e3.png)

Having the choice of where to put a checkbox (same line or next line) would be interesting.

**Comment by sangwinc** [comment]
This is an interesting suggestion.

I've played around with this today.  The problem with a single option for a checkbox is the following.  How do you distinguish an "empty" response from a "I know not to check this box"?  Currently STACK has an option for an "empty response" which is coded internally as BLANK and is different from a VALID response.  So, if you leave the single box empty you never get past BLANK, and the prt which depends on this won't get to score (ever!).  So, if empty is the right answer there is no way to award the marks.....

Actually, the Moodle core MCQ (with checkboxes for multiple answers) requires students to check at least one!  I agree students should actively choose what they do want.

I think in your example we should have two choices, with a radio button.  "The limit does not exist" and "The limit exists".  In this case, you'll probably want the new lines between choices!

If you really want checkboxes without formatting we can certainly add in an option to do this, but it will look odd with checkboxes along a line.

**Comment by timhunt** [comment]
Chris, what you say about a combined input makes sense. Ideally, if you tick the "Does not exist" box, then the text input box should become disabled. Still, this needs to be passed back to STACK in some way.

**Comment by sangwinc** [comment]
This is related to issue #304, and I put a start at solving this in the branch iss304.

**Comment by sangwinc** [comment]
This issue will be solved in the "input2" proposals, so I'm closing it here.
