### ISSUE TITLE
Plot error: plot_size must be a list of two positive integers

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#361]
I am getting this error on the healthceck page (where it tries ot show the sample plots). The third example plot works:

CASText failed validation. The CAS returned the following error(s):plot([x^4/(1+x^4),diff(x^4/(1+x^4),x)],[x,-3,3]) caused the following error: Plot error: plot_size must be a list of two positive integers. plot([sin(x),x,x^2,x^3],[x,-3,3],[y,-3,3],grid2d) caused the following error: Plot error: plot_size must be a list of two positive integers.

This is with Maxima: %build_info("5.38.1","2016-09-06 15:07:07","x86_64-redhat-linux-gnu","SBCL","1.0.38-3.el6")

Has anyone else seen that?

(Note, I am also getting similar errors from some of my questions.)

**Comment by aharjula** [comment]
Check you maximalocal.mac it is missing that parameter.

**Comment by timhunt** [comment]
Thank you! I think you have just saved me from about a million years of debugging :-)
