### ISSUE TITLE
Fix question tests & editing for questions with neither PRTs nor inputs

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#363]
STACK has long has the feature to have 'questions' like Moodle's descriptions, which neither inputs nor PRTs. however, this is not much used, and seems to have got a bit broken recently.

I ahve jus fixed all the problems I found with a question like that, and this issue is to hendle submitting the changes for review.

**Comment by timhunt** [comment]
My branch also inclues a small unrelated coommt to change questiontestrun so the question tests are run after the session is unlocked. I hope that is OK.

**Comment by sangwinc** [comment]
Just for the record, this is a useful addition beyond Moodle's descriptions because we can use it to create randomly generated mathematics.  That is, we can have random versions of questions without any interactions.

**Comment by aharjula** [comment]
I am pretty sure that we have also used that feature. Having access to CAS makes even non random content generation much simpler. CAS->LaTeX processing is obviously another reason why this is superior to 'descriptions'... So lets try to keep it alive and functioning.

**Comment by timhunt** [comment]
Well, what I think is the necessary fix is sitting there as a waiting for someone to merge it in ;-)
