### ISSUE TITLE
significantfigures() (sigfigsfun) should throw an error if the value does not evaluate to a raw number

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#369]
`t:significantfigures(%pi/blaah,3);`

Assuming `blaah` is unknown that previous statement returns nothing, which is a problem in some cases. As for STACK that will essentially stop processing of evaluated values and the error generated might not be obvious to the user.

Maybe that function could throw an error of some kind if it reaches the end of the function without returning a value.

Not a major issue but caused an interesting debug session when a typo in an expression was not noticed and the error was assumed to exist on the more complex next line.

**Comment by sangwinc** [comment]
Ok Matti,

This is a bug.  In the sandbox
`t:significantfigures(%pi/blaah,3);
does return a value, but it is nonsense and takes ages.  This function should throw an error.
