### ISSUE TITLE
Require lowest terms problem

### ISSUE THREAD

**Issue by jcopado** [maths/moodle-qtype_stack#370]
Hi!

I got this question from one of our users, asking why despite Require lowest terms is checked, the validation accepts a solution which is not in lowest terms. I don't really know if it is a bug or the intended behaviour.

Are lowest terms checked during validation?

(This question has no points given in the PRT, but add points to the node doesn't change the problem)
[stack_question_6489.zip](https://github.com/maths/moodle-qtype_stack/files/1919848/stack_question_6489.zip)

**Comment by sangwinc** [comment]
The docs currently say that (https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/Inputs.md) 

> "When this option is set to yes, any coefficients or other rational numbers in an expression, must be written in lowest terms."

So, I intended this functionality to look for things like 2/4, not really thinks like x^9/x^7 which is what I guess will happen in your question?  We could expand the functionality if people really want to but I don't consider this to be a bug.

**Comment by timhunt** [comment]
Presumably there is a way to achieve the desired result with suitable use of Maxima code and Answer tests, so perhpas just document that somewhere.

**Comment by sangwinc** [comment]
Again, this test case indicates the intention of the test:
https://github.com/maths/moodle-qtype_stack/blob/master/tests/fixtures/answertestfixtures.class.php#L1502
x^2/x returns "1" meaning this passes the test.

At this point there is no way to reject x^9/x^7 as invalid, rather than wrong.  Sorry!

**Comment by timhunt** [comment]
Oh! sorry, it is a validity, rather than correctness, thing. I was not paying attention.

**Comment by sangwinc** [comment]
Tim,
Yes, you can do this in the potential response tree with "lowesttermsp" (as mentioned in the test suite), but you can't (currently) do this as part of validation.
Chris

**Comment by sangwinc** [comment]
I'm closing this as it is not really a bug. It was added to the feature request page.
