### ISSUE TITLE
Stack mcq evaluation of the answer

### ISSUE THREAD

**Issue by yusuf20188** [maths/moodle-qtype_stack#377]
hi,
I have created a multiple choice stack question. it has 2 true and 2 false answers. when i choose one of the correct answers i get zero points, but actually i sould have had 0,5 point. Is there a solution to change the evaluation of the mcq question or the students have to choose every correct answers?
best regards
Yusuf Emin Cansiz
thank you in advance

**Comment by sangwinc** [comment]
Please export the single question and email it to me at C.J.Sangwin@ed.ac.uk.
I'll look at it for you.

**Comment by sangwinc** [comment]
Yes, this is very easy to do by using the potential response tree to check for each of the options in the student's answer.   Rename the attached as a ".xml" and the import it.

[questions-Scratch-MCQ Test-20180606-1720.txt](https://github.com/maths/moodle-qtype_stack/files/2077179/questions-Scratch-MCQ.Test-20180606-1720.txt)

By the way, you emailed me 57 questions!  You can export a single question from the question test page.  Very useful.
