### ISSUE TITLE
Support for Moodle 3.5

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#378]
I'm currently testing STACK on Moodle 3.5

These changes seem to cause a problem:
https://github.com/moodle/moodle/commit/e7329cd026e5a3ce89ef8360ab861bc9b660390f#diff-a22f7fcc9a0c5e983df0ac8d96aaf5e7L1636

The check in line 1636 is also needed for unit testing. In particular, the lack of this return now breaks the qtype_stack https://github.com/maths/moodle-qtype_stack/blob/master/tests/editform_test.php

Reinstating the is clause following 1636 restores the previous behaviour of the unit tests!

Any suggestions on what to do here?

**Comment by sangwinc** [comment]
The refactoring of the validation into the questiontype has reduced the extend of this problem. Indeed, this seems sensible since a lot of these tests are about validation and not a proper moodle question. So, with this https://github.com/maths/moodle-qtype_stack/commit/102330ebd20152bb57a423b2d9b8ed215c785457
we have only two remaining failing unit tests.  But, they are both the same cause.

**Comment by timhunt** [comment]
I'll try to take a look at this.

**Comment by timhunt** [comment]
I think that the changes on the iss378 branch are what we need to fix this.

**Comment by sangwinc** [comment]
Thanks Tim
