### ISSUE TITLE
Addresses inside GitHub doc links are for Moodle Docs 2.2 versions

### ISSUE THREAD

**Issue by germanvaleroelizondo** [maths/moodle-qtype_stack#387]
Hi Chris and Tim,

While translating, I noticed that several files have links to very old Moodle Docs versions (Moodle 2.2).

For example,  moodle-qtype_stack/doc/en/Authoring/Quiz.md
 file at line 30:

Levels of [feedback](Feedback.md) are controlled by the [quiz settings](http://docs.moodle.org/22/en/Quiz_settings), and in particular the [question behaviours](http://docs.moodle.org/22/en/Question_behaviours).

Would it be possible/desirable for you to search for all references to http://docs.moodle.org/22 and replace them all by http://docs.moodle.org/35  in all of the English documentation. 

I do not know enough GitHub to do this.

Thanks in advance.

**Comment by sangwinc** [comment]
Very good idea. Thank you for pointing this out.  I've changed the links here: https://github.com/maths/moodle-qtype_stack/commit/b5f46dd702aa441cc24443b9469cbedfe8db8efa

**Comment by timhunt** [comment]
Just to note that you can actually leave the version number out completely (e.g. http://docs.moodle.org/en/Multi-language_content_filter) and it will then auto-redirect to the latest current version.

**Comment by sangwinc** [comment]
Ok Tim,
I didn't know that.  See here: https://github.com/maths/moodle-qtype_stack/commit/0cb48279ff728315dda7c2888ffe31b32a7dab39
