### ISSUE TITLE
MAXIMA commands shown verbatim in questions.

### ISSUE THREAD

**Issue by ianjones** [maths/moodle-qtype_stack#391]
I'm finding some MAXIMA commands (e.g. matrix, list) are being shown verbatim in questions, as in the attached.  This has started since my university updated Moodle to version 3.4, and is also the case on the STACK demo server (stack2.maths.ed.ac.uk).

Ian

![matrix](https://user-images.githubusercontent.com/651129/43317914-b77c81e2-9196-11e8-9e69-a80d0b2302db.jpeg)

**Comment by sangwinc** [comment]
Thanks.  Yes, I already fixed that question in the latest version of the sample materials.   Can you confirm which course you are in please and I'll sort it out on the server.

**Comment by ianjones** [comment]
Great, thanks Matt. I've sent that link to the administrator at my institution.

Demo server course is IK Scratch.

**Comment by sangwinc** [comment]
Ok, I've auto-updated the question in your scratch course.
