### ISSUE TITLE
Localisation and MCQ labels

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#392]
Localisation of questions has become quite easy during the recent upgrades to STACK, but there is one place where [the currently preferred way of handling localisation](https://docs.moodle.org/en/Multi-language_content_filter) does not work. The labels of options in MCQ inputs where we can output strings generated at CAS level.

We should naturally generate strings in the form `<span class="multilang"...>Yes</span><span ... lang="fi">Kyllä</span>` and get them outputted as the labels and hope that the multilang filter can catch them at the place where they come out and that all the authors remember to not push inputs or other things outputting such things inside other multilang blocks. But there is a technical problem stopping us from doing that...

 1. The multilang filter [requires](https://github.com/moodle/moodle/blob/master/filter/multilang/filter.php#L57) that the span-element uses `"`-quotes for its arguments and placing those into Maxima strings requires escaping. If `'`-quotes were an option this would not be an issue.
 2. The implementation of MCQ label handling however does not make that easy as It pushes the strings through many processing steps and seems to lose some escapes between those steps causing things to crash. I do believe this issue has been causing trouble also with custom LaTeX labels.

Problem is that while the logic knows how to [unescape](https://github.com/maths/moodle-qtype_stack/blob/version4.2/stack/input/dropdown/dropdown.class.php#L135) things it does not remember to [escape](https://github.com/maths/moodle-qtype_stack/blob/version4.2/stack/input/dropdown/dropdown.class.php#L239) if it sends things back to Maxima. To see this problem in action just push this into your MCQ input:

`
[[1,true,"<span class=\"multilang\" lang=\"en\">Yes</span><span class=\"multilang\" lang=\"fi\">Kyllä</span>"],[2,false,"<span class=\"multilang\" lang=\"en\">No</span><span class=\"multilang\" lang=\"fi\">Ei</span>"]]`

Naturally, that example is not a real example as we already have localised boolean inputs available from the system itself, so feel free to consider more complex strings as labels.

That escaping issues might be nice to solve for other uses also...

At some point there has been conversation of providing the selected locale as an parameter into the CAS so that one could directly output just the correct languages strings. That however would be a spectacularly bad idea as it would make it possible for the grading logic to depend on the currently selected language and if the student were to change their locale between inputs all sorts of trouble could arise. While it might make something possible for some authors it would be a minefield for many others and as long as we cannot identify those mines we cannot allow them to come into play.

**Comment by aharjula** [comment]
#203 was the last time this came up and the solution then handled the unescape bit but forgot to apply the new `php_string_to_maxima_string` function when pushing the strings back to Maxima.

**Comment by aharjula** [comment]
@sangwinc I am thinking of allowing writing those MCQ-labels in CASText(2). Basically, instead of writing `[[1,true."label \\(..."]...]` one could write `[[1,true.castext("label {@foo@}")]...]` and let the compiler do the value injections. Basically, would work as before but if the TA-of the input has a CASText2 list structure as the label the system would know what to do to display it.

Problem is that this would still not fix the localisation issue, i.e. pushing multilang tags through all that escaping is fine and all but you still have trouble if you end up with nested language contexts when placing an input with language blocks inside a lang block.

What I am thinking is that I would simply take over the language system and add a block that could deal with nesting, and would either do the selection itself or convert back to multilang or whatever if need be (I see no need but who knows). Could do the selection at CAS level but I think returning all lang-variants from there and caching them as a single thing is probably better. So `[[i18n lang="en"]]...[[(i18n]]` with lang as a parameter to match the syntax of other blocks and to allow the addition of more parameters. `[[lang lang="foo"]]` just would seem odd...

Opinions?

**Comment by sangwinc** [comment]
This is related to issue #1051.
