### ISSUE TITLE
Update to Release 4.2.1 fails on dependency requirements

### ISSUE THREAD

**Issue by spinozarabel** [maths/moodle-qtype_stack#395]
<img width="864" alt="sketch" src="https://user-images.githubusercontent.com/16438408/43814385-bac963b0-9ae7-11e8-89a5-2e937fb32f0a.png">
When I try to upgrade to latest Stack plugin version on Moodle 3.5.1+ I get the error as shown in the attached file: Basically it fails for some dependencies that I am not aware of. The plugin worked fine prior to update.

**Comment by aharjula** [comment]
Chris,

Could it be that this is an issue for users of the Moodle plugins directory? It seems like those behaviours are not there while 4.2.1 is. I have no idea how that directory works as I always put my files into their correct places myself but maybe it provides a simpler way that is now unable to fulfill the requirements?

**Comment by sangwinc** [comment]
Indeed Matti, 
I've released new official versions of these three plugins through the directory.
I didn't appreciate how crucial the directory is, as I always update myself from the command line....
Chris
