### ISSUE TITLE
Localisation of nounor and nounand commands

### ISSUE THREAD

**Issue by lassikor** [maths/moodle-qtype_stack#396]
Students are often confused with symbols for logical or/and. Therefore, the commands nounor and nounand are very useful, for example in MCQ:s, but they are available only in English. Would it be possible to get these commands also in other languages or is there some way to get around this problem.

**Comment by sangwinc** [comment]
Sorry, that should have been done before.

**Comment by lassikor** [comment]
Wow, that was fast 🙂
