### ISSUE TITLE
Selective simplification in MCQ:s

### ISSUE THREAD

**Issue by lassikor** [maths/moodle-qtype_stack#397]
We are trying to make MCQ question including a choice abs(x-5)=abs(5-x). However, this is always simplified to abs(5-x) = abs(5-x), even if the variable simp is set false. Is there some way to turn the simplifaction off within MCQ choices?

**Comment by sangwinc** [comment]
Ok, this is now fixed.

**Comment by lassikor** [comment]
Thanks  :)
