### ISSUE TITLE
Kelvin in casstring.units.class.php

### ISSUE THREAD

**Issue by nwalet** [maths/moodle-qtype_stack#399]
in casstring.units.class.php: the SI unit Kelvin definitely is used with a prefix! Needs moving to $supportedunits from $nonpreficunits.
Niels

**Comment by sangwinc** [comment]
Sorry about that Niels,
Is the above what you needed?

**Comment by nwalet** [comment]
Yes!
Niels

________________________________
Prof. Niels R. Walet                             Phone:  +44(0)1613063693
School of Physics and Astronomy         Mobile: +44(0)7516622121
The University of Manchester                Room 7.7, Schuster Building
Manchester, M13 9PL,  UK
email: Niels.Walet@manchester.ac.uk   twitter: @nwalet
________________________________

**Comment by sangwinc** [comment]
Ok, I've merged this into master.
