### ISSUE TITLE
Notes textarea size it not properly calculated

### ISSUE THREAD

**Issue by jcopado** [maths/moodle-qtype_stack#402]
![notes3](https://user-images.githubusercontent.com/7701512/44400887-25338b80-a54d-11e8-8132-9f3d25523ed6.PNG)

As you can see, size of notes input doesn't adapt well to the page when user input is a long text. I think the problem is in

notes.class.php line 52
foreach ($rows as $row) {
            $boxwidth = max($boxwidth, strlen($row) + 5);
        }
taking the max lenght, without any cap will make textarea big in those cases.

**Comment by sangwinc** [comment]
Yes, that isn't optimal at all.   Do you have a specific suggestion of how you would like this to look?  E.g. setting a maximum length?

**Comment by jcopado** [comment]
Yes, I would set the maximum length to 100, that would be OK for most of the browsers, but for sure not for mobile phones.

**Comment by timhunt** [comment]
Probably, whatever size is specified in the HTML, the CSS should also specify max-width: 100% (or something like that - it may already) so there should not be a problem on smaller screens.

**Comment by sangwinc** [comment]
Ok, is this what you have in mind?  Seems to fix the problem for me.

Do we need this kind of thing anywhere else, e.g. validation feedback divs?

Chris

**Comment by timhunt** [comment]
Yes, but perhaps also add

```
.que.stack input[type=text] {
    max-width: 100%;
}
```

**Comment by sangwinc** [comment]
Ok Tim,
https://github.com/maths/moodle-qtype_stack/commit/f5ef83d326d22d36d035f7af21e15a874dc534db
I'll leave 24 hours or so for further comments.
Chris

**Comment by timhunt** [comment]
Yes. That should do it.
