### ISSUE TITLE
Function that forces answers and random values to be shown in scientific notation

### ISSUE THREAD

**Issue by jmbragg** [maths/moodle-qtype_stack#403]
I've managed to do a work around for the text of this question where the first part of the scientific notation is a variable and the power of 10 is a variable.  However, it would be really nice to have a function that could force the display of a number into scientific notation.  Mostly for the answers... Because those are spectacularly unhelpful for students as they try to spot errors when they're off by a power of 10 or two.
![need sci not display](https://user-images.githubusercontent.com/4606870/45005618-681c4700-afc2-11e8-99e2-b35093f1d124.PNG)

**Comment by sangwinc** [comment]
I think we can already do this.  If you have question variables
```
ta1:stackunits(8.08e-10,m)
ta2:stackunits(3.71e17,Hz)

```
then you get this:
![units1](https://user-images.githubusercontent.com/781615/45253788-10d0fa80-b365-11e8-85b1-dd878e0f443a.png)

Documentation is here: https://stack2.maths.ed.ac.uk/demo/question/type/stack/doc/doc.php/CAS/Numbers.md

Can you confirm this is working and close the issue? If you need other options, or have problems, just let me know.

**Comment by sangwinc** [comment]
Another option is the following:
```
ta1:stackunits(displaysci(8.08,4,-10),m)
ta2:stackunits(displaysci(3.71,4,17),Hz)
```
![units2](https://user-images.githubusercontent.com/781615/45253878-d4ea6500-b365-11e8-95dd-3514afa862a8.png)

**Comment by jmbragg** [comment]
Bah... Chalk this one up to funky display when searching inside github that I hadn't noticed yet.  I got linked to the Numbers docs page but didn't notice that it wasn't showing all the results on that page, just the "top results".   Sorry for the bother.
