### ISSUE TITLE
Answer Test: NumDecPlaces

### ISSUE THREAD

**Issue by yusuf20188** [maths/moodle-qtype_stack#417]
Is it possible to apply Answertest NumDecPlaces in an input [x=..., x=....]? or the answers should be given as fractial numbers?

**Comment by sangwinc** [comment]
There is no automated way to do this I'm afraid.

In some cases where the whole answer test is in Maxima this would be possible, by writing a small amount of code to apply the answer test to the RHS of each element of the list.  In the case of the NumDecPlaces this test is a mix of PHP and Maxima (see, e.g. https://github.com/maths/moodle-qtype_stack/blob/master/stack/answertest/atdecplaces.class.php#L60) so we have no easy solution.  Sorry!
