### ISSUE TITLE
"sigfigsfun(x,n,d) requires a real number as a first argument" depends on units?

### ISSUE THREAD

**Issue by jmbragg** [maths/moodle-qtype_stack#427]
I've attached the problematic question.  Go to deployed variant 691456901.

A student entered this wrong answer.  It should be marked wrong because the units are incorrect.  I wouldn't think it would throw that error message.
![image](https://user-images.githubusercontent.com/4606870/49773467-42889300-fcbf-11e8-84c4-deb79213ec44.png)

[questions-APChem-Rate Constant-20181210-2051.zip](https://github.com/maths/moodle-qtype_stack/files/2665643/questions-APChem-Rate.Constant-20181210-2051.zip)

**Comment by sangwinc** [comment]
Ok, I'll take a look. But this week I have 600 exam papers to mark!  You'd have thought someone might have written software to do this by now....

**Comment by sangwinc** [comment]
Just looking at your question, your variables have

oblist:[0,1,2]
obwordlist:["zeroth","first","second"]

Actually, you don't need the word list!

Try {@(stackintfmt:"~:r",0)@} and {@(stackintfmt:"~r",0)@}.

Anyway, this isn't the issue here!

**Comment by sangwinc** [comment]
To fix your question, change the TA in the answer test to "k*kunits" (i.e. remove the stackunits).

This will avoid the problem, but there is a bug here which I will fix....

**Comment by sangwinc** [comment]
Ok, I think I have a fix to this. I'll push changes once I'm back next week and confirmed all the unit tests run.

Thank you very much for reporting the problem.
