### ISSUE TITLE
Make inputs optional: add in null values for the teacher's answer.

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#431]
A colleague asked me to author the question at the end of this issue.

The problem is that the correct teacher's answer for some parts of this is "not answered", e.g. the part "W is not a subspace because it does not contain the origin." should not be answered if W is a subspace.

So, we need to add in "null" values for the teacher's answer, which give "not answered" when we will in the correct answer.

:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
Question: Is the following subset a subspace of 𝑉? The straight line W through the origin and (−1,3,2).

Instructions: Pick one answer and fill in the corresponding blank. Note that
1)  If W is not a subspace, more than one option "W is not a subspace because ..." may be correct. You only need to pick *one* that is correct.
2) If you pick one of the fill-in-a-blank options, there may be more than one correct way of doing so. You only need to write *one* that is correct.

Answers:
[ ] W is a subspace, it is the subspace {\lambda(_,_,_)^T: \lambda \in R}
[ ] W is not a subspace because it does not contain the origin.
[ ] W is not a subspace because it is not closed under addition. For example, (_,_,_) and (_,_,_) are in W but their sum (_,_,_) is not.
[ ] W is not a subspace because it is not closed under scalar multiplication. For example, (_,_,_) is in W and _ is a scalar but the scalar multiple (_,_,_) is not in W.

**Comment by sangwinc** [comment]
So, I've made progress on this issue but not completely solved the problems.

In particular, for this question we are going to need some PRTs which don't fire.  This makes it impossible to get full marks on the question! (Unless PRTs have a value of 0....)

Will have to think about this.

**Comment by timhunt** [comment]
Just to clarify, is this using the 'checkbox' input type?

Surely the way to model what is going on here is that all four checkboxes are a single input, and the value of the input is the set of selected options.

I have not used checkbox inputs before, but from reading the code and docs, that seems to be how it works. So, what is the problem?

**Comment by sangwinc** [comment]
Tim,
The checkboxes are not really the issue here. It is the bits "For example, (,,) and (,,) are in W but their sum (,,) is not.".  If you do not choose that checkbox value, then these inputs will remain blank.

George and I talked at length about this question today.  More to follow.

**Comment by sangwinc** [comment]
Here is the question, and a proposal for a new block.

Over the last couple of months, George, Konstantina and I have needed this kind of functionality on a number of occasions.  It would have been very useful for a wide variety of questions.  The colleagues at the STACK conference in Germany persuaded me that empty inputs should be permitted, and I think this is a compelling use-case.

We will collect more use-cases.

**Comment by sangwinc** [comment]
This question can now be authored with the "allowempty" options in input.
