### ISSUE TITLE
Upgrade YUI javascript to AMD

### ISSUE THREAD

**Issue by Beedell** [maths/moodle-qtype_stack#436]
This is not so much an issue as a small improvement request - upgrade JavaScript from YUI to AMD. 

YUI is no longer supported so upgrading to AMD is recommended. There is only one file (input.js), but this calls an AJAX end point that is no longer recommended. So a new (replacement) Moodle webservice is to be included that can be used both by the website and by mobile platforms (qtype_stack_validate_input).

This upgrade should have no effect on functionality, and all current passing phpunit and behat tests should pass (we have a couple of known failures on our system at the OU unfortunately). However with the new webservice we have the first step in hopefully making this plugin work on the mobile platform.

I have pushed suitable code to my github fork (https://github.com/Beedell/moodle-qtype_stack) as branch wip-upgradejs-master. The compare url is: https://github.com/maths/moodle-qtype_stack/compare/master...Beedell:wip-upgradejs-master. I have not clicked on the pull request as I am not sure whether you use that system.

I hope you like this code upgrade.

**Comment by sangwinc** [comment]
Thank you that is great.

This has been on my list for a while.  And I'm trying to roll this in with a couple of other Javascript changes.

I really appreciate this contribution.  I'll be in touch.

Chris

**Comment by sangwinc** [comment]
(PS is that an Advance Alpha 2 in your avatar ?!)

**Comment by Beedell** [comment]
That is very observant of you! (Well its actually a very old Alpha 3.) Still got it, though I don't know why. Is there any good flying near you?

I have just posted a second commit to my github branch. This contains a fix that Tim asked me to submit to you to make the 'Check' button disappear properly for browsers that are javascript enabled. The fix is a line of css and removing the 'hide the button' process in the input.js script. The issue with the 'hide the button' javascript is that on slow systems the button would appear long enough for users to notice and then disappear. Just a bit irritating really, but an easy fix.

**Comment by Beedell** [comment]
Whoops, clicked on the wrong button - I seem to have closed the issue, so reopening. Sorry.

**Comment by sangwinc** [comment]
Sorry about the delay in resolving this. I'm really keen this work does not get lost....

I've been using this today, and noticed one issue that even invalid responses can have valid LaTeX, so we need to trigger the filters.  I hope this is the correct way to do this
https://github.com/maths/moodle-qtype_stack/commit/ba88fb6cf34688dd9cae7fa6b239541b4382910e

**Comment by timhunt** [comment]
That looks right.

**Comment by sangwinc** [comment]
Ok, can I close the issue and merge back into master?

**Comment by timhunt** [comment]
I think so.
