### ISSUE TITLE
Correct misleading unicode characters

### ISSUE THREAD

**Issue by oneuh** [maths/moodle-qtype_stack#438]
Recently we had a problem with a student's answer not being accepted because it had a '–' in it. Upon further investigation it turns out it was an en-dash (U+2013) instead of the expected '-' (U+002D). He was frustrated and missed a few answers because of this. Our guess is it happened because he was working on his iPad and the "Intelligent Punctuation" feature might have wrongly corrected it.

So my feature request is to check users inputs for unicode characters that look similar to ones that are often used (e.g. +,-,*,/) and replace them with the intended ones before passing the string on to the CAS.

As more and more students start filling out tests on mobile devices, this might be more of a concern than previously because many of those devices offer typographical correction features

**Comment by aharjula** [comment]
This is again on of those things that might be handled in the work relating to #324 as we again need some amount of context to do these. I would however want to point out some other related things.

```
listofvars(x–y+z);

incorrect syntax: – is not an infix operator
listofvars(x–

listofvars(xπz+δy);
                              [xπz, δy]
```
Not all Unicode chars are bad, and some are even valid in variable names in Maxima but not currently in STACK. We also need to note that that em-dash could just as fine be within a string-value and needs to be protected there.

Related to this we should consider the following things:
- Is it Ok to fix errors that the user does not know their machines do? Or should we let them know that those machines do those things and their should deal with it. Is it sensible for us to fix random things some filtering process does between us and the user or should we let the user know that they have a problem there that might affect other things as well.
- Probably better would be to hint those machines to not do any "intelligent" things on the input values, surely that should be possible.
- If we replace those obvious operator cases i.e. `+,-,*,/` where do we draw the line for similarity just for minus I found these dashes `﹘,‒,–,—,⸺,⸻`, I feel like I would not accept the two longest ones there no matter what but someone might meet some combination of tools that leads to those. Note that there are also hyphens that look the same. There are also plenty of crosses for the plus sing and various systems generate multiplication dots and there are slashes of various types as well.
- For the multiplication sign case we really need to consider whether we want to support copy paste from other tools as many tools use different symbols for that and I would not be surprised if they intentionally use different presentations to stop direct copy paste working.
- We must not forget `^` as it too has variants and Apple provided features that play with it.
- Finally, there is the issue of `π` as a single character variable name. Do we also start to fix that i.e. `π => pi => %pi` or are we requiring the use of our defined names for specific constants? If we open this door where does it end, do we then start to require that students understand that they can write what they see or can use ASCII aliases i.e. learn to write things using Unicode and learning code-points and how to input them if they do not have character pallets to pick them from as they will never notice the list of aliases? Or could we hope that the [Space-cadet keyboard](https://en.wikipedia.org/wiki/Space-cadet_keyboard) would return and fix this for us.

For Chris, these types of operator fixes should happen in the parsingrules section in the iss324 branch and if we start to play with π it can be renamed either in the validation logic, thus allowing forbidding all variants with a single forbidden word definition or it can happen in Maxima just as the current one happens... Also the iss324 parser currently can deal with variable names with Unicode letters and numbers in them as well as some slected ASCII characters but it will not allow punctuation class Unicode so those would need to be handled anyway.

**Comment by sangwinc** [comment]
Thanks Matti,
I agree we should roll all this in with issue #324.  
Just for the record, things like em-dash and unicode often arise when students cut and paste from other software such as Wolfram Alpha!

**Comment by sangwinc** [comment]
Thanks for reporting this.  Please don't hesitate to add more characters as needed.  We have a special note for these, so we can look at the logs and respond to actual usage as needed.
