### ISSUE TITLE
Broken images in Author quick start

### ISSUE THREAD

**Issue by fgnievinski** [maths/moodle-qtype_stack#439]
Figures like `![Integration exercises](%CONTENT/IntegrationExercises.jpg)` seem unavailable in  the
[Author quick start](https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/Authoring_quick_start.md)

**Comment by sangwinc** [comment]
No the images don't show up on the github site because these are extensions to markdown.

See https://stack2.maths.ed.ac.uk/demo2018/question/type/stack/doc/doc.php/Authoring/Authoring_quick_start.md

**Comment by fgnievinski** [comment]
Thanks for the clarification.

I was following the "Useful links- More documentation on this plugin" in the moodle plugin webpage:

https://moodle.org/plugins/qtype_stack

Maybe the link could point to the live documentation instead of Github?

**Comment by sangwinc** [comment]
Ok, thanks for that suggestion.
Done.
