### ISSUE TITLE
Upgrade to Moodle 3.6

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#442]
I've successfully upgraded a test server from Moodle 3.5 to 3.6 (STABLE) today and run all the unit tests.

One (known) problem is associated with Maxima 38.1 putting in extra brackets. This is not a blocker.

```
2) qtype_stack_test::test_xml_export
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
+    <idnumber></idnumber>\n

/var/www/html/live2018/question/type/stack/tests/questiontype_test.php:51
/var/www/html/live2018/question/type/stack/tests/questiontype_test.php:258
/var/www/html/live2018/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "qtype_stack_test" `question/type/stack/tests/questiontype_test.php

```
I think this is related to this issue: https://tracker.moodle.org/browse/MDL-62708?attachmentOrder=asc

This may in fact be an issue with the Moodle upgrade process, rather than STACK. Any comments Tim?

**Comment by sangwinc** [comment]
I've just installed STACK from scratch, and the default Maxima command was set as that contained here:
https://github.com/maths/moodle-qtype_stack/blob/master/db/install.php#L79
This is wrong!

**Comment by sangwinc** [comment]
The qtype_stack_test::test_xml_export test failure also exists on a new install.

**Comment by timhunt** [comment]
Yes, we broke that with our improvements to question export in Moodle 3.6. We worked out a hack to let the unit tests work in all Moodle version: https://github.com/moodleou/moodle-qtype_oumultiresponse/blob/master/tests/questiontype_test.php#L433

I'll try to get that fix added to STACK shortly.

**Comment by timhunt** [comment]
OK. Fix pushed.

**Comment by sangwinc** [comment]
Thanks.

**Comment by timhunt** [comment]
Well, acutally, first try failed. Hopefully that test will pass in https://travis-ci.org/maths/moodle-qtype_stack/jobs/494999119 this time.

**Comment by timhunt** [comment]
That seems to have worked.
