### ISSUE TITLE
Use a PRT to subtract points that are given by other PRTs

### ISSUE THREAD

**Issue by C0untC0unt** [maths/moodle-qtype_stack#443]
We worked on some questions dealing with combined inputs that exclude each other. That means, just one of the inputs should be filled and the other should remain empty. So far we use 3 PRTs and we are able to evaluate every possible combination of answers and to give a good feedback.
The only problem we faced is that if the correct input is answered correctly but the second input is answered as well, the student will always get the full amount of points. In this case we wanted that the points given for the correct input are canceled by the one that contradicts it. We could find no way to manage that problem and thought that it might be an interesting option to use PRTs to subtract points that were given by another PRT "beforehand".

**Comment by aharjula** [comment]
This is not an uncommon problem/idea that authors come across, it however has some very complex technical things behind it that make it difficult to solve without breaking down the STACK PRT model.

1. The penalty system might cause issues if we had negative scores possible in PRTs so dealing with this issue simply by allowing a PRT to generate a negative score is not the easy solution. It might need additional fields to define this and we already have quite a lot of fields.
2. To generate a score a PRT must have a score value and the questions total score forms from the total value of all PRTs if some of them just generate negative value getting "full points" from a question might be impossible and the surrounding VLE might startt to give interesting feedback. Not to mention evaluating relative weights of those PRTs. Basically, having a PRT that is not always generating score causes issues for the model.
3. Not all this score logic happens inside STACK much of the evaluation of total score happens in question behaviours in the case of Moodle and they too would need to deal with the logic of question parts affecting each other, I am not aware of such logic existing. Also if we have additional fields defining this then the behaviours would need to know what to do with them.

Subtraction could make validation of the logic difficult, I would select a more complex way of defining this. At the question level define that the question points should be selected from whichever set of PRTs has the highest total score and then define the sets to match the exclusion logic. Such definition should be easier to validate against negative total question scores and such oddities.

Personally, I think that trying to add exclusion of points to the model could make things very difficult and would add a feature to the system that might provide authors a very complex way of causing trouble to themselves.

I have worked on a STACK based question type that does have "exclusion" style behaviour in it and the definition of grading there is a mess, based on that experience on thinking about this I feel rather strongly that adding this as a feature to STACK could break STACK.

It will be interesting to hear what Chris thinks of this.

**Comment by sangwinc** [comment]
Thanks Matti, for your comments.  I agree with this!

We had this question at the STACK conference last Nov.  People are using STACK in ways I did not anticipate, and I am committed to supporting this kind of functionality.

Actually, I think the solution here is to use a single PRT, and the new "allowempty" tag on inputs.  This may not yet be on your system, so look at the docs here: https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/Inputs.md

Would this be a better solution?  If not, please email me your question and I'll take a look.  I'm always looking for interesting use-cases and want the design to be driven by that.
Chris

**Comment by C0untC0unt** [comment]
The "allowempty"-tag would be a way better solution. 

The described problem was just an attempt to evade the fact that we were not able to check if an input is empty. We just recognized that you mentioned working on that in issue #431 but we did not know how far the progress is. We will check if it is on our system. Thanks so far.


Do you still collect use-cases to improve that? I think we then can provide some of ours to #431 to help you.

**Comment by sangwinc** [comment]
Great. 

I'll close this issue, but if you can't satisfactory solve the problem re-open it and I'll look at the question specifically.  If you do get it working then please do email me the question. I'm always curious.

Chris
