### ISSUE TITLE
Numeric input type does not reject not numerical answers

### ISSUE THREAD

**Issue by EvaMix** [maths/moodle-qtype_stack#446]
Hey Chris, 

I reported this issue in Mantis (Bug ID 0024803), the Bugmanagementsystem of ILIAS, but Jesus said that this problem is the same in moodle so I will describe it here:

**Description of the Problem:** If only letters are typed in no information about entering non numerical characters is shown. Only the automatic Feedback is shown. In case of letter and numbers, you get the extra message. In the attached Screenshots you can see how this looks in ILIAS.

**Steps to reproduce:** Create a STACK question with an input field "Numerical."
Type in letters or spaces. 
Creating a sample question is done quickly but I also attached one.

Situations in which only letter would be typed in as an answer to questions which expect numerical inputs are not that often but they happen. And also, at least in ILIAS, the prts are not evaluated when typing in only letters so it is not possible to create a self written Feedback. It would be good if in case of only letters the same message would be shown as it is shown when typing in letters combined with numbers.

Eva

![letters and numbers](https://user-images.githubusercontent.com/46485597/54123792-f0abf200-4400-11e9-9417-f06a8c8b3efe.PNG)
![only letters](https://user-images.githubusercontent.com/46485597/54123793-f0abf200-4400-11e9-8a16-e40bdb5a070c.PNG)

[stack_question_7597.zip](https://github.com/maths/moodle-qtype_stack/files/2952098/stack_question_7597.zip)

**Comment by sangwinc** [comment]
Eva,
Thanks for reporting this.  You are reporting a design decision:  the whole point of the numerical input is to make sure the student types in a number, and make it invalid otherwise!   If you are going to permit letters, then why not use the algebraic input type?
Chris

**Comment by christianp** [comment]
I think the point is that if you only use letters, you don't get the helpful message "This input expects a number, and so may not contain variables"

**Comment by sangwinc** [comment]
Ok, thanks Christian!

**Comment by EvaMix** [comment]
> 
> 
> I think the point is that if you only use letters, you don't get the helpful message "This input expects a number, and so may not contain variables"

Yes, that is excatly what I meant.

**Comment by sangwinc** [comment]
Eva,
Thanks for suggesting this improvement.  Much appreciated.
Chris
