### ISSUE TITLE
Usefulness of "UnitsAbsolute" answer test

### ISSUE THREAD

**Issue by jmbragg** [maths/moodle-qtype_stack#448]
In the documentation there is this paragraph:
"Similarly, for NumAbsolute the option is an absolute difference. Literally we test |sa-ta| < |tol|. Here sa and ta are the numerical value of the student's and teacher's answer respectively once they have been converted to base units. Note, where the units are compatible, the same tol is used before and after conversion to base units. For this reason, the test UnitsAbsolute is likely to give strange behaviour for answers where the units are compatible."

Sadly I didn't read that before I setup a question....

I would have assumed that if specifying an absolute tolerance that the tolerance would be converted into other units if comparing different answers.

For example, I have a question where the correct answer is -124 kJ/mol.  Some students chose to enter the answer as -124000 J/mol because the equation that is used to do the calculation will give them the answer in J even if most chemists would convert it to kJ.  I would think that if I specify a tolerance of 5 with an answer of -124 kJ/mol that STACK would be capable of recognizing:
1) The TAns in the PRT has units (indeed it must for UnitsAbsolute)
2) The tolerance specified is probably specified for those units.
3) I'm not using UnitsStrictAbsolute so conversions are allowed.
Therefore, convert the tolerance to the base units and use the new tolerance to check if the student is correct.

There are a couple ways I can fix my question that I see so no big deal there.  I'm just suggesting that for an ease of use fix, its far more likely that someone would intend to use UnitsAbsolute and expect the tolerance to also change units than that the tolerance doesn't change units.  In fact, the standard Moodle core question types do this when using units and absolute tolerances.  So mostly this is just a usability suggestion.

**Comment by sangwinc** [comment]
Indeed,
>I would have assumed that if specifying an absolute tolerance that the tolerance would be converted into other units if comparing different answers.
This is perfectly reasonable!
The code is here: https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stackunits.mac

Conversion is done here: https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stackunits.mac#L96

And the answer test code is here: https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stackunits.mac#L430

I would welcome a pull request where we return a "conversion factor", which is then applied to the test tolerance!  Please include unit tests here: https://github.com/maths/moodle-qtype_stack/blob/master/tests/fixtures/answertestfixtures.class.php#L1558
(You don't need to install the PHPunit to run all the answer test unit tests, just login as a moodle admin, and go to the plugin page....)

If you need a new answer test, so as not to break back compatibility I'm happy to take a pull request with the working features and sort out a new answer test from there.
Chris

**Comment by jmbragg** [comment]
Heh... If I had the ability to take care of a pull request, I'd write one for you for sure.  One of these days I'm going learn more about PHP so that I can do exactly that... But I'm not really capable yet...

I would bet that no one is using UnitsAbsolute expecting a different behavior and has written their question in a way that this issue hasn't come up for them.  But that's a guess on my part...

**Comment by sangwinc** [comment]
I've been reflecting on this issue. 

At best, I think the current situation is "a serious omission".  It might better be described as a bug.  (Even if the docs accurately describe what I coded...) If you are comparing quantities with dimensions for an absolute difference then the tolerance should respect the dimensions.

So, I propose a change in behaviour of the absolute test to (1) accept units in the option, and (2) convert the tolerance if needed.

**Comment by sangwinc** [comment]
I completely understand if folk can't contribute "pull requests".  Git is complicated, and there is a significant learning curve to get started.
However, I would really appreciate contributions of test cases both to test the current code, and fix the behaviour.
The fact is almost none of the test cases failed with the above changes! 

It is possible to edit the code directly through the website, and you can run the answer test script so no need to add in PHP unit or a developer environment.  Any STACK user can contribute test cases to the answer tests, and I'd really welcome your examples (particularly important cases and edge cases).  The code is here: https://github.com/maths/moodle-qtype_stack/blob/iss448/tests/fixtures/answertestfixtures.class.php#L1558

If you want a skype call to get started please let me know.

**Comment by dhilsen** [comment]
The proposed change would be beneficial when considering our particular needs of the UnitsAbsolute test. The proposed change would not break any of our existing questions, nor create any foreseeable issues. This is most certainly a step in the right direction. I will do my best to contribute some useful test cases.

**Comment by jmbragg** [comment]
I was looking at the tests that you seem to have added in there already here: https://github.com/maths/moodle-qtype_stack/blob/84fd0eacbb23b13803323839f64b36a90a31ce5d/tests/fixtures/answertestfixtures.class.php#L1567

Those look good and work as I expect.

Is this line not working because the option was set with different units from the TAnswer?  https://github.com/maths/moodle-qtype_stack/blob/84fd0eacbb23b13803323839f64b36a90a31ce5d/tests/fixtures/answertestfixtures.class.php#L1558
That seems sensible, but perhaps could use a more helpful error message than I see there.  I vaguely remember that note is not the final message that gets shown...

I think you've hit all the potential problems I can see at first glance already with your tests...

**Comment by sangwinc** [comment]
Thanks for the feedback on these changes, and for confirming you are broadly happy with this.

An explicit error message will help teachers/question authors so I've added this in (one extra line of code, because the mechanism is all in place...)

I'll keep this issue open, and I'd really appreciate test cases.  The fix will make it into the next version.

**Comment by sangwinc** [comment]
Very sorry the fix to this issue (which I wrote a year ago...) didn't make it into STACK 4.3.  I'm tidying up outstanding issues and will merge this back into the development branch.
