### ISSUE TITLE
Surds not consistently tested

### ISSUE THREAD

**Issue by ianjones** [maths/moodle-qtype_stack#449]
Apologies if this has arisen before, I couldn't find it in issues when searching.

Unless I'm mistaken the attached question is not assessing surds consistently. Attached are two student screengrabs one marked correctly, one incorrectly. Both should have been marked correctly. This apparent inconsisency is evident across a few dozen student responses.

[correct.pdf](https://github.com/maths/moodle-qtype_stack/files/2979267/correct.pdf)
[incorrect.pdf](https://github.com/maths/moodle-qtype_stack/files/2979268/incorrect.pdf)

[questions-18MAA202-export-20190318-1636.xml.zip](https://github.com/maths/moodle-qtype_stack/files/2979270/questions-18MAA202-export-20190318-1636.xml.zip)

**Comment by sangwinc** [comment]
Ian,
 
The AlgEquiv general answer test treats _sets_ and _expressions slightly differently.

For expressions STACK tries to simplify the difference to zero.  For sets you can't do this, so STACK "simplifies" the objects in the sets, then compares the sets of objects.  Sometimes you need to give STACK a helping hand. This is in the docs under the AlgEquiv test, but it is subtle.  Sorry.  In this case apply "radcan" to the teacher's answer in the question variables, and also to the student's answer in the PRT.  Examples added to the test cases above.

Happy to talk on the phone if you need further help tomorrow (Tues).
Chris
