### ISSUE TITLE
TEST FAILED: algebraic_equivalence: evaluating the difference of two expressions threw an error.

### ISSUE THREAD

**Issue by jebarviabb** [maths/moodle-qtype_stack#451]
On a Moodle quiz activity, we have encountered an error in which if the answer is cos(1200*%pi*t)  then we get the following:
```TEST_FAILEDThe answer test failed to execute correctly: please alert your teacher. algebraic_equivalence: evaluating the difference of two expressions threw an error. The CAS timed out.CAS failed to return some data.```

A correct answer is 1.0⋅cos(1200⋅π⋅t), which can be typed in as follows:
1.0*cos(1200*%pi*t)

It only happens with the cos() function. Using others are working

These are the question settings/values and variables:
**Question Variables:**
```
Fs: rand(4) + 2
Amp: (rand(5)+1)*0.5
n: rand(2)*5+5
Tans: Amp*cos(2*%pi*Fs*1000/n*t)

p(k) := [discrete, [[k, 0], [k, Amp*cos(2*%pi*Fs*1000/n*k)]]]
pl: append(makelist(p(k), k, -0.005, 0.005, 1/Fs/1000), [Amp*cos(2*%pi*Fs*1000/n*x)])
```

**Question Text**
```
 Discrete version of signal is sketched here at
{@plot(pl, [x, -0.005, 0.005], [color, blue], [xlabel, "n/f_s"], [ylabel, "x[n]"])@}
If the sampling frequency is \(f_s={@Fs@} kHz\), provide the corresponding analogue signal expression for that frequency
Syntax: Type in \(\pi\) as '%pi'
\(x(t)=\) [[input:ans1]] [[validation:ans1]]
```
Input: ans1
type: Algebraic input
model answer: Tans
strict syntax: yes

Potential response tree:
Answer test: AlgEquiv
Sans: ans1
TAns: Tans

**Comment by sangwinc** [comment]
Very sorry, but I can't reproduce the issue, despite your very helpful and comprehensive report!

If you email me your actual question to C.J.Sangwin@ed.ac.uk I'll take a look.
Chris
