### ISSUE TITLE
students can access solving functionality through validation

### ISSUE THREAD

**Issue by oneuh** [maths/moodle-qtype_stack#452]
I found that you have access to maximas solve, linsolve, factor and simplify functionality over input fields and can see their output in the text validation. Maybe this issue covers even more functions.
![example](https://user-images.githubusercontent.com/47157032/55249133-aec9db00-524b-11e9-848b-ba2ad7a43a5c.PNG).
Interestingly, determinant(A) is only shown as det(A), but not calculated in the validation.

If this is intended, it'd probably be wise to communicate this and the affected functions more clearly so teachers can take measures to prevent this behaviour if they don't think it's appropriate.

**Comment by sangwinc** [comment]
Please have a look at the Forbidden words docs.
https://stack2.maths.ed.ac.uk/demo2018/question/type/stack/doc/doc.php/Authoring/Inputs.md
We have provided lists, so you shouldn't have to try to figure out all the things you should forbid!
