### ISSUE TITLE
unbalanced ]-char in casstring, wish list for new cassession

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#453]
The way the old CAS session unpacks the response from Maxima is somewhat sensitive to the contents of that response. One example of that is a simple unbalanced `]`-char which causes havoc no matter where you place it. Luckily, you can only place that into the CAS as a string, but there is the possibility of a LaTeX representation generating such a symbol into the response.

The fault is in connector.class.php in the unpackers and the way the look for matching `[]` that assumption ins not safe and we have been pretty lucky it has not caused trouble before. It however will block the CASText2 project and if the single pass PRT evaluation project takes the logical step of also using CASText2 then we have a problem.

To see how this is a problem, add this to your question-variables:
```
prefix:"[";
suffix:"]";
```
Or just drop `{@"]"@}` into CASText.

We should truly start work on a new version of CAS session with new connector logic. My current wish list is as follows:
- True encapsulation of return values at the CAS end, maybe true JSON or something similar, the value must not be able to be mistaken as the wrapper under no circumstances.
- Only output what is needed, i.e. if a function definition has been pushed into the CAS we probably do not need to have it appear thrice in the response unless we specially ask for that. That old "don't generate a LaTeX representation of a list of numbers if it is not going to be displayed in math-mode" wish.
- Only output the last value of a key that is requested to be outputted, do not output values from each step on the way. Again the problem here is a situation where one build large lists of things in multiple steps and thus causes exes output that never gets used but still takes room in the cache.
- Do output errors for each statement.
- Sub statement level error handling support for single pass PRTs and similar larger and more complex things.
- Way of defining that one wants the session to evaluate this list of statements but only wants to have the raw end values of a separate list of variable-identifiers and maybe LaTeX presentations for others. The simplest way would probably be to have sub classes like `stack_cas_castring_quiet` and `stack_cas_castring_value` that could be used in place of `stack_cas_castring` when adding statements to the session and the session would then check which ones have been used for the keys it knows of and generate suitable output for them.
- Finally, a timeout handler on the CAS side, maybe something that would stop evaluation of new statements once 50% of the allocated time has been used so that it could return some form of a better response to help identify the situation. Maybe even statement by statement times as output. This is somewhat important as if we only output the last values we can only output them after all statements have been processed.

**Comment by sangwinc** [comment]
Yes Matti, this is some of the oldest code still in STACK and as you point out we need to refactor it.....

**Comment by sangwinc** [comment]
Thank you Matti, for all your work since April to refactor this core component and address the issue.
