### ISSUE TITLE
Maxima in hosting

### ISSUE THREAD

**Issue by AsdrubalBeltran** [maths/moodle-qtype_stack#455]
Hello, I have moodle 3.1 in a hosting, I  install Stack q_type,  how install maxima in the hosting?
thanks

**Comment by sangwinc** [comment]
Sorry about the delay in replying to this issue, but I've been away!  You will need to contact the provider of your hosted environment to install Maxima.  This isn't something I can help with, beyond saying all I do on my machine is "apt-get install maxima" with suitable (root) permissions.

Chris
