### ISSUE TITLE
allowempty not honoured correctly

### ISSUE THREAD

**Issue by sgparry** [maths/moodle-qtype_stack#457]
I have been trying to use the allowempty option on matrices and it is letting me down when the answer includes empty cells / nulls. You can "fill in with correct answers" and submit, that works, but if you try to enter any actual data, the dreaded question marks start appearing and then you cannot submit a correct answer that includes empty cells / nulls....

**Comment by sangwinc** [comment]
Argh, ok!  
There is then the issue of "empty" and "partially" empty.  I can see a need for both.  Leave it with me.....

**Comment by sgparry** [comment]
I've added a "allowsparse" to my codebase for base N if you want to use that...

**Comment by sangwinc** [comment]
Thank you very much indeed.  I've documented and added in a test case here: https://github.com/maths/moodle-qtype_stack/commit/a9cae9e73689ba636fbebebf3a7bf0bc4fc33816
This is a very sensible addition, so thank you very much!  It will make its way into master in due course...
