### ISSUE TITLE
Automatically determine maxima version on installation

### ISSUE THREAD

**Issue by christianp** [maths/moodle-qtype_stack#462]
I just clicked through all the setup forms without changing anything. The default value for "Maxima version" is not the one I have, so of course the healthcheck script.

Could we do something like `maxima --version` when creating the form, to get the version of maxima, if it exists?

**Comment by sangwinc** [comment]
Christian,
maxima --version looks sensible, but if you compile Maxima from code it doesn't work!  We also have a branch with much better install code in it, and I hope we can merge all this together soon.
