### ISSUE TITLE
Make it easier for teachers to install Maxima sandbox

### ISSUE THREAD

**Issue by gustavdelius** [maths/moodle-qtype_stack#464]
The[ current explanation](https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/CAS/STACK-Maxima_sandbox.md) for how to set up a Maxima sandbox is not easy to understand. There is the file [sandbox.wxm](https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/sandbox.wxm) that could in principle make it easy, but it currently has hard-coded paths that assume the user has access to a moodle server. It would be good to have a version of this file that works well for users who do not.   Michael Kallweit (@m-r-k) suggested having different versions of the file for different operating systems to make it even easier for the user. Once these files are in place, the page explaining the setup can be drastically simplified.

**Comment by m-r-k** [comment]
Please try the attached ZIP-file.
[Maxima STACK Sandbox (2018080600).zip](https://github.com/maths/moodle-qtype_stack/files/3132222/Maxima.STACK.Sandbox.2018080600.zip)
It contains everything you need and should work out of the box on a linux system:

1. unzip
2. install maxima and wxmaxima
3. open sandbox.wxm with wxmaxima
4. have fun

Please give feedback if it worked as expected (or not).

**Comment by sangwinc** [comment]
Thanks folks, I'm very open to suggestions for improvements here.
Just keep in mind that the easiest way to make sure you have the latest code (Maxima libraries) is to clone the repository on your local machine.   So you don't need access to a server, but the best thing to do is checkout the code with git onto your local machine, and edit the paths to where your code sits.

**Comment by m-r-k** [comment]
I see. My ZIP file was just a quick help for Gustav.

But anyway, the instructions in sandbox.wxm are misleading. They say you should not edit the variables `file_search_*` but i think the paths are for the case of using the files from a server installation. For example:
In `file_search_maxima` you have `"/question/type/stack/stack/maxima/###.{mac,mc}"`.

If we change this to `"/maxima/###.{mac,mc}"`, you really just need to customize `stacklocation` to your needs.

**Comment by gustavdelius** [comment]
Michael, thank you for your pull request. Your fixes to the paths in sandbox.wxm work for me. I agree that it is better to ask users to take the code from github. I'll make further comments directly on the pull request.
One reason I had difficulties was that I had installed maxima but not maxima-share which contains extra packages, like stringproc for example.

**Comment by sangwinc** [comment]
Thanks Michael, 
I really appreciate you fixing this.
