### ISSUE TITLE
Travis tests failing

### ISSUE THREAD

**Issue by gustavdelius** [maths/moodle-qtype_stack#466]
All pull requests are currently failing the travis tests, but I suspect that is because master is failing them as well, perhaps related to #221?

**Comment by timhunt** [comment]
Yes. I need to fix this. The last time I worked on this I got it very close, but nealy passing tests are not that helpful. I am busy for the next couple of weeks, but hopefully after that.

**Comment by sangwinc** [comment]
Fixed.
