### ISSUE TITLE
New input type: data entry/resizable matrix

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#468]
We want to better support colleagues in physics who would like to accept data from students in a lab situation.

Based on some ideas we had for resizable matrices we would like the following features.

Validation options
1. require min/max number of rows/columns (If they are equal, that forces, e.g. the number of columns)
2. require min/max accuracy dp/sf by column/row.  That is, require column 1 to be to 2 sfs, but column 2 to 3sf.  This validates data entry.
3. As in 2 but require units, with various options such as compatible units.

The result would be a matrix.

We would also need better answer tests for dealing with sig figs in matrix entries.

**Comment by sangwinc** [comment]
We should also implement issue #469 and make sure this is also available here.

**Comment by dhilsen** [comment]
The ability to enter physics lab data in Stack would be very useful. This could be valuable for both a physical lab involving apparatus or a computer simulated lab. 

I would envision the instructor would be able to specify the number of columns and rows, along with the physical quantities that define the columns. For example, a Hooke's law lab would have the instructor establish two columns, one for the weight applied (to vertically oriented spring), and a second for the measured extension of the spring. Specifying 10 rows would require the student to gather 10 data points. It would be important to have Stack validate entries in each column for the correct number of significant figures and correct unit. 

With an investigative lab the goal is often to have the student find the relationship which exists between the involved quantities. I think most would agree this is more valuable than simply verifying an already known relationship. After the data has been gathered perhaps Stack could generate a plot of the data. The student would then enter a mathematical model and Stack would evaluate if the data fits the model. If the data does not fit the model the student would be required to enter a new model. This would of course require that some specified tolerance be taken into consideration by Stack to allow for error in measurement.

**Comment by christianp** [comment]
I've had such headaches about the right design for a customisable matrix input in Numbas.
There's a data grid (spreadsheet) component called [handsontable](https://handsontable.com/) that I've been meaning to have a go at using for a long time. That would work well for entering lab data.
