### ISSUE TITLE
New cloned question type

### ISSUE THREAD

**Issue by sgparry** [maths/moodle-qtype_stack#473]
Some STACK questions can be fiendishly complex and take a lot of work to create and will require many revisions and much testing to to get 'perfect'. If the author has any need to have multiple copies of the question in a quiz, he then has to make duplicates of that question in his question bank and perhaps manually tweak the deployed questions list in each to ensure that the same question variant does not appear twice. This user's question bank is littered with hundreds of such copies of defunct variants of questions.  If the questions requires fixes, you have the nightmare of propagating those fixes through many multiple copies.
Common use cases of this are are quizzes such as "do the following 10 matrix multiplications" or "do the following 10 binary floating point additions". These practice quizzes are invaluable tools for allowing students to practice their skills - but are a real maintenance nightmare.
This proposed enhancement would either add a new question type (STACK clone or link) that would allow a question to be a linked duplicate of an existing question. In the most basic use case, user would create a question of the "STACK clone" type and the question settings would simply consist of choosing an existing question category and then an existing STACK question from that category. The type would include features that minimize duplication, perhaps. a sequence number within the quiz used to 'salt' the existing random choice of question variant. For more advanced usage, the type should include a means to select a subset of the 'master' question's deployed variants. This would allow clones to re-use the deployment pool while for example giving a means to select harder variants later in the quiz. In this use case it makes sense for the master question not to appear in the quiz. This need not be enforced though.
To keep the implementation simple, the initial implementation of the clone type should delegate as many options to the master question as possible. Any 'smart logic' should be in the master question.
I am happy to try and implement this feature, but guidance on any gotchas would be appreciated.

**Comment by aharjula** [comment]
So essentially you want to define separate deployed variant pools that reference the same base question. Would you also provide tools that make it easy to see if the variant pools overlap and thus make it simple to ensure that if one wants to reserve certain variants to for example exam use those other pools would not contain those?
It would also be nice that when one runs question tests for the system also these variants in these "clones" would be tested.
I like your idea. My quick response is that it would be nice that these separate pools were separate objects and the referenced question should not need to know of them. Salting the seed makes little sense as if we were to simply act on deployed variants then the seed is the thing that defines the variant and no salttng is needed beyond that, in any case quiz already uses the order of questions in a quiz as offset for the seed. The interesting thing will be to deal with Moodle, how does one link those pools to the master question and maintain that link during import/export/backup or when that master question gets moved. Also the permission model of Moodle might fight against having the master question within a different course, but it might be nice to maintain the true master material in a central location, maybe even away from the actual usage location thus sharing between courses.
And yes keep all the question logic in the master question and delegate behaviour to it the clones should only contain the list of variants from which the master question gets the seed. One just needs to be careful to check that the master question has no deployed variants as that might affect the way how the seed selection works, but that can be bypassed by overriding just a small bit of logic.

**Comment by sgparry** [comment]
Thanks for your feedback @aharjula  - I am not very knowledgable on how the seeding within STACK works so your input is invaluable.
At a simple level I think the permissions probably will be as restrictive as we allow them to be - and @timhunt  will no doubt give us some guidance on that. I have not reviewed the database API but I would be surprised if they stop a question from one course looking at data from another. However, the backup, import and export stuff is potentially a concern. I presume ids numbers are not preserved. I will need to investigate. My thinking is that, for the most part, this question type would be a 'weak reference' requiring few alterations or none in the main question code and leaving the onus for example for not deleting a master question on the question authors.

> It would also be nice that when one runs question tests for the system also these variants in these "clones" would be tested.

> 
This was one example of why I was leaning towards the idea of just selecting a subset of the master pool within the clone. This keeps the main code cleaner and allows question author to test all used variants in one go. The model I had in mind was that you would encourage authors not to use the master question directly anywhere, but to always use a clone, avoiding some of the overlap issues. You could add an information screen or panel to list cloned uses of the variants. A general enhancement that would help here would being able to have a comment against each deployed variant - e.g. 'reserved for use in  summer 2019 summative'.

**Comment by aharjula** [comment]
[The seeding is quite simple](https://github.com/maths/moodle-qtype_stack/blob/master/question.php#L254-L277), the quiz of whatever calls the question generates a seed which the STACK question either uses directly, if there are no deployed variants or maps it to the list of deployed variants and picks the seed from there.
For some reason I don't feel that combining all these sets of variants to the master question is a good idea, but naturally it is the place where it makes most sense to provide the UI-tools for managing these separate pools. The testing logic can surely go fetch the variant seeds from the clones without them existing in the master question so it should not be necessary for them to exist on the master question side, just for that.

**Comment by sangwinc** [comment]
Thanks for raising a really important and difficult issue.

My current thinking of this problem is to push on with the YAML question format in the api_v4 branch.
Users can then cut and paste from one question to another.  Or, it might be possible to do more with git control, and text files in the future.  Does that sound like a sensible route to take?

The textfile format would also enable parts to be "loaded" into a question to updates could propagate. There must be models for this already, and I think the YAML (or other) text-based format would enable us to access these models and not reinvent one.  How this works within Moodle, ILIAS or other systems isn't clear at this moment...

Chris

**Comment by aharjula** [comment]
Chris,
I guess the objective here was to explicitly avoid cut and paste and cover cases where you want to use the same question with different deployed seed selections multiple times. I don't really see how YAML would help there as why would one cut and paste from questions when one wants to just duplicate the whole question, there is that duplicate button already? 

If I understand this correctly the idea is to provide an alternative to the duplicate question button that would allow one to provide a reference to the question with only a different variant list. As an idea it is nicely contained as the only thing it wants is to handle deployed seeds sets and there are plenty of use cases for that.

You should not consider this as a question type or anything dealing with the contents of the question, instead you should consider this as a tool to manage deployed variants sets in VLEs that only act on distinct questions and thus need additional logic to handle coordination tasks for those sets.

As to YAML having abilities for loading stuff into the question do look at #474 and consider that very carefully, the same issues will surely apply to pretty much every form of loading stuff in.

**Comment by sangwinc** [comment]
I think, for now, this issue is best addressed working offline.  A number of people are working on offline tools, and rather than complicate the moodle authoring it's best to concentrate there for now.  I'm closing this issue here.
