### ISSUE TITLE
Add options for boolean expressions to be rendered using alternative symbols

### ISSUE THREAD

**Issue by sgparry** [maths/moodle-qtype_stack#476]
Currently, although maxima happily renders logical expressions using wedge symbols, STACK overrides this behaviour and renders them using words ("and" "or" "not"). This behaviour is not always consistent or reliable. Also, not gets bracketed for simple variables.
My proposal it have options or variables or inert functions to allow the symbols rendered in logical expressions to be overridden to use any choice of symbols and to override the current bracketing behaviour. This is separate from how input is parsed - another can of worms - although the same inert functions could be used in the future as hints to the input system as to what syntax to expect / require.

**Comment by sangwinc** [comment]
Yes, this is on the list!  We need this.....  Thanks for creating an issue to bump it up.

**Comment by sangwinc** [comment]
If you would like further options, please re-open this issue.

**Comment by sgparry** [comment]
Thanks, I will take a look at some point soon. big long backlog...

**Comment by sangwinc** [comment]
I've fixed this issue with two options: symbols such as LaTeX \vee, and language "or".  If you would like further options please re-open the issue and we can add them.
