### ISSUE TITLE
Check button doesnt appear

### ISSUE THREAD

**Issue by Meridiana** [maths/moodle-qtype_stack#480]
The validate button for stack questions is missing (deferred feedback with explicit validation question behaviour ) no matter how the setting "qtype_stack | ajaxvalidation" is. 
It seems to be dependent on the check-in "Qtype: STACK: Simplify check button appearance." where some javascript in the file amd/src/input.js was removed (lines 356 ... 368) and the addition of a "display:none" in the styles.css.

Can you fix this issue, please?

**Comment by sangwinc** [comment]
Sorry about this.  When you say the code "was removed" can you point me to a specific commit here in Github?  I'll certainly look into this and fix it....

**Comment by Meridiana** [comment]
Sorry that I forgot that:

[Qtype: STACK: Simplify check button appearance.]https://github.com/maths/moodle-qtype_stack/commit/01f22387484bf3ff47a786c46f835a86d30c7389

Thank you very much for taking care of it.

**Comment by timhunt** [comment]
Looks like losnig the hasClass check here is hte problem: https://github.com/maths/moodle-qtype_stack/commit/01f22387484bf3ff47a786c46f835a86d30c7389#diff-c1f55c5994ce6ed9bbc86a7b3366f508L362

**Comment by sangwinc** [comment]
I hope this fixes the issue.  Sorry about that Meridiana.  John, I'm sorry to have reverted your contribution in https://github.com/maths/moodle-qtype_stack/commit/01f22387484bf3ff47a786c46f835a86d30c7389 I'm very happy to reconsider this fix to issue #480 if you have an alternative suggestion?
