### ISSUE TITLE
Question test cases do not respect forbidden words option on inputs

### ISSUE THREAD

**Issue by georgekinnear** [maths/moodle-qtype_stack#482]
I have a question which forbids the word "limit" in the student answer.

When I add a question test to check this is working, with "limit(f,x,a)" as the input, the answer receives a score rather than being rejected as invalid.

It appears that the scoring that takes place in a question test does not fully respect the validation settings on the input.

**Comment by sangwinc** [comment]
A subtle issue George, well spotted.  This should be addressed by the docs.
