### ISSUE TITLE
Radio input broken

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#483]
Something funny seems to be going on with Radio inputs. Here is an annotated screen grab from Q2 in https://stack2.maths.ed.ac.uk/demo2018/mod/quiz/view.php?id=147

![image](https://user-images.githubusercontent.com/138653/59364366-a7847a80-8d2e-11e9-97e6-731ba8179a25.png)

Note, the Moodle core solution https://tracker.moodle.org/browse/MDL-5311 has now landed in Moodle 3.7.

**Comment by sangwinc** [comment]
This is the very subtle difference between

1. I want to uncheck my answer and move away and not choose anything (no answer given) and 
2. I want my answer to actually be "None of these" other answers.

If there is a way to uncheck a radio answer, I'll reconfigure the radio to remove the "no answer given" box.

This is not a bug, but is the intended behaviour!

**Comment by timhunt** [comment]
My feeling is that we should only add "None of these" if the question author wants it.

We should steal the Moodle core solution for "(no answer given)" (which is essentially JavaScript to un-tick all choices, or at least make it look like that is what has happened). I wish I had time to volunteer to do that now, but I think I should not allow myself to be distracted from what I am supposed to be working on.

**Comment by sangwinc** [comment]
Indeed, the "none of these" must be added by the teacher! See
https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/MCQ.md

There is an option to remove the "No answer given" as well, but I don't recommend (or indeed use) that myself.

I'm trying to improve the Javascript support in other areas, so this might be rolled in as well.
