### ISSUE TITLE
Versions/variants naming inconsistency

### ISSUE THREAD

**Issue by malthesporring** [maths/moodle-qtype_stack#487]
Is it called a deployed version or a deployed variant? In "Editing a STACK question" and the preview box, they are called "versions", as in the links to "Question tests & deployed versions". But in the actual deployment and testing window, they are called "variants".

**Comment by sangwinc** [comment]
Well spotted Malthe, thanks.

I suggest we use "variant".  The word "version" might get confused with changes over time when we are editing.  

Can you make the changes in https://github.com/maths/moodle-qtype_stack/tree/catedocupdate both in any language strings and in the docs?

(If you include the tag "issue #487" in any commit messages Github will recognize it relates to this issue!)

Chris

**Comment by malthesporring** [comment]
Will do.

Malthe

**Comment by timhunt** [comment]
+1 for Variant. That is the word used in the core Moodle question system.

**Comment by aharjula** [comment]
Variantti on parempi kuin versio, laajemmassa käytössä ja vähemmän epäselvä.

Also in Finnish localisation that is.

**Comment by malthesporring** [comment]
Hi Chris,

I have fixed this in English, but I am not quite sure how to fix it in other languages.
How do I go about fixing it in other languages (both documentation & code)? How many languages do we support?

Malthe

**Comment by sangwinc** [comment]
The translators may well have used a consistent phrase from the start in their own language.  I trust (?) the language system recognizes a change in the language strings and alerts maintainers accordingly.

If you are done with this issue, please close it.
