### ISSUE TITLE
CAS variables do not show up formatted in question test preview

### ISSUE THREAD

**Issue by malthesporring** [maths/moodle-qtype_stack#488]
When previewing feedback in a Question Test, standard answer tests (like Int) seem to be able to show CAS variables like the student answer, but manual specific feedback does not seem to display CAS variables like {@ans1@} in LaTeX formattng. See image below.

![Question tests](https://user-images.githubusercontent.com/52042426/60089234-f3c0b900-9737-11e9-866c-23c91ab58e38.PNG)

This is only an issue in the Question Test preview pane. When previewing manually, the CAS variables are formatted correctly.

**Comment by sangwinc** [comment]
Thanks Malthe, this is a long standing bug which I never quite got round to fixing.  It did seriously irritate me though...
