### ISSUE TITLE
Misleading interface when creating question tests for already deployed variants

### ISSUE THREAD

**Issue by malthesporring** [maths/moodle-qtype_stack#489]
Currently the question testing interface does not seem to work well if you deploy variants first and create question tests after. This is important if you come back to a working question (with deployed variants and tests) and decide to add another test, or if you are a new user and decide to deploy variants before creating a question test (that is the order they appear on the page anyway).

Let's say you've deployed some variants. If you now create a question test that only -a few- of your deployed variants will pass, STACK will show text such as "Testing question variants (100%)" (plural), and show a lot of green, indicating that everything is okay.

It is not intuitive at all that this is only testing a single question variant (usually the arbitrary variant) and that you actually need to click "Run all tests on all deployed variants" before you know that some of them failed. Indeed, this is not clear in the documentation either (I can take care of this part!)

When you try to deploy variants with existing question tests, there is an algorithm that will test all variants and display the first failure it comes across. I suggest having this same algorithm (or a similar one) be at play when you create a question test with existing deployed variants. Alternatively, you can "run all tests on all deployed variants" by default when you create a test (even though this will be slow!)

Malthe 

![all tests passed](https://user-images.githubusercontent.com/52042426/60186530-e41e9e80-9823-11e9-96c1-84c210da8875.PNG)
(this is the screen shown after creating a question test that only one variant fails. Not intuitive that not all variants are tested or that one failed.)

**Comment by sangwinc** [comment]
Malthe,

Thanks for raising this.  The behaviour is a slight hangover from when we always ran every test on every variant, which proved so slow as to be unworkable on questions with lots of variants.  I'm proposing to address this by clarifying the text, rather than a redesign (for which I don't really have a lot of time....)  

![issue](https://user-images.githubusercontent.com/781615/60197940-644eff00-9838-11e9-996f-94a3dc452ab0.png)

**Comment by malthesporring** [comment]
Thanks Chris, this is a definite improvement.
