### ISSUE TITLE
Bug in singlefrac answer test

### ISSUE THREAD

**Issue by lcorson** [maths/moodle-qtype_stack#491]
![Screen Shot 2019-07-04 at 09 53 02](https://user-images.githubusercontent.com/52528353/60653256-9a484080-9e41-11e9-9b73-661bb85c1941.png)

When I use the SingleFrac answer test it interprets the power as a separate fraction and claims the answer contains fractions within fractions. The answer ((sqrt(5))^3 +6)/15 passes the test.

I've attached the question. 

[SingleFrac_MWE.xml.zip](https://github.com/maths/moodle-qtype_stack/files/3358550/SingleFrac_MWE.xml.zip)

**Comment by sangwinc** [comment]
Apologies, this is a bug.  Thanks for reporting it so clearly.
Chris
