### ISSUE TITLE
Unsupported keyword: create_list.

### ISSUE THREAD

**Issue by samfearn** [maths/moodle-qtype_stack#494]
Apparently `create_list` is unsupported, maybe deliberately? I guess most use cases can be covered using `makelist`, but the maxima documentation lists both, so it seemed strange to me that `create_list` doesn't work.

**Comment by sangwinc** [comment]
I don't remember any reason why this should be forbidden.  I think this was just the underscore in the parsing logic.  Let's now allow this.
