### ISSUE TITLE
Scientific Notation Format Feedback

### ISSUE THREAD

**Issue by dhilsen** [maths/moodle-qtype_stack#498]
We have encountered a number of physics students (and instructors) who attempt to input scientific notation using the format `a x 10^b`. This is understandable as they see it written that way in the question text immediately preceding the input. Unfortunately, when a numerical answer is entered in this way it trips up different parts of our PRT depending on how spaces are inserted around the x. This then generates an irrelevant error message.

For numerical and unit question types, might I suggest we provide validation feedback for `a x 10^b` and give information as to the acceptable forms of scientific notation. In addition to the form `aEb`, physics students also use `a*10^b`.

**Comment by aharjula** [comment]
Not entirely impossible once the tools that come with 4.3 are present:
```
23.2 x 10^b
----------- MP_Root
----------- MP_Statement
----------- MP_Operation * [fixspaces]
----        MP_Float 23.2
     ------ MP_Operation * [fixspaces]
     -      MP_Identifier x
       ---- MP_Operation ^
       --   MP_Identifier 10
          - MP_Identifier b
```
Should not be too difficult to spot `x*10^` as a pattern and check where the stars came from and then invalidate the statement with a suitable error or even rewrite it but just for those two special input types as that kind of pattern detection might cause trouble in other inputs that might actually have a reason to have `x` in play.

I hope Chris can try to make such an filter at some point, but probably just now.

**Comment by sangwinc** [comment]
Good suggestion David.

This is the kind of incremental improvement we can certainly make.  I'm in the last stages of releasing STACK 4.3, and this is a priority for our own teaching in the 2019-20 session.

Chris

**Comment by dhilsen** [comment]
Thank you Matti and Chris for all your fantastic work. 

Just thought to mention that it will be important to look for both `x*10^` and `x10^`.
