### ISSUE TITLE
Problem with forbidden %

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#500]
Hi,

I have the following question code:
apar : rand([-3,-2,-1,1,2,3]);
DE : 'diff(y,x)=apar*y;
IC : rand([-3,-2,-1,1,2,3]);
Tansyg : rhs(ode2(DE, y, x));

The problem is that ode2 returns undetermined constants as %c and the percent sign is forbidden e.g. in question tests.

In standard maxima it works fine to just put in the line
Tansyg : ev(Tansyg,%c=C);
or
Tansyg : Tansyg,%c=C;
in order to replace %c by C, but STACK does not allow me to save the question with this modification.

How should I deal with this (apart from avoiding the use of ode2)? Maybe other maxima commands also return percent signs?

Thanks,
Mikael

**Comment by aharjula** [comment]
Have you by any chance tried the 4.3 alpha branch? Maybe it would allow more.

That branch is pretty close to ready, still some issues with performance in complex CASText but very near now. It will also allow `Tansyg : Tansyg,%c=C;` style evaluation-flag syntax which is currently forbidden.

**Comment by sangwinc** [comment]
Have you seen this function?
https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stackmaxima.mac#L2564

I confess, it is a while since I used this.  If this does not fix the problem I will do so some other way.

This function is designed to address the problem that constants of integration do not have a consistent name.

**Comment by alcarola** [comment]
Aha, do I dare to switch to 4.3 alpha for production/teaching use? If yes, then that is perhaps the best way of fixing this problem.

I had a look at subst_int_const, but it doesn't substitute anything in my case. I tried debugging, and obtained the following (is there a bug here?):

(%i9) ex:Tansyg;
(%o9) %c*%e^-(3*x)

(%i10)   lv:listofvars(ex);
(%o10) [%c,x]

(%i11) li:sublist_indices(lv, lambda([ex],is(smismatch("integrationconstant",string(ex))>19) or is(smismatch("%c",string(ex))>2)) );
(%o11) []

Hence the line if emptyp(li) then return(ex) is executed, hence no substitution, as li is incorrectly an empty list, it seems?

(%i21) smismatch("%c",string(ex));
(%o21) 3

Also just using the subst command doesn't work, because that also requires a forbidden %.

**Comment by aharjula** [comment]
Well 4.3alpha is nearing usable, and works in many places but it does have its issues the latest has been with situations where we have large number of variables in play (think 400+ and [[foreach]]-loops) where it times out trying to push all that to Maxima.
The new communication-logic with Maxima is a bit more complex and causes overhead but it gives us perfect peace of mind about certain things and the ability to input some others. But it has its problems.

**Comment by aharjula** [comment]
If you cloned the code before this message you will want to clone again, there was a bug there during the last two hours or so.

**Comment by sangwinc** [comment]
There is a fix in pre v4.3, see docs on differential equations.
https://github.com/maths/moodle-qtype_stack/blob/stack4.3A/doc/en/CAS/Differential_equations.md
(I'm pointing at the v4.3 docs because I updated them...)

**Comment by alcarola** [comment]
Thanks a lot! This fixed my problem. Now I can probably wait with 4.3 until it's finished and released.

One thing, you wrote

assume(x>0);
ode = x^2*'diff(y,x) + 3*y*x = sin(x)/x;
sol = stack_strip_percent(ode2(ode,y,x),[k]);
ta = rhs(ev(sol,nouns));

Did you mean that the first equal signs on every row should be colons?

**Comment by sangwinc** [comment]
Well spotted. Thanks.
