### ISSUE TITLE
significantfigures can no longer accept a list?

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#501]
I have a question with the following code, which I believe worked fine before:

tscale:rand_with_step(1.6,1.9,0.1);
tdata:significantfigures([0.2,0.4,0.5,0.6,0.7,0.8,1]*tscale,3);

Now, however I get the error message that the first argument to significantfigures needs to be a real number.

If this is not intended to work, then what is an efficient way to achieve this?

**Comment by timhunt** [comment]
Just to say that I say a similar error from some of the questions we have at the OU. Mikael, thanks for reporting it with such a clear reproduction case.

**Comment by aharjula** [comment]
Ignoring the problem I would do it like this:
```
sf3(x):=significantfigures(x,3);
tdata:map(sf3,[0.2,0.4,0.5,0.6,0.7,0.8,1]*tscale);
```
Naturally would be nice if it still worked with non atoms although it does need the items to be real which is a natural requirement.

**Comment by alcarola** [comment]
Thanks for the responses! I now checked all my questions, and I have quite a few of them suffer from this problem, many of which passing lists to significantfigures in a way which cannot be worked around as easily as this one.

**Comment by sangwinc** [comment]
Ok, I'll make sure this functionality is in V4.3, and put unit tests to make sure it doesn't disappear.

Sorry if this caused problems.

**Comment by alcarola** [comment]
Thanks! Approximately when do you estimate that this will work again? I can do a git pull almost anytime, and do not necessarily have to wait for V4.3. If I recall correctly, I will need this only at the beginning of 2020.

**Comment by aharjula** [comment]
I too am interested in the schedule for this, as this is pretty much the last thing in v4.3 that affects the material pool I am testing on. Others being people actually using `arctan` and it being forbidden now and people writing to input variables which is also forbidden now, but those are just wrong and are fixed on the material side while this function has been used widely to process data for many different uses.
