### ISSUE TITLE
(No answer given) is automatically added as an possible answer

### ISSUE THREAD

**Issue by V-Mor** [maths/moodle-qtype_stack#502]
I am trying to create a radio button or a dropdown response field. And "(No answer given)" is automatically added as an possible answer. I don't need it in my list of answers!

**Comment by aharjula** [comment]
There exists a fairly good reason for that options existence, and as one is likely to forget to add it and need it we add it by default.

But if you are sure you do not need it you can add `nonotanswered` to the extra options field of that input.

The full reason why one would need it might not be obvious in [the documentation](https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/Multiple_choice_questions.md) but trust me when you need it you will know.

**Comment by V-Mor** [comment]
@aharjula Thank you soooooooo much for your answer!!! It's very helpful

**Comment by V-Mor** [comment]
@aharjula But it doesn't work for true/false questions. Can you advise anything for this?

**Comment by aharjula** [comment]
The boolean input just does not provide that option, if you want such an input you will need to build one from the dropdown-input. Basically, define your own true/false options in that dropdown and then use `nonotanswered`.

I guess this is now covered and will close the issue.

**Comment by V-Mor** [comment]
@aharjula Thank you
