### ISSUE TITLE
Different STACK-Maxima library version is used than is installed

### ISSUE THREAD

**Issue by rikkpa** [maths/moodle-qtype_stack#503]
This library version problem started when we were having trouble with the STACK's answer interpretation. It seems that STACK wrongly interprets numbers as variables when user is writing a numerical answer. STACK gives the following message before the answer (in this example number 2.6) is submitted:

> "Your last answer was interpreted as follows: The variables found in your answer were: _stack_validate_listofvars_(2.6)"

From the old closed issue https://github.com/maths/moodle-qtype_stack/issues/490 we found that the problem might result from the version conflicts. That led us to a new problem related to the used STACK-Maxima library version:

We installed STACK from the master branch (4.2.1 for Moodle 3.0+, 2019052700). In our Maxima server both 2019052700 and 2018080600 libraries are installed. Our STACK healthcheck gives the following information:

> Healthcheck results:
> OK	CAS returned data as expected. You have a live connection to the CAS.
> OK	Correct and expected STACK-Maxima library version being used (2018080600).
> 	Load optional Maxima libraries: stats, distrib, descriptive
> 	CAS results are being cached in the database.

So it seems that somehow STACK uses the wrong STACK-Maxima library version that it should be using. Is there a solution to make the STACK-Maxima library versions match in this case?

**Comment by timhunt** [comment]
I thought STACK did this automatically as part of the upgrade, but on the healthcheck page, can you try clicking the 'Clear CAS cache' button.

**Comment by rikkpa** [comment]
Thanks a lot for the suggestion. Unfortunately that didn't help since the version still remains the same in the healthcheck results (2018080600).

**Comment by sangwinc** [comment]
Perhaps you could upgrade to this tagged version?
https://github.com/maths/moodle-qtype_stack/releases/tag/v4.2.2
Chris

**Comment by rikkpa** [comment]
Thanks for the advice. We will try the tagged version 4.2.2 in our demo server and see if that works.
