### ISSUE TITLE
Installation instructions for Ubuntu incomplete

### ISSUE THREAD

**Issue by sm8ps** [maths/moodle-qtype_stack#506]
Following the instructions STACK for Moodle on Ubuntu 18.04 (LXC installation) do not result in a working installation. The healthcheck script complains about not being able to connect to the CAS. 
Manually trying the steps, it turns out that the presence of Gcc is expected which was not true. Searching for the cause cost me quite some nerves and time. So I thought it would be nice to spare others from the same trouble. Please include this information in the instructions, thank you!
And thank you very much for making STACK available!!!

**Comment by sangwinc** [comment]
Thanks very much indeed for raising this issue.  We are trying to support this on a wide range of platforms, but of course each one is different and it is impossible for us to test all of them.  

Could you propose a specific edit to the docs, e.g. here: https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Installation/index.md

or would it be better here: https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Installation/Maxima.md

**Comment by sm8ps** [comment]
Many thanks for your quick and kind reaction, @sangwinc! I would suggest a change in the installation instructions for STACK.
https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Installation/index.md#2-install-gnuplot-and-maxima
The first sentence could read: "Ensure gcc, gnuplot and Maxima are installed on your server."

I should point out that the issue is specific for containers. For most other installations, gcc will most certainly be present. Nevertheless, adding it in does not hurt.

**Comment by sangwinc** [comment]
Thank you for your help.  Please do report any more suggestions for improvements.
Chris
