### ISSUE TITLE
STACK demonstration site (v4.3.0 beta)

### ISSUE THREAD

**Issue by ianjones** [maths/moodle-qtype_stack#507]
I have a question working ok on my institution's Moodle that is bust when I try it on the Edinburgh demo site. Should that be expected?

Thanks!

**Comment by sangwinc** [comment]
Ian,
The Edinburgh demo site is running the latest version 4.3, which has tightened up the teacher's input considerably. Things will break.  Please email me the question and I'll take a look.
Chris
