### ISSUE TITLE
Statistics about STACK usage

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#518]
There was again a need to come up with numbers about STACK usage and again I had to do some work in the Moodle database and try to get something sensible out. Given the way that database is structured a simple query collecting all the details can become quite cumbersome and the ways we can define what we actually want tends to vary so I though that maybe we should have a tool that collects data according to common definitions and using queries that are correct (i.e. such that Tim thinks that they make sense).
I however have no idea about what the statistics people would want are? For me the things I want to know are:

 1. How many STACK questions were initialised for students during the last time interval.
 2. How many attempts those students made to those question during that time on average.
 3. Which courses had most attempts and which courses had the most STACK questions in use.
 4. Question bank status by course, how many questions were in use, which questions have not been used for a long time.
 5. Quiz/activity usage, i.e. in what context are the questions being used and for example how many questions are present in a quiz by average.
 6. Duplicate questions, how many copies of the same questions are present in the question banks.

For me the problem is the definition of what is an attempt and how one extract a sensible attempt number when we have various question behaviours storing various amounts of things as steps.

I know that this would probably also work as a generic Moodle feature where one could select the type of questions, but for now I think that the nature of behaviours in use in STACK makes us somewhat special and the tool should probably be built on our side.

Note how I want to have data by course. While Moodle will give some statistics about all time usage of various things it tends to not tell you those by course and for me personally it is somewhat important to know which of hundreds of courses are active and see if some new course starts to use or stops using STACK. I know that one can easily find out in which courses question banks specific types of questions are but that is not quite enough as cloning a course might bring the questions but they might not get used.

**So** what sorts of statistics do you believe we should be able to collect about STACK usage? Do you have some specific metrics you would want to include in a tool that could generate somewhat equivalent (naturally we cannot know about the intent of specific quizzes which are review which are assessment and so on thus equivalent only in the sense of questions served) data when executed on various Moodles around the world?

**Comment by timhunt** [comment]
The main report I run (scheduled to run once per week using https://moodle.org/plugins/report_customsql) counts the number of question_attempts with timemodified in the last week. That is the number of questions that students have interacted with.

```
SELECT COUNT(1)
FROM {question_attempts} qa
JOIN {question} q ON q.id = qa.questionid
JOIN {quiz_attempts} quiza ON quiza.uniqueid = qa.questionusageid
WHERE quiza.preview = 0
AND q.qtype = 'stack'
AND qa.timemodified BETWEEN %%STARTTIME%% AND %%ENDTIME%%
```

And, here is a query that does number of questions attempted (ever) by course

```
SELECT c.shortname AS Website, COUNT(1) AS Number_of_STACK_questions_attempted

FROM {question_attempts} qa
JOIN {question} q ON q.id = qa.questionid
JOIN {quiz_attempts} quiza ON quiza.uniqueid = qa.questionusageid
JOIN {quiz} quiz ON quiz.id = quiza.quiz
JOIN {course} c ON c.id = quiz.course

WHERE q.qtype = 'stack'
AND quiza.preview = 0

GROUP BY c.shortname

ORDER BY COUNT(1) DESC, c.shortname
```

Moodle has a built-in report that will count the number of questions of any type in the question bank (report/questioninstances) but I think this is a less useful statistic.

Another useful report, which we use for planning the time of upgrades, is this one, which lists the close date of quizzes uses STACK (including ones that use STACK questions via Moodle's 'Random question' feature:

```
SELECT DISTINCT
    c.shortname AS Website,
    quiz.name AS iCMA,
    quiz.timeopen AS Open_date,
    quiz.timeclose AS Close_date

FROM {quiz} quiz
JOIN {course} c ON c.id = quiz.course

WHERE to_timestamp(quiz.timeclose) > 'now'::timestamp - '1 month'::interval
AND EXISTS (
    SELECT 1
    FROM {quiz_slots} slot
    JOIN {question} q ON q.id = slot.questionid
    WHERE slot.quizid = quiz.id AND (
        q.qtype = 'stack' OR q.qtype = 'random' AND EXISTS (
            SELECT 1
            FROM {question_categories} qc
            JOIN {question} rq ON rq.category = qc.id
            WHERE qc.id = q.category AND rq.qtype = 'stack'
        )
    )
)
ORDER BY Close_date, Website, iCMA
```

One final query, which lists all the people who have created STACK questions in your site (useful if you need to email them about something:

```
SELECT u.firstname, u.lastname, u.username, u.email, number_created, number_modified

FROM (
    SELECT COALESCE(createdby, modifiedby) AS userid,
           COALESCE(number_created, 0) AS number_created,
           COALESCE(number_modified, 0) AS number_modified
    FROM (

        SELECT createdby, COUNT(1) AS number_created
        FROM {question} WHERE qtype = 'stack'
        GROUP BY createdby

    ) qscreated
    FULL JOIN (

        SELECT modifiedby, COUNT(1) AS number_modified
        FROM {question} WHERE qtype = 'stack'
        GROUP BY modifiedby

    ) qsmodified ON createdby = modifiedby

) comined_counts

JOIN {user} u ON u.id = userid

ORDER BY number_created DESC, number_modified DESC
```

I am not saying that these are the best queries to use, just that they are the ones I happen to have written over the years, because someone asked me for some specific info. The way the JOINs work may help you work out the queries for the statistics you want.

**Comment by aharjula** [comment]
Thank you Tim, those will surely help.

Any idea on how to remove people that have only imported/restored question-banks/quizzes from that last listing? We have a pretty common use case where people get their questions from elsewhere and never edit them but as they do the importing the creator and last modifier detail is not really correct. Would I need to identify import/restore actions from logs and then identify questions with the same timestamp and person editing?

**Comment by timhunt** [comment]
I know what you mean about only import/restore. I don't have a good answer to that. Sorry.

**Comment by sangwinc** [comment]
Tim, Matti,
I'm reviewing and tidying up issues.  Perhaps this could be moved into the docs so the discussion does not get lost, then we can close the issue?

**Comment by sangwinc** [comment]
Matti, Tim, if you have more useful queries could you please add them to the docs?
Thanks for these useful tips!
