### ISSUE TITLE
4.2.1 works but 4.2.2 not

### ISSUE THREAD

**Issue by jval** [maths/moodle-qtype_stack#523]
I just had to revert the "stack" subdirectory to the one from 4.2.1 because the latest 4.2.2 couldn't connect to CAS. 4.2.1 works just fine.

Our Moodle version is 3.5.9. The value of "qtype_stack | platform" in our settings is "Linux (optimised)" and "qtype_stack | maximacommand" is the following:

timeout --kill-after=10s 10s /path/to/moodledata/stack/maxima_opt_auto -eval '(cl-user::run)'

**Comment by sangwinc** [comment]
The most likely reason is that you have cached maxima images on your system.  Please remove the maxima images from your data/stack directory.  This should happen when you run the healthcheck script again.

**Comment by jval** [comment]
Reverting/downgrading only "stack/cas" and "stack/maxima" is enough it seems.

When everything is from 4.2.2 the healthcheck page reports the following as failed: "The version of the STACK-Maxima libraries being  used (2017121800) does not match what is expected (2019090200) by this  version of the STACK question type. Please rebuild your optimised Maxima executable."

**Comment by jval** [comment]
When I click the "Create Maxima image" button I get this: "Create Optimised Maxima Image FAILED : [Uncached connection failed: CAS failed to return any evaluated expressions. Please check your connection with the CAS. CAS returned some data as expected, but there were errors."

**Comment by jval** [comment]
No, only the healthcheck started to draw plots and the library version error went away but the actual plots don't work. There is still something wrong.

**Comment by sangwinc** [comment]
Very sorry you are having these problems upgrading.  This has not been widely reported, and indeed you should not normally need to remove the maxima images by hand.

**Comment by jval** [comment]
Removing the image by hand did not fix all the problems so this issue should not have been closed I think.

**The new version does not plot lines with slope=0.** I had to downgrade "stack/cas" and "stack/maxima" to the previous 4.2.1 to get those to plot too. I don't think that issue is related to upgrading at all. It's just a bug in 4.2.2. Can you investigate that please? Can others get lines with slope=0 to plot, using 4.2.2? Thanks!

**Comment by sangwinc** [comment]
Do you mean something like this? 
{@plot(2,[x,-3,3], [y,-1,3])@}
I've just tested this on the code from the master branch (4.2.2).  I can't reproduce the problem, sorry.
Chris

**Comment by jval** [comment]
{@plot(f0,[x,-20,20],grid2d)@}

**Comment by jval** [comment]
CASText failed validation. The CAS returned the following error(s):plot(f0,[x,-20,20],grid2d) caused the following error: Warning: empty y range [-5:-5], adjusting to [-5.05:-4.95]

**Comment by jval** [comment]
I created #524 for the issue.
