### ISSUE TITLE
4.2.2 not does not handle {@plot(f0,[x,-20,20],grid2d)@}

### ISSUE THREAD

**Issue by jval** [maths/moodle-qtype_stack#524]
The new version 4.2.2. does not handle {@plot(f0,[x,-20,20],grid2d)@}. I had to downgrade "stack/cas" and "stack/maxima" to the previous 4.2.1 to get those to plot too.

When trying to create/edit, this error is given: 

> plot(f0,[x,-20,20],grid2d) caused the following error: Warning: empty y range [-5:-5], adjusting to [-5.05:-4.95]

For creating/editing a full downgrade to 4.2.1 is needed.

**Comment by sangwinc** [comment]
The "problem" is the improved error message!  The solution here is to provide an explicit y-range.  This fixes your issue in 4.2.2.  E.g. this case works, where f0:5 is explicit below.

{@plot(5,[x,-20,20],[y,4,6],grid2d)@}

**Comment by jval** [comment]
Big thanks! And sorry. I'm only our Moodle admin, not the STACK user, so didn't know the syntax wasn't correct... :)

**Comment by jval** [comment]
Sorry again. But are you sure? I'm asking because Maxima documentation states: _A range for the vertical axis is an **optional** argument_.

E.g. see the documentation of the STACK recommended Maxima version 5.38.1 and the function plot2d (as the plot function is a wrapper to Maxima's plot2d):

http://flex.phys.tohoku.ac.jp/texi/Maxima%205.38.1%20Manual.htm#SEC65

**Comment by jval** [comment]
Maybe the change in 4.2.2 is that warnings are handled like errors? If that is the case please reconsider because IMO a warning should not be handled like it's an error because it's a warning, not an error.

**Comment by jval** [comment]
[-5.05:-4.95] doesn't make sense I guess but the 4.2.1 seems to use [-6, -4] automatically which does make sense and causes a nice plot to be drawn.
