### ISSUE TITLE
Default shape of matrix parentheses

### ISSUE THREAD

**Issue by HsH-Wolf** [maths/moodle-qtype_stack#526]
If I choose a shape for matrix parentheses with the dropdown „matrixparens“, it only affects the depiction of the parentheses in the question text, but not the dispiction in the input field for the student’s answer.
![matrix_parentheses](https://user-images.githubusercontent.com/56588802/69335809-c849e800-0c5d-11ea-85d4-9e6f6e340160.png)

**Comment by sangwinc** [comment]
Yes, this is an issue.  Thanks for raising it.

In STACK version 1.0 (ancient history!) we used "JSMaths" to display mathematics.  This had the very nice feature of being able to put HTML form elements into an equation.  So, we could have inputs within a LaTeX formula.  Lovely....

This was lost when we moved to MathJax.  I have been asking the MathJax folk for years to support this, but alas it is a fringe issue for them, and probably has some complications.

So, to get the matrix input working at least at some level, we had to create a table with borders.  You can see how we did this here:
https://github.com/maths/moodle-qtype_stack/blob/master/stack/input/matrix/matrix.class.php#L224

This is, a "cludge". I would really appreciate help here in improving the display. If you are able to help, it would be much appreciated.

It would be worth checking again if MathJax support HTML input elements within the equations now.  If so, that might be one route. 

My priorities for the very near future is the release of V4.3, sorry.
Chris
