### ISSUE TITLE
Assessement of presenting a differential equation using diff

### ISSUE THREAD

**Issue by tkokkone** [maths/moodle-qtype_stack#527]
Hi,

Not sure if this is an issue with STACK or with my skills of using it. Please guide me to other forums if it is the latter.

I would like to use STACK for teaching students to solve numerically the governing groundwater flow equation. The first step is just to present it. So I would like to check that students have typed in the following equation

d2H / dx2 = -R/T

using diff, i.e. diff(H,x,2) = -R/T. Now apparently STACK assumes H to be a constant and simplifies its second derivative to zero. So 0 = -R/T is accepted as a correct answer and it is also shown as the model answer after the 'Check'  button has been clicked. What I would like is that STACK would accept diff(H,x,2) = -R/T and equivalent presentations (such as diff(H,x,2) + R/T = 0) as correct answers but nothing else. Is there a way to achieve this? I attached a Moodle XML respresentation of this question here.

Many thanks for any help! Cheers,

Teemu
[Groundwater_equation.zip](https://github.com/maths/moodle-qtype_stack/files/3874996/Groundwater_equation.zip)

**Comment by smborio** [comment]
There might be other ways of doing this but one solution could be to add a node to the potential response tree checking specifically if the student enters 0 = -R/T and mark it as incorrect. I hope this helps!

**Comment by sangwinc** [comment]
This is a very good illustration of the issue of how we deal with "nouns".

The command "diff(H,x,2)" is a command to actually do the differentiation.  It is a verb (to do).

We also need a command which represents (names) the derivative.  To do this the teacher should use
ta:noundiff(H,x,2)=-R/T;

See the documentation on Differential Equations.
https://stack2.maths.ed.ac.uk/demo2018/question/type/stack/doc/doc.php/CAS/Differential_equations.md

Please do contribute further examples.  If the docs are not clear, or do not cover the cases you want please let me know and I will improve the docs.

**Comment by aharjula** [comment]
Chris,

I think the actual issue here was not the nouns but this, which is why I instructed the author of this issue to ask about it here:

```
(%i2) simp:false;

(%o2) false
(%i3) ATAlgEquiv(0=-R/T,noundiff(H,x,2)=-R/T);

(%o3) [true,true,"ATEquation_sides",""]
```
The nouns should be fine in his logic the thing breaks is the unexpected equality in AlgEquiv.

**Comment by aharjula** [comment]
While this is something the author can handle by adding a separate test for that `0=R/T` it is something that one would expect the AlgEquiv test to already handle, therefore it feels to me like maybe something is broken? The presentation of the teachers answer is obviously a noun issue but the equality of every differential of unbound identifiers with zero is something else.

**Comment by aharjula** [comment]
Demonstration:
```
(%i2) simp:false;

(%o2) false
(%i3) ATAlgEquiv(0,noundiff(f,x,40));

(%o3) [true,true,"",""]
(%i4) f:x^434+x*4;

(%o4) x^434+x*4
(%i5) ATAlgEquiv(0,noundiff(f,x,40));

(%o5) [true,false,"",""]
(%i6) ATAlgEquiv(0,noundiff('f,x,40));

(%o6) [true,false,"",""]
```

**Comment by tkokkone** [comment]
Hi,

Thanks for the comments!

I am not sure how the work-around of checking separately for 0 = -R/T should work. Sure one can add another node in the potential response tree, but what should the Answer test be? If it is AlgEquiv nothing is in my mind gained as then also the correct answer (noundiff(H,x,2) = -R/T) would be assessed to be incorrect due the (undesired?) equality between 0 and noundiff(H,x,2). A string comparison sounds a bit risky, in particular as there are many algebraically equivalent ways of writing 0 = -R/T, e.g. R = 0 (which is also accepted as the correct answer when using AlgEquiv test on nonundiff(H,x,2) = -R/T).

Another issue is presentation of the corerct answer after the 'Check' button has been clicked. I have in 'Input: ans1' noundiff(H,x,2)=-R/T as the 'Model answer'. Now the correct aswer is shown as:

A correct answer is d2Hdx2=−RT, which can be typed in as follows: 'diff(H,x,2) = -R/T

While 'diff may be another way of writing noundiff, it will raise the following error if students try to use it when giving their asnwer:

Your last answer was interpreted as follows: 'diff(H,x,2) = -R/T
This answer is invalid.
Apostrophes are not permitted in responses.

This is a bit confusing although I can instruct beforehand students to use noundiff instead of 'diff.

Thanks again for any help!

Teemu

**Comment by aharjula** [comment]
As a side comment if this happens and I assume it happens in the Aalto MyCourses environment then we have 4.3 in play in the form it was late September and noun display may thus have issues. That equality issue however is present also in master and deserves some attention.

**Comment by aharjula** [comment]
Some preprocessing can be of use but you will need to deal with the nouns as well:
```
(%1) ans:subst('diff(H,x,2)=magic,'diff(H,x,2)=-R/T);
(%o1) magic = (-R)/T
(%i2) ans:subst('diff(H,x,2)=magic,0=-R/T);
(%o2) 0 = (-R)/T
(%i3) ans:subst(['diff(H,x,2)=magic,noundiff(H,x,2)=magic],0=-R/T);
(%o3) 0 = (-R)/T
```
Doing that in the feedback variables and the using AlgEquiv on the result should let one separate things. But again I feel like the test itself should be aware of this and provide more support for differential equations.

**Comment by sangwinc** [comment]
Just to let you know that I'm working on this issue currently, to fix it in v4.3.

In earlier versions we did not permit apostrophes in expressions.  Therefore, to give access to a "noun form" of the diff command, absolutely necessary for entering a DE, I added the parallel "noundiff" command.  (noundiff was also an opportunity to fine-tune the display, e.g. \frac{dy}{dx} not \frac{d}{dx}y)

From v4.3, we have Matti's new parser, we can be more selective in permitting apostrophes in expressions.  This allows us to use Maxim'a existing commands for 'diff(y,x).  My current thinking it is more natural to make use of the core Maxima syntax, and phase out noundiff.  I'm refactoring with this in mind.

However, the business of nouns is rather complex in itself.  ATAlgEquiv has for a very long time always evaluated noun forms, e.g.
https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stackmaxima.mac#L1212

In many situations where we want "Algebraic Equivalence" then, just as we want 1+1->2, we also want diff(x^2,x)->2*x.  We can't change Algebraic Equivalence without breaking a whole host of other things such as "true and false" being evaluated to "false".  If we preserve the noun forms, i.e. we don't evaluate nouns, then "and" will remain as a noun here.

We are probably going to need another answer test.  This will not evaluate nouns forms of functions, but will valuate verb forms, and will simplify algebraic expressions.  So, this will sit part way between "EqualsComAss" and "AtAlgEquiv".

I have been working on an entirely new design which lists each rule separately, and allows teachers to roll their own answer tests by selectively choosing which rules are to come into play.  If only we could start writing STACK from a blank sheet of paper, with a CAS of our own making....

**Comment by sangwinc** [comment]
I have been working on the nouns issue in v4.3, so I hope that is now fixed there.

I think a work-around for now is the following.

    ans1:'diff(y(x),x)+1 = 0;
    ansyx:subst(y,y(x),ans1);
    ansyx:ev(ansyx,y=y(x));

This has the effect of (safely in a two step process) in turning all "diff(y,x)" terms into "diff(y(x),x)" terms which will not be evaluated further whether or not the nouns are switched on.  Maxima can't further evaluate the derivative of the evaluated function y(x).

**Comment by sangwinc** [comment]
I would be very grateful if colleagues could provide some more examples of cases they would like to consider here before I write a new answer test which does "algebraic equivalence" without evaluating the nouns in an expression.

**Comment by smborio** [comment]
I'm not sure if these are relevant but I had similar issues with two concepts: sqrt(8) showing as 2^(3/2) and I'm not being able to keep it as a noun, and I'm using the sum function as part of student answers to express things as sums (nouns) and unless I turn simplification off they get evaluated. I managed to solve the second turning simplification off but with the first sometimes it's more complicated, particularly when dealing with complex numbers and modulus questions. I'll try to find some specific examples and add them here when I find a spare moment.

There were other cases as well which I will add when I find them as I cannot recall them off the top of my head. 

Thanks,

Santiago
