### ISSUE TITLE
plotting a graph (context: Graph Theory)

### ISSUE THREAD

**Issue by impemic** [maths/moodle-qtype_stack#528]
I'm teaching Graph Theory in academic course. I want draw, in a stack question vertices and edges, for example:
x1:makelist(cos(%pi/10+2*k*%pi/5),k,0,5);     #x-coordinates of a 5-vertices graph
y1:makelist(sin(%pi/10+2*k*%pi/5),k,0,5);      #y-coordinates
p1:plot([discrete,x1,y1],[x,-1,1],[y,-1,1],[style,points],[box,false],[axes,false]); #vertices
p2:plot([discrete,x1,y1]);    #edges for K5

How could I get both p1 and p2 in the same 2d-plot? Thanks

**Comment by sangwinc** [comment]
I've added some documentation to explain how, within the existing plot functionality, we can produce plots of simple graphs.

This could do with a lot more work, and as you will see, some convenience functions to stop duplication of code between questions.

This is an area where, having started this off, I'd really appreciate contributions from other users.
