### ISSUE TITLE
Some problems in documentation

### ISSUE THREAD

**Issue by lassikor** [maths/moodle-qtype_stack#529]
Hi,
I noticed some html problems in authoring guides (here in GitHub). The embedded videos and some other stuff like links to images are not working properly. You can see some of these cases in the image attached.
![auth1](https://user-images.githubusercontent.com/42375494/70035618-ded83380-15bb-11ea-9e74-728ee9d83ddf.jpg)

BR
Lassi Korhonen

**Comment by aharjula** [comment]
I don't think that the documentation on GitHub has ever been feature complete, although I wish it were. I have understood that the documentation is meant to be red through the Moodle installation and has special rendering logic there. Basically, `/question/type/stack/doc/doc.php/` as the address on your Moodle server.

**Comment by lassikor** [comment]
Of course, I just didn't get that. The pages are working correctly in our Moodle installation. This case can be closed. However, the text area in the case addressed by the image could be wider.
Sorry for the inconvenience :)

**Comment by aharjula** [comment]
Well that is one of those things one just needs to know... In any case I would be very happy if someone modified the filter that the Moodle side uses to render these so that it could work with GitHub compatible stuff and then turned these into a form that works in both.
