### ISSUE TITLE
Issues with UnitsSigFigs Answer Test with Negatives and Parentheses Placement

### ISSUE THREAD

**Issue by jmbragg** [maths/moodle-qtype_stack#530]
![image](https://user-images.githubusercontent.com/4606870/70530301-96bb9280-1b20-11ea-8bff-0df846645ca1.png)

Depending on the way a student uses parentheses near a negative sign and unit, they will be graded differently.  This is set to grade with UnitsSigFigs and [3,2] as the option.  Both answers are the same for this question and should be marked the same.  The first one is marked as failing the test, the second passes the test.

**Comment by aharjula** [comment]
#405 which is essentially this same issue is nearing a fix, well I hope so. The features in 4.3 should allow the safe extraction of the relevant numeric bit for the sigfigs logic. I am not sure if Chris already fixed (re-implemented this so that the context does not matter) this in that branch.

**Comment by jmbragg** [comment]
Wow.  It seemed familiar...  LOL.  Sorry for the noise.
