### ISSUE TITLE
Error "part: invalid index of list or matrix." on question test

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#531]
In the attached question (sorry for slight non-minimality), question test 3 fails, but the same input gets correctly evaluated if the same answer is entered in the question preview. Also the first two question tests evaluate correctly.

I guess the problem could be related to #86 .

[quiz-DiffEkv 2019-Export-20191218-0029.xml.zip](https://github.com/maths/moodle-qtype_stack/files/3975734/quiz-DiffEkv.2019-Export-20191218-0029.xml.zip)

**Edit:** I just upgraded to Stack 4.3A today.

**Comment by sangwinc** [comment]
Thank you very much for reporting this.

The problem was that state is now stored in the question which was contaminating from one test situation to another.  Please do continue to report strange problems, it is much appreciated.
