### ISSUE TITLE
More question test problems

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#533]
In a question test, I incorrectly get
`ATNumSigFigs(2.15, 75701719/35227192, 3) = [0, "ATNumSigFigs_WrongDigits. "];
`
but when I run the same in the STACK-Maxima Sandbox, I correctly get
`(%i29) ATNumSigFigs(2.15, 75701719/35227192, 3);
(%o29) [true,true,"",""]`

How can this be?

The question is here: 
[quiz-SannolStat 2020-Export-20191218-0053.xml.zip](https://github.com/maths/moodle-qtype_stack/files/3975782/quiz-SannolStat.2020-Export-20191218-0053.xml.zip)

**Comment by sangwinc** [comment]
This is now working in the STACK 4.3 development branch.

**Comment by alcarola** [comment]
It seems not, I did a git pull today and the problem is still there:
[root@stack stack]# git branch
  help
  list
  master
* stack4.3A

Running in the STACK-maxima sandbox
[ STACK-Maxima started, library version 2019121800 ] 
(%i1) ATNumSigFigs(2.15, 75701719/35227192, 3);
(%o1) [true,true,"",""]

I was not prompted to create a new optimized Maxima image after the git pull. Should I do that nevertheless? (It is a bit of work to get it running in the Maxima pool, so I don't do it unless the Healthcheck script says that I should.)

**Comment by sangwinc** [comment]
The problem in your question is that you are evaluating abs(SAns1) in the PRT.   This evaluation of the student's answer will strip off trailing zeros, which might be significant.  So, I've created a fix which will work when we have non-zero last digit this is still going to be a problem.

What would you like abs(-1.0000) to be?  It is currently 1.0 and not 1.0000.

**Comment by sangwinc** [comment]
Ok, the proposed fix breaks assessing sig figs when we have units.  This issue will have to remain unresolved for now.  Sorry.

**Comment by alcarola** [comment]
Thanks for pointing the abs problem out -- I would never have found this myself! I now eliminated the abs function and indeed the question now works according to the old question tests.

I guess most functions screw up the number of significant digits, but what surprises me is that this behaviour seems to have changed since the question was created?

For my part this issue can be closed, unless you had something in mind that you still wanted to fix at some point.

**Comment by sangwinc** [comment]
Thanks for confirming,

I think, in the past, the question would have looked like it worked in most cases, until you wanted to check trailing zeros...
