### ISSUE TITLE
(%i7) beta: wrong number of arguments. #0: detexcolor(ex=

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#535]
The attached question gives me the following error in the question preview; I am also unable to save the question in the edit form, with the same error next to the Question variables field:

(%i7) beta: wrong number of arguments. #0: detexcolor(ex=g(alfa,beta):=block(x:alfa*(1-1/beta[1]),for i from 2 thru length(beta) do x:x*(1-1/beta[i]),return(...) (stackmaxima.mac line 630) #1: stack_dispvalue(ex=g(alfa,beta):=block(x:alfa*(1-1/beta[1]),for i from 2 thru length(beta) do x:x*(1-1/beta[i]),return(...) (stackmaxima.mac line 113) #2: _CS2dv(_k=__s3,_v=g(alfa,beta):=block(x:alfa*(1-1/beta[1]),for i from 2 thru length(beta) do x:x*(1-1/beta[i]),return(...) (stackmaxima.mac line 503) -- an error. (%i8) (%o8)

I just upgraded to STACK 4.3A, but I had to increase the plugin version to 2019103100 manually, in /var/www/html/moodle/question/type/stack/version.php in order to get the STACK health check script not to complain on versions. How can I check that my STACK upgrade succeeded?

[quiz-Talteori-Export-20191218-1051.xml.zip](https://github.com/maths/moodle-qtype_stack/files/3977464/quiz-Talteori-Export-20191218-1051.xml.zip)

**Comment by sangwinc** [comment]
Thank you for taking the time to test STACK version 4.3A.  We have made a lot of progress, but we have some work to do.

Let me apologize for being lazy about the mis-matched version numbers.  If you have re-generated your Maxima image there is nothing to worry about. The error would be helpful if you have upgraded and not created the image, in which case the mismatch would be genuine.  It is spurious here.

I will fix that now.

**Comment by aharjula** [comment]
Can confirm that this happens on a correct installation. 

Seems like it tries to create a display-value of a function-definition which seems to break down in interesting ways. Maybe it shouldn't do that, it should not do any value retrieval for question-variables nor for feedback-variables, but maybe someone has needed them for debug or some other reasons. In any case you could try changing this line:

https://github.com/maths/moodle-qtype_stack/blob/stack4.3A/stack/cas/keyval.class.php#L116

to use the `stack_ast_container_silent`-class instead thus seeing if it fixes that issue.

**Comment by sangwinc** [comment]
The problem with your question is this function in the question variables.  If you change beta to beta2 as follows, then the question saves just fine.

`g (alfa,beta2) := block(x : alfa*(1-1/beta2[1]), for i from 2 thru length(beta2) do (x : x*(1-1/beta2[i])), return(x));`

**Comment by sangwinc** [comment]
Note, that in the new version of STACK, we now track information on names defined within Maxima, so we can have better control over the parsing.  E.g. here: https://github.com/maths/moodle-qtype_stack/blob/stack4.3A/stack/cas/security-map.json#L823

If this error is related to the new parser then Matti will be in a better position to comment why this is happening.

**Comment by aharjula** [comment]
So `beta` is a special identifier? And cannot be used as an argument in function-definition? Who knew... Or could this tie to some display-value generation bit, maybe related to `beta` the function triggering when you play with subscripts.

I doubt it's the parser, probably missing logic that may have previously stopped the function-definitions from being turned to display-values. If so then the keyval-class or cassession2 should check for it and stop the generation of display-values. Or maybe `beta` has become special during the same time we worked on 4.3 and this is unrelated.

**Comment by alcarola** [comment]
Thanks for suggesting the fix and confirming that my little hack did not introduce errors!

I should of course have guessed that beta may be special and tried changing that. Is there a clever way to avoid using reserved names other than just trying them in the sandbox and seeing if they are already defined?

Now this question is fixed and this issue can be closed for my part.

**Comment by aharjula** [comment]
Well now that we have that map of names and the ability to tag them with various metadata we could naturally add a separate validation that would check the arguments in function-definitions and error out in some sensible way if one uses `beta` or some other know trouble-maker. Trouble is that we do not know what makes `beta` so special, while we know that it is a function of more than one argument, so is `atan2` and that works just fine.

Well... should not be too difficult to test every identifier already present in the map. Hopefully, someone does it.

**Comment by sangwinc** [comment]
Thank you very much for reporting this problem.
