### ISSUE TITLE
Euler totient function

### ISSUE THREAD

**Issue by impemic** [maths/moodle-qtype_stack#536]
I am teaching now an academic course about Cryptography. I realized that the Maxima function "totient" is not supported in stack question, right? Is it possibile to support it? Thanks

**Comment by sangwinc** [comment]
This function is supported in the forthcoming v4.3.
https://github.com/maths/moodle-qtype_stack/blob/stack4.3A/stack/cas/security-map.json#L7423

**Comment by aharjula** [comment]
Chris, did you forget to push your change? It still reads as 'f' there.

On 26 Dec 2019 19:27, Chris Sangwin <notifications@github.com> wrote:

This function is supported in the forthcoming v4.3.
https://github.com/maths/moodle-qtype_stack/blob/stack4.3A/stack/cas/security-map.json#L7423

**Comment by sangwinc** [comment]
Thanks Matti
