### ISSUE TITLE
Reactive Power [VA] as Unit

### ISSUE THREAD

**Issue by jensfortmann** [maths/moodle-qtype_stack#537]
I try to teach my students the difference between active power (P)  with units  W, kW, MW on one side and reactive or apparent power (Q, S) with units VA, kVA, MVA.
In Stack,
- using 10e3*VA is interpreted as 10.000 * VA [which is what I would have expected]
- using 10*kVA leads to "unkonwn function kVA"

The same happens if I try to use MVA - unfortunately a common unit in power systems.
Could VA/kVA/MVA be implemented as units? 
Best regards, Jens

**Comment by sangwinc** [comment]
Jens,
Do we really need this?  We already define volts:
https://github.com/maths/moodle-qtype_stack/blob/stack4.3A/stack/cas/casstring.units.class.php#L88
and we define amps
https://github.com/maths/moodle-qtype_stack/blob/stack4.3A/stack/cas/casstring.units.class.php#L85

We can add this, but I'll need to take advice as to whether this leads to any conflicts with other notation.  I can't see any conflicts, but there may be some. No conflict, no problem!

**Comment by aharjula** [comment]
Chris,
The 4.3 single-char vars logic could also handle this, for it `kVA=kV*A` would just work as it would know that `kVA` is not a reserved id but both `kV` and `A` are. Problem is that the order of terms might not stay sensible i.e. that Ampere will probably move to the front of the expression. Also, the kerning will always be slightly different if we have those as multiplied terms.
From my point of view, the unit system will easily survive the addition of this unit as long as the unit system only works in a single direction i.e. just converts everything back to SI base units. However, if it ever needs to start to convert to the other direction, without explicit guidance, this will lead to problems as there will be multiple choices, well it already has those.
In any case, the unit system is in need of some work, it should have ways for defining units on the fly and more support for switching between various sizes of pints and the like. But I feel like we will need the new capabilities of the parser and the future compiling-system to build those.

**Comment by sangwinc** [comment]
Yes Matti, the "single char vars" was my first approach.  It did look odd, so if this causes no conflicts then we should add it.

**Comment by sangwinc** [comment]
Matti, any concerns if I merge this into the V4.3 release?

**Comment by jensfortmann** [comment]
Chris, 
thanks for implementing! I did not find problems so far.

**Comment by aharjula** [comment]
> Matti, any concerns if I merge this into the V4.3 release?

No objections, but I would eventually want the unit systemtto only provide the base and derived SI-units (well one should be able to select those other units as well but maybe not the full set of both at the same time) and specifically require authors to state if they want to add others. If that ever happens materials relying on the base set having this may be broken in an upgrade and be difficult to detect for automated fixing.

**Comment by sangwinc** [comment]
Thank you both for confirming.
I'll merge into the V4.3 release.
