### ISSUE TITLE
Maxima connection broken?

### ISSUE THREAD

**Issue by aacchhee** [maths/moodle-qtype_stack#538]
CASText failed validation when checking an answer to one of the model problems. 

Screenshot is attached:
<img width="2680" alt="STACK_issue" src="https://user-images.githubusercontent.com/59649991/71976769-6e09e400-3217-11ea-92f2-bf67c3c317d4.png">

Error message:
CASText failed validation. (%i4) STACK-OUTPUT-BEGINS> Error: Fast links are on: do (si::use-fast-links nil) for debugging Signalled by CONCATENATE. Condition in CONCATENATE [or a callee]: INTERNAL-SIMPLE-PROGRAM-ERROR: CONCATENATE [or a callee] requires less than sixty-eight arguments. Broken at CONCATENATE. Type :H for Help. 1 Maxima top-level 2 Maxima top-level 3 Maxima top-level 4 Maxima top-level 5 Return to top level. MAXIMA>> Error: Fast links are on: do (si::use-fast-links nil) for debugging Signalled by CONCATENATE. Condition in CONCATENATE [or a callee]: INTERNAL-SIMPLE-UNBOUND-VARIABLE: Cell error on QUIT: Unbound variable: Broken at CONCATENATE. 1 (abort) Return to debug level 1. 2 Maxima top-level 3 Maxima top-level 4 Maxima top-level 5 Maxima top-level 6 Return to top level. MAXIMA>>> NIL MAXIMA>>> TIMEDOUT

Your answer does not satisfy p(x0)=f0

.

Your answer does not satisfy p(x1)=f1

.

Your answer does not satisfy p′(x0)=0

.

Your answer does not satisfy p′(x1)=0

.

Your answer is plotted below, although part of your graph might appear out of range of the plot!

plot([pg,anspt],[x,(x0-2),(x1+5)],[y,-3,3])

**Comment by sangwinc** [comment]
Thank you very much for reporting this issue.

This is an issue with GCL on Maxima 5.38.1. Not on SBCL or CLISP.  We already have a failing unit test which reproduces this bug.

1) stack_cas_session2_test::test_scientific_notation
Failed asserting that '2.998e8' matches expected null.

/var/www/html/live2018/question/type/stack/tests/cassession2_test.php:1373
/var/www/html/live2018/lib/phpunit/classes/advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "stack_cas_session2_test" question/type/stack/tests/cassession2_test.php

**Comment by sangwinc** [comment]
Thank you very much indeed for reporting this issue.
