### ISSUE TITLE
Question tests interpreting expression differently to the question, with no simplification

### ISSUE THREAD

**Issue by timlowe** [maths/moodle-qtype_stack#539]
Hi,
In a question on surd rationalization (which has simplification off so I can give feedback in different forms of answer), I wanted to include question tests to test different  forms of the answer are being marked correct.

The attached trivial question has three versions of the teachers answer:
ta: (-1+sqrt(11))/10;
ta2: (-(1-sqrt(11)))/10;
ta3: -( (1-sqrt(11))/10);
which the question can display as intended.
Note ta2 is a fraction containing a negated numerator, and ta3 is a negated fraction.

However, when I include these answers as question tests, ta3 gets interpreted/rendered the same as ta2,  so I don't seem to be able to create a test for the ta3 form of the answer?

I thought there was no simplification of the question test input? I could well be doing something stupid though!

Best wishes,
Tim

[questions-MATHS-WS-OSEP-Question test issue demonstration-20200108-1157.zip](https://github.com/maths/moodle-qtype_stack/files/4035182/questions-MATHS-WS-OSEP-Question.test.issue.demonstration-20200108-1157.zip)

**Comment by sangwinc** [comment]
Tim,
Thank you for such a careful bug report.  Much easier to track down the issue.  This is a subtle (Maxima) unary minus problem with  -(a/b) being stored as -a/b which was subsequently interpreted as (-a)/b.

Sigh.
C
