### ISSUE TITLE
matrix+string: something wrong

### ISSUE THREAD

**Issue by impemic** [maths/moodle-qtype_stack#542]
Multipart question: the first answer is a matrix, the second one is a string.
If I do a preview (adaptive mode):
1. Once written the matrix elements, the validation message does not appears.
2. The first "check" shows just the validation message "Your answer was interpreted as follows..." but does not show correct/uncorrect.
3. A second "check" shows a correct checking for the matrix, but shows "uncorrect" for the string, that is still empty. 
![image](https://user-images.githubusercontent.com/56223576/72818038-13d33f00-3c6b-11ea-8e98-546ef315b472.png)

**Comment by timhunt** [comment]
This is a known bug. I am working on it.

**Comment by timhunt** [comment]
This should now be fixed in the 4.3 branch.
