### ISSUE TITLE
Problem with displaying a power of arctan and other inverse trigonometric functions.

### ISSUE THREAD

**Issue by ItSSt-here** [maths/moodle-qtype_stack#543]
It seems there is a problem to display a power of arctan(x) (and other inverse trigonometric functions).

Stack displays arctan(x) as \tan^{-1}(x) (why?).

So arctan(x)^2 is converted for display into \tan^{-1}^2(x) which is not valid in tex.

The problem is only with the display, maxima works fine.

Am I missing something? Is there a solution or workaround? I want to ask my students to find the derivative of (say) 1/arctan(x).

**Comment by sangwinc** [comment]
Yes, there is already a question level option (bottom of question authoring form) Inverse trigonometric functions which controls tan^{2}, atan or arctan.  I don't like tan^{-1} either as you point out, there is no sensible way to write the square of the value of the inverse tan.  Babbage complained about this in the 1830s but people still use it!  Also, you could set this option on the plugin config page (if you are a site admin) so all new questions start with this option as the default.

**Comment by ItSSt-here** [comment]
Thank you very much, I was not aware of this option.
