### ISSUE TITLE
Set test feedback (too much of feedback)

### ISSUE THREAD

**Issue by aacchhee** [maths/moodle-qtype_stack#545]
We are implementing tasks which involve set test. We want to have questions for training, but we do not want to tell the complete solution after the first attempt.

Set test is different from other tests in a way it tells you two things:
1. which extra (wrong) elements did a student propose 
2. which elements are missing.

1+2 contain full information about the solution, so any second and third attempt are turning meaningless. Another tests tell the student that something is wrong, but do not tell how to fix it, unless it is programmed in a response tree/hints.

Therefore I suggest to remove part 2 from the set test. An alternative could be to make a new very similar test SecretSet without part 2 to maintain backwards compatibility.

**Comment by smborio** [comment]
Hi, if you want to use the set test and avoid the automatic feedback you can simply select the Quiet option. The test will work exactly in the same way but the points 1 and 2 will not be there. You can then use PRTs to give the relevant feedback you might want. If you have an example of a question and the sort of feedback you would like to give I might be able to give you some guidance.

**Comment by aacchhee** [comment]
Yes, we have used Quiet option to resolve the issue. What I want: feedback from 1., but not from 2.

My point here is to have exactly the same behavior for all tests in a question with multiple input fields and tests. Another tests produced feedback that was considered usable for training without Quiet option.

To give the same feedback (that some elements are wrong) in PRT I would have to essentially reimplement the test, parse the set and so on. This is a repetitive job that is already done :)

**Comment by sangwinc** [comment]
I think you can use AlgEquiv for 1 (without quiet).  The reason for the (relatively new) sets test was to provide 2.  See this test case: https://github.com/maths/moodle-qtype_stack/blob/master/tests/fixtures/answertestfixtures.class.php#L203

Please confirm if this works, and if so close the issue.
