### ISSUE TITLE
Simple Table-Type response

### ISSUE THREAD

**Issue by jensfortmann** [maths/moodle-qtype_stack#548]
I am looking for a simple table type of question/answer sheet, much in the way as it would be seen on a normal paper or pdf:
---------
GeneralQuestion Student Answer 	Interpreted as		OK
1) Q1		   [    ]		        [     ]			        [   ]
2) Q2		   [    ]		        [     ]			        [   ]
3) Q3		   [    ]		        [     ]			        [   ]
----
If I use for example:
---
A) Calculate active \(P\) at nominal operation .
\(P\)	\(=\)	[[input:ans1]]		[[input:ans2]] 	 
 	 	[[validation:ans1]]     [[validation:ans2]]
---
once the student types '100' as example in the first answer, the table setup is 'crashed' adding about 10 more lines with a feedback  contining the german version of 'studentValidation_yourLastAnswer'
---

Ihre letzte Antwort 
wurde 
folgendermaßen 
interpretiert:

100

----
Instead of what I would prefer:
--
GeneralQuestion Student Answer 	Interpreted as		OK
1) Q1		   [  100  ]		        [    100 ]			[   ]
---
So: Is there a way to add a single table heading: "Interpreted as" instead of having every single anser modified with the long text string "Your last answer has been interpreted as xxx"? 
Instead of  a text box of about 20x8 characters, simple feedback of the interpreted value would be great. 
I did not find anything in the documentation - is there a simple way to achieve this?
It would make it easier for students to look at intermediate or previous results without having to scroll up and down a screen filled up with redundant comments.
Jens

**Comment by sangwinc** [comment]
Jens,
Yes, this is a very sensible use case. 

1. You can switch off the validation feedback, which will "work" for now, I think.  Inputs "require validation" to no, and "show feedback" to no.
2. Stack v4.3, will have an alternative "compact" feedback, which will show the student's answer without the sentence "your last answer was".  We have a release candidate in the "dev" branch.
3. Matti is working on "inputs2" which will have a lot of more interesting features for entering tables of numbers.  Not sure of the proposed timescale here.

**Comment by aharjula** [comment]
To manage expectations I have to say that inputs2 will need to prove itself in Stateful before we begin the massive task of rewiring STACK around it. Also it would greatly benefit from having CASText2 and compiled+cached PRTs integrated before it. Given how long it took to integrate cassession2 into the system don't expect this to happen this year. Also inputs2 might be something for STACK v5.

**Comment by jensfortmann** [comment]
Chris, 
thanks for the fast feedback.
1. Option 1, settig (require validation)  to no [...] leads to no student feedback at all. Keeps the formating, but not so nice for students not familiar with the moodle syntax.
2. Option 2 "compact" feedback would be a great step if it works as described.
