### ISSUE TITLE
Coding error received on bulk testing questions in a course: inconsistent placeholders

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#551]
Thanks for looking into my other issues! While looking into them, I got a coding error, when bulk testing questions. Here is the developer-level error log:

Coding error, must be fixed by developer: Inconsistent placeholders.

```
    line 62 of /question/type/stack/renderer.php: coding_exception thrown
    line 388 of /question/engine/renderer.php: call to qtype_stack_renderer->formulation_and_controls()
    line 109 of /question/engine/renderer.php: call to core_question_renderer->formulation()
    line 113 of /question/behaviour/behaviourbase.php: call to core_question_renderer->question()
    line 861 of /question/engine/questionattempt.php: call to question_behaviour->render()
    line 459 of /question/engine/questionusage.php: call to question_attempt->render()
    line 344 of /question/type/stack/stack/bulktester.class.php: call to question_usage_by_activity->render_question()
    line 175 of /question/type/stack/stack/bulktester.class.php: call to stack_bulk_tester->qtype_stack_seed_cache()
    line 75 of /question/type/stack/bulktest.php: call to stack_bulk_tester->run_all_tests_for_context()
```

**Comment by sangwinc** [comment]
Ok, can I ask you to edit the question and try to save it.  You should get a sensible error message at that point.  The idea is that broken questions should not be saved, but once saved we do not regularly re-validate them as this is an expensive process.

For the bulk test we pull something out of the database and try to use it, hence the exception.

**Comment by alcarola** [comment]
Indeed, this solved the problem. Thanks!
