### ISSUE TITLE
ATDecimalPlaces broken?

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#553]
Hi,
I have a bunch of questions using ATNumDecPlaces which used to work but presently all fail with a message like

> The answer test failed to execute correctly: please alert your teacher. For ATNumDecPlaces the test option must be a positive integer, in fact "4" was received. 

In the automatic question testing, I get text in the style of

> ATDecimalPlaces(0.1153, %e^-(54/25), 4) = [0, "ATNumDecPlaces_STACKERROR_Option."];

Running the same command in the STACK-Maxima sandbox, I get
``(%i4) ATDecimalPlaces(0.1153, %e^-(54/25), 4);
(%o4) ATDecimalPlaces(0.1153,%e^-(54/25),4)``

but I expected something more along the lines of

``(%i3) ATAlgEquiv(true, true);
(%o3) [true,true,"ATLogic_True. ",""]``

Concerning #481, I checked, that the call to the test just has a hard-coded digit 4 in the parameter box of the test, not a string or anything like that.

**Comment by sangwinc** [comment]
Ok, could you email me a question and I'll fix this for you?
