### ISSUE TITLE
Failure to include new input on validation.

### ISSUE THREAD

**Issue by AslakTon** [maths/moodle-qtype_stack#554]
It seems STACK fails to update values in certain cells after the student inputs a new value in said cell.
The following pictures expains the issue:
![0e61c62515](https://user-images.githubusercontent.com/48435289/73759441-44879e00-476c-11ea-87a4-b916ff586293.png)
Here the answer in 1b) [1, 2] is incorrect, the answer should be [1, 1]. However after running a check on the answer, it does not give feedback on the answer as it should do. 
![9c842b0df6](https://user-images.githubusercontent.com/48435289/73759597-7862c380-476c-11ea-8058-99632f70af7d.png)
Here i first gave the right answer of [1, 1] and then changed the answer to [1,2] and rechecked. STACK did not give me feedback on the wrong answer. However, it would give the correction if i tried to check again.

![6f639b2fc8](https://user-images.githubusercontent.com/48435289/73765774-515cbf80-4775-11ea-8727-3024a5dc1764.png)

This issue was also previously reproduceable in the opposite case, where i first gave a wrong answer, and then gave the right answer. However, i cannot reproduce that issue myself today. While i cannot reproduce this bug right now, it has been reported to me trough students taking a test at NTNU Gjøvik, as well as Students taking the same test ay NTNU Ålesund.

**Comment by sangwinc** [comment]
Very sorry about this.

Please can you confirm what version of STACK you are using?  (Go to the documentation page for your own server, e.g. my docs are here: https://stack2.maths.ed.ac.uk/demo2018/question/type/stack/doc/doc.php/ ) and look at the bottoms of the page.  This tells us which version you are using.

I suspect this is a bug with the instant validation and matrix inputs which we fixed last week.  You are also welcome to email me a question (C.J.Sangwin@ed.ac.uk) privately and I'll look into it for you.

Chris

**Comment by AslakTon** [comment]
We are currently running on version 2019121800. It may be a patched issue by now then, I'll bring forward this information to the maintainers of our server.

**Comment by timhunt** [comment]
I am pretty sure that what you report here is something I fixed a couple of weeks ago.

**Comment by AslakTon** [comment]
I'll encorage an update of our server and assume that it fixes the problem. Will report if the issue still persists.
