### ISSUE TITLE
Option for "show the validation" got wrong german translation

### ISSUE THREAD

**Issue by nfa019** [maths/moodle-qtype_stack#559]
I use Stack in German and found that

"yes, without variable list" is translated into "Nein, ohne Variabelliste", what is obiously wrong.

At least, the "Nein" should be a "Ja" :) 

Instead of "Variabelliste", I would prefer "Variablenliste".

**Comment by sangwinc** [comment]
Thank you very much indeed for contacting us.  I'm sorry the German translation isn't correct.   Moodle has a whole, separate, translation mechanism and as the plugin developers we are very separated from all this.  The separation of development and translation has a lot of advantages, including the amazing way translations appear "as if by magic" without us having to include and maintain language string files for each language and each plugin.

The down-side is that this isn't the place to fix the problem. Sorry. 
https://docs.moodle.org/dev/Translating_plugins

The place to look is https://lang.moodle.org/  

Many of the translators don't actually use the plugins they translate, so they may not see the language strings in context.  Anyway, I'm sure the German translators will welcome suggestions for improvements.  

I'm going to close this issue, but if you have any problems contacting the translators through AMOS please let me know and I'll help investigate.
Chris
