### ISSUE TITLE
Syntax-Comment with units.md interpreted as input

### ISSUE THREAD

**Issue by jensfortmann** [maths/moodle-qtype_stack#561]
If using the "units.md" function for inputing value + unit, a Syntax comment is interpredet as input.

Example:
In the answer section, the Syntax comment "Value and unit"  has been added.
No matter how "Hint attribute" is selected ("value" or "placeholder"), the text "Value and unit" needs to be deleted manually to enter an answer. 
The code:

\(I_{A}\) | \(=\) | [[input:ans31]]
-- | -- | --
  |   | [[validation:ans31]] [[feedback:prt31]]

leads to 

I_A  | =| Value and unit
-- | --| --

with " Value and unit" not beeing grey and in the background but as predefined answer. 

Best regards,
Jens

**Comment by sangwinc** [comment]
Sorry about that.  Thank you for reporting this bug.
Chris
