### ISSUE TITLE
An issue with question text parser: LaTeX is not being called

### ISSUE THREAD

**Issue by aacchhee** [maths/moodle-qtype_stack#563]
The parser does not recognize a part of the question as LaTeX, see the screenshots. 

The reason for this sits in the line with [[input:ans11]][[validation:ans11]][[feedback:prt6]].
When I moved the integral above it -- above part f., it got rendered, as shown on the screenshot. No LaTeX code below the line was recognized and rendered.

The problem is solved by first moving the above-mentioned line to the end of the question, saving the question, then reopening the question and moving the line back. Now 
everything is rendered, however, the behavior on the screenshot does not look correct for me.

![stack_latex_issue](https://user-images.githubusercontent.com/59649991/75380167-d51e4d80-58d6-11ea-8154-ac340305c0ee.png)
![stack_latex_issue2](https://user-images.githubusercontent.com/59649991/75380170-d64f7a80-58d6-11ea-8e9c-565a6bc1fda8.png)

**Comment by aacchhee** [comment]
There is something here. The issue keeps coming, see attachment. Rendering is proper when I open just the question from the question bank. If I run a quiz attempt, LaTeX is not rendered properly.

![STACK_tex_2quest](https://user-images.githubusercontent.com/59649991/76765244-5e1dfb80-6796-11ea-918d-155b7e07618d.png)
![STACK_tex_2rend](https://user-images.githubusercontent.com/59649991/76765245-5eb69200-6796-11ea-999f-e1fb018618a1.png)

**Comment by sangwinc** [comment]
Can you have a look at your raw HTML with the raw mode in the editor?  Sometimes rubbish in the HTML stops MathsJax from processing the the rest of the maths in a div.

Chris

**Comment by aacchhee** [comment]
Looks clean. If there would be HTML garbage, why would the question when opened from question bank look as it should? If I remove the line with input and validation, things get rendered.

Deretter kan man uttrykke \(r\) og \(s\) som funksjonene av \(b\) og \(c\). Multipliser:<br></p><p><span>[[input:ans1]] [[validation:ans1]]</span></p><p></p>Sett inn \(x=0\). Hvordan avhenger da \(c\) av \(r\) og \(s\)?

**Comment by sangwinc** [comment]
Ok, if you email me the question privately then I will take a look.
Chris

**Comment by aacchhee** [comment]
Hi,
we have been testing this within our group. Some people get it right, I get it wrong. One of our TA's reported that he observed a somehow similar issue in jupyter. We were thinking that this behavior might be due to some issues in the browser, but I get it reproduced both in iexplore and in firefox. 

The question is attached here.
[questions-IMAG2021 2020V-Oppgave 4.2.30-20200318-1934.zip](https://github.com/maths/moodle-qtype_stack/files/4350727/questions-IMAG2021.2020V-Oppgave.4.2.30-20200318-1934.zip)

**Comment by aharjula** [comment]
Quick test, remove the `<span>` wrapping from around `<span>[[input:ans1]] [[validation:ans1]]</span>`. Also from the next one...
The problem could be that the validation-blocks are spans and wrapping them in more spans can cause trouble for various Moodle filters that do not really parse things.
In addition to this, it is important to check the ordering of one's filters. Multi-lang at the top, possible HTML-tidy before possible JSXGraph and MathJax as the last. Also, are there some other filters active that could affect this?

Now if validation blocks were not spans things might be simpler, but pretty much every type of element has some meaning outside STACK that will cause conflicts.

**Comment by aacchhee** [comment]
We had a few more occasions of this today. Removing a <span> tag manually in HTML mode removes problems. I would be though nice to avoid this manual editing...  :)

**Comment by aharjula** [comment]
Ohh, how much simpler the world would be if we did not have those WYSIWYG-editors. Most serious authors I know switch their Moodle text-editor to plain-text and just write the HTML themselves, typically leads to much cleaner layout at the same time. Most importantly, absolutely no `spans` magically appear to mess things up, when the tool does not try to "help".

**Comment by aacchhee** [comment]
Hi guys,
this time the issue comes when there are no spans at all in the question.

[questions-IMAG2021 2020V-Oppgave 4-20200406-1515.zip](https://github.com/maths/moodle-qtype_stack/files/4438578/questions-IMAG2021.2020V-Oppgave.4-20200406-1515.zip)
![stack_nospan_issue](https://user-images.githubusercontent.com/59649991/78562637-ff3e2600-7819-11ea-950e-77a60e52ad86.png)
![stack_nospan_issue2](https://user-images.githubusercontent.com/59649991/78562640-ffd6bc80-7819-11ea-9fa9-876caac7fc5d.png)

**Comment by aharjula** [comment]
Chris, seems like that equiv-input validation wraps stuff in multiple spans which might mess things after a check button press, even if it works before that. Could tie to those inputs separately from question-text patches.

**Comment by sangwinc** [comment]
Thank you for pursuing this.  I think the problem is caused by the paragraph tag here
https://github.com/maths/moodle-qtype_stack/blob/master/stack/input/inputbase.class.php#L1195
which ends up inside a span tag for equiv inputs.  The paragraph gets spat out, and mathjax breaks.
For now, just edit the question to not show the variables in the student's answer for that one input.  I'll fix the issue.

**Comment by sangwinc** [comment]
Thank you very much for persevering with this, and for your example question.  Much easier to track down the problem with an example.

**Comment by aacchhee** [comment]
I'm testing now multilang with a few questions from Abacus. It seems that I have the same issue as before with MathJax due to span-tags. This time though a simple solution with removing spans removes also translations...

![multilang1](https://user-images.githubusercontent.com/59649991/107765309-dd62d900-6d31-11eb-853e-fe51146e8c7a.png)
