### ISSUE TITLE
Automated assessment of graph sketching

### ISSUE THREAD

**Issue by C0untC0unt** [maths/moodle-qtype_stack#565]
I've been working on my Bachelor thesis (together with Tobias Mai from Paderborn) concerning automated assessment of students' freehand graph scetches. I'd like to contribute some code into a maxima-library so we don't have to duplicate complex code between questions. Eventually it might help to have a supported input type.

What is the best way to proceed?

**Comment by sangwinc** [comment]
Alex, 

Thank you for posting online.  I would really welcome your contribution to STACK. 

We already have your conference paper here: https://github.com/maths/moodle-qtype_stack/blob/master/doc/content/2018-proceedings/mai_tobias_2019_2582427.pdf
So other people will be able to get a good idea of what you mean.

For now, we can talk in person and decide how to proceed. 

Chris

**Comment by smborio** [comment]
Hi Alex, As per my email if you could start by translating the question to English it'd be great. Happy to work on generalising assessment parameters and working on randomisation aspects.
Thanks,
Santiago

**Comment by sangwinc** [comment]
A number of people are working graph sketching, but we've made no direct progress with this particular issue so I'm closing it for now.
