### ISSUE TITLE
ATUnits_units_match test fail

### ISSUE THREAD

**Issue by tdjones** [maths/moodle-qtype_stack#566]
Running tests in 3.8.1 with stack version 2019121800
2 Tests out of all tests fail.
First Question: 
Answer Test: UnitsStrict
Student Response: -(36*Kj)/mol
Teacher answer: -36*Kj/mol
Options: 2
Feedback: Your answer contains the wrong number of significant digits.
Answer note: ATUnitsStrictSigFigs_WrongDigits. ATUnits_units_match.
ATUnitsStrictSigFigs(-(36*Kj)/mol, -36*Kj/mol, 2);

Second Question: 
Answer Test: Equiv
Student Response: [a^2=b nounand b^2=a, b=a^2 nounand a^4=a, b=a^2 nounand a^4-a=0, b=a^2 nounand a*(a-1)*(a^2+a+1)=0, b=a^2 nounand (a=0 nounor a=1 nounor a^2+a+1=0), (b=0 nounand a=0) nounor (b=1 nounand a=1)]
Teacher answer: []
Options: [assumereal]
Feedback: 
Answer note: ATEquiv([a^2=b nounand b^2=a, b=a^2 nounand a^4=a, b=a^2 nounand a^4-a=0, b=a^2 nounand a*(a-1)*(a^2+a+1)=0, b=a^2 nounand (a=0 nounor a=1 nounor a^2+a+1=0), (b=0 nounand a=0) nounor (b=1 nounand a=1)], [], [assumereal]);

**Comment by aharjula** [comment]
Thank you for reporting this. However, that is an "old" version of STACK, and things may be different in the development version. Also, this is an issue with STACK+Maxima so it would be very helpful to know which Maxima version (also which LISP it is running on: GCL, CLISP, SBCL etc...) is in use.

**Comment by tdjones** [comment]
Hi Aharjula,
Maxima 5.41.0
I don't know how to show the lisp version tbh.
To my knowledge this is the latest released version of stack according to the moodle plugin website. (4.2.2 for Moodle 3.0+). Unless you are specifically referring to the latest release being behind the current development head.

Thanks!

**Comment by sangwinc** [comment]
Also, different versions of Maxima put brackets in different places!  We will support Maxima 5.41.0, so thanks for the report.
