### ISSUE TITLE
After Moodle update STACK can't open a CAS process (error stack_cas_connection)

### ISSUE THREAD

**Issue by azampa** [maths/moodle-qtype_stack#567]
Recently I upgraded Moodle to version 3.8.2 from version 3.1.2 (with an intermediate step to 3.2.9). I upgraded to the latest version of STACK and of the correlated question behaviours. I set platform type to Linux in order to rebuild the optimisation of maxima, but the healtcheck script immediately ends (after checking MathJax) with the error stack_cas_connection. I'm using Maxima 5.38.1.
I tried different solutions:

- leaving blank option _maximacommand_

- setting _maximacommand_ option to **/usr/bin/maxima**

- setting _maximacommand_ option to **/usr/lib64/maxima/5.38.1/binary-clisp/lisp.run -q -M /usr/lib64/maxima/5.38.1/binary-clisp/maxima.mem**

always ending with the same error.
At the level of command line, in the server, both last two options correctly start Maxima, so I can't understand the origin of this failure.
Since in the moodle.org site STACK is reported to be compatible up to version 3.6, is this a problem of compatibility?
Regards

Alessandro Zampa

**Comment by timhunt** [comment]
Can you try setting Moodle debugging setting (Admin -> Development -> Debugging) to Developer level temporarily, to see if that gives any more info in the error message.

**Comment by azampa** [comment]
After setting Developer level I get the following

**Debug info:**
Error code: exceptionmessage

**Stack trace:**

- line 63 of /question/type/stack/stack/cas/connector.unix.class.php: stack_exception thrown

- line 72 of /question/type/stack/stack/cas/connector.class.php: call to stack_cas_connection_unix->call_maxima()

- line 286 of /question/type/stack/stack/cas/connectorhelper.class.php: call to stack_cas_connection_base->compute()

- line 316 of /question/type/stack/stack/cas/connectorhelper.class.php: call to stack_connection_helper::stackmaxima_nocache_call()

- line 155 of /question/type/stack/healthcheck.php: call to stack_connection_helper::stackmaxima_genuine_connect()

**Comment by sangwinc** [comment]
I did try out the latest STACK on Moodle 3.8 very recently.  Could you email me privately, and include your healthcheck script and I'll get onto this tomorrow (Wed) for you.  I will help sort this out.
Chris

**Comment by timhunt** [comment]
Open University Moodle development (not live use yet) has moved on to Moodle 3.8(.2) and we are not seeing any problems.

**Comment by sangwinc** [comment]
Thanks for the Skype call.  I'm 99% sure you need to install Maxima on your server.
