### ISSUE TITLE
What would be the best way of controlling 'parsercacheinputlength' when unit-testing

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#571]
I happened to need to run unit-tests that had nasty amounts of parsing and noticed that the new cache in the parser was largely not in use in most tests that repeated the same strings. What would be the best way of setting up ones unit-testing config so that `parsercacheinputlength` would be smaller maybe even `1`? Do we need to build the same kind of logic as with the DB-caching configs? The default `50` just is so much larger than most test-cases.

Also, I have the disk and the memory, how do I trade them for speed here, can I make it remember those caches over phpunit runs?

**Comment by timhunt** [comment]
Well, to be more accurate: Moodle purges all caches between each unit test, to ensure each test is independent of the others.

This si the right thing to do. The only down-side is performance.

**Comment by aharjula** [comment]
Feared that we have something like that in play, so if I want to do this I would need to build and configure a special cache provider that would not respect those purge commands. Not worth the effort.

**Comment by timhunt** [comment]
If you want a quick and dirty hack to speed things up while you are working things, you could try going into lib/phpunit/classes/util.php and commenting out the line that clears the caches. That is probably the line self::reset_dataroot();

Obivously, when you are finished, you should do a final run with that restored to normal.
