### ISSUE TITLE
Plot directed graphs

### ISSUE THREAD

**Issue by hwesterholt** [maths/moodle-qtype_stack#572]
I've checked out the docs for [plotting graph-theory related material](https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/CAS/Plots.md#graph-theory) and am aware of Stack's current limitations regarding this matter (still an amazing piece of software). Is there maybe some way to plot digraphs with the methods and packages that are currently part of Stack?

**Comment by sangwinc** [comment]
I'm not aware of anything.  I do document tips like this, as you have found.  Could you investigate options and let me know?   If you can find something, I'll add an example to the docs.  Javascript may also be an option.  E.g JSXGraph.

**Comment by aharjula** [comment]
If I recall correctly there is a Maxima library but it did some very odd file-based operations and syntax tricks which do not work with the way STACK wants to keep Maxima safe and contained.

Back in the STACK 1.X days we had a CASText block for running DOT and other Graphviz definitions to generate graphs. Naturally, there is no reason why we could not have such again, although if one would go for such the decision would be between requiring the server to have Graphviz or doing the drawing in JavaScript on the client-side. The latter option might integrate better to some sort of interaction elements although those would be difficult to define in any case.
This actually works but could be a bit overpowered tool to load for just some plots: 
https://github.com/magjac/d3-graphviz

**Comment by sangwinc** [comment]
Yes Matti,
The "graphs" package for Maxima is excellent, and would be very useful.
http://maxima.sourceforge.net/docs/manual/de/maxima_50.html
I investigated this thoroughly a couple of years ago at the request of a colleague here in Edinburgh.  

As you say, it does some very strange read-write operations.  Worse, it is incompatible with the current API which STACK uses to communicate between PHP and Maxima.  

The following illustrates the immediate problem,
```
load (graphs)$
g : create_graph([1,2,3], [[1,2], [2,3], [1,3]])$
string(g);

"?GRAPH\(3\ vertices\,\ 3\ edges\)"
```

The package will need some work so that "string" outputs an object we can store and put back into Maxima.  This is not impossible to do, (beware large graphs....) but needs work.  It is not simply a case of "load(graphs)", check and add the graphs and "Bob's your uncle" (as they say in England), i.e. we are good to go.

Since I investigated this before, I'm recording the outcome here to save other people time in the future!

**Comment by hwesterholt** [comment]
Thank you both for all the advice, suggestions, and work-arounds so far!

If using the "graphs" package is out of the question for now (I would be willing to contribute in the future if my workload allows it) would the same apply to the "draw" package? I know that it is currently not available in STACK but the arrow head feature for vectors described here (e,g, on page 18) looks like a possible workaround:
[http://www.austromath.at/daten/maxima/zusatz/Graphics_with_Maxima.pdf](http://www.austromath.at/daten/maxima/zusatz/Graphics_with_Maxima.pdf)

I am certain that there are good reasons for this package's absence but I wanted to ask either way ... for now, I will give JSXGraph a go

**Comment by sangwinc** [comment]
I did look at draw some years ago.  The routine for plot is quite complicated, and there is a chain of events to get a file back through the system and onto a user's screen.  I didn't really want to have to support that chain in two different places!

Have you looked as JSXGraph?  That might be a better option, in that the nodes of your graph could then potentially be dragged by students.   I've had a look at the examples
https://jsxgraph.uni-bayreuth.de/wp/about/index.html
but nothing immediately springs to mind.  I can't find a JSXGraph library for doing this immediately.

Would JSXGrpah be useful?

**Comment by hwesterholt** [comment]
I think that JSXGraph should do the trick, but I can currently only plot parts of my graph.

Entering this MWE in the question text via the HTML editor
```html
[[jsxgraph]]
  // boundingbox:[left, top, right, bottom]
  var board = JXG.JSXGraph.initBoard(divid, {boundingbox: [-1, 5, 7, -5], axis: false, showCopyright: false});
  var a = board.create('point', [0.0, 0.0]);
  var b = board.create('point', [2.0, 2.0]);
  var c = board.create('point', [2.0, -2.0]);
  var d = board.create('point', [4.0, 2.0]);
  var d = board.create('point', [4.0, -2.0]);
  var f = board.create('point', [6.0, 0.0]);
  var ab = board.create('arrow', [a, b]);
  var ac = board.create('arrow', [a, c]);
  var bc = board.create('arrow', [b, c]);
  var bd = board.create('arrow', [b, d]);
  var be = board.create('arrow', [b, e]);
  var cd = board.create('arrow', [c, d]);
  var ce = board.create('arrow', [c, e]);
  var df = board.create('arrow', [d, f]);
  var ed = board.create('arrow', [e, d]);
  var ef = board.create('arrow', [e, f]);
[[/jsxgraph]]
<p>[[input:ans1]] [[validation:ans1]]</p>
```
produces a plot in which only four out of the expected ten edges are drawn:
![screenshot](https://user-images.githubusercontent.com/62615938/79891717-b08bb100-8401-11ea-85a3-5ed44de11a01.png)

Changing the drawing order by swapping some lines in the above code has confusing consequences: sometimes other edges are drawn, sometimes fewer edges are drawn, sometimes the entire plot goes missing  ... can you tell me what I did wrong?

On another note, is there any way to keep the HTML code formatted the way it is after saving? I have observed that saving the question adds and removes line breaks somewhat arbitrarily in both the WYSIWYG and HTML editors. Sometimes, this even occurs in the middle of variable declarations (see below). While this does not seem to be related to my problem (first line break occurs long before plot elements go missing) I was just wondering if this can this be avoided as it makes editing the question text more tedious than it should be.

Before saving:
![Nicely formatted question text](https://user-images.githubusercontent.com/62615938/79894115-483ece80-8405-11ea-85b6-4f97ab2a76f9.png)
After saving:
![Ugly question text](https://user-images.githubusercontent.com/62615938/79894167-57be1780-8405-11ea-9add-cf8657170671.png)

**Comment by aharjula** [comment]
Three rules of writing scripts in Moodle:
 1. Always switch your text-editor to the plain text editor in the user preferences. The source view in the WYSIWYG editors just does not work as the editor will helpfully clean stuff.
 2. When editing set the "formatting" option to raw HTML-formatting. All others will cause trouble.
 3. Assume that no line change ever survive import/export, so do not write line-comments `//` instead use block-comments `/* ... */` and remember to use semicolons. This applies to that last screenshot.

**Comment by hwesterholt** [comment]
1. I can't find the text-editor option in my user preferences, otherwise I would have switched to plain text a long time ago :( 
2. I should have been clearer on that. I have been using the HTML formatting option the entire time, but as I cannot set my editor options (see above), the editor defaults back to WYSIWYG whenever I save or reload the page. This is when the formatting breaks.
3. That one's on me ... I usually use `/* ...*/`for block comments (also helpful for debugging), but had some leftovers from when I copied the JSXGraph example from this [STACK help page](https://stack2.maths.ed.ac.uk/demo2018/question/type/stack/doc/doc.php/Authoring/JSXGraph.md). I'll contact the authors and let them know.

**Comment by sangwinc** [comment]
I think you are refering to a point "e", e.g. in the line
`var be = board.create('arrow', [b, e]);`
but you didn't define a point "e" so JS gives up!

This works fine...

```
[[jsxgraph]]
  /* boundingbox:[left, top, right, bottom] */
  var board = JXG.JSXGraph.initBoard(divid, {boundingbox: [-1, 5, 7, -5], axis: false, showCopyright: false});
  var a = board.create('point', [0.0, 0.0]);
  var b = board.create('point', [2.0, 2.0]);
  var c = board.create('point', [2.0, -2.0]);
  var d = board.create('point', [4.0, 2.0]);
  var d = board.create('point', [4.0, -2.0]);
  var e = board.create('point', [6.0, 0.0]);
  var ab = board.create('arrow', [a, b]);
  var ac = board.create('arrow', [a, c]);
  var bc = board.create('arrow', [b, c]);
  var bd = board.create('arrow', [b, d]);
  var cd = board.create('arrow', [c, d]);
  var de = board.create('arrow', [d, e]);
[[/jsxgraph]]
```

**Comment by aharjula** [comment]
In Moodle the editor preferences should be present on the `/user/preferences.php` page or directly through `/user/editor.php`, those addresses are in relation to your Moodles root... From there you should be able to change the editor unless someone has specifically disabled editors in the Moodle, it will change all text-editors for yuour user-account so maybe you'll need to switch it as needed.

**Comment by aharjula** [comment]
>     2. I should have been clearer on that. I have been using the HTML formatting option the entire time, but as I cannot set my editor options (see above), the editor defaults back to WYSIWYG whenever I save or reload the page. This is when the formatting breaks.

There are multiple ways to interpret the statement about HTML-formating when dealing with the WYSIWYG editor the source editor is something but it does not equal to Moodle text-formatting that gets applied to most things no matter what editor is used to write the content. When one has the plain text editor active then Moodle will actually ask (show the option for formatting) how to format the content and the options range from interpreting and rendering as Markdown to direct output i.e. HTML-format.

What you describe sounds like the normal "helpful" behaviour of the WYSIWYG-editor, the trouble with that is that when the WYSIWYG editor loads/saves content it tries to beautify it and typically damages any scripts or pre-formatted content while doing it.

**Comment by hwesterholt** [comment]
@sangwinc well ... this is awkward. Very awkward indeed. Thank you, I shall go and hang my head in shame.

**Comment by sangwinc** [comment]
Don't worry!

What about the following?

Question variables

```
pts: [[0.0,0.0],[0.0,1.0],[1.0,0.0],[1.0,0.5]];
edges:[[0,1],[0,2],[1,3]];
```

Then in your question

```
[[jsxgraph]]
  /* boundingbox:[left, top, right, bottom] */
  var board = JXG.JSXGraph.initBoard(divid, {boundingbox: [-1, 5, 7, -5], axis: false, showCopyright: false});
  var pts = {#pts#};
  var boardpts = new Array();
  var arrayLength = pts.length;
  for (var i = 0; i < arrayLength; i++) {
    boardpts.push(board.create('point', pts[i]));
  }

  var edges = {#edges#};
  var boardedges = new Array();
  var arrayLength = edges.length;
  for (var i = 0; i < arrayLength; i++) {
    boardedges.push(board.create('arrow', [boardpts[edges[i][0]], boardpts[edges[i][1]]]));
  }
[[/jsxgraph]]
```

That way you can create lists of points and edges (i.e. your graph) in Maxima and create a random graph.  The real strength of this solution is that your users can drag the point and get a dynamic graph.

**Comment by sangwinc** [comment]
Ok, since we have a reasonable solution to this problem, I'm going to close the issue.  Please re-open this to discuss it further.

**Comment by hwesterholt** [comment]
This thread has been extremely helpful and I would like to thank all of you.

I have tried to implement the very elegant solution provided by @sangwinc and have run into #433, so I contacted my local moodle admins. As it turns out, atto was the only editor available at my university (until now), but markdown and plaintext editors will be available shortly. That explains a lot of my previous problems.

I hope it's okay to reopen this issue and ask follow up questions that somewhat relate to the inital issue of "Plot(ting) directed graphs", otherwise please let me know how to proceed.

The questions I am currently working on are exercises related to shortest path and maximum flow problems. Students will not be required to drag vertices and/or edges around, so I "fixed" all of them to their initial position. A question that I have not found and answer to would be: is it possible to include student answer fields at a given position in the JSXgraph block, e.g. for edge weights?

What I currently have is:

```
[[jsxgraph]] 
var board = JXG.JSXGraph.initBoard(divid, {boundingbox: [-1, 5, 7, -5], axis: false, showCopyright: false });
var inputField = board.create('point', [2.0, -0.25], {size:0.0, strokeColor:'black', name: '{#[[input:ans2]]#}'});
/* rest of
the graph
.... */
[[/jsxgraph]] 
```

This is the result:
Upon saving, STACK adds answer ans2 to the potential response tree and demands a model answer (e.g. 3). Sadly, instead of the graph and an input field, I get the graph and the text `[[3]]` at the correct position. Is there any way to make this work?

**Comment by aharjula** [comment]
Unfortunately, placing a STACK input field within a JSXGraph is not feasible, using STACK provided tools, at least currently and I fail to see how that would work in the future. The closest that we could currently provide would be to place a JSXGraph slider for setting a real-number value and [binding](https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/JSXGraph.md#convenience-tools-for-building-graphs) that to a STACK input-field (hidden or visible). STACK does support binding points, sliders and pairs of points to STACK-input fields using STACK provided utility functions but beyond that, the author must find out the ways of writing the logic themselves.

One could, in theory, do some DOM-manipulation and transplant a STACK input-element to a JSXGraph e.g. replace something generated with [this](http://jsxgraph.uni-bayreuth.de/~alfred/jsxgraph/distrib/docs/classes/Input.html). But I have no experience on how that would happen and how it would react to updates or page resizes. A general solution for doing that would require for us to parse the JavaScript to identify its meaning (if it wants to place inputs etc.) so it is very hard for us to do and is probably not happening, but suitably adventurous question author might be able to do it for singular questions. Would require some serious JavaScript, DOM, and event understanding though, also making it so that the input affects Moodle/ILIAS in a sensible way could also be a slight complication.

In any case, I would rate this in complexity very much lower than trying to place inputs within MathJax. At least I know that JSXGraph is a different style of a library with general architecture that is somewhat supportive for this kind of behaviour.
