### ISSUE TITLE
This function call 'matrix(A) does not appear to have an easily visible function name

### ISSUE THREAD

**Issue by knedlyk** [maths/moodle-qtype_stack#575]
I have moodle 3.8.2+ and maxima sbcl 5.43.2, Stack version 4.3.0 for Moodle 3.5+ 2020040300  and I am using archlinux. Version of maxima is not important, I also tried lower version down to the version 5.38, the result is the same:
```
    The field ""Question variables"" generated the following error: This function call 'matrix(A) does not appear to have an easily visible function name. Due to security reasons you may need to simplify the call so that the validator can see the function name.
    CASText failed validation. This function call 'matrix(A) does not appear to have an easily visible function name. Due to security reasons you may need to simplify the call so that the validator can see the function name.
    CASText failed validation. This function call 'matrix(A) does not appear to have an easily visible function name. Due to security reasons you may need to simplify the call so that the validator can see the function name.
    This function call 'matrix(A) does not appear to have an easily visible function name. Due to security reasons you may need to simplify the call so that the validator can see the function name.
    The field ""Question text"" generated the following error: CASText failed validation. This function call 'matrix(A) does not appear to have an easily visible function name. Due to security reasons you may need to simplify the call so that the validator can see the function name.
    The field ""Specific feedback"" generated the following error: CASText failed validation. This function call 'matrix(A) does not appear to have an easily visible function name. Due to security reasons you may need to simplify the call so that the validator can see the function name.
    The field ""Question note"" generated the following error: CASText failed validation. This function call 'matrix(A) does not appear to have an easily visible function name. Due to security reasons you may need to simplify the call so that the validator can see the function name. 
```
It worked before upgrading the stack qtype plugin. In the question I have 
```
ta:apply('matrix,A);
```
it converts list to matrix, as it is described in Maxima manual 23.1.2 http://maxima.sourceforge.net/docs/manual/maxima_23.html 
Downgrading the plugin is not possible in Moodle, is there any quick fix for that?

**Comment by sangwinc** [comment]
What about dropping the apostrophe?
`ta:apply('matrix,A);`
If that works, please close the issue!

Thanks for your interest in STACK,
Chris

**Comment by aharjula** [comment]
Is there a particular reason for that apostrophe `'` there? That should work without it, but indeed the security check does not like to apply nounified function identifiers. Maybe that will be changed in the future, if a true need exists.

In any case that is an odd example in the docs, but you probably do not need that apostrophe.
```
(%i1) A:[[1,2],[3,4]];
(%o1)                          [[1, 2], [3, 4]]
(%i2) apply(matrix,A);
                                   [ 1  2 ]
(%o2)                              [      ]
                                   [ 3  4 ]
```

**Comment by aharjula** [comment]
Chris, this is due to the apply/map-security handler that builds virtual function-calls, it seems to not be able to deal with function names that are not directly identifiers or strings. Not a major mod to make it able to do so, but seems like a very odd use case to apply nounified functions, would really want to know the intention if one does that, before allowing it...

Essentially, [this](https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/parsingrules/998_security.filter.php#L179) creates a function-call where the name contains the apostrophe when normally the apostrophe is outside of the function-call.

**Comment by knedlyk** [comment]
Not sure, without apostrophe I got timeout. It works in maxima, but not in
qtype_stack.

**Comment by knedlyk** [comment]
It doesn't work without apostrophe. You could check my my maxima code (finding extremum of the function depending on the two variables):
```
a:rand(4)+1;
b:a+(-1)^rand(3)*rand(3)+3;
fxy:rand([a+(a-b)*x-b*x^2+(a+b)*(-1)^b*x*y-a*y^2,a*x^2+b*x*y^2+(a-b)*x*y,(b*x^2-y)^2 + (y-a)^3,x^2 +a*x*y-b*y^2 +a*x+b*y+a*b,x^3+ a*x*y^2-b*x*y]);
f(x,y):=fxy;

dfx(x,y):=(diff(f(x,y),x,1));
dfy(x,y):=(diff(f(x,y),y,1));
dfxx(x,y):=(diff(f(x,y),x,2));
dfxy(x,y):=(diff(f(x,y),x,1,y,1));
dfyy(x,y):=(diff(f(x,y),y,2));
det(x,y):=dfxx(x,y)*dfyy(x,y)-(diff(f(x,y),x,1,y,1))^2;
        
sol:solve([dfx(x,y)=0,dfy(x,y)=0],[x,y]);

A:[[X,Y,EXTR]];
B:A;
N:[no,no,no];

test1:for i:1 thru length(sol) do (x[i]:ev(x,sol[i]),y[i]:ev(y,sol[i]),  test2:(if (imagpart(x[i])=0 and imagpart(y[i])=0) then test3:(if subst([x=x[i],y=y[i]],det(x,y))=0 then (extr:no) else  test4:(if subst([x=x[i],y=y[i]],det(x,y))<0 then extr:no else test5:(if subst([x=x[i],y=y[i]],dfxx(x,y))>0 then extr:min else extr:max)), result[i]:[x[i],y[i],extr],A:append(A,[result[i]]))));

test6:if A=B then A:append(A,[N]);
ta:apply(matrix,A);
ta:ratsimp(submatrix(1,ta));
```

**Comment by aharjula** [comment]
Are you sure that the line starting with `test1: for`... is as it should be. In my STACK 4.3 installation, the matrix application works just fine if I remove that line.

Also, you might benefit from the new feature in 4.3 where one can write long statements on multiple lines, no need for single-line statements anymore. For example:
```
fxy:rand([a+(a-b)*x-b*x^2+(a+b)*(-1)^b*x*y-a*y^2,a*x^2+b*x*y^2+(a-b)*x*y,
          (b*x^2-y)^2 + (y-a)^3,x^2 +a*x*y-b*y^2 +a*x+b*y+a*b,x^3+ a*x*y^2-b*x*y]);
```
Is still a monster but bit simpler to look at. That for-loop though...

**Comment by aharjula** [comment]
Actually, Maxima version might matter, if you have upgraded it lately then there might be these kinds of errors within the for-loop, these are caused by addressing a variable that has not been initialised as a list like a list.
```
ARRSTORE: use_fast_arrays=false; allocate a new property hash table for $X
ARRSTORE: use_fast_arrays=false; allocate a new property hash table for $Y
ARRSTORE: use_fast_arrays=false; allocate a new property hash table for $RESULT
```
If that is the case I wonder why those errors are not coming out...

**Comment by knedlyk** [comment]
> Is still a monster but bit simpler to look at. That for-loop though...
Thanks for the tip, I didn't know about it. Code is very old, but it worked well for me before upgrade and should work regardless of the stack version, I suppose. Can I just remove this security check?

**Comment by aharjula** [comment]
I would not remove it but you can try replacing it with a new version from [here](https://github.com/maths/moodle-qtype_stack/blob/dev/stack/cas/parsingrules/998_security.filter.php#L179-L183) so just that previously mentioned line.

However, that `use_fast_arrays` thing will break that question again when you eventually update Maxima and you probably will need to do that maybe even when 4.4 of STACK comes out.

**Comment by knedlyk** [comment]
OK, another way is to form matrix  vector by vector manually... Function
apply('matrix, A) is very useful, it's a pity that I can't use it.

**Comment by aharjula** [comment]
If you apply [this change](https://github.com/maths/moodle-qtype_stack/commit/53fd5333b71519867d4d98c375ff627cb6fbea92) to your STACK then you will be able to use `apply('matrix,A)`.

**Comment by knedlyk** [comment]
I got TIMEDOUT:
````
TIMEDOUT
The field ""Question text"" generated the following error: CASText
failed validation. TIMEDOUT
The field ""Specific feedback"" generated the following error: CASText
failed validation. TIMEDOUT
The field ""Question note"" generated the following error: CASText
failed validation. TIMEDOUT
The field ""Question variables"" generated the following error: TIMEDOUT

````

**Comment by aharjula** [comment]
Try commenting out that `test1` line with the loop and see if you still timeout... If not then it is most likely due to those list access issues. And those we really cannot do anything as it is a change in Maxima. You'll just need to initialise those variables as lists before accessing them as lists and we will need to figure out why that error message does not come out through the system.

**Comment by knedlyk** [comment]
Yes, it's due to this line. Thank you very much for the help!

**Comment by aharjula** [comment]
```
x:makelist(0,x,1,length(sol));
y:makelist(0,x,1,length(sol));
result:makelist(0,x,1,length(sol));
```
Before the loop should get you to your next problem. It is probably something that was completely hidden in earlier versions but now caught in the new evalaution system.

**Comment by knedlyk** [comment]
Thanks for the advice, I'll change the question code accordingly.

**Comment by knedlyk** [comment]
Everything works. Closing issue.

**Comment by knedlyk** [comment]
Everything works. Closing issue.
