### ISSUE TITLE
missing picture

### ISSUE THREAD

**Issue by miroi** [maths/moodle-qtype_stack#578]
in https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/Authoring_quick_start_2.md

missing picture 
https://github.com/maths/moodle-qtype_stack/raw/master/doc/en/Authoring/%CONTENT/IntegrationExercises.jpg

**Comment by sangwinc** [comment]
Ok, thanks for raising this.  The STACK documentation system extends markdown (e.g. embedding content, support for LaTeX mathematics) in ways that GitHub does not render.  Really, you are best looking at the docs on your own system (so you know which docs match the version you have).

My server is here, and it renders the docs.
https://stack2.maths.ed.ac.uk/demo2018/question/type/stack/doc/doc.php/Authoring/Authoring_quick_start_2.md
