### ISSUE TITLE
[Proposal] Number formatting

### ISSUE THREAD

**Issue by chigle** [maths/moodle-qtype_stack#581]
Hello All, Thank you for a great tool you are developing. 
I wonder if it is possible to extend STACK Maxima/Lisp support for sign-preserving formatting of integers: "~@d"?  This would be helpful to display generated equations in a neater way (avoiding "-+" situations), such as
`\[ {@A@} \frac{d^2y}{dt^2} {@(stackintfmt:"~@d",B)@}\frac{dy}{dt}  {@(stackintfmt:"~@d",C)@}y = 0\,. \]`
or `\[ Y = {@k@}(X {@(stackintfmt:"~@d", -X0)@}) \]`

Apologies if this feature is already in the latest STACK version, or if I am missing something. If this is the case, perhaps, you could update the user manual on https://stack2.maths.ed.ac.uk/demo2018/question/type/stack/doc/doc.php/CAS/Numbers.md .
Many thanks,
Igor

**Comment by sangwinc** [comment]
Well, really the idea in STACK is to "solve the problem at the mathematical level", so to get the signs right I'd promote something like
\[ {@A*diff(y,t,2)+B*diff(y,t)+C=0@} \] or \[ Y= {@k*(-X0)@} \]
rather than a sign-preserving _format_.  Does this make sense?

**Comment by chigle** [comment]
Thank you, Chris. I am aware of the alternative format, but it also generates brackets around the derivatives (at least in our STACK version). I also miss this formatting option to be able to show extra solution steps in the feedback.

**Comment by sangwinc** [comment]
Ok, well, fair enough.

Unfortunately, the @ characters have special meaning in Maxima and are not currently allowed in input.  This includes within strings (as you have them).  So

1. Question variables `s1:(stackintfmt:"~@r",75);` fails because it has an @ symbol.
2  Castext such as `The decimal number {@n:73@} is written in Roman as {@(stackintfmt:"~@r",n)@}.` does bot get through the castext parser (problems matching `{@..@}` and it tries to be helpful and throws an error!)

Matti may wish to comment on all of this.

**Comment by aharjula** [comment]
Injections with `@` and `#` are indeed broken, but:
 1. The first broken bit is the CASText parser that cannot deal with `@` inside `{@...@}`, currently this is a thing that will not be fixed as CASText2 does have a parser that has no problem with this and the old parser is inconvenient to fix. Unfortunately, CASText2 is not coming out this year as it is tied to a pretty large refactoring of the core logic and requires plenty of time to mature.
 2. If one cannot put a `@`-char inside CASText, one could probably just reference a variable that has it in its value.
 3. However, at that point STACK says that no statement can have `@` which is a bit odd thing as I think that I already made it allow everything inside strings, maybe someone (Chris...) has returned some really old logic or is checking without removing strings first...

Well, we can work around 3 by using the following trick and then use 2:
```
In question vars:
myformat:sconcat("~",ascii(64),"d");

In CASText:
{@(stackintfmt:myformat,n)@}
```
Note, however, that that "hack" works only in STACK 4.3+ as before the update of the CASSession subsystem it would have evaluated that `ascii(64)` to `"@"` and then revalidated it as invalid.

I fear that you will find some extra signs in the result though and we get back to Chris talking about the unary minus...

**Comment by chigle** [comment]
Dear Chris and Matti, thanks a lot for the suggestions, in particular for the "ascii"-trick! I wonder if `"@"` could be escaped, like `"//"`, in the string variables? Please let me know if you need any help with debugging the parser - I will try to look at it when time allows.
