### ISSUE TITLE
AlgEquiv not identifying some simple equivalences

### ISSUE THREAD

**Issue by rogercolbeck** [maths/moodle-qtype_stack#582]
6*e^(6*(y^2+x^2))+72*x^2*e^(6*(y^2+x^2))
and 
(72*x^2+6)*e^(6*(y^2+x^2))
are not recognized as equivalent using AlgEquiv
Screenshot: 
![Screenshot from 2020-05-31 13-30-39](https://user-images.githubusercontent.com/32660531/83352445-4f7dc400-a343-11ea-9bca-984ac81e0787.png)

**Comment by sangwinc** [comment]
I can't reproduce the problem as a test case to AlgEquiv.  Please see the above test case which passes on my machine.  Can I ask you to double check your PRT?  If this is a question authoring mistake please close the issue.  If not, email me your question and I'll take a quick look...

**Comment by rogercolbeck** [comment]
This seems to be a version issue. I confirmed that this issue is not present when using the stack demo server.

**Comment by sangwinc** [comment]
Ok roger, if you go to your home server and look at the docs page you will find the version number, e.g. look at the bottom of
https://stack2.maths.ed.ac.uk/demo2018/question/type/stack/doc/doc.php/
I'm happy to talk with York about which version you are currently using and upgrade options.  Let's do that on email.
