### ISSUE TITLE
Problems with New Version of STACK

### ISSUE THREAD

**Issue by hayyanhelal** [maths/moodle-qtype_stack#584]
I'm coming from the RWTH Aachen University and we've been using STACK intensively lately.
We've experienced some problems after installing the latest version of STACK:
1. Inverse trigonometric functions that were accepted as arccos, arcsin, and arctan are now not accepted anymore and we have to change all already made exercises including these functions which's exhaustive. 
2. Using Greek letter alpha as a function was okay, now not anymore unless we add it to the allowed words.
3. When we make a copy of an exercise it looks like the copy has some different settings (which I guess go back to default). One example of this problem is that the random variables in one exercise changed suddenly into being non-random, i.e. getting always the same value, but then after copying the exercise, the random variables in the copy functioned as they're supposed to.

I'd like to know if anybody else experienced any similar problems and if there are any solutions to these problems.

**Comment by sangwinc** [comment]
I think 1 & 2 are fixed.  If 3 is still an issue please open a new issue and attache a question with a specific setting problem.  This issue has too many parts, and part 3 isn't reproducible by me sorry!
