### ISSUE TITLE
Inverse trigonometric functions display problem - for arccos(x) type

### ISSUE THREAD

**Issue by marlag** [maths/moodle-qtype_stack#590]
Hi,

Seems something is broken for exponent - then expression isn't recognized and displayed "raw".
Example below for asin, however all are affected. AFAIR in older version (I don't remember exact numbers - c.a 4.0-4.1) it was working fine. Currently 4.3.3 is used.

![Outlook-ty4fgak5](https://user-images.githubusercontent.com/11375408/85321124-7b184800-b4c4-11ea-8bd9-41b92ec13f2a.png)

Could somebody take a look at that?

**Comment by sangwinc** [comment]
Thanks for pointing this out.  This is not entirely "STACK's fault".  Try the following in Maxima (without the sandbox).

```
p1:asin(x)+asin(x)^3;
tex(%);

texput(asin, "{\rm foo}");

p1:asin(x)+asin(x)^3;
tex(%);
```

The second tex command does not display "foo" for the normal arcsin.  You actually get `$${rm foo}^3x+\arcsin x$$`.  So the fix won't be elegant.

**Comment by sangwinc** [comment]
This unit test passing means this issue is not live in the latest version.
https://github.com/maths/moodle-qtype_stack/blob/master/tests/cassession2_test.php#L448
