### ISSUE TITLE
"Question tests & deployed variants" openinig with "new seed"

### ISSUE THREAD

**Issue by marlag** [maths/moodle-qtype_stack#591]
Hi,

As discussed in [moodle forum](https://moodle.org/mod/forum/discuss.php?d=405557#p1637089) it seems unintentionally change was introduced - to show new variant of quiz for "Question tests & deployed variants" option.

Manual switching to arbitrary variant by copying the seed from the response history isn't so helpful like opening it in place. I would appreciate if you improve it (or fix as it was working like that).

BR

**Comment by sangwinc** [comment]
Thanks for reporting this, much appreciated.
