### ISSUE TITLE
Strange issue with noun* in question variables

### ISSUE THREAD

**Issue by NeilStrickland** [maths/moodle-qtype_stack#592]
I have two different servers running Moodle + Stack.  Machine A runs Ubuntu, and has optimized Maxima and MaximaPool.  Machine B runs Windows 10 with unoptimized Maxima and no MaximaPool.  For a minimal case of the issue, I set up a Stack question with algebraic input and answer 42, and I have two spurious question variables that are not actually used for anything, as follows:
```
x: 1 noun* 1; 
y: 1;
```
On machine B this works with no problem.  On machine A, when I try to save the question, the question variables box is outlined in red and followed by an error message:
```
The CAS returned the following error(s):CAS failed to return any data. y: 1
```
Note that the error message is associated with `y`, but it is clearly caused by the setting of `x`.  Changing `noun*` to `noun+` makes the error go away.  Note here that `noun*` comes from the "Noun arithmetic" section of `stack/maxima/assessment.mac`, and the error message is generated at line 245 of `stack/cas/cassession.class.php`.  I only have proper PHP debugging set up on machine B, so it is hard for me to dig deeper than this.

**Comment by aharjula** [comment]
Which version of STACK and is it certain that the MaximaPool runs a version of the scripts that matches the corresponding STACK installation. And that the versions of STACK match on those systems, MaximaPool itself should not affect anything at this level.

`cassession.class.php` has not been a thing since 4.3 was released so those would have to be "older" installations.

I wonder if those particular operators are even meant to be accessible by the author and if they should only exist as intermediate products of the Maxima side processing. Maybe Chris can explain. But I would guess that they are not something that is intended to be used directly, at least the 4.3 parser upgrade does not think of them as something it should accept.

**Comment by NeilStrickland** [comment]
OK, I lost sight of the fact that it is 10 months since I set up machine A, although I only started using it seriously a couple of weeks ago.  I have tried to update and thereby broken everything.  I will post again when it is fixed.

**Comment by NeilStrickland** [comment]
Now I have successfully updated everything and my two servers are behaving the same.  However, this means that `noun*` and similar things do not work anywhere.  This seems undesirable, as I cannot work out any other reasonable way to have unsimplified expressions e.g. in Stack-based multiple choice questions.  If I understand correctly, it should be possible to fix this by making minor edits to `MP_classes.php` and `parser_grammar.pegjs` and then regenerating `parser.mbstring.php`.  But I have not properly digested the framework for that yet.

**Comment by aharjula** [comment]
I am guessing that you are missing something basic related to STACK+Maxima. The `noun*` features are almost certainly internal logical constructs for EqualComAss test, that you should not access whereas the typical way of stopping evaluation is to stop simplification during the input of an expression:

```
x1: 1*1;
simp:false;
x2: 1*1;
simp:true;
/* after that output should provide */
string(x1) => "1"
string(x2) => "1*1"
```
There are other means for doing that but I'll leave explaining them to Chris.

Or is the MCQ-input simplifying those as well? If so you might turn off the simplification of the whole question. Or maybe the MCQ-input fails to ensure `simp:false` in its processing. Maybe append, `simp:false;` into your question-variables to see if that works. If that is the issue then there probably is a bug in the MCQ-logic or in the logic of evaluating and giving the teacher-answer field to the inputs.

Note that you can also work around this issue by generating your own labels for the MCQ-options and possibly not expecting the answer to be the expression but instead, some form of identifier telling which option was selected.

**Comment by NeilStrickland** [comment]
Thanks; I was indeed unaware of that approach.

**Comment by sangwinc** [comment]
Neil,
The noun* features were intended to be purely internal, which is why I didn't document and recommend people use them.  I'm really sorry if this messes up your questions.   How many questions would you have to fix?
Chris

**Comment by NeilStrickland** [comment]
Chris, thanks for getting back to me.  This is no longer a problem now that @aharjula has explained the correct use of the `simp` option.  I will close the issue now.
