### ISSUE TITLE
Display of powers of logarithms to an arbitrary base

### ISSUE THREAD

**Issue by stebac** [maths/moodle-qtype_stack#594]
Hi, 
I've noticed that powers of logarithms to an arbitrary base are not rendered correctly (STACK 4.3.2)
![grafik](https://user-images.githubusercontent.com/52776824/85398767-ff66db80-b555-11ea-8153-434278f7bb34.png)
One problem about this is that the student will be uncertain wether the input was interpreted as intended (which is acutally the case) or not. 
Stephan

**Comment by sangwinc** [comment]
Sorry about this Stephan, thanks for reporting the problem.
