### ISSUE TITLE
Extra input option: hideanswer

### ISSUE THREAD

**Issue by stebac** [maths/moodle-qtype_stack#595]
Hi, 
could we have the extra option "hideanswer" also be supported for other input types than just string input, especially Numerical and True/False?

I am using JSX-Graph in combination with numerical input (not string) - here it does not make sense to display the coordinates of a point as the correct answer.
When using True/False questions in a different language but English the correct answer is still displayed as **true** or **false** even though the options in the drop down menu are e.g. "Wahr" or "Falsch" (in German). This is kind of awkward.

It would actually be nice being able to decide on question level if the correct answer will be displayed or not and not only on quiz level. Because in one quiz you might have both questions with rather advanced input where I want to take advantage of the "which can be typed as" info and questions were displaying the correct answer is rather confusing than helpful.

Stephan

**Comment by sangwinc** [comment]
Good suggestion, thanks Stephan.

I'm not going to add this option for all inputs, as some of the more complex inputs such as matrix and the MCQ inputs make assumptions about the internal form of an answer which might not be respected by etc.

I'm sorry about the use in Maxima of "true" and "false".  We should have localised this a long time ago. My appologies....
