### ISSUE TITLE
Wrong Validation for Algebraic input and Units input together in same question

### ISSUE THREAD

**Issue by dhilsen** [maths/moodle-qtype_stack#596]
We have recently installed STACK v4.3.3 with Maxima 5.41.0. 

An issue has been encountered for our questions that have Algebraic input(AlgEquiv answer test) and Units input(UnitsRelative answer test) both contained together in the same question. These questions will ask for a physical equation to be entered for the first part of the question, and then a numerical answer involving a unit for the second part of the question. 

When entering the student answer for the Algebraic input, the validation will display "Input of units is case sensitive. {a} is an unknown unit". This validation is displayed for most variables that are entered into the Algebraic input student answer. The validation for the algebraic input seems to behave as if the question was a unit input. This behavior has only been observed for cases where Algebraic input and Units input both appear together in the same question.

**Comment by aharjula** [comment]
This is an inconvenient side-effect of the new 4.3 logic of automatically defining the whole question to use units if even one units input is present. In your case, it annoyingly thinks that a is Ampere and whines. That feature exists to ensure that no-one can redefine the units anywhere in the question, i.e., the author cannot assign a value for example for `g` or `s` and break the unit system. Unfortunately, the case-sensitivity checks for units come in the same package as all the other units related checks.

To avoid this kind of friendly fire we have the input option `nounits` which can be added to the inputs to make sure that it does not validate the input looking for units.

**Comment by dhilsen** [comment]
Thank you Matti, the `nounits` input option nicely fixes this situation. The new logic in 4.3 is a major step forward - thank you for this!

**Comment by sangwinc** [comment]
Thanks Matti,
Chris
