### ISSUE TITLE
Query on counting of tries in reports

### ISSUE THREAD

**Issue by pgb2** [maths/moodle-qtype_stack#60]
I am checking out the Stack response analysis that we have installed and it seems to me that saving a response is being treated the same as submitting a response and I'm wondering if this is intended.

I created a test to run in interactive with multiple tries mode and we have instant rendering turned on.
There were four questions of which three were STACK.
I ran the test with three students.
To one question one student
- entered a response of 49q^2 and pressed Next (not check)
- then they returned to the question and pressed Check
- after try again they extended their answer to 49q^2 + 49q
- after try again they answered correctly.
  Only one student saw this variant of the question.
  But the STACK analysis implies that their were two responses of 49q^2. It's this that I'm querying.
  See attached
  ![stack report 1](https://f.cloud.github.com/assets/3472828/135299/d7316862-7118-11e2-93b3-4681d4a15fae.png)
  ![stack report 2](https://f.cloud.github.com/assets/3472828/135300/da41c3ee-7118-11e2-8177-0df727733f7a.png)

**Comment by sangwinc** [comment]
Tim,
Did we every fix this?!   (I'm looking at all the open issues....)

**Comment by timhunt** [comment]
No idea. I think you need to try Phil's steps to reproduce this, and see if the bug still occurs.

**Comment by christianp** [comment]
For info, this has not been fixed. I've just reproduced the problem exactly as described.

**Comment by christianp** [comment]
For info, this isn't fixed. I've just reproduced it exactly as described.
