### ISSUE TITLE
new function for exact regex match ?

### ISSUE THREAD

**Issue by nfa019** [maths/moodle-qtype_stack#601]
Just a wish:

For my course in theoretical computer science I often need to check whether a string is an exact match for a regex.

 What Maxima has is a function, that delivers matches inside a string, so what I really would like to have is something shorter for this:

`list : regex_match(regex,string);
bool1 : listp(list);
if bool1 then (ansmatch : first(list), bool1: sequal(ans1,ansmatch) );
`
bool1 is true for an exact match and false otherwise.

Frauke

**Comment by sangwinc** [comment]
That looks like a very sensible suggestion, and just the kind of thing I would add to the STACK core myself.  Thanks.

Is this the kind of function you want?  (I've put "p" at the end to match Maxima's convention on predicates.)

```
regex_match_ansp(regex, str, ans) := block([11, bool1],
  l1:regex_match(regex,str),
  bool1:listp(l1),
  if bool1 then block([ansmatch],
     ansmatch:first(L1), 
     bool1:sequal(ans, ansmatch)
  ),
  return(bool1)
)$

```

If so, please send me some examples to add as "unit tests" to make sure this gets supported in the long term.

**Comment by nfa019** [comment]
This is already too much, sorry my example was a bit wrong (ans should be the same as string)

I will play around with this and provide a function and some examples.

Frauke

**Comment by nfa019** [comment]
This should do the right thing now

`
regex_match_exactp(regex, str) := block([l1, bool1],  
  l1:regex_match(regex,str),  
  bool1:listp(l1),  
  if bool1 then block([strmatch], 
    strmatch:first(l1),  
    bool1:sequal(str, strmatch)   
  ),   
return(bool1) 
);
`

only some examples:
Regex                      String                      Result
(aaa)*(b|d)c             aaaaaabc                true
(aaa)*(b|d)c             dc                            true
(aaa)*(b|d)c             aaaaaaabc              false
(aaa)*(b|d)c             cca                          false              

Frauke

**Comment by sangwinc** [comment]
Sorry Frauke,
but
`regex_match_exactp("(aaa)(b|d)c", "aaaaaabc");`
returns `false`.

`regex_match("(aaa)(b|d)c", "aaaaaabc");`
returns
`["aaabc","aaa","b"]`

Am I missing something obvious here?

**Comment by aharjula** [comment]
Chris, remember that this is GitHub and that _italic_ text there probably means that you are missing the asterisk from the pattern...

**Comment by nfa019** [comment]
yes, there was a star behind (aaa) ....

**Comment by aharjula** [comment]
So with backticks the pattern was `(aaa)*(b|d)c`.

**Comment by sangwinc** [comment]
Ok!  I updated the original comment for posterity!

**Comment by nfa019** [comment]
Thank you !
