### ISSUE TITLE
scientific_notation making question unusably slow.

### ISSUE THREAD

**Issue by ianjones** [maths/moodle-qtype_stack#607]
Including ta1: scientific_notation(a1,2); is REALLY slowing down the question when previewing. It takes several seconds to load, and several seconds for any button (e.g. fill in correct responses) to do anything. (When I use ta1: float(a1) just to test things it works at normal speed).

I'm working on https://stack2.maths.ed.ac.uk/demo201, for those with access it's question "1.2.6.2 Give scientific notation NOT WORKING"

**Comment by aharjula** [comment]
Maybe someone can look at the question itself (I don't have access and that link points to a 404), but in general, this is probably an issue with exact calculations vs floats:
1. If one works with integers and generates a large exponent number like the number of quarks in few universes or some tunnelling probability for significant distances then evaluating the actual number will take time as will the logarithm operations required for that function.
2. However if one does that in floats some accuracy is lost and rounding may happen but the number is directly usable and the powers that matter are easily accessible with less work for logarithms. Problem is that one cannot present truly large or small numbers with floats in Maxima, things will simply break if one tries to go beyond `1e308` and things will turn to zero below `1e-324` these are places where numbers break and we need to turn to accurate evaluation if any evaluation needs to be done and that is slow.
3. We have done some development work to do that conversion (oversized value to exact value) automatically for student input, but it is still under work. There is also some effort being placed on making the input itself convert the received values directly to floats for faster evaluation.
4. All of this also applies to the sigfigs and numerical answer-tests and they are probably the things that are slow.
5. Also whether we have `simp:true` or `false` might also affect here especially with the teacher's answer field which is very much `simp:false` so evaluating the value at question-vars and referencing to it int the teacher's answer might be better.
6. Further complications may come from the LISP-interpreter running Maxima, there has been some anecdotal experience stating that some interpreters are fast with floats and others are not similarly some are slow with integers...

**Comment by ianjones** [comment]
Thanks Matti, appreciate the thoughtful reply. The link SHOULD have been https://stack2.maths.ed.ac.uk/demo2018

Number size shouldn't be the problem I'm only dealing with 3-digit numbers. The variables box is
stackfltfmt:"~e";
simp:false;
a1: rand([431,432,433,435,436,437,438,439]);
ta1: scientific_notation(a1,2);


[questions-HELM2020-1.2.6.2 Give scientific notation NOT WORKING-20200709-1325.xml.zip](https://github.com/maths/moodle-qtype_stack/files/4896716/questions-HELM2020-1.2.6.2.Give.scientific.notation.NOT.WORKING-20200709-1325.xml.zip)

**Comment by malthefogsporring** [comment]
Matti's suggestion (4) was indeed correct: the NumAbsolute answer test was responsible for slowing down the question. It seemed very unhappy with having an entry of the form scientific_notation(a1,2). Using the original integer a1 instead helped with the speed.
