### ISSUE TITLE
Error with 'If' statements in Question Variables

### ISSUE THREAD

**Issue by MaciejTMatuszewski** [maths/moodle-qtype_stack#611]
Hello,

I just noticed a minor issue. If there are 'if' statements as the last lines in the "Question variables" field, they will not execute, giving an error "CAS failed to return any evaluated expressions. Please check your connection with the CAS." 

For example, a question (asking students about how many words can be made from a selection of letters) containing the following code in "Question variables":
```
letters: rand([5,6,7]);
wordlen: rand([4,5, 6, 7]);

solution: letters^wordlen;

if is(letters=5) then letterset: "V, W, X, Y, Z";
if is(letters=6) then letterset: "U, V, W, X, Y, Z";
if is(letters=7) then letterset: "T, U, V, W, X, Y, Z";
```
this will not work, however the following addition of any non-comment and non-if line will make it work as required:
```
letters: rand([5,6,7]);
wordlen: rand([4,5, 6, 7]);

solution: letters^wordlen;

if is(letters=5) then letterset: "V, W, X, Y, Z";
if is(letters=6) then letterset: "U, V, W, X, Y, Z";
if is(letters=7) then letterset: "T, U, V, W, X, Y, Z";

dummy: 0;
```

There does not appear to be a similar problem with the "Feedback variable" field.

**Comment by aharjula** [comment]
On which version of STACK does this happen? I cannot reproduce this with that sample with the master-branch or dev-branch version. I would be very surprised if this happens on any version since 4.3, but it could happen with something older as they had quite different logic.

**Comment by MaciejTMatuszewski** [comment]
It says "This question was authored with STACK version 2018080600" which I believe corresponds to 4.2.1 for Moodle 3.0+

**Comment by smborio** [comment]
This happened before with my version of STACK and I went round it by saying something like 
letterset:if letters = 5 then "V, W, X, Y, Z" elseif letters=6 then "U, V, W, X, Y, Z" else "T, U, V, W, X, Y, Z". not ideal but works.

**Comment by sangwinc** [comment]
This isn't a problem on STACK 4.3.  I'm sorry about the previous problem, but at least your suggested fix gives you a way round here.
