### ISSUE TITLE
Make validation div instead of span

### ISSUE THREAD

**Issue by malthefogsporring** [maths/moodle-qtype_stack#617]
Can we please have the validation show as a div instead of a span? It looks much better on narrower screens. The trade-off of the validation box taking on the full width on wide screens is minor in my opinion.

span:
![span](https://user-images.githubusercontent.com/67361419/90413649-a70c1000-e0a6-11ea-90c2-5f5fd429001c.PNG)

div:
![div](https://user-images.githubusercontent.com/67361419/90413677-b0957800-e0a6-11ea-8089-40fa061c330f.PNG)

**Comment by aharjula** [comment]
`div` vs `span` makes sense, there could be more error messages there and it would make more sense to put an `ul` inside that div as well. In any case, every `span` we can remove lessens the trouble that the multi-lang filter causes.

Naturally, either will work if one changes that `span` to a block in the styles then everything will fit it just as well. But that woul be silly.

**Comment by shinuito** [comment]
@sangwinc Is there a chance this might have reintroduced issue #563  https://github.com/maths/moodle-qtype_stack/issues/563 by any chance?

I was testing out moodle 3.5 with Stack 4.3.5 and maxima 5.42.2 on mac today and I seem to be getting this issue, of things not rendering after the input/validation boxes.
