### ISSUE TITLE
Question which validates fine when you save it, but then gives fatal parser errors.

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#618]
If you import this question (Moodle XML format. .txt extension added just to keep Github happy.)

You can edit the question and click save, and there are no validation errors.

However, if you then try to preview the question, or run the question tests, there are fatal errors from the parser.

And, if you run the question tests in bulk, then this fatal error will case the bulk run to crash out. Surely it should report the error, then move on to the next question?

[weirdquestion.xml.txt](https://github.com/maths/moodle-qtype_stack/files/5097659/weirdquestion.xml.txt)

**Comment by timhunt** [comment]
Note, this is not a big priority for us. I made the problem go away by editing the question. From the question name, you can guess it is probably not an important, well-authored question. I just thought I would record what we found.

**Comment by aharjula** [comment]
To me, it looks like the equiv input is enforcing the forbidden words on itself when it should probably only check for them for the contents of the input. Basically, the forbidden words here contains `[` and `]` which are quite important for the value that equiv-input generates, as it generates a list. Pretty much the same as forbidding `matrix` from being used within [the matrix input](https://github.com/maths/moodle-qtype_stack/blob/1ae9a49f6eca5f3c1821d0d902384735dc6f7e04/stack/input/matrix/matrix.class.php#L208-L222) should not forbid the value that the input generates but only forbid the cells from the containing matrices.

The equiv-input is something that I do not understand so Chris will have to deal with this.

**Comment by sangwinc** [comment]
Thanks for the report Tim, and the hint Matt.  Good to weed out issues like this.  We would want to forbid lists in equiv inputs.
