### ISSUE TITLE
"Scary" coding error when all PRTs are in mode "Formative"

### ISSUE THREAD

**Issue by lassikor** [maths/moodle-qtype_stack#619]
This issue is not fatal, but it may scare someone :)
If the choice PRT feedback style is set to "Formative" for all PRTs the system gives a coding error when previewing the assignment (see picture). Could it be possible to handle this case (no marks available for the question) when saving the assignment with a bit more informative message? For example: The PRTs of this question will not give any marks. At least one of the PRTs must use other style than "Formative".
BR Lassi Korhonen
![feedback2](https://user-images.githubusercontent.com/42375494/91013592-943a9380-e5f0-11ea-802f-b00013abd03b.png)

**Comment by sangwinc** [comment]
You will also need to update the question behaviour to fix this edge case.
https://github.com/maths/moodle-qbehaviour_adaptivemultipart/commit/55d1de30797a5c348e780389db8f90f273da65e5

Thanks for reporting this.
