### ISSUE TITLE
Wrong formatting of PRT feedback in compact feedback style

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#624]
If feedback style is set to compact, then the PRT feedback isn't in yellow.

![grafik](https://user-images.githubusercontent.com/12987918/91645551-3ec61280-ea46-11ea-9e84-f822ab739f22.png)

**Comment by sangwinc** [comment]
Can you email me your question and I'll check on the new version?  (I think I fixed this already...)

**Comment by mkraska** [comment]
The issue is in PRT Iyy, when type is set to compact. The above message is triggered, when changing the exponent of a in the correct solution (question test case 3).

[quiz-T-B2-MB-TM2-Hauptträgheitsmomente-20200901-1207.zip](https://github.com/maths/moodle-qtype_stack/files/5155509/quiz-T-B2-MB-TM2-Haupttragheitsmomente-20200901-1207.zip)

**Comment by sangwinc** [comment]
Are you sure that is the right question?  There is no test case 3!

**Comment by sangwinc** [comment]
Are you sure that is the right question? There is no test case 3!

**Comment by mkraska** [comment]
Yes, I am sure
![grafik](https://user-images.githubusercontent.com/12987918/91854018-5dedbb80-ec63-11ea-9ea1-3b6e946b13d0.png)

**Comment by sangwinc** [comment]
Sorry that I didn't spot you have two questions in your .xml!

The problem is that you have paragraph html tags <p>...</p> in your PRT feedback.  STACK then puts this into your feedback which is now compact, and so displayed in span tags.  You cannot have block level HTML elements inside a span tag, which is an inline element.
https://edu.gcfglobal.org/en/basic-html/blocklevel-inline-and-organizational-elements/1/
So, this is an authoring problem (not a STACK bug), albeit a subtle one.

I recommend you don't use the default editor which adds in paragraph tags....

**Comment by mkraska** [comment]
Oh, sorry for export issue. I just expected the "export this question" button in the question test page to export the question and not the quiz (from where I may have opened the question). Might be another issue though.

As to the formatting issue: I confirm that removing the <p> tag works. 
I may have misunderstood the [documentation](https://stack-demo.maths.ed.ac.uk/demo/question/type/stack/doc/doc.php/Authoring/Future_proof.md).
It says 
- <li>Paragraphs are your friends use <code>&lt;p&gt;...&lt;/p&gt;</code> tags and do not leave your content as raw text. The top level of your CASText document should consist of <code>&lt;p&gt;</code>, <code>&lt;table&gt;</code>, <code>&lt;div&gt;</code>, or CASText block elements not of raw text.</li>
Perhaps the key is in what is a "CASText document". I assumed them to be any field with enabled editor.

![grafik](https://user-images.githubusercontent.com/12987918/91883616-f7799500-ec84-11ea-9221-ac7c285bb4c9.png)

**Comment by sangwinc** [comment]
Ok, well I'm sorry about that potentially confusing documentation.  I did add a note here 
https://stack-demo.maths.ed.ac.uk/demo/question/type/stack/doc/doc.php/Authoring/Potential_response_trees.md
at the end which explains the problem.  The compact PRTs are relatively new, so I forgot about these lines in the FutureProof docs.  And nobody can read all the docs, so thanks for pointing it out and sorry for the confusion.

**Comment by mkraska** [comment]
Thank you for the clarification.
I'd recommend to also clarify the recommendation for  `<p>` tags in the Future-proof page cited above.
- what is meant by the top level of my CASText document? 
- What is "CASText document"? The whole question or any CAStext field?
- What hierarchy is the term "top level" referring to? 

A possible wording would be (just reflecting my current understanding):

Paragraphs are your friends. Use ... tags and do not leave your content as raw text. The top level of any  CASText field should consist of ..., or CASText block elements.  An exception is the PRT feedback with compact style, where this would break inline formatting.

Also, a hint in the PRT style field helper callout would be good.
