### ISSUE TITLE
Greek Letters

### ISSUE THREAD

**Issue by hayyanhelal** [maths/moodle-qtype_stack#625]
There are still a lot of problems with Greek letters in the new version:

1. Most of uppercase Greek Letters are not recognized. The validation tells that it's not recognized and asks if a lowercase letter was meant instead.
2. Some letters, like "gamma", when written lowercase one gets a capital one.
3. Some letters, like "beta", are predefined to be some function and thus it cannot be used in general.

Another occurring problem:
How could one use the letter "t" as a variable not as a unit (while using other scientific units)? It's not being accepted because the validation tells that units are case sensitive and one could have meant T instead.

**Comment by sangwinc** [comment]
Thanks for reporting this problem.
