### ISSUE TITLE
Test for validation is impossible in question tests

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#626]
in the attached question I want to test for input without units which (to confirm that this issues a validation message).
[Documentation](https://stack-demo.maths.ed.ac.uk/demo/question/type/stack/doc/doc.php/Authoring/Testing.md) says in such cases (or for missing input) one has to leave the fields for expected score and penalty emptyand set the answer hint to NULL

This doesn't seem to work because the expected penalty is displayed as "(default)" and the actual penalty field is empty.

[quiz-T-B1-MB-TM1-[no wisywig] [DE] resultant force mixed polar and cartesian-20200831-1141.zip](https://github.com/maths/moodle-qtype_stack/files/5149582/quiz-T-B1-MB-TM1-.no.wisywig.DE.resultant.force.mixed.polar.and.cartesian-20200831-1141.zip)

**Comment by sangwinc** [comment]
Thanks for reporting this.

Your question was created with version 2020061000.The current version of STACK is 2020081700, and I fixed this bug already!  I'm sorry about this.

Chris
