### ISSUE TITLE
a < b not equivalent to b > a

### ISSUE THREAD

**Issue by hayyanhelal** [maths/moodle-qtype_stack#630]
Why is "a > b" not equivalent to "b > a" in STACK?
One should add both to the answers in order to accept both, but one should be enough.

**Comment by sangwinc** [comment]
The algebraic equivalence answer test already does this, e.g. here is the test case.
https://github.com/maths/moodle-qtype_stack/blob/master/tests/fixtures/answertestfixtures.class.php#L352
