### ISSUE TITLE
Funny little example for the doc-team `4-2*sqrt(sqrt(2)+2) - 4+4*cos(%pi/8) = 0`

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#637]
A student did some extra trigonometry and "simplified" one cosine down to this, now obviously the AlgEquiv testing on itself can't deal with it but I can't seem to figure out how to make this work with the normal trigsimp/ratsimp wrappings either. Any have any ideas?

`4-2*sqrt(sqrt(2)+2) - 4+4*cos(%pi/8) = 0`

So the first is the sans and the second the tans.

**Comment by sangwinc** [comment]
Matti, some notes I made about this issue a couple of years ago are below.  Perhaps we should put all this into Maxima core?
[Almost_nice_trig.pdf](https://github.com/maths/moodle-qtype_stack/files/5294142/Almost_nice_trig.pdf)

**Comment by aharjula** [comment]
Chris, that would surely be the best solution. What worries me is the reason why they are not there already? Is it simply because the `pi/8` identities are not part of common tables and no one has not bothered doing the mixing of multiple identities to build those that can be built or is it because they bring in so much complexity that the general simplification becomes too slow?

In any case, the original question from which this came up was `int(sin(x/4),x,0,pi/2)=?` which actually is sufficiently complex to make Alpha time-out every now and then, and it does know those simplifications. In this case the question author obviously did not consider that the student would ever simplify the cosine out of the answer and thus did not use caution when selecting the range for the integral.

Given the rules you have calculated and that the student had worked out we can naturally add those simplifications, probably even at the question level but it is unlikely that the author would ever remember to do so. So a more general solution would be nice.
```
(%i1) sin ([1/8,1/6, 1/4, 1/3, 1/2, 1]*%pi);
                          %pi   1     1     sqrt(3)
(%o1)                [sin(---), -, -------, -------, 1, 0]
                           8    2  sqrt(2)     2
(%i2) cos ([1/8,1/6, 1/4, 1/3, 1/2, 1]*%pi);
                         %pi   sqrt(3)     1     1
(%o2)               [cos(---), -------, -------, -, 0, - 1]
                          8       2     sqrt(2)  2
(%i3) tellsimpafter(sin(%pi/8), sqrt(2-sqrt(2))/2);
(%o3)                        [sinrule1, simp-%sin]
(%i4) tellsimpafter(cos(%pi/8), sqrt(1-(2-sqrt(2))/4));
(%o4)                        [cosrule1, simp-%cos]
(%i5) 4-2*sqrt(sqrt(2)+2) - 4+4*cos(%pi/8) = 0,simp,ratsimp;
(%o5)                                0 = 0
(%i6) sin ([1/8,1/6, 1/4, 1/3, 1/2, 1]*%pi);
                 sqrt(2 - sqrt(2))  1     1     sqrt(3)
(%o6)           [-----------------, -, -------, -------, 1, 0]
                         2          2  sqrt(2)     2
(%i7) cos ([1/8,1/6, 1/4, 1/3, 1/2, 1]*%pi);
                       2 - sqrt(2)   sqrt(3)     1     1
(%o7)        [sqrt(1 - -----------), -------, -------, -, 0, - 1]
                            4           2     sqrt(2)  2
```

**Comment by sangwinc** [comment]
Matti,
Just noting the following from http://maxima.sourceforge.net/docs/manual/maxima_54.html#Functions-and-Variables-for-Trigonometric
`%piargs`
We should probably review the package `ntrig` and add in these rules there.
https://github.com/andrejv/maxima/blob/master/share/trigonometry/ntrig.mac

**Comment by aharjula** [comment]
Not sure if [ntrig](https://github.com/andrejv/maxima/blob/master/share/trigonometry/ntrig.usg) is the one we want to modify it seems to have some use case behind it. Maybe the `spangl` one next to it in that directory is a better start point, although again I worry that there is a reason for these not declaring all of these rules. In any case, modifying 20+-year-old libraries might have some side effects where ever they are used so this is most definitely something that needs to be checked with the Maxima people.

**Comment by sangwinc** [comment]
This example has been languishing for a while....
https://github.com/maths/moodle-qtype_stack/blob/master/tests/fixtures/answertestfixtures.class.php#L449

**Comment by sangwinc** [comment]
Maxima already has tools to do this.
share/contrib/trigtools/trigtools.mac
see trigeval.

**Comment by aharjula** [comment]
Good to know. I did try to build a table of all the possible fractions ([0,2n]/n where n < 30 and n in Fermat primes or 2^m multiple of such) and found out that even 1/17 multiples (not to mention any higher Fermat primes) start to be too complex to evaluate to algebraic expressions, by simple Maxima evaluations of the base rules of summing, doubling and halving of angles.

But in any case someone needs to evaluate that package and check if it is available in the supportted versions of Maxima and if we should include it by default. 

Maybe a variant of AlgEquiv that would agressively do trig-simplification would be the simplest way for helpping authors to use this. I think that a different test would be better than to add options to the test itself. Similarily for powers/logarithms and so on...

**Comment by sangwinc** [comment]
I'm happy to sort all this out (i.e. make a proposal).  I already checked this small, clean library and it has been around for a while...
