### ISSUE TITLE
Documentation of model answer seems wrong

### ISSUE THREAD

**Issue by knuesel** [maths/moodle-qtype_stack#640]
Hi, the [documentation](https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/Inputs.md) of the "model answer" says

> This value will be available as a question variable named tansn (where n is 1, 2, ...)

As I understand, it should be possible to use the `tans1` variable in the PRT to refer to the expression given as model answer 1. This seems wrong: as far as I can see the `tans1` variable is not set in the PRT (unless I define it manually of course).

**Comment by sangwinc** [comment]
Sorry about that confusion.  Thanks for pointing out this mistake, much appreciated!
Chris
