### ISSUE TITLE
Answer test FacForm

### ISSUE THREAD

**Issue by stebac** [maths/moodle-qtype_stack#642]
Hi, 
I'm not sure whether this is intended or not but I just observed, that the answer test FacForm is accepting just factoring out the the variable - even if there is an absolute terms. 

An example: 
If the students are to factor t: x^2-4*x+4 and enter ans1: x*(x-4+4/x) then ATFacForm(ans1, t) will evaluate to true. 
This is certainly not what I would expect.

Stephan

**Comment by sangwinc** [comment]
No Stephan, this is not the intended behaviour!  There is no case like yours in the unit tests for this function, so I think I just didn't consider it, sorry.

I'd say an expression "is factored" if it is the product of powers of (distinct?) irreducible terms.   So, that is my intention in the code, such as this.
https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stackmaxima.mac#L2264

I suppose x-4+4/x in your example is "irreducible" in some real sense.  So the behaviour is not completely ridiculous.  

Perhaps we need to have a more restrictive check that the factored form of a polynomial is a product of powers of (distinct?) irreducible polynomial terms?  I think this is what most teachers would expect (myself included).

**Comment by stebac** [comment]
Hi Chris, 
I guess I would not have considered it either if not a student had used this strategy to factor a polynomial.  
Allowing negative exponents would always leave the option of further "reducing" an expression by factoring out the variable once more. Therefore the term "irreducible" only makes sense together with non-negative exponents, which is the case for polynomials.
So I agree that restricting the factors to powers of irreducible polynomial terms should be fine.

**Comment by sangwinc** [comment]
Thanks for reporting this edge case.  By such small improvements, over the years, we make progress...
