### ISSUE TITLE
Option 'rationalnum' not working for input type 'numerical'.

### ISSUE THREAD

**Issue by shinuito** [maths/moodle-qtype_stack#643]
I've been getting a bit confused regarding the options for numerical input
https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/Numerical_input.md  

`intnum` seems like it works as expected. `rationalnum` suggests that integers are invalid and mentions that this is due to the `rational_numberp()` predicate.

>rationalnum: requires the student's answer to be a rational number (i.e. a fraction), as judged by STACK's rational_numberp predicate. Integers are excluded here!

Actually when testing on STACK version 2020070100, I'm finding that `rational_numberp(1)`, `rational_numberp(2/3)`, `rational_numberp(-2)` and `rational_numberp(-4/3)` commands are all returning false.

I don't really understand what `rational_numberp()` is supposed to be checking then, and it doesn't seem like the `rationalnum` input is really calling this predicate in this case, unless of course I'm just misunderstanding how to use it.

At the moment I can't see the `rationalnum` forbidding anything, at least in the way `intnum` forbids input.

**Comment by shinuito** [comment]
The `rational_numberp()` predicate is also returning false for the above examples on STACK version 2020081700 that I have on my mac with moodle version 3.5.

**Comment by sangwinc** [comment]
Very odd, but I can't reproduce this problem!  What version of Maxima are you using?

**Comment by shinuito** [comment]
I was using Maxima 5.42.2 on the mac version I installed myself with STACK version 2020081700. The STACK version 2020070100 is on a moodle server that the university is using, so I'm not exactly sure how to check the maxima version since I'm not an admin.

I saw that you can check the `/question/type/stack/doc/doc.php/` and I didn't realise you can just call
`{@stackmaximaversion@}` in a question and it displays it. That might even be easier than just remembering the relative path to the docs.

Is there some command I can run, or some file I can look at to see this? It doesn't seems to be in `stackmaxima.mac` or `assessment.mac`.

Oh wait if I call {@MAXIMA_VERSION@} I get [5,41,0], so presumably that is the version on the moodle server.

**Comment by shinuito** [comment]
Hi, it probably won't help (since you're obviously able to test these things yourself), but in any case here's a minimal example: 
![image](https://user-images.githubusercontent.com/26803867/97293759-032ca680-1845-11eb-87e9-b8d198f6b4a5.png)

I made a question variable `testcases:[rational_numberp(1),rational_numberp(-2),rational_numberp(2/3),rational_numberp(-4/3)]` and called that {@testcases@} in the first line, and then in the next lines I called the predicates separately {@rational_numberp(1)@}... etc

Also I've put 'rationalnum' as an option to the numerical type input box and it doesn't flag `3=3` as an incorrect type. This is independent of whether the option `Check the type of the response` is set to `yes` or `no` as that option doesn't seem to work for input type `numerical` (which is why I reopened https://github.com/maths/moodle-qtype_stack/issues/644)

**Comment by shinuito** [comment]
I apologise for not being able to pinpoint the issue sooner. 

I was looking into it again, and safe_op(2/3) is returning an empty string which is why rational_numberp() is returning false. In stack version 2020070100 the code in assessment.mac for safe_op looks like
>safe_op(ex) := block([st],
    /* Subtle changes in mapatom, in Maxima 5.42.2, with simp:false. */
    if atom(ex) then return(""),
    if op(ex) = "-" then return("-"),
    if mapatom(ex) then return(""),
    if stringp(op(ex)) then return(op(ex)),
    st:string(op(ex)),
    /* %and operators are displayed as "?%and" on some systems and "%and" on others.*/
    if ?subseq(st, 0, 1) = "?" then
        st:?subseq(st, 1, ev(?length(st), simp)),
    return(st)
)$

With maxima version [5,41,0] and [5,42,2] `mapatom(2/3)` is returning `true` and hence `safe_op(2/3)` is returning `""` and not `/` which causes rational_numberp(2/3) to be false since one of the `and` statements of the code is false. The code I can see for `rational_numberp` in assessment.mac is
>/* Do we have a rational number?  */
rational_numberp(ex) := block(
   if safe_op(ex)="/" and simp_integerp(num(ex)) and simp_integerp(denom(ex)) then return(true),
   return(false)
);

Hopefully this is more helpful. I honestly didn't know where to begin to look for these things, but I was just using ctrl+f to find things in stackmaxima.mac and then where it loaded other files like assessment.mac lead me to find the definitions of these functions.

I should probably read the developer documentation to see if that helps me get a bit more familiar with things.

**Comment by aharjula** [comment]
I am sorry that I do not have the time to look at this at all, but I'll give this little hint to the probably corect direction:
```
(%i8) simp:false;

(%o8) false
(%i9) safe_op(2/3);

(%o9) "/"
(%i10) simp:true;

(%o10) true
(%i11) safe_op(2/3);

(%o11) ""
(%i12) rational_numberp(2/3),simp:false;

(%o12) true
(%i13) rational_numberp(2/3),simp:true;

(%o13) false
(%i14)
```
Most of these structural functions are internal functions and/or meant for use only in the PRTs where simplification is by default turned off, if used elsewhere one needs to be careful with simplification. Also, simplification needs to be off outside the function call as otherwise the argument to the function would be simplified before it gets to the function. Given what you just wrote however, it seems like it is that predicate function could ensure itself that it calls `safe_op` with `simp:false`, maybe no one has ever used it outside `simp:false` contexts before.

**Comment by shinuito** [comment]
It wasn't that I was necessarily trying to use the predicate function myself in a question, rather I was trying to understand why the `rationalnum` option for the `numerical` input type wasn't working while `intnum` was working correctly. 

I guess I latched onto the idea that maybe there was an issue with `rational_numberp()` since it wasn't behaving as expected in the Question variables or the Question itself. However as you've mentioned with `simp:false;` it is returning `true` for `2/3` etc and `false` for integers `1` etc as expected.

However even with `simp:false` defined in the question variables, it doesn't change that `rationalnum` is not working at all as an option for the validation step. Maybe `simp` is `true` by default there?

Anyway I'll update the issue name, to reflect your new information, and that the issue really is about the `rationalnum` option.

**Comment by sangwinc** [comment]
Thanks for digging into this - I'm snowed under, but I will try to look into this.

**Comment by sangwinc** [comment]
Thanks very much for reporting all this, and for your careful bug report.  This makes it much easier to investigate!

With `simp:true` maxima treats rational numbers as single objects, internally `4/3` is `((RAT SIMP) 4 3) ` and `mapatom` considers this to be an "atom".  There is a basic ambiguity as to whether `4/3` should be a single object (the rational number) or the division of one integer by another. Anyway, I hope we can fix the issue.

I'm not proposing we change the documented behaviour of `rational_numberp` to think that an integer is also a rational number.  It is useful to have a predicate which confirms this really is written as the ratio of two integers.

**Comment by sangwinc** [comment]
Thanks for reporting this.
