### ISSUE TITLE
lmxchar doesn't affect the input type Matrix.

### ISSUE THREAD

**Issue by shinuito** [maths/moodle-qtype_stack#645]
I'm working mainly with STACK version: 2020070100, Maxima version: [5,41,0] and will find out about updating to newer versions in the future.

At the moment calling `lmxchar:"(";` in the Question Variables will change the display of say for instance `{@transpose(matrix([x,y,z]))@}` from the default of square to round brackets, but it doesn't seem to change the square brackets on a question input of type 'Matrix'. I'm not sure if there's already an answer option that would change this or whether it's already been implemented in a newer version or its just something specific to the setup I'm using.

**Comment by sangwinc** [comment]
No, this is because the question variables are not evaluated when the student validates.  There is an option for matrix parentheses in the question level options "Default shape of matrix parentheses".  You need to use this option for inputs.
