### ISSUE TITLE
+[space]- confusing answer tests

### ISSUE THREAD

**Issue by timlowe** [maths/moodle-qtype_stack#647]
With algebraic input (it seems independent of any particular ans1 settings)

Input: x+-1
Validation renders as x \pm 1
Validation fails as not an "expression, equation, inequality, list etc"
I'm OK with this - the student cannot progress.

However,
Input: x+ -1   [note the +[space]-, which a student entered to overcome the above example! ]
Validation renders as x -1  (fine)
Validation passes (even with "Check type of the response" enabled)
But,  AlgebraicEquiv answer test fails as at this late stage STACK now thinks the input is not an expression, equation, list etc!!

Any ideas?

Thanks,
Tim

**Comment by sangwinc** [comment]
This looks like a duplicate of issue #641, so this should be fixed.  Sorry about this.
