### ISSUE TITLE
Cannot restore STACK-demo.mbz in moodle

### ISSUE THREAD

**Issue by daisyarif** [maths/moodle-qtype_stack#648]
I tried to restore this course STACK-demo.mbz on my moodle because I would like to have a look at the sample questions. The file has been successfully imported, however when I try to access the quiz, it says "Coding error detected, it must be fixed by a programmer: Unknown question type stack"
Any help or advice would be greatly appreciated!

**Comment by sangwinc** [comment]
Ok, you need to install qtype_stack on your Moodle system.  If you just want to have a look at the question type then you can view it here:  https://stack-demo.maths.ed.ac.uk/demo/

**Comment by daisyarif** [comment]
Thank you, I have just installed qtype_stack but now it returns "Can't find data record in database table qtype_stack_options."
Is there another way to have a look at the codes behind the sample questions? I would like to duplicate the questions, but unfortunately my institution does not have a moodle, so I have to import the questions to a Moodle I created myself.

**Comment by sangwinc** [comment]
Ok, so this isn't a "bug".  Email me at C.J.Sangwin@ed.ac.uk and I'll try to help.
