### ISSUE TITLE
Dropdown Request: Edit the wording of the default not answered option.

### ISSUE THREAD

**Issue by shinuito** [maths/moodle-qtype_stack#650]
(Testing with STACK version: 2020070100, Maxima version: [5,41,0], and STACK version: 2020081700, Maxima version: [5,42,2], both with Moodle 3.5.)

I've been using dropdown along with numerical input boxes to make a question where students need to type in the domain and range of a function (and also other questions to do with sets, where the Lecturers of the module didn't like the `oo,oc,co,cc` for intervals). One thing that would be useful, since the documentation strongly recommends not to used the 'nonotanswered' option, would be the ability to edit/customize the default empty message that appears. Currently it is `No answer given` which is a very long message, and I believe it sets the minimum size of the dropdown box, since I can't make the dropdown box any smaller. 
It would be useful to either:

- allow customization of this to, for example, a much shorter message in this instance.
- have a question option to display an empty string "", say as whitespace instead (I believe the formulas question does this as default, but they have the downside of not allowing empty answers in other input types, and that can make grading tougher and possibly requiring javascript work arounds...)
- make the input box size smaller than the length of the largest option (not ideal really).

For example suppose the two dropdown boxes are something like
>ta1:[["{",true],["[",false],["(",false]];
ta2:[["}",true],["]",false],[")",false]];

Then not using the `nonotanswered` option would produce something like
![image](https://user-images.githubusercontent.com/26803867/98104853-f33d4400-1e8e-11eb-8350-6c3a6c0e5184.png)
while using the `nonotanswered` option would allow the dropdown boxes to be much smaller in keeping with the size of their options
![image](https://user-images.githubusercontent.com/26803867/98105088-516a2700-1e8f-11eb-9bc9-c812049352fa.png)

Small thing about validation: Suppose the drop down answers are strings like the above for example,
>ta1:[["{",true],["[",false],["(",false]];
ta2:[["}",true],["]",false],[")",false]];

the validation step won't display the `"{"` option (as below). This is probably a bit of a silly edge case that's not so urgent, as other things like "{some stuff}" would display correctly since the curly brackets match up and don't interfere with mbox{}. I did also try things like `"\{"` and `"\\{"` but they also run into the issue below.
![image](https://user-images.githubusercontent.com/26803867/98105798-57acd300-1e90-11eb-9e0e-8157be0efd0e.png)

Of course I can turn off the validation for the dropdown, since you can already see what you're selecting, or the other option would be to internally represent the options as 1,2,3 etc but then showing those in the validation step probably isn't useful (especially if for some reason they wanted to be shuffled) so would probably turn off validation in that case too.

As an aside point on the documentation under `Internals` https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/Multiple_choice_questions.md#internals
>Internally STACK has a number of "states" for a student's answer, including BLANK, VALID, INVALID, SCORE etc.
A student who has not answered will be considered BLANK. This is not invalid, and potential response trees which rely on this input type will not activate.

I find the sentence starting with  "This is not invalid" confusing. It's hard to understand what it's trying to convey. One would think "not invalid" would translate to valid, but then it's not clear why the PRT would not activate. If the PRT doesn't activate I would think the response must be invalid in some way.

**Comment by sangwinc** [comment]
Thanks for all your comments, they really are appreciated.
1. I'll improve the docs, thanks for pointing this out.
2. The "\{" is almost certainly a bug.  I'll try to find time to look at it.
3. Changing the "not answered" message is such an edge case I'm really sorry that I probably won't have time to address this in the short term.  You are welcome to follow through the option in the code.  If you add in an optional argument, such as 
nonotanswerd:"text you want"
and send me a pull request I'd be very grateful.
