### ISSUE TITLE
Calling ordergreat() and exdowncase() in the same question causing Algebraic equivalence issues.

### ISSUE THREAD

**Issue by shinuito** [maths/moodle-qtype_stack#651]
(Tested with STACK version: 2020070100, Maxima version: [5,41,0], and STACK version: 2020081700, Maxima version: [5,42,2], both with Moodle 3.5.)

I am experiencing an issue with using `ordergreat(x,y,z)` in the question variables and using `exdowncase()` on the variables `x,y,z` anywhere barring the SAns PRT node. What's happening is that once `ordergreat()` is used in the question then `x` is not algebraically equivalent to `exdowncase(x)` or `exdowncase(X)` outside of the PRT node (it does seem to work okay if I compare an SAns `exdowncase(ans1)` with a TAns `ta` in a PRT node). That is

`ATAlgEquiv(exdowncase(x),x)=[𝐓𝐫𝐮𝐞,𝐅𝐚𝐥𝐬𝐞,ATAlgEquiv\_WrongCase. , ]`
and
`ATAlgEquiv(exdowncase(X),x)=[𝐓𝐫𝐮𝐞,𝐅𝐚𝐥𝐬𝐞,ATAlgEquiv\_WrongCase. , ]`
(It's the same if I swap the order of inputs). I might be using `exdowncase` incorrectly but calling 
`ATAlgEquiv(exdowncase([x,y,z]),[x,y,z])`
returns
![image](https://user-images.githubusercontent.com/26803867/98234429-57780a80-1f58-11eb-9aa7-092f0c01cb69.png)

Maybe this is the intended behaviour (and it's documented somewhere)? However the confusing behaviour is then that `subst([x=1,y=1,z=1],exdowncase([x,y,z]))=[x,y,z]` rather than `[1,1,1]` which makes it harder to use the `Feedback variables` since, there also, `x` is not algebraically equivalent to `exdowncase(x)` or `exdowncase(X)`.

Specifically in my case I was hoping to have a student submit the gradient of a function `f` say `ans1`  should be `fx`, `ans2` should be `fy`,  `ans3` should be `fz` standing for the respective partial derivatives. Then in another part of the question they've to compute a directional derivative. I'd like to use the PRT to have a node that used the students answers to compute the "correct" directional derivative: "correct" being the right answer if they didn't make a mistake, but if they did, then "correct" meaning the answer they should end up with, if they make no further mistakes using their gradient. This requires the use of `subst([x=p1,y=p2,z=p3],[ans1,ans2,ans3])` for some point `(p1,p2,p3)` say or with `exdowncase(ans)` in place of `ans` to ignore uppercase variables.

I know that `ordergreat()` in maxima defines aliases for the variables so that an `x` before calling `ordergreat(x,y,z)` is not equivalent to an `x` afterward, as I think internally they are different. Calling say
<pre>f:x*y*z;
ordergreat(x,y,z);
g:x*y*z;
v1:listofvars(f);
v2:listofvars(g);</pre>

then `:lisp $v1;` gives `((MLIST SIMP) $X $Y $Z)` while `:lisp $v2;` gives `((MLIST SIMP) _101Z _102Y _103X)`.

I can't actually find a way to get my comparisons and grading to work the way I want unless I don't use `ordergreat(x,y,z)` so that's what I'm going with for now. Maybe there's a way I should deal with this through Maxima commands? I'm still fairly new to Maxima.

---------
I need to do some more testing but maybe just using `powerdisp:true;` is the better option as it doesn't seem to interfere with exdowncase or the algebraic comparison from a quick glance. The main reason I was using `ordergreat` is because it appears in the documentation in a couple of places https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/CAS/Simplification.md#ordering-terms and https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/CAS/Matrix.md#vectors.

**Comment by sangwinc** [comment]
This is all to do with maxima internals.  

`exdowncase` is defined here and is a STACK function
https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/assessment.mac#L180

I have recommended `ordergreat` but there may be better options.  `powerdisp` is not one I use much and might be better.  If you are in a position to track down the internals of Maxima here and make a specific recommendation that would be much appreciated.  I certainly don't understand every corner of the Maxima code yet!

**Comment by shinuito** [comment]
I'm not sure exactly what's happening.

If I look into why `ATAlgEquiv(exdowncase(x),x)` is failing once `ordergreat(x)` is used, I find that `algebraic_equivalence(exdowncase(x),x)` is false, and again looking into that the very first test `numerical_not_alg_equiv(exdowncase(x),x)` is `true`, so `algebraic_equivalence` returns `false` at this line I guess https://github.com/maths/moodle-qtype_stack/blob/4d317fe0ce74c9f2d164c5e5f74a1add60e7714c/stack/maxima/assessment.mac#L693 

Why `numerical_not_alg_equiv(exdowncase(x),x)` is returning `true` is harder to pinpoint. There's already differences in the first couple of lines of `numerical_not_alg_equiv` if I run it in a maxima commandline versus either of a Stack question or the CAS chat script. https://github.com/maths/moodle-qtype_stack/blob/4d317fe0ce74c9f2d164c5e5f74a1add60e7714c/stack/maxima/assessment.mac#L775  For instance if I copy the code definition of `exdowncase` to a maxima terminal session and then run `listofvars([exdowncase(x),x]` I get `[x]` regardless of whether I've used `ordergreat(x)` or not. However using either the CAS chat script or defining `pvars:listofvars([exdowncase(x),x]` I get `[x,x]` if I have called `ordergreat(x)`, or `[x]` without using `ordergreat(x)`. Then `lv` returns `[x=2,x=3]` instead and then this line

https://github.com/maths/moodle-qtype_stack/blob/4d317fe0ce74c9f2d164c5e5f74a1add60e7714c/stack/maxima/assessment.mac#L778

returns `-1` for `ev(p1-p2, lv, simp)`  https://github.com/maths/moodle-qtype_stack/blob/4d317fe0ce74c9f2d164c5e5f74a1add60e7714c/stack/maxima/assessment.mac#L783 and since this redefinition will be `true` the code should return `true` in the check 
https://github.com/maths/moodle-qtype_stack/blob/4d317fe0ce74c9f2d164c5e5f74a1add60e7714c/stack/maxima/assessment.mac#L785 This is the same behaviour as if you called something like `numerical_not_alg_equiv(x,y)`. I think points to `x` and `exdowncase(x)` being two different variables - except it doesn't happen if I work purely within maxima.

Can something be going wrong in how the commands are being relayed to and from maxima? That the variables `exdowncase(x)` and `x` are being treated differently before they're relayed to maxima, since the results from working purely within maxima or using the CAS chat are different?

I'm not really sure which files to start checking myself to answer that question. I presume it could be in some of the many php files in the CAS folder.

**Comment by sangwinc** [comment]
Thanks, this is a real help.  I'll look into this myself...

**Comment by sangwinc** [comment]
Ok, so I've reproduced the problem on Maxima 5.42.2 (But this is also present on 5.38.1 so I don't think this is a Maxima version issue).  A minimal way to reproduce this is to define variables

```
ordergreat(x);
pvars:listofvars([exdowncase(x),x]);
```

Then, the result is `[x,x]` with internal representation of `pvars` is `((MLIST) |_101X| $X)` which indicates that the two variables are not being identified as the same.  I'd expect all the other problems will follow.

**Comment by sangwinc** [comment]
Ok, for a minimal command line example compare

```
block(ordergreat(x),p: parse_string("x")-x,listofvars(p));
ordergreat(x);p: parse_string("x")-x;listofvars(p);
```
This is a question for the Maxima people!  (I'll ask them...)

**Comment by sangwinc** [comment]
https://sourceforge.net/p/maxima/mailman/message/37151139/

**Comment by shinuito** [comment]
That is quite strange. I never would've expected the `block` to return to return different results to not running something in a `block`. 

Thanks for looking into this, I kind of hit my limit of knowledge of maxima above. I still don't really understand the response to the maxima message above either :)

So are all the expressions involved `x` being treated as dummy variables inside the block, as they're being interpreted before `ordergreat` is called? While calling parse_string("x") only parses the variable after `ordergreat`?

**Comment by aharjula** [comment]
Chris, this is truly interesting and the response you got from the Maxima people basically means that one cannot ever use `ordergreat()` within feedback-variables (at least not related to the input-values) as the input-values get injected to the session before them. Luckily, we can probably ensure in the future, if not already, that the question-variables could be injected before the input-values, even if it means some extra cost for cache matching as the discriminating content will be further down the string to match. Also, the curent way of constructing the feedback-CASText might have additional problems here, but maybe in the future this will be simpler.

In any case, good to know that playing around with `ordergreat()` must always be done before the relevant expressions get defined.

**Comment by sangwinc** [comment]
Matti,
I wonder if we should develop a (short) list of Maxima functions which need to be executed in a separate block?

texput/ordergreat/orderless can only occur in the question variables.  These commands are then available to all parts of the question, including the inputs.  

Could we filter in this kind of way? It might solve a lot of other problems and give considerable flexibility. E.g. defining ad-hoc units, etc.

**Comment by aharjula** [comment]
Chris,

Sure just add a tag for them in the security-map, or actually, maybe we want a separate definition map for these. Separate as these are things that would only be validated when saving a question while the security-map should focus more on student input. Would keep things smaller, maybe even faster.

Once tagged we can then during validation check that these kinds of things only appear in question-vars (or in Stateful case question-vars or scene-vars).

By separate block execution do you mean that we should extract these from the question-vars and execute them out of order before any other question-vars execute? Note that there are plans to turn the whole question-vars into a single block of execution (like inlining the feedback-vars into a PRT-function as opposed to separate statements) and if these cannot exist inside that block then we might have trouble and would need to do such extraction.
