### ISSUE TITLE
Option to display natural logarithm 'ln' as 'log' instead.

### ISSUE THREAD

**Issue by shinuito** [maths/moodle-qtype_stack#656]
Apologies if there already is a setting for this, I was wondering if there was a Question level setting/option or other setting that could be used to display the natural logarithm 'ln' as 'log'?

It's been a request that I've gotten when making questions for a differential calculus course, and it's likely to come up again in the next semester when using stack for integral calculus.

At the moment I can't find that option/setting mentioned (it isn't visible to me on STACK version: 2020070100 although I know that's old - we're in the process of asking for it to be updated).

Supposing such an option doesn't exist, is it just a matter of adding in an option into the list here and a get method? https://github.com/maths/moodle-qtype_stack/blob/12d94193c01cc3d3f5a5ec9f7230c52f7a1cb6a3/stack/options.class.php

At some point I'd like to be able to help out with the development, although I do need to learn php and also the proper way to suggest updates on github (whether to fork and push to my own branch and then submit a pull request?)

**Comment by sangwinc** [comment]
Thank you for suggesting this.  Yes, it would be the right place to add that option. However the options code is one of the oldest bits, and when you add a new option you have to change the options part of the database, so it isn't quite as simple as adding the code in to that file (which is a real shame, sorry for this poor design....).

**Comment by sangwinc** [comment]
There is no need to add in a specific "option" as would have been in the past.  The command

`texput(log, "\\log ", prefix);`

in the question variables will now alter the display of the log function throughout the whole question including the students' input validation and in feedback generated by the answer tests.  In the future we can't continually add options for every such issue, so this is a more flexible solution for question by question issues.  The downside is we can't search over bunches of questions and update all the values of a particular option.
