### ISSUE TITLE
Wrong german translation of validation error message

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#659]
When type testing is on and model answer is a list but students answer isn't, then a validation message appears.

In the german version, this message is misleading because it demands curly brackets instead of square brackets. It says

Diese Antwort ist ungültig.Ihre Antwort sollte eine Liste sein, ist es aber nicht. Beachten Sie die Syntax: In einer Liste wird die Auflistung der Elemente (jeweils durch Kommata getrennt) mit geschweiften Klammern eingeschlossen.

correct would be (with a bit of simplified wording):

Diese Antwort ist ungültig. (missing space here) Ihre Antwort sollte eine Liste sein, ist es aber nicht. Listen werden in eckige Klammern eingeschlossen und ihre Elemente durch Kommas getrennt: [a,b,c].

**Comment by m-r-k** [comment]
You're right.
I have just submitted a correction in the moodle translation tool AMOS. It may take a moment for an update to be released.

**Comment by mkraska** [comment]
Thanks!
