### ISSUE TITLE
Display of Scientific notation in unit input type and model answer

### ISSUE THREAD

**Issue by shinuito** [maths/moodle-qtype_stack#661]
I've started testing out the Unit input type and the Units answers tests to try and create some physics questions (possibly to demonstrate in an internal webinar on STACK in our university in the future). 

I've noticed that the display of scientific notation is different depending on whether one chooses say the Algebraic/Numerical input type or Unit input type regarding the validation display. (on the left STACK version: 2020070100, on the right STACK version: 2020081700). It seems to be consistent across Algebraic and Numerical I believe.

My primary issue is that for the Unit input type no multiplication symbol appears for the input 1.2*10^4 in between the significand/mantissa and the power of ten. 
<img src="https://user-images.githubusercontent.com/26803867/100475413-f4067600-30da-11eb-9c94-51355df662c5.png" width="300" height="300"/><img src="https://user-images.githubusercontent.com/26803867/100475440-02ed2880-30db-11eb-8646-771da231ff9f.png" width="300" height="300"/>

A side issue (which maybe other users don't mind) is that I don't particularly like the display of floats like 1.2e-3 as below (it's the same display if one writes 1.2E-3). I'd probably prefer the capital E in the display at least.
<img src="https://user-images.githubusercontent.com/26803867/100475077-19df4b00-30da-11eb-8762-029c50a794a1.png" width="300" height="300"/><img src="https://user-images.githubusercontent.com/26803867/100475092-22378600-30da-11eb-8532-f6892565c7c9.png" width="300" height="300"/>

While in theory this is just for the student input, and if they prefer using powers of 10 it's not really an issue. However I'm unsure how to control the display of the correct answer (model answer) when it appears after an attempt, and it seems to default to the above form `xe-m` in particular when the exponent is too small or too big, even if one gives the model answer in a different form (`x*10^(-m)` or `xE-m` say). I guess `displaysci(x,n,expo)` is the thing I should use if I was going to convert a number to the form `a*10^(expo)`, I'm not sure what to do with something that has units. (I might try the newest version of STACK and try some more things out with `displaysci`, it was being a bit funny when converting something like `1.2E-7` to any other exponent).

<img src="https://user-images.githubusercontent.com/26803867/100476172-d4704d00-30dc-11eb-9212-47c8274fe10b.png" width="400" height="200"/><img src="https://user-images.githubusercontent.com/26803867/100476185-d9cd9780-30dc-11eb-941f-976eed28e6d3.png" width="400" height="200"/>

Or I suppose in quizzes one could turn off the display of answers and use the general feedback to display things in the format one wants (maybe?). It does seem like a bit more work, and in some basic instances maybe one just wants to write the same thing as the auto-generated text instead of a full worked solution.

I'm primarily using STACK version: 2020070100, Maxima version: [5,41,0], but the behaviour seems the same on STACK version: 2020081700, Maxima version: [5,42,2], both with Moodle 3.5. Apologies if any of this has been fixed in the most recent updates (I'll hopefully move to the newest version soon -- although as a side question, if on github it says STACK 4.3.7 Build failing, should I wait until it is not failing to update?).

Aside: I'm still learning to use the units functions in STACK but I didn't see a way to simplify SI units in the documentation so far. That is suppose one would like C*T/kg to simplify to `s^(-1)` `1/s` or `Hz`, I was thinking to use the function `stack_unit_si_to_si_base(ex)` in stackunits.mac although in this particular case it displays say `stack_unit_si_to_si_base(stackunits(4.31,C*T/kg))` as `4.31 x 1/s` with a cross for multiplication between the number and unit. One could just do the numerical calculation (for a teachers answer say) and then put in the right units at the end but it might be nice to have an option to massage the units of the answer to a specific SI form. (Maybe I'll think about it some more and do more tests and write up a separate request if need be - I'm just imagining maybe one could want an answer specifically to end up in MHz or kHz etc and have randomization in the question variables etc)

**Comment by aharjula** [comment]
Not a full answer but some specific bits of it:

1. The differences in the display are mainly due to the units input making a `stackunits` object of the student's input and it having a different presentation style. Other inputs do not do such things to the input. 

2. The teacher's answer:
```
tans: stackunits(1.2345678,m);
/* One would hope that one could write the following but unfortunately 
   the disp* functions do not like units, they probably should. */
/* tansdisp: dispsf(tans, 2); */
/* So we do it in parts */
nums: stack_units_nums(tans);
units: stack_units_units(tans);
tansdisp: stackunits(dispsf(nums,2), units);
/* Or as one liner  */
tansdisp: stackunits(dispsf(stack_units_nums(tans),2), stack_units_units(tans));
/* In any case you use that tansdisp as the teacher's answer in inputs and unit-tests. 
   Especially. if you are testing for a specific number of significant digits or decimal places.
*/
```

3. Conversion of units, seems to be broken (it has some interaction with the previous example and breaks down), `stack_unit_si_present(value, unit)` was the tool to do it but apparently, something has broken with it. It also has a mode where one gives it a list of units and it picks the one where the numerical part is reasonable i.e. it can select between metres, centimetres and millimetres based on the value. But as said something has broken, hopefully, it can be fixed for the next update.

From memory, it should have done things like this, but practically no one used it:
```
(%i9) stack_unit_si_present(tans, nm);
(%o9) stackunits(1.2345678e+9,nm)
(%i10) stack_unit_si_present(tans, [km,mm,cm,um]);
(%o10) stackunits(123.45678,cm)
```
It would work with more complex units as well, but one must make sure that the units are equivalent otherwise one can get something completely random out of it.

**Comment by aharjula** [comment]
Actually, that previous one (the stack_unit_si_present) works just fine as long as one does not define a variable named `units`. If one does that then `if not member(units, features)` style logic inside the libraries breaks. @sangwinc maybe we need to forbid `units` as a variable or maybe just change the feature name to something less likely to conflict., or add an apostrophe...

An example of the trouble is short:
```
tans: stackunits(1.2345678,m);
units: stack_units_units(tans);
stack_unit_si_present(tans, nm);
member(units, features);
member('units, features);
```
