### ISSUE TITLE
Feature request: Check of physical dimensions in algebraic input

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#665]
Doing a check for units matching is a standard plausibility test for symbolic expressions representing physical quantities.

Because it is so generic, it would be good to have it as an option to the algebraic input tests, much like the test for missing or extra variables.

The main logic for such a test has been proposed by Leo Butler [here](https://moodle.org/mod/forum/discuss.php?d=406908#p1673210).

![image](https://user-images.githubusercontent.com/12987918/101759766-4af84c00-3ada-11eb-91d2-aa89fd949651.png)

So the user has to specify a list of variables and a list of unit symbols. The units from STACK can't be used, because the input namespace and the units namespace aren't disjoint and there are too many common clashes between symbol names and unit names.

My proposal would be to specify something in the test options like

[vars, answers]: [ [l=LE, g=LE/ZE^2, m=ME, c=ME/ZE^2,b=LE], [S_a2=1/ZE^2]];

and let the algebraic test produce additional (formative) feedback in the case of false:

"The dimension of your answer is correct" or "Perform a dimension/units check, there seems to be a mismatch."

Note that the vars list must be processed to replace l=LE by l=l*LE before applying it to Leo's procedure.

The dimension check must be preceeded by a check for extra variables (with no replacement rules in the vars list). In case of extra variables, the dimension check is pointless and the feedback should be

"Variables ... aren't given. Please restrict your answer to ...."
The latter is of course a matter of taste.

This would make it much easier to implement consistent question behaviour. By now you can do all this but it requires two additional PRT nodes per input.

With the proposed user interface this comprises no added complexity (more option fields) for all those not interested in the feature, but provides a huge simplicifcation for those who are interested in this.

**Comment by mkraska** [comment]
The check has been implemented as part of Meclib, see [fb_dim](https://github.com/mkraska/meclib/wiki/fb_dim).

**Comment by sangwinc** [comment]
This can now be done with the bespoke validation.
