### ISSUE TITLE
Radio-buttons for selecting algebraic expression

### ISSUE THREAD

**Issue by miroi** [maths/moodle-qtype_stack#668]
Hello,

we hit a STACK question where the correct answer **ta1** via radio button, containing algebraic expression, is evaluated as incorrect.

Variables in the question:
~~~
c1x:rand([17.3,17.2,17.4,17.1,17.5]); /* koncentrácia molekúl vodíka */
c2x:rand([6.1,6.2,6.0,6.4,6.3]); /* koncentrácia molekúl jódu */
c3x:rand([67.9,67.8,67.7,68.0,68.1]); /* koncentrácia jodovodíka */

Kcvztah: (c1*c2)/(c3*c3); /* SPRAVNY vzťah pre rovnovážnu konštantu */
Kcnesp1: c1*c3/c2;
Kcnesp2: c1*c2/c3;
Kcnesp3: c1*c1;
ta1: [[Kcvztah,true],[Kcnesp1,false],[Kcnesp2,false],[Kcnesp3,false]];
ta1: random_permutation(ta1);
~~~

The link to xlm of that  question:  https://drive.google.com/drive/folders/1b_Gepbjw46de2ohwlq9E9vMasSqldh2O?usp=sharing

And the printscreen showing "incorrect" correct answer:
<img width="960" alt="radiobuttons" src="https://user-images.githubusercontent.com/1047336/103107552-be07d380-463f-11eb-80ee-cb144e2e39a2.png">

**Comment by miroi** [comment]
Well, I manipulated the algebraic expressions, simplified them, but it did not work... Still incorrect answer shown.

**Comment by sangwinc** [comment]
Ok, I think this is a question authoring issue.  In your potential response tree you have set the score to be zero!  This means your question works fine, up to the point you assign a score.  Then you give the correct answer a score of zero.  The feedback "Incorrect answer" is triggered by the score here.  If you disagree, please reopen the issue!

**Comment by miroi** [comment]
Hello, when I changed the Question value to 0 in prt1, I got programmers error: " There is an error authoring your question. The $totalvalue, the marks available for the question, must be positive in question (LFUPJŠ2016-630) Tepelný rozklad HI - TESTOVACIA". Any help, please ? We have Moodle 3.9 and quite recent version of STACK.

**Comment by sangwinc** [comment]
Yes, you have to have a non-zero value in the question because PRT outputs get scaled, and you would divide by zero.  This is not a bug!

If you want to give your question a zero weight, then the place to do this is the quiz not the question.  Internally, the questions use scores from PRTs to decide if a student's answer is "correct".

**Comment by miroi** [comment]
Dear Chris,

no way.

I had to reset Question value to 1 (nonzero) in prt1 to get the question working within a Quiz and StudentQuiz. Likewise the question "Default mark" must be nonzero - student must get mark when they pass this question. 

When I try this question in Quiz and StudentQuiz (not internally in question bank), I am still getting "Incorrect answer".

What to do ? 

![Quiz](https://user-images.githubusercontent.com/1047336/103171611-f4b33900-484d-11eb-9050-4a4673199360.png)
![student-quiz](https://user-images.githubusercontent.com/1047336/103171617-f846c000-484d-11eb-953b-3716304821fb.png)

**Comment by sangwinc** [comment]
I'm sorry you are still having problems.  In the PRT choose to modify the mark in the true branch to be "1".  Then the question works.  

<img width="960" alt="MCQ" src="https://user-images.githubusercontent.com/781615/103173315-1e6e5f00-4852-11eb-8f75-1f26a1ce83db.png">

**Comment by miroi** [comment]
Excellent ! So this the prt1's Score value that must be set to 1 !

Closing this issue as really solved.
