### ISSUE TITLE
integrate, outative, noun forms

### ISSUE THREAD

**Issue by NeilStrickland** [maths/moodle-qtype_stack#670]
Currently STACK defines `int` to be an alias of `integrate` (`stack/maxima/stackmaxima.mac`, line 81) and defines `nounint` to be a wrapper around `'integrate` that checks that the integration variable is specified explicitly (`stack/maxima/assessment.mac`, line 1292).  Evaluating `properties(integrate)` in Maxima shows that the `integrate` function has properties `noun`, `outative` and `rule`.  These properties ensure that `'int(a/x,x)`, `'integrate(a/x,x)` and `nounint(a/x,x)` all simplify to `a*'int(1/x,x)` (for example).  The expression `'nounint(a/x,x)` does not simplify, but also `'nounint(a/x)` does not generate an error about the unspecified variable of integration.  This behaviour seems undesirable, and incompatible with general expectations about the behaviour of noun forms (and it breaks some code for integration questions that I have just ported from Maple).  I would suggest that 
* The behaviour of `integrate()` should be unchanged, to avoid messing with the internals of Maxima.
* Instead of `alias(int,integrate)` we should have `int([ex]) := apply(integrate,ex)`.  This ensures that the verb form of `int` invokes `integrate`, but the noun form does not do any simplification.
* Then `nounint` should be defined using `nounify(int)` rather than `nounify(integrate)`.

The function `safe_op()` should be adjusted if necessary so that it still returns `"int"` for `integrate()`, `int()` and `nounint()`.  The `tex()` and `tex1()` functions should be adjusted so that they typeset `int()` in the same way as `integrate()` (I am not sure what is the most efficient way to arrange that.) 

Am I missing any issues here?

**Comment by sangwinc** [comment]
Gosh Neil,
Thanks for this very helpful suggestion. Yes, I think this will clarify the situation and I'll look into sorting this out.
Chris

**Comment by NeilStrickland** [comment]
I can make a PR from this branch if you want: https://github.com/NeilStrickland/moodle-qtype_stack/tree/nounint.
But I am not well-practiced with the whole PR process.

**Comment by sangwinc** [comment]
Neil,
Oh dear! We are working in parallel!  I'll push my changes once the unit tests finish running and we can compare approaches. Not much substantial differences but we have created conflicts.
Chris

**Comment by NeilStrickland** [comment]
No worries.  I have not worked out how to deal with the unit testing framework yet, so your version will probably be safer.

**Comment by sangwinc** [comment]
I think the only significant difference is the way I've hooked into the existing tex code to display int with the same internal tex function as integrate.
https://github.com/maths/moodle-qtype_stack/commit/9557da8069c2a5a5972d87bdae0d9367b8a8db58#diff-25243c3a58024b848a786bd282b541f118e833ee9bcf69378d1a51c14ce58c10R212

Are you happy with this?

**Comment by NeilStrickland** [comment]
That's fine, I would have done it that way if I had known how to.

**Comment by sangwinc** [comment]
Ok, no unit tests fail (and plenty use int, nounint etc.) so I'll close this issue for now.  Thanks for the suggestions in fixing it, always much appreciated.
