### ISSUE TITLE
TEST_FAILEDThe answer test failed to execute correctly: please alert your teacher. TIMEDOUT

### ISSUE THREAD

**Issue by miroi** [maths/moodle-qtype_stack#671]
Hello,

I have simple formula producing big numbers like 4.85E22 .  But I can not make it working without showing error.

The PRT is giving error "TEST_FAILEDThe answer test failed to execute correctly: please alert your teacher. TIMEDOUT" when I want to check it againts the tollerance +/- 0.01e+22.  

Any help please ? 

The printscreen:
![bignum](https://user-images.githubusercontent.com/1047336/103646146-79423d80-4f59-11eb-9fe4-6bc65000a0f4.png)

The attached zipped xml question:
[questions-TestovacíKurz-Test with large numbers-20210105-1321.zip](https://github.com/maths/moodle-qtype_stack/files/5770093/questions-TestovaciKurz-Test.with.large.numbers-20210105-1321.zip)

**Comment by miroi** [comment]
Well, when I change answer test in PRT2 to "AlgEquiv", I got "Incorrect answer."

![bignum2](https://user-images.githubusercontent.com/1047336/103663061-f88f3b80-4f70-11eb-9ac0-1c0cef3d77ee.png)

**Comment by sangwinc** [comment]
Ok, I'm looking into this issue.  A quick fix is to make sure the second argument of the numerical test really is a number, and not a "displaysci" object.  So, create another variable with just the value in it.

**Comment by miroi** [comment]
Ah, you made the fix. So, I will not do the workaround as you are suggesting, rather I will wait for a new official release.  When it will be ?

**Comment by miroi** [comment]
Well, indeed, in between I need to do the quick workaround: would you please tell me how to convert "ta2:scientific_notation(subst([m=mx,M=Mx,NA=NAx],N_vztah),2);" into a number for prt2 ?

**Comment by sangwinc** [comment]
You need two variables

ta2:scientific_notation(subst([m=mx,M=Mx,NA=NAx],N_vztah),2);
ta3:subst([m=mx,M=Mx,NA=NAx],N_vztah);

Use ta3 in the PRT.
