### ISSUE TITLE
Add support for the sgn() function

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#672]
I propose to accept sgn() as alias for signum() in user input and in all cas text and question variables and add a texput rule

     texput("signum","\\mathrm{sgn}");

This rule is missing in Maxima. This would allow for input, validation and \({@@}\) display to be consistent with the outside world, where the standard for the signum function seems to be sgn(). Also, please add a hint on this function in the doc of supported functions.

See [Forum discussion](https://moodle.org/mod/forum/discuss.php?d=415711)

**Comment by sangwinc** [comment]
Ok, I've thought about this (and I'm sorry other work has delayed this for so long).  

I agree we should have an alias of "sgn".

I agree both sgn and signum should be output as "sgn" in TeX.  I don't think we need an option here.

Chris
