### ISSUE TITLE
Strange error involving ssubst

### ISSUE THREAD

**Issue by NeilStrickland** [maths/moodle-qtype_stack#674]
Has anyone else seen this?
``` CASText failed validation. (%i5) STACK-OUTPUT-BEGINS> `ssubst': unsuitable start or end position. -- an error. (%i6) (%o6) ```
This is extremely strange, for a number of reasons.
1. When submitting an answer to a certain large and complex question, I get a `TIMEDOUT` error.  (This is fast, even after clearing the cache, so it does not seem to be a real timeout.)
2. Running the same code in the CAS Chat  window gives an error as above
3. If I run Maxima from the command line, load `stackmaxima.mac` and run the same code, I get no error, either on my Linux server or my Windows desktop.  On the server I am using the same Maxima executable as is invoked by Stack via MaximaPool.
4. I can make the error go away by reducing the size and complexity of the question.  No specific piece seems to be critical, but it is not a straightforward count of characters either.  Some size-reductions work and others do not, with no obvious pattern.
5. The function `ssubst` can be called with three or six arguments.  The error message only makes any sense for the six-argument form.  I do not directly call `ssubst`.  The Stack source code has a number of calls to the three-argument form, which all seem completely harmless, and no calls to the six-argument form.  
6. In the Maxima source code, `ssubst` is defined in `share/stringproc/stringproc.lisp`.  There are a couple of functions in the same file that call `ssubst`, but none of them seem to be relevant for this issue.  As far as I can tell, there are no other calls to `ssubst` anywhere else in the Maxima source code.

Unfortunately, it is hard for me to post a self-contained question file as I am using a modifiied version of Stack.  However, I may try to find a way around that if no one can offer other suggestions.

**Comment by NeilStrickland** [comment]
This seems to be a bug in Maxima which I have reported at https://sourceforge.net/p/maxima/bugs/3700/.  It should be possible to work around it by refactoring the calls to `ssubst` in `stackmaxima.mac`.  I will sort out details of that shortly.

**Comment by aharjula** [comment]
Thank you for tracking this down. Do you happen to know if it is just the GCL version that has this problem? For me trying in SBCL (5.42.2) even inputting that string is an interesting thing, it seems to parse it for quite a long time, actually does not even complete (in half an hour). I have to wonder though if it is the shell that has trouble parsing that and if that string would work if being generated programmaticaly from smaller bits. Quick split to small fragments for `sconcat` did not do the trick though.

Seems like a deep string library problem, I wonder what we are to do if we have to have even more slashes in play for the future markdown support...

**Comment by NeilStrickland** [comment]
I have updated the report on the Maxima bug tracker, and will repeat the main point here.  If we set `s` to be a string consisting of the letter "a" repeated 1355 (or more) times, and evaluate `ssubst("b","a",s)`, then we get the error `ssubst: unsuitable start or end position.`.  So the issue is not with the special properties of the backslash character or the detailed structure of my earlier example.  It may be related to the fact that `ssubst` is defined recursively, but my knowledge of lisp is not strong enough to be sure about that.

**Comment by aharjula** [comment]
Looks good and will be very valuable when CASText2 is coming as it will lead to way more sting content being pushed through Maxima and if we have to deal with double escaping for markdown as well this will be something that would have broken things quite badly.
