### ISSUE TITLE
How to create Bode Diagrams with Stack

### ISSUE THREAD

**Issue by TimoFK** [maths/moodle-qtype_stack#675]
In CAS Maxima we can create a Bode-Diagrams with functions and variables for bode. 
But in Stack-Moodle there is i.e. prohibited functions: load and a  bode_gain.
The example you can find here:
code-source: [https://maxima.sourceforge.io/docs/manual/de/maxima_36.html](url)

If you guys know how to make bode diagrams in Stack-Moodle, it will really help me, thanks.

**Comment by timlowe** [comment]
You can generate these plots with the standard "plot" function, by plotting an appropriate  functions. I've attached an outline example if that is of any help. (Moodle XML with disguised file extension.)
[questions-Bode plots-20210129-1532.xml.txt](https://github.com/maths/moodle-qtype_stack/files/5894776/questions-Bode.plots-20210129-1532.xml.txt)

**Comment by sangwinc** [comment]
Thanks Tim, this is super helpful.

I've reviewed the bode package and there isn't really much to it!  I'm not going to support this package, so instead this issue is resolved by documentation.
