### ISSUE TITLE
Unit "kWh" for Energy in addition to Joule

### ISSUE THREAD

**Issue by jensfortmann** [maths/moodle-qtype_stack#678]
In the energy sector, the unit Joule is often used for primay, mainly thermal, energy in the form of GJ or PJ.
In electrical engineering and for studies on electrical energy, the unit Wh (or kWh, MWh, GWh) is commonly used to describe  
1. **Batter storage** capacity, like 100 kWh for an electric car or 2 TWh as Energy needed to supply on country with electricity for one day.
2. **electrical Energy** consumtion, like 600 TWh as electrical energy consumption in  Germany in 2019, or 120 TWh per year as needed energy if we switch for fossil fuels to electric cars. 
3. **electrical metering**, the price of energy at home or at the stock markets is defined in ct per kWh or €/$ per MWh.

It would be very helpfull if this unit could be included in the variable list of "casstring.units.class.php". I am aware thatt this is not SI, but industry standard for electrial energy.
In tests for my students it is not realistic to use Joule if the literature and books use kWh / MWh / GWh as common unit for Energy.

BR, Jens

**Comment by sangwinc** [comment]
Jen,
Thanks for this very helpful suggestion.
Chris
