### ISSUE TITLE
random_subset

### ISSUE THREAD

**Issue by impemic** [maths/moodle-qtype_stack#682]
The functions like
random_subset(a)
do not work on our system. Do you know why?
![2021-02-03_100628](https://user-images.githubusercontent.com/56223576/106723582-8bbaa000-6607-11eb-8a00-31c4aaea2959.jpg)

**Comment by aharjula** [comment]
Well, that function was added to the code-base seven months ago and probably appeared in the primary branch during the break just now. Has your system been updated since then? Place this into the question-text to see what the version is: `{@stackmaximaversion@}`

**Comment by impemic** [comment]
The version is 2020070100

**Comment by sangwinc** [comment]
Normal users can easily find which version of STACK they are using by going to your local docs.
E.g. on the demo site https://stack-demo.maths.ed.ac.uk/demo/
the local docs are in https://stack-demo.maths.ed.ac.uk/demo/question/type/stack/doc/doc.php
This means you can find the docs for the version you are actually running, not the very latest version.

To avoid doubt, look at the very bottom of the docs front page.  The demo site says "Your site is running STACK version 2020120600". This number is literally year_month_day_num.  So, if your version is before 2020070100 (July 1st 2020) then you won't have this feature!

**Comment by impemic** [comment]
Thanks

**Comment by sangwinc** [comment]
Oh dear, you missed this feature by 2 days!  Next update...
