### ISSUE TITLE
Separating out STACK admin functions from question maintainance.

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#683]
Since qtype_stack is an extension to the Moodle quiz its own “admin page”.  This is available in moodle under

Site administration > plugin > question > type > stack

The page is where a site administrator sets critical settings, such as which version of Maxima is being used and how the Moodle PHP scripts connect to Maxima on the server.  As such, access to this page carries quite a high level of trust and responsibility.  It is currently limited to “moodle admin” users.

Over the years we have added a lot of features to this page which are useful, essential indeed, to a slightly wider group of people. In particular those who write a lot of STACK questions and who are responsible for longer term maintenance of STACK questions would benefit from access to the following:

- Documentation for local STACK: you can find out which features of STACK really exist on your server (whereas the public docs are for the latest release, which is frustrating to users you are trying to help).
- The healthcheck script helps you verify that all aspects of STACK are working properly (probably should be admin only).
- The CAS chat script lets you test the connection to the CAS, and try out Maxima syntax. (This page is easily available at the bottom of a question testing page.)
- The answer-tests script verifies that the answer tests are performing correctly. They are also useful to learn by example how each answer-test can be used.
- The input-tests script provides test cases of how STACK interprets mathematical expressions. They are also useful to learn by example.
- The run the question tests in bulk script lets you easily run all the STACK questions in a given context.
- The fix maths delimiters script can be used to replace old-style delimiters like @...@, $...$ and $$...$$ in your questions with the new recommended {@...@}, (...) and [...].

It would be very helpful indeed if a wider group of people, particular those writing a lot of STACK questions and maintaining them, have access to all these features, but the bulk testing is probably the most important.  (Bulk testing is also available via the server command line, but that really does require expert access.)

I'm proposing to separate/duplicate access to these features onto a separate page.  Questions for Matti and Tim:

1. What Moodle "role" should have access to these functions and how do I implement that?
2. Any concerns over wider access to bulk testing?  I don't think we want random teachers running this every day...

**Comment by timhunt** [comment]
Asking "What Moodle 'role' should have access to ..." is a classic wrong question in Moodle development. That is not your business as a developer. It is up to the admin. As developer, you should define appropriate capabilities, and leave it up to the admin to define roles. 

At the moment we just have 'qtype/stack:usediagnostictools'. I would suggest splitting that into 'qtype/stack:viewdocs' (for the docs) 'qtype/stack:viewhealthcheck' (for healthcheck), 'qtype/stack:usecaschat' (for caschat) and 'qtype/stack:runselftests' (for selftests). That gives admins full control.

The issue with the selftests is that they put a lot of load on the server. It might be bad if a teacher decided to run those in the middle of an exam.

-----

A more significant question is which context you will check the permissions in. There is an issue that teachers are only teachers within one course, but naturally these tools live in the system context, where most users just have 'Authenticated user' role.

I tried to get round that with the current checking of qtype/stack:usediagnostictools, but that is probably not great. (Basically, pass an appropriate context id in the URL when following a link to one of these tools, which are already separate page.)

That raises the other question: from where will you link to these tools? And on the page for the tool - and they are all already separate scripts - how will you set up the standard Moodle navigation elements?

**Comment by aharjula** [comment]
I do worry that if people can bulk test everything then they will do that and get worried about things they should not even worry about. So to me, the important thing is that the bulk testing must limit to the contexts where these people have the rights to the materials. Probably, just allow the course teacher to see that their courses materials work though might be nice to not have the tool limited to a single course for those that need to check larger subsets of the systems STACK questions.

So simply no testing materials you cannot edit is the key. Preferably allow testing to be easily targeted to specific courses or even quizzes.

For non-admin users, we also need to worry about the load from bulk testing, it might be that if people are running them in small Moodle installs they will tie up resources in a way that will cause trouble. So could be that access to that would require special rights that could be revoked if need be. It is a single thread of load but still a lot of load and will eat MaximaPool and DB capacity at quite a high rate which could cause a DOS style problem if executed at the wrong time. Imagine a trouble maker importing the demo-course and running bulk-tests on it, that is a task that currently takes an hour on a well-tuned server and on a small system much longer, during that time other users would need to deal with the server being slow (probably DB load is the major thing).

Note that at some point we could start removing things like the delimiter fixing script as they start to turn to relics confusing people.

As to the answer-tests script, while it does indeed work as documentation in addition to the unit-testing, it might make more sense to have it provide more documentation and interactivity if it would be present to non-admin users. It could also include most of the functionality of CAS-chat if it included simple tools for generating the values to the tests and allowed direct testing of them with specific inputs. This would benefit from the metadata and test specific logic that the more files solution in Stateful has... The input-tests could benefit from similar interactive documentation, built from the option-metadata like in input2...

The documentation could simply be linked to the question-editor... and as it is already open should not cause trouble. All others could be linked in the same place.

**Comment by sangwinc** [comment]
So, two UK universities (in addition to Edinburgh) now have academic colleagues who write STACK questions as the majority of their role.  They typically have access to a wide range of courses, and need to dip into different courses they are not teaching.  They have responsibility to help normal teachers write STACK questions and these people need to be able to run bulk tests.  They have enough expertise to know when to run bulk tests, but don't need to mess with server settings!   Also, for now, and for this group we don't need to worry about them having access to all courses/contexts on a site just to be aware that they do

I hope this makes sense? 

Thanks for the tip about "usediagnostictools". That gives me a hook to get started.

Chris

**Comment by sangwinc** [comment]
I've created an index page, but not changed any functionality.  For the problem I'm trying to solve, the colleagues will basically have multi-course responsibility and will almost certainly be able to edit any STACK questions (that is why they are employed) but they are not complete moodle site admins.  And they should not have access to the qtype_stack page.  

They are capable of understanding the load implications, so that is fine.

>  So simply no testing materials you cannot edit is the key. Preferably allow testing to be easily targeted to specific courses or even quizzes.

In the case I'm trying to solve we'd want these colleagues to be able to alert those with editing rights to things like "you need to add question tests"!  So, for now I disagree.  This is paradoxical, but actually I'd expect them to actually have editing rights anyway.

> Note that at some point we could start removing things like the delimiter fixing script as they start to turn to relics confusing people.

Possibly, but the functionality is really useful when colleagues use $s.  This is in the question editing logic so the bulk convert functionality is almost redundant.  I'm still giving some support to people with very old systems, so let's not bin something which isn't broken yet!

Tim, I agree you are right logically wanting to separate out the capabilities.  I'm happy to close the issue here since we have one specific capability for now which solves my problem, without complicating things. 

I've been meaning to move all these scripts (and there are now quite a few) into a single purpose sub-directory for some time, so this is a useful refactor/tidy.

Any objections to the changes and closing this here?

**Comment by sangwinc** [comment]
Ok, I've merged this back into dev.
