### ISSUE TITLE
Error using UnitsRelative if sans = 0

### ISSUE THREAD

**Issue by jensfortmann** [maths/moodle-qtype_stack#688]
Using UnitsRelative in the PRT-section I seem to get a wrong evaluation if the expected student answer is 0.0
![image](https://user-images.githubusercontent.com/59441937/107936874-789ebd00-6f83-11eb-943d-b4eced08b854.png)

![image](https://user-images.githubusercontent.com/59441937/107936894-7dfc0780-6f83-11eb-860f-e0af26a6077b.png)

if I replace UnitsRelative with UnitsAbsolute it works fine.

![image](https://user-images.githubusercontent.com/59441937/107937060-b865a480-6f83-11eb-9e1c-4852773a5c79.png)

![image](https://user-images.githubusercontent.com/59441937/107937087-c1ef0c80-6f83-11eb-9405-bcb4ec2d9c03.png)

One obvious question would be - why not use UnitsAbsolute then? 
Well - the input is generated by a data base of questions, and one of these datasets could require the student to input zero as an answer. I do not want to modify the PRT depending on the data selected.  

For an answer of zero, UnitsRelative is probably not defined due to a division by zero (I did not look at the code). Maybe It could be a solution to switch the evaluation methodology from UnitsRelative to UnitsAbsolute if the expected answer is zero or very close to zero. 

Could that work?

**Comment by sangwinc** [comment]
Ok, this is an edge case we already fixed in UnitsRelative.  I've added in your example, and this works on my development system. What version are you using?

**Comment by sangwinc** [comment]
This is odd.  We fixed this 5 years ago!
https://github.com/maths/moodle-qtype_stack/commit/1afb0b674d655f3effa005a029f5de2e6c80353b
Perhaps you could email me your whole question and I'll take a look at what is going on?
