### ISSUE TITLE
Upgrade of JSXGraph to 1.2.1

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#690]
I'd need some JSXGraph features (Math.Clip) which aren't supported in 0.99.7. Is there any hope for an JSXGraph update in the near future?

Or is there any way to locally use higher versions than officially supported?

**Comment by aharjula** [comment]
A new branch based on master has been created with 1.2.1. Hopefully, someone could test it and let us know if it works. We had one branch with 1.1 already but it was never tested enough, too many things to do and so on.

If you have access to a Moodle server and don't want to update your recent STACK install, you can simply replace the `/question/type/stack/amd/` directory with the one from the new branch. And remember to purge the Moodles caches (especially the JavaScript cache) you can then test things with it, to ever restore the original and directory and purge caches again. However, I do recommend a separate install for the testing to avoid all side-effects.

https://github.com/maths/moodle-qtype_stack/tree/jsxgraph1.2.1

Initial testing showed that it loaded on Chrome and Firefox, but many more need to be checked and it needs to do more than just load.

**Comment by aharjula** [comment]
I have a theory that has not been tested, but it seems to me that if one takes the `jsxgraphcore.js` file from the normal JSXGraph release and changes one string (`define("jsxgraphcore")` -> `define("qtype_stack/jsxgraphcore-lazy")`) in it one can simply replace the `/amd/build/jsxgraphcore-lazy.min.js`-file with it. This has not been tested, and will more than likely depend on the Moodle version and its way of loading stuff.

And we really would not want to do that renaming of the defined thing, but we need to be able to address the library through the module system and for that it needs a name of a specific style. The `-lazy` suffix is also important.

**Comment by mkraska** [comment]
Thanks for the hints. I'll ask my admin if he can do the replacement trick on our external moodle server. And I am exploring the level of support I can get for running a dedicated development server.

**Comment by mkraska** [comment]
OK, our admin has exchanged the directory contents and reset the cache.
There is a problem with math latex stuff, which I do not really know if that change is to blame:
When Mathjax filter is on and Tex filter is off, the math texts aren't processed in the question text (no mathjax content in the JSX itself for now). 

The console error message is

![image](https://user-images.githubusercontent.com/12987918/108502234-c896c000-72b2-11eb-927d-1f71a563d238.png)

**Comment by aharjula** [comment]
Well, that should be easy, please check the link in the upper error message and ask the admin to check the MathJax filters config.

And one generally does not have both of those filters (MathJax and Tex) on at any point. I tend to ask people why they even have the Tex filter active at all when MathJax seems to do things better.

**Comment by mkraska** [comment]
Somehow (did our admin work on weekend?) the problem disappeared. The updated version seems to run.

![image](https://user-images.githubusercontent.com/12987918/108606292-9d4ac880-73b9-11eb-99b3-e0b9bead0f5c.png)

**Comment by aharjula** [comment]
Ok. I'll assume it has been tested and will merge it to the current dev, that will probably turn into a release soon.

**Comment by aharjula** [comment]
Merged to dev.
