### ISSUE TITLE
$union": argument must be a set

### ISSUE THREAD

**Issue by miroslavfikar** [maths/moodle-qtype_stack#699]
The attached STACK single choice question generates warning in preview but not in the quiz:
The input has generated the following runtime error which prevents you from answering. Please contact your teacher.
"$union": argument must be a set; found: oo(-inf,-7)

[test-ZM_II-interval-20210312-1223.xml.txt](https://github.com/maths/moodle-qtype_stack/files/6129663/test-ZM_II-interval-20210312-1223.xml.txt)

**Comment by sangwinc** [comment]
Thanks for reporting this.  Much appreciated.

A subtle bug!
