### ISSUE TITLE
Why isn't the "specific feedback" field of type CAS text?

### ISSUE THREAD

**Issue by KingaS03** [maths/moodle-qtype_stack#701]
We are creating an online self-assessment tool for the potential future students of mathematics at University of Bern. We are using STACK problems for it, integrated into an Ilias test.

We are using also the "specific feedback", which is independent of students' answers. In some situations we would like to include question variables into this field. Unfortunately, the "specific feedback" doesn't support CAS text. We were wondering what is the reason for this and whether it would be possible to change the type of the "specific feedback" field to CAS text.

**Comment by sangwinc** [comment]
Sorry about the misinformation in the docs here.  Actually the specific feedback is CAS text and has been for ages!  (I don't use this feature, so didn't immediately remember.)  Can you try your system and if it does not work, please let me know the version number you are using (bottom of the home page of the docs on your server).

If you still have problems, please re-open this issue.

**Comment by KingaS03** [comment]
In Ilias the text of specific feedback is not handled as CAS text.
<img width="594" alt="Ilias_SpecFeedback_Ex" src="https://user-images.githubusercontent.com/43032259/114032215-64d55000-987c-11eb-8b14-7d82d5d7edc1.png">

In Moodle however running the same problem generates the desired specific feedback output. <img width="809" alt="Moodle_SpecFeedback_Ex" src="https://user-images.githubusercontent.com/43032259/114032229-67d04080-987c-11eb-84e1-10ce2848cb15.png">

The remark about the type of this field is a bit misleading. According to this, the specific feedback shouldn't be CAS text either in Moodle or Ilias. 
<img width="692" alt="Moodle_TypeOdSpecFeedback" src="https://user-images.githubusercontent.com/43032259/114032319-7e769780-987c-11eb-98cb-a91936107928.png">
<img width="1475" alt="Ilias_TypeOfSpecFeedback" src="https://user-images.githubusercontent.com/43032259/114032338-820a1e80-987c-11eb-80bb-42681afbcec2.png">

We have the version 3.3.2 of the STACK plugin for Ilias.

**Comment by sangwinc** [comment]
Ok, so the ILIAS plugin is behind the main plugin for STACK.  I'm really sorry about this.
