### ISSUE TITLE
Latex rendering in validation feedback does not respect texup

### ISSUE THREAD

**Issue by timlowe** [maths/moodle-qtype_stack#703]
Possibly related to #679,

It would be nice if the rendering of validation feedback could respect texup definitions. So, for example a student entering "i" in a vector question could see it rendered in bold, or the rendering of  phi displayed as \phi,  not \varphi.

**Comment by sangwinc** [comment]
The introduction of "context variables" should have fixed this issue.  E.g. https://github.com/maths/moodle-qtype_stack/commit/b399e7d35ed2b3f976eeabd7ba3562202ed351c9

Basically if you define a texput in the question variables, this new tex will show up in the feedback variables.  If you send me some specific examples (e.g. by email), I'll make sure they work and put them into the unit tests before the next release.
