### ISSUE TITLE
Automatic regrading sometimes hangs

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#704]
Hi there!

It has recently happened several times that I make som changes to PRTs after a quiz deadline to improve the automatic grading, based on student feedback. When I press _Dry run a full regrade_ to verify that my new grading works as intended, the regrading gets stuck already at the beginning, typically on attempt number two. This prevents me from efficiently fixing the automatic regrading and if the grading change affects many students, then I'm in big pain.

Any ideas how to fix this, or any suggestions how I could collect more useful troubleshooting information?

**Update:** I'm running fairly updated versions of both Moodle (3.9, stable git branch, did a git pull on Monday 5 April) and STACK (master git branch version 2020120600, git pull on 4 January). I can do a fresh git pull on STACK in a couple of weeks; now I don't dare to (unless you say it will likely resolve my problem), because I am still using STACK in teaching for a few weeks.

**Comment by timhunt** [comment]
'gets stuck' is not a very detailed bug report.

You need to find out more information (which is always hard when the only thing you can see is that nothing appears to be happening.)

You could try looking at the top output on the server, to see what processes are running. In my set-up, what I would do is to use our test server, which has a copy of our live system, but were I can add extra debug code to print out more informatoin about what is going on.

**Comment by alcarola** [comment]
Thank you for the fast response! I turned on debugging-level error messages in the developer-section on the moodle server, but only the following lines show up in the file /var/opt/remi/php72/log/php-fpm/www-error.log mentioned in the php setting error_log when I do a regrade dry run:

[15-Apr-2021 11:01:32 Europe/Helsinki] Default exception handler: Din session har löpt ut. Vänligen logga in igen. Debug:
Error code: invalidsesskey
* line 498 of /lib/setuplib.php: moodle_exception thrown
* line 33 of /lib/ajax/setuserpref.php: call to print_error()

After five minutes, still only one attempt has been graded:
Regrading attempt (1/22) - Attempt 1 by <Name and ID> 4.55%

Every now and then the line

1612 apache    20   0  635288 184920 116060 S  11,6   3,1   4:47.49 php-fpm          
                           
pops up in the top output, sometimes with 40% CPU rather than the 11.6% in the previous output, but otherwise typical output from the top command is the following:

top - 11:00:55 up 9 days, 23:46,  3 users,  load average: 1,35, 0,70, 0,47
Tasks: 301 total,   4 running, 297 sleeping,   0 stopped,   0 zombie
%Cpu(s): 46,1 us, 27,9 sy,  0,0 ni, 21,2 id,  3,0 wa,  0,7 hi,  1,0 si,  0,0 st
MiB Mem :   5919,9 total,    226,2 free,   2570,9 used,   3122,8 buff/cache
MiB Swap:   1640,0 total,   1487,2 free,    152,8 used.   2638,5 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                           
1157262 root      20   0  269528  50324  14084 S   7,6   0,8   0:20.32 sssd_be                                           
   1097 dbus      20   0   92256   6044   4796 S   4,0   0,1   9:38.32 dbus-daemon                                       
   1169 root      20   0  229948  15976  13724 R   2,0   0,3   3:39.72 sssd_nss                                          
   1117 polkitd   20   0 1630260  18316  11408 S   1,3   0,3   2:26.32 polkitd                                           
   1170 root      20   0  194468  11340  10648 S   1,3   0,2   1:41.16 sssd_pam                                          
    864 root      20   0  178084  58268  51516 S   1,0   1,0   5:31.27 systemd-journal                                   
   1062 root      16  -4  150804   3084   2200 S   1,0   0,1   2:04.56 auditd                                            
   1064 root      16  -4   48520   2216   1908 S   0,7   0,0   0:44.57 sedispatch                                        
   1106 avahi     20   0   87852   7560   4504 S   0,7   0,1   0:56.19 avahi-daemon                                      
   1470 root      20   0  444620  12300  10168 S   0,7   0,2   3:21.44 rsyslogd                                          
   1608 apache    20   0  614040 170452 122612 S   0,7   2,8   5:50.45 php-fpm                                           
   1611 apache    20   0  600596 152404 117644 S   0,7   2,5   4:50.18 php-fpm                                           
   1612 apache    20   0  633240 182872 116060 S   0,7   3,0   4:43.23 php-fpm                                           
   2642 apache    20   0  625560 181084 123576 S   0,7   3,0   6:12.89 php-fpm                                           
   2647 apache    20   0  609100 160724 117772 S   0,7   2,7   4:44.03 php-fpm                                           
      1 root      20   0  180036  13928   9280 S   0,3   0,2   9:02.97 systemd                                           
     11 root      20   0       0      0      0 R   0,3   0,0   1:15.69 rcu_sched                                         
    626 root       0 -20       0      0      0 I   0,3   0,0   0:41.72 kworker/0:1H-xfs-log/dm-0                         
   1297 tomcat    20   0 3072480 609076   7580 S   0,3  10,0  12:33.26 java                                              
   1330 mysql     20   0 1152796 278140  12728 S   0,3   4,6  46:16.25 mariadbd                                          
   1609 apache    20   0  603400 153236 116096 S   0,3   2,5   4:55.29 php-fpm                                           
   1610 apache    20   0  603928 153476 115512 S   0,3   2,5   4:43.53 php-fpm                                           
 627378 apache    20   0 1357900  19724   9472 S   0,3   0,3   1:12.49 httpd                                             
 860684 apache    20   0  581332 121832 105836 S   0,3   2,0   0:43.80 php-fpm           

What sort of information should I print out and where should I add the printout code? Can you give me a sample code line for printing out the code?

**Comment by timhunt** [comment]
The code which does the regrading is https://github.com/moodle/moodle/blob/master/mod/quiz/report/overview/report.php#L327, and that uses https://github.com/moodle/moodle/blob/511a87f5fc357f18a4c53911f6e6c7f7b526246e/question/engine/questionusage.php#L886 and https://github.com/moodle/moodle/blob/511a87f5fc357f18a4c53911f6e6c7f7b526246e/question/engine/questionattempt.php#L1406.

To start with, I would just start printing out messages to see how far it is getting.

**Comment by alcarola** [comment]
After having dug in this for a couple of hours, I noticed that the problem was that coderunner questions are graded very slowly, and the student, on which the grading got stuck, did a huge amount of attempts on the coderunner questions. The regrade actually does not hang, but regrading that single student takes over 10 minutes. Already displaying the progress bar and the text "Regrading attempt (1/21) - Attempt 1 by NAME (id ID) takes a very long time.

While regrading, in the top output, load average is over 2 on the server, but seldom any process seems to use very much CPU and memory seems OK too. If the server is working hard on regrading, I would suspect to see faster progress and processes such as maxima_opt_auto and octave-cli-5.2.0 using considerable amounts CPU. (I only use STACK and coderunner.) I need to try to figure out why we have this performance problem with the real sys admin of the server.

I will try to remember this debugging technique for future problems, in this case adding the following line to moodle/question/engine/questionattempt.php:
echo '<pre>'; print_r($step->get_submitted_data()); echo '</pre>';

Clicking around the source code on github was easy and efficient, but I still do not know how to find out which particular .php file it is that I should add the debugging code into (mod/quiz/report/overview/report.php in this case).

**Comment by alcarola** [comment]
Some further information. At least one performance problem in case somebody else bumps into this. Coderunner has a so-called "jobe server", which is perhaps comparable to stack's maxima pool. However, unlike maximapool, where the tomcat user starts a number of maxima processes in advance, jobe starts the octave processes for evaluating matlab code on demand, apparently as the apache user.

Due to some legacy configuration at our university, the apache user was configured in NIS rather than locally. This setup possibly gave sssd a bit of work every time a jobe precess was started, since a noticeable speedup was obtained by creating a local apache user and changing NSS to use files before SSSD.

I will notify the developer of coderunner of this observation.
