### ISSUE TITLE
Binding stack guard page reprotected

### ISSUE THREAD

**Issue by sehomer** [maths/moodle-qtype_stack#707]
Hello,

one of our professors is faced with the following error message after submitting a solution to a question. We are running Moodle 3.5 (latest) and STACK Plugin Version 2020120600. We also use the dockerized maximal pool: https://github.com/uni-halle/maximapool-docker but with the latest STACK version inside.

Any help is appreciated, i also attach an xml/txt of the question.
[question.txt](https://github.com/maths/moodle-qtype_stack/files/6384991/question.txt)

Best regards
Sebastian 

`TIMEDOUTTIMEDOUTTIMEDOUT (%i11) INFO: Binding stack guard page unprotected Binding stack guard page temporarily disabled: proceed with caution Maxima encountered a Lisp error: Binding stack exhausted. PROCEED WITH CAUTION. Automatically continuing. To enable the Lisp debugger set *debugger-hook* to nil. INFO: Binding stack guard page reprotected (%i12) (%o12) Node PRSANS1 generated the following runtime error: TIMEDOUT Node PRTANS1 generated the following runtime error: TIMEDOUT Node PRATOPT1 generated the following runtime error: TIMEDOUT`

**Comment by sehomer** [comment]
[question.txt](https://github.com/maths/moodle-qtype_stack/files/6384980/question.txt)

**Comment by sangwinc** [comment]
I've had a look at this question, and I'm fairly certain this is not a bug with STACK itself - the question (which looks like a German translation of the demo materials?!) works fine in old and new STACK servers.  If you are still having problems, please email me and I'll talk about your server set up.
