### ISSUE TITLE
Minor display inconsistency: sin(x) v sin^5 x

### ISSUE THREAD

**Issue by timlowe** [maths/moodle-qtype_stack#710]
It's really nice that sin(x)^5 is displayed as sin^5 x, but its been pointed out to me that this has no parenthesis, whilst maxima always insists on including them in sin(x). This leads to inconsistencies in expressions like cos(x) sin^5 x.

I guess is it to do with lines 238+ of stacktex.lisp  (but I don't read lisp!)

**Comment by sangwinc** [comment]
This issue has been around for a very long while, but thanks for prompting me to fix it.  One line of lisp code needed...
