### ISSUE TITLE
Algebraic equivalence of sets

### ISSUE THREAD

**Issue by wehro** [maths/moodle-qtype_stack#711]
If the teacher's answer is the set {0.5,1} (defined by `ta:set(0.5,1)`) in a Stack question, the student's answer {1/2,1} is not accepted with the “AlgEquiv” answer test.
Is this a bug or should I use another answer test?

**Comment by sangwinc** [comment]
Good question.  Sorry about this: for expressions, the algebraic equivalence test subtracts two expressions, and compares with 0.  In this situation 0.5 and 1/2 end up at the same "type" (try desktop maxima!).  We can't use that approach for sets (duplicates, order, etc....).   If you know you have sets of numbers, and you would like to accept 0.5, then apply "fullratsimp" to the student's answer in the feedback variables before applying the answer test.  This will convert floats 0.5 to 1/2.  Of course, you'll also end up with 0.33 as 33/100, which is not 1/3.  

We don't have an "approximate set" function yet, and it might be useful.

I don't consider this a bug as much as a "consequence of design decisions", but thanks for reporting the issue, happy to help.  If this doesn't fix the issue please reopen this ticket. 

Chris
