### ISSUE TITLE
Documentation about SRegExp outdated (?)

### ISSUE THREAD

**Issue by sm8ps** [maths/moodle-qtype_stack#713]
I have been playing with the SRegExp test -- successfully in the end. I recall discussions about the transition from (PHP-?)RegExp and it seems that the documentation is a bit behind the current state.
[It reads](https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Authoring/Answer_tests.md#sregexp): "Currently this is not provided as a separate answer test so you will need to use this predicate in the question variables and check the result against the expected value, or supply the predicate as an argument to an answer test." -- This remark made me jump through quite some hoops in order to circumvent a problem that does not seem to exist anymore in my version 4.3.8 of Stack where the SRegExp test is available and works well. I do not have any good suggestion about how to describe the current state though.

**Comment by sangwinc** [comment]
Very sorry about the incorrect docs here. Thank you very much indeed for letting me know.
Chris

**Comment by sm8ps** [comment]
Thank you for providing this great tool!

**Comment by shinuito** [comment]
> Very sorry about the incorrect docs here. Thank you very much indeed for letting me know.
> Chris

Did the recent update break something on the documentation page? It seems like the top bar with the search is broken for me now and squashed into the top left corner. There's also a console error ```Uncaught ReferenceError: Missing element: expected "#__config" to be present```

**Comment by malthefogsporring** [comment]
Thanks for pointing this out @shinuito. The above pull request fixes this issue.
