### ISSUE TITLE
SRegExp: exact matching as an option?

### ISSUE THREAD

**Issue by sm8ps** [maths/moodle-qtype_stack#715]
I am very pleased (in light of #512) to see that SRegExp is available. I used it e.g. for a randomized question about the network part of an IP-address in combination with the approximate number of local addresses.

Though, I took me a while to get my head around the way this answer test works. Presumably it evaluates `regex_match( tans, sans)` where `tans` provides a regular expression and `sans` is the student answer. If Maxima returns false, then the student answer is graded as incorrect. In the opposite case, a match is found _anywhere within_ the student answer and it is graded as correct.

My original interpretation had been that the test would compare the result against the provided sample solution for an exact match. Given, this is was wildly speculative and the documentation wiki does state clearly that `regex_match_exactp()` is currently not provided as a separate answer test. Nevertheless I would suggest to append the documentation e.g. in the following way:
"This test uses Maxima's regex_match function and yields true if the pattern is matched anywhere within the student answer and false otherwise. Cf. below for exact matching of the pattern."
For experienced users this is of course obvious, but those do not need the general documentation anyways and I as a non-experienced user did not realize this right away. So I guess it might be helpful.

Furthermore I would like to ask if having an option to switch to exact matching against the sample answer would make sense in the general context. Providing, say "exact=true", as an option, the answer test  would evaluate `regex_match_exactp(tans, sans)` which would yield true or false.

**Comment by aharjula** [comment]
Well, it does do regexp matching and it does work just fine if you tell it to match the pattern to the start and end of the string. Personally, I might not exactly be a non-experienced user so my opinion might not be the best to base this on, however:

- People that do "exact" string matching can do it with the direct equality tests just fine.
- People needing pattern matching will need to use RegExp and do need to understand the basics of RegExps.
- One of the most basic thing is the anchoring of the pattern to the start and/or end of the string. This is in no form special for STACK and is just assumed to be understood.
- I would not want to include an option for `exact=true` as a separate config parameter for a use case that is possible to deal with by adding two characters to the pattern. e.g. I will rather write the anchored pattern `"^[0-9]{1,3}(\\.[0-9]{1,3}){3}$"` than try to figure out whatever extra options or special tests are needed.
- Overall I don't like the term exact here, to me a pattern that is not anchored is in no form less exact than a pattern that is.
- Also `regex_match_exactp()` is an interesting take on this issue, it just seems to test if the whole string is the part that matches the pattern ignoring any concepts of anchoring.

**Comment by sm8ps** [comment]
Thanks for sharing your opinion @aharjula! I agree that anchoring solves the problem. I had started from a mis-interpratation of the answer test. I shall try to add this information to the docs via a pull-request.

**Comment by aharjula** [comment]
Anyway, assuming you were not the one that had IP related questions before, if you need to get the numbers out of the address for more validation this snippet might be useful. Obviously, this requires one to first validate the pattern for that split to function...
```
ans1: "1.2.3.334/32";
mask: split(ans1,"/")[2];
bytes: split(split(ans1,"/")[1],".");
mask: stack_string_parse_number(mask);
bytes: map(stack_string_parse_number, bytes);
valid: is(mask>0) and is(mask<33) and ...
```
STACK JSON-parser includes some logic for parsing string for certain things, and one will need to parse them manually as we just cannot `eval` those strings due to security reasons.

**Comment by sm8ps** [comment]
Very helpful, indeed. Thanks a lot for pointing this out! In fact, dealing with strings in Mathematica was novel territory to me and your example comes in very handy for giving general ideas.

**Comment by sangwinc** [comment]
So, the truth is that during my 20 years of online assessment I've _never_ written an answer test using a regular expression!  Since this is not something I use or even need, I've not thought deeply about how to use it, options or better documentation. Sorry.  I can see in cases like this why it really is needed.  I would very much appreciate contributions in docs, examples (which I can add as test cases to spot if things change in the background) and even concrete suggestions for improvements.
