### ISSUE TITLE
Wrong feedback for differentiation problem

### ISSUE THREAD

**Issue by wehro** [maths/moodle-qtype_stack#718]
It seems that the feedback given by the “Diff” answer test is not always correct. I created a question requiring to differentiate e^x+2. A student of mine supposed that the derivative is again e^x+2 and got the feedback “It looks like you have integrated instead!”.
However, the integral would be e^x+2x.
![Bild1](https://user-images.githubusercontent.com/33468411/121955289-0e92fa80-cd60-11eb-82f0-2acc20cea933.png)
![Bild2](https://user-images.githubusercontent.com/33468411/121955295-118deb00-cd60-11eb-9870-e6f2001fc8bf.png)
![Bild3](https://user-images.githubusercontent.com/33468411/121955297-13f04500-cd60-11eb-87ba-11f88176e398.png)

**Comment by sangwinc** [comment]
Ok!  Yes, this is because STACK has interpreted this as the integral of e^2 with a constant of integration +2.  The exponential is an edge case, so please use the "quiet" option in this case with the diff test.

**Comment by wehro** [comment]
I am sorry, but I don’t understand. The integral of e^2 would be e^2*x.
Is there any documentation on the diff test advising when to use the “quiet” option?

**Comment by sangwinc** [comment]
Sorry, my mistake in typing an answer to you earlier.  

e^x+2 looks like an integral of e^x, with a constant of integration +2.  Of course, that isn't sensible feedback.  You need to use the quiet option with e^x, which is a unique edge case.

**Comment by wehro** [comment]
OK, thanks.
