### ISSUE TITLE
Variants are identified by order of creation and not by seed for random groups

### ISSUE THREAD

**Issue by rb-clz** [maths/moodle-qtype_stack#723]
Hello,

we had a problem using random groups with STACK for two questions:
![grafik](https://user-images.githubusercontent.com/85869200/126488118-9487e71e-a380-4ec7-bfbf-a68a8b216f41.png)

If the order of creation for the different seeds was not identical, then the two questions have different seeds in one test. The criteria for choosing the corresponding values within a random group seems to be the order of creation of that variant and not the seed. That's irritating because in the table they are ordered by their "question notes" and not by their order of creation and one can only notice it when hovering over the "preview"-icon of a variant (please see illustration).

**Comment by sangwinc** [comment]
Related to issue #724, so this will be resolved there.
