### ISSUE TITLE
Exception thrown when adding a PRT

### ISSUE THREAD

**Issue by georgekinnear** [maths/moodle-qtype_stack#725]
We have just updated our STACK server to version 2021071900 and I am now seeing a bug when trying to add a PRT to an existing question.

This is on the server at https://stack-demo.maths.ed.ac.uk/demo and also on our live server used with students, and I've replicated the bug on both servers using the following steps:

1. Make a minimal working question by creating a new STACK question, setting ans1 to have model answer `0` and prt1 to have node 1 answer test `AlgEquiv(ans1,0)`.
2. Save the question.
3. Edit the question, adding to the specific feedback: `[[feedback:prt2]]` to add a new PRT.
4. Click "verify the question text and update the form", then complete prt2 (e.g. make node 1 check ans1 is AlgEquiv to 1).
5. Try to save the question. For me, this throws an exception:
> stack_potentialresponse_tree: __construct: the specified first node does not exist in the tree.

**Comment by sangwinc** [comment]
Thanks for reporting this George,
I fixed the bug last Friday!
https://github.com/maths/moodle-qtype_stack/commit/b02674bc3d14915e598c42f017c86afdfd11a3b0
We just need David to update the servers with the patch.
