### ISSUE TITLE
Warning: Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' (this will throw an Error in a future version of PHP) in question/type/stack/stack/cas/connector.dbcache.class.php on line 170

### ISSUE THREAD

**Issue by danowar2k** [maths/moodle-qtype_stack#727]
GLOB_BRACE is not defined on some OS. In other places there is a defined() check, not so in https://github.com/maths/moodle-qtype_stack/blob/2657c7e427ca2312829b0810ad6804e4a8716882/stack/cas/connector.dbcache.class.php#L170

This led to

`Warning: glob() expects parameter 2 to be integer, string given in question/type/stack/stack/cas/connector.dbcache.class.php on line 170`

and then to

`Warning: count(): Parameter must be an array or an object that implements Countable in question/type/stack/stack/cas/connector.dbcache.class.php on line 171`

**Comment by sangwinc** [comment]
Sorry about that!
