### ISSUE TITLE
Errors running GitHub actions workflow PHP unit tests

### ISSUE THREAD

**Issue by nadavkav** [maths/moodle-qtype_stack#729]
When I push our custom Moodle instance that includes a Stack question type (that works fine) to our GitHub repository, I am getting errors from the automatic action workflow PHP unit test jobs (see log excerpts at the end)

I am using Moodle core workflow actions file:
https://github.com/moodle/moodle/blob/master/.github/workflows/push.yml

-->qtype_stack
Default exception handler: Coding error detected, it must be fixed by a programmer: maxima_opt_auto creation failed. Debug: Uncached connection failed: CAS failed to return any evaluated expressions.  Please check your connection with the CAS. CAS returned some data as expected, but there were errors.

<h3>Context used</h3><pre>Platform: linux
Maxima shell command: maxima
Maxima initial command: load(&quot;[dataroot]/stack/maximalocal.mac&quot;);

Maxima timeout: 10</pre><h3>Maxima command</h3><pre>cab:block([],print(&quot;[STACKSTART Locals= [ 0=[ error= [&quot;), cte(&quot;CASresult&quot;,errcatch(diff(x^n,x))), print(&quot;1=[ error= [&quot;), cte(&quot;STACKversion&quot;,errcatch(stackmaximaversion)), print(&quot;2=[ error= [&quot;), cte(&quot;MAXIMAversion&quot;,errcatch(MAXIMA_VERSION_STR)), print(&quot;3=[ error= [&quot;), cte(&quot;MAXIMAversionnum&quot;,errcatch(MAXIMA_VERSION_NUM)), print(&quot;4=[ error= [&quot;), cte(&quot;externalformat&quot;,errcatch(adjust_external_format())), print(&quot;5=[ error= [&quot;), cte(&quot;CAStime&quot;,errcatch(CAStime:&quot;2021-08-03 04:58:24&quot;)), print(&quot;] ]&quot;), return(true));
</pre><h3>CAS process return value: 127</h3><h3>Timings</h3><pre>Start: 1627937904.3017, End: 1627937904.3028, Taken = 0.0010828971862793</pre><h3>CAS result</h3><pre>sh: 1: maxima: not found
</pre><pre>unpack_raw_result: no STACKSTART returned. Data returned was: sh: 1: maxima: not found
]]]]</pre><h3>Unpacked result as</h3><pre>Array
(
)
</pre>
Error code: codingerror
* line 82 of /question/type/stack/db/install.php: coding_exception thrown
* line 665 of /lib/upgradelib.php: call to xmldb_qtype_stack_install()
* line 1917 of /lib/upgradelib.php: call to upgrade_plugins()
* line 489 of /lib/installlib.php: call to upgrade_noncore()
* line 466 of /lib/phpunit/classes/util.php: call to install_cli_database()
* line 150 of /admin/tool/phpunit/cli/util.php: call to phpunit_util::install_site()

!!! Coding error detected, it must be fixed by a programmer: maxima_opt_auto creation failed. !!!
!! Uncached connection failed: CAS failed to return any evaluated expressions.  Please check your connection with the CAS. CAS returned some data as expected, but there were errors.

<h3>Context used</h3><pre>Platform: linux
Maxima shell command: maxima
Maxima initial command: load("[dataroot]/stack/maximalocal.mac");

Maxima timeout: 10</pre><h3>Maxima command</h3><pre>cab:block([],print("[STACKSTART Locals= [ 0=[ error= ["), cte("CASresult",errcatch(diff(x^n,x))), print("1=[ error= ["), cte("STACKversion",errcatch(stackmaximaversion)), print("2=[ error= ["), cte("MAXIMAversion",errcatch(MAXIMA_VERSION_STR)), print("3=[ error= ["), cte("MAXIMAversionnum",errcatch(MAXIMA_VERSION_NUM)), print("4=[ error= ["), cte("externalformat",errcatch(adjust_external_format())), print("5=[ error= ["), cte("CAStime",errcatch(CAStime:"2021-08-03 04:58:24")), print("] ]"), return(true));
</pre><h3>CAS process return value: 127</h3><h3>Timings</h3><pre>Start: 1627937904.3017, End: 1627937904.3028, Taken = 0.0010828971862793</pre><h3>CAS result</h3><pre>sh: 1: maxima: not found
</pre><pre>unpack_raw_result: no STACKSTART returned. Data returned was: sh: 1: maxima: not found
]]]]</pre><h3>Unpacked result as</h3><pre>Array
(
)
</pre>
Error code: codingerror !!
!! Stack trace: * line 82 of /question/type/stack/db/install.php: coding_exception thrown
* line 665 of /lib/upgradelib.php: call to xmldb_qtype_stack_install()
* line 1917 of /lib/upgradelib.php: call to upgrade_plugins()
* line 489 of /lib/installlib.php: call to upgrade_noncore()
* line 466 of /lib/phpunit/classes/util.php: call to install_cli_database()
* line 150 of /admin/tool/phpunit/cli/util.php: call to phpunit_util::install_site()
 !!
Error: Process completed with exit code 1.

**Comment by larsbonczek** [comment]
The stack documentation says

> If, for some reason, you have the STACK code in your codebase, and you want to run other unit tests on a server without Maxima installed, then you will get an error when you try to install the PHPunit site. You can avoid that by putting
> 
> ```
> define('QTYPE_STACK_TEST_CONFIG_PLATFORM',        'none');
> ```
> 
> in your config.php file. This will prevent the install from trying to create maxima-optimised. It will also cause most of the STACK unit tests to be skipped.

https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Developer/Unit_tests.md#stack-specific-set-up-steps

Adding that line to .github/workflows/config-template.php in your Moodle repository should probably do the trick.

**Comment by nadavkav** [comment]
Thanks @larsbonczek , I was not aware of this.
