### ISSUE TITLE
Error from CAS after upgrade

### ISSUE THREAD

**Issue by nwalet** [maths/moodle-qtype_stack#732]
I am trying to upgrade my moodle/stack to a more recent version (my old stack was running on 4.2), and I see to hit an error starting maxima with the header files (plugin is master from github):

> CAS result
> 
> Maxima 5.41.0 http://maxima.sourceforge.net
> using Lisp SBCL 1.4.0-0.1.el7.bootstrap
> Distributed under the GNU Public License. See the file COPYING.
> Dedicated to the memory of William Schelter.
> The function bug_report() provides bug reporting information.
> (%i1) STYLE-WARNING:
>    Character decoding error in a #|-comment at position 1016 reading source stream #<FORM-TRACKING-STREAM for "file /usr/share/maxima/5.41.0/share/stringproc/cryptools.lisp" {10057777A3}>, resyncing.
> STYLE-WARNING:
>    Character decoding error in a #|-comment at position 1483 reading source stream #<FORM-TRACKING-STREAM for "file /usr/share/maxima/5.41.0/share/stringproc/cryptools.lisp" {10057777A3}>, resyncing.
> STYLE-WARNING:
>    Character decoding error in a #|-comment at position 1653 reading source stream #<FORM-TRACKING-STREAM for "file /usr/share/maxima/5.41.0/share/stringproc/cryptools.lisp" {10057777A3}>, resyncing.
> STYLE-WARNING:
>    Character decoding error in a #|-comment at position 1951 reading source stream #<FORM-TRACKING-STREAM for "file /usr/share/maxima/5.41.0/share/stringproc/cryptools.lisp" {10057777A3}>, resyncing.
> STYLE-WARNING:
>    Character decoding error in a #|-comment at position 2154 reading source stream #<FORM-TRACKING-STREAM for "file /usr/share/maxima/5.41.0/share/stringproc/cryptools.lisp" {10057777A3}>, resyncing.
> WARNING: redefining MAXIMA::OPAPPLY in DEFMACRO
> WARNING: redefining MAXIMA::OPCONS in DEFMACRO
> WARNING: redefining MAXIMA::CARTESIAN-PRODUCT in DEFUN
> ARRSTORE: use_fast_arrays=false; allocate a new property hash table for |$all_transp|
> Maxima encountered a Lisp error:
> 
>  :ASCII stream decoding error on
>  #<SB-SYS:FD-STREAM for "file /var/www/html/moodle/question/type/stack/stack/maxima/noun_simp.mac" {10042CD7C3}>:
> 
>    the octet sequence #(194) cannot be decoded.
> 
> Automatically continuing.
> To enable the Lisp debugger set *debugger-hook* to nil.
> (%i1) 

Anyone seen that before, and have an idea what could be causing that?

**Comment by aharjula** [comment]
Have not seen but can guess based on that `ASCII stream decoding error` I guess Chris has gotten up to the point where he develops with a UTF-8 capable system, and apparently the system where that error appears is not using UTF-8 environment settings for that Maxima process.

The issue seems to be in that `noun_simp.mac` file which is new since 4.2 and in it we have a bit sequence starting with 194 on line [571](https://github.com/maths/moodle-qtype_stack/blob/bc5bb9e1dd56c99d66d8ec176cf2cf56cc2a7898/stack/maxima/noun_simp.mac#L571), basically, the space before the text inside that comment is not a normal space (it is actually a non-breaking space), and as it is not it is no longer ASCII and the logic reading it in gets very confused indeed.

I would guess that simply removing that line from the file would make your system function, but it is possible that we have more of these nice little spaces that are not spaces in the files so might be better to figure out how to switch to UTF-8 locales in the system.

@sangwinc you need to figure out if STACK will in the future require UTF-8 for executing the Maxima scripts and if not how you would ensure that the scripts stay clean enough to be executed on ASCII systems.

**Comment by nwalet** [comment]
Thanks Matti,
that was what I expected you to say (i.e., utf-8/ascii mixup). I may just compile my own maxima with utf-8 enabled, but I am trying to make instructions for our e-learning staff how to maintain stack--this is a deal-breaker, I think.
Niels


________________________________
Prof. Niels R. Walet CPhys FInstP
http://bit.ly/nielswalet
Associate Dean for online and flexible learning
Faculty of Science and Engineering
Theoretical Physics Group
Department of Physics and Astronomy
University of Manchester
Manchester, M13 9PL,  UK        Phone:  +44(0)1613063693
Mobile: +44(0)7516622121
Room 7.07, Schuster Building
email: ***@***.***  <https://outlook.manchester.ac.uk/owa/redir.aspx?C=GtyQOOwEkmH8trDX5qX8G4QD6W9pIp0fMiMDUPqAyhsSVHY-OG3XCA..&URL=mailto%3aNiels.Walet%40manchester.ac.uk>   twitter: @nwalet

________________________________

**Comment by nwalet** [comment]
Ok, this is a bit less clear-cut than I thought. It is a locale set by php, not by my system (which is uTF8). I see Chris discussed this issue 4 years ago, without a statement of the reslution... https://github.com/maths/moodle-qtype_stack/issues/260
[https://opengraph.githubassets.com/a235dec55037f8ff7968aa67efaa4c68a49b11e7b72379663bcbec2ee0b6bb17/maths/moodle-qtype_stack/issues/260]<https://github.com/maths/moodle-qtype_stack/issues/260>
Support for Maxima's "unicode()" command? · Issue #260 · maths/moodle-qtype_stack · GitHub<https://github.com/maths/moodle-qtype_stack/issues/260>
It is funny how one issue bubbles to the surface with a number of separate people basically asking for something which all relate to the same underlying issue.
github.com

Niels
________________________________

**Comment by aharjula** [comment]
As you already noticed...

I think that pretty much every Maxima packaged since Maxima 5.38 has been compiled with UTF-8 support, the issue is just the environment settings saying to it to assume the C-locale i.e. ASCII. In most webservers, the webserver runs with the C-locale unless otherwise instructed and as it is executing the Maxima that locale gets passed on to the Maxima. The solution could simply be an addition of a single line to the Apache (assuming apache) config. Something like:
```
SetEnv LC_CTYPE "en_US.utf8"
```
in the virtual host config might be enough, assuming that that locale has been installed to the system. Pretty much every modern English server install has an unicode locale as well...

**Comment by nwalet** [comment]
Yes that will work, but probably fail in the future for newer version of php (below for 8.1): It would make sense to execute such commands inside the right php locale:
Niels

Do not inherit LC_CTYPE locale from environment

Treatment of locales in PHP is currently inconsistent: The LC_ALL
locale is set to "C", as is standard behavior on program startup.
The LC_CTYPE locale is set to "", which will inherit it from the
environment. However, the inherited LC_CTYPE locale will only be
used in some cases, while in other cases it is necessary to perform
an explicit setlocale() call in PHP first. This is the case for
the locale-sensitive handling in the PCRE extension.

Make things consistent by *never* inheriting any locales from the
environment. LC_ALL, including LC_CTYPE will be "C" on startup.
A locale can be set or inherited through an explicit setlocale()
call, at which point the behavior will be fully consistent and
predictable.

________________________________

**Comment by aharjula** [comment]
I am a bit hesitant on calling `setlocale()` inside a plugin in a system like Moodle as it might have some side effects. Obviously, people can try that if they want.

Also, is that going to affect the Maxima process spawned by the PHP-code, i.e. does it affect the environment or just PHPs internal state? If not then we would need to set the environment of that process and setting it might not be that simple as the environment variables affecting it might vary between systems.

**Comment by nwalet** [comment]
Agree. We can apparently specify this on the line that spawns Maxima. I.e., prefix Maxima by LC_ALL=. Will try that first.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sangwinc** [comment]
I'm really sorry if I've messed up here.  I don't recall needing anything in my Maxima code which really needs more than ASCII.  Can you recommend a good tool for highlighting where non-ASCII characters are used and converting the code to ASCII?   I think if we start writing code in utf-8 with non-breaking spaces then it should at least be a conscious choice on my part!

**Comment by nwalet** [comment]
OK, just changed the maxima command to LC_ALL=en_GB.UTF-8 timeout --kill-after=10s 10s /bin/maxima; that solves the issue for now.
Niels

________________________________
Prof. Niels R. Walet CPhys FInstP
http://bit.ly/nielswalet
Associate Dean for online and flexible learning
Faculty of Science and Engineering
Theoretical Physics Group
Department of Physics and Astronomy
University of Manchester
Manchester, M13 9PL,  UK        Phone:  +44(0)1613063693
Mobile: +44(0)7516622121
Room 7.07, Schuster Building
email: ***@***.***  <https://outlook.manchester.ac.uk/owa/redir.aspx?C=GtyQOOwEkmH8trDX5qX8G4QD6W9pIp0fMiMDUPqAyhsSVHY-OG3XCA..&URL=mailto%3aNiels.Walet%40manchester.ac.uk>   twitter: @nwalet

________________________________

**Comment by nwalet** [comment]
Not sure the filter I used works, but it is a start: almost all files contain non-ascii?
for file in `find ./ -name "*.php"`; do if LC_ALL=C grep -q '[![:cntrl:][:print:]]' $file; then   echo "$file contains Non-ASCII"; fi ; done
Niels

________________________________
Prof. Niels R. Walet CPhys FInstP
http://bit.ly/nielswalet
Associate Dean for online and flexible learning
Faculty of Science and Engineering
Theoretical Physics Group
Department of Physics and Astronomy
University of Manchester
Manchester, M13 9PL,  UK        Phone:  +44(0)1613063693
Mobile: +44(0)7516622121
Room 7.07, Schuster Building
email: ***@***.***  <https://outlook.manchester.ac.uk/owa/redir.aspx?C=GtyQOOwEkmH8trDX5qX8G4QD6W9pIp0fMiMDUPqAyhsSVHY-OG3XCA..&URL=mailto%3aNiels.Walet%40manchester.ac.uk>   twitter: @nwalet

________________________________

**Comment by nwalet** [comment]
for file in `find ./ -name "*.php"`; do file $file| grep -v ASCII; done
./cli/maximalibcheck.php: PHP script, UTF-8 Unicode text
./stack/cas/parsingrules/090_special_forbidden_characters.filter.php: C++ source, UTF-8 Unicode text
./stack/maximaparser/autogen/parser.mbstring.php: C++ source, UTF-8 Unicode text, with very long lines

________________________________

**Comment by nwalet** [comment]
Or better
for file in `find ./ -type f`; do file $file| grep -v ASCII; done
Niels
________________________________

**Comment by sangwinc** [comment]
Yes, the PHP files for contain some non-ASCII for good reasons, although there may also unknowingly be non-breaking spaces which don't need to be in UTF-8.... 

I've checked all the Maxima files by hand, and will push a change to just that one file which provoked the issue.

Thanks for your patience here Niels, we should check the encoding of all the rest.

**Comment by nwalet** [comment]
Actually, it looks quite OK:
./amd/build/jsxgraphcore-lazy.min.js: UTF-8 Unicode text, with very long lines
./cli/maximalibcheck.php: PHP script, UTF-8 Unicode text
./stack/cas/parsingrules/090_special_forbidden_characters.filter.php: C++ source, UTF-8 Unicode text
./stack/maxima/noun_simp.mac: UTF-8 Unicode text
./stack/maximaparser/autogen/parser.mbstring.php: C++ source, UTF-8 Unicode text, with very long lines
./tests/fixtures/test_strings.json: UTF-8 Unicode text
./thirdparty/php-peg/examples/Rfc822UTF8.peg.inc: C++ source, UTF-8 Unicode text
Niels

________________________________
Prof. Niels R. Walet CPhys FInstP
http://bit.ly/nielswalet
Associate Dean for online and flexible learning
Faculty of Science and Engineering
Theoretical Physics Group
Department of Physics and Astronomy
University of Manchester
Manchester, M13 9PL,  UK        Phone:  +44(0)1613063693
Mobile: +44(0)7516622121
Room 7.07, Schuster Building
email: ***@***.***  <https://outlook.manchester.ac.uk/owa/redir.aspx?C=GtyQOOwEkmH8trDX5qX8G4QD6W9pIp0fMiMDUPqAyhsSVHY-OG3XCA..&URL=mailto%3aNiels.Walet%40manchester.ac.uk>   twitter: @nwalet

________________________________
