### ISSUE TITLE
Javascript error on quiz review page

### ISSUE THREAD

**Issue by georgekinnear** [maths/moodle-qtype_stack#743]
I have a quiz that uses JSXGraph, and I noticed when reviewing an attempt that the graphs were not showing. My browser developer tools show this error:
![image](https://user-images.githubusercontent.com/30723394/135078072-6e953f47-f0d9-490d-a0dd-8d8567e343d2.png)
This seems to be the offending line of javascript code:
```javascript
    function initInputs(a, b, c, d) {
        for (var e = document.getElementById(a), f = !0, g = 0; g < d.length; g++) {
            f = initInput(e, b, c, d[g]) && f
        }
        if (f && (e.classList.contains("dfexplicitvaildate") || e.classList.contains("dfcbmexplicitvaildate"))) {
            e.querySelector(".im-controls input.submit").hidden = !0   /* this is causing the error*/
        }
    }
```
I couldn't locate this code in the codebase using search on GitHub, so I'm not really sure where this is coming from - but the mention of `dfexplicitvaildate` in this bit of code made me think it's STACK-specific.

I think it's because on the quiz review page, there are no check buttons being shown. I'm not seeing this behaviour when I review  a student's attempt using my teacher account, but it does arise when I use the "log in as" feature to view the quiz as if I'm the student.

(I realise this is not a super-helpful bug report, but hopefully it's meaningful enough for whoever wrote that code!)

**Comment by aharjula** [comment]
Seems like a minified version of [this](https://github.com/maths/moodle-qtype_stack/blob/97b5f2fd7f7fe6481934d62fd9e73ac955bf17c8/amd/src/input.js#L431-L445), maybe that helps tracing it. This probably depends on the question themselves and the settings they have for inputs as well as possible scripting in the question affecting the input elements.

**Comment by taraghi** [comment]
We observe the same problem while reviewing an attempt. We came across the problem as we tried to print the attempt on Chromium as PDF. The generated pdf is cropped. We believe that the Js errors are the cause.

Anyway the solution would be very simple here. One just need to modify the line https://github.com/maths/moodle-qtype_stack/blob/master/amd/src/input.js#L443 as follows:

```javascript
const input = questionDiv.querySelector('.im-controls input.submit');
if (input) input.hidden = true;
```

I hope that some one from Stack team cares of this issue in future releases

**Comment by sangwinc** [comment]
@EJMFarrow could you review this please?  If still an issue could you propose a resolution?  Thanks,
Chris

**Comment by EJMFarrow** [comment]
This is still an issue. The suggested fix helps but, alas, shoves the problem further along the line - the id on the iframe holder divs is being stripped. Will investigate further...

**Comment by EJMFarrow** [comment]
'Log in as' sets` forceclean = true` so this is blocked by #1252 .
