### ISSUE TITLE
Functions in question variables and quote-quote operator

### ISSUE THREAD

**Issue by timlowe** [maths/moodle-qtype_stack#744]
The Maxima quote-quote operator does not seem to work in STACK?

In Question variables, I have
f(x):=1/(x+3)^2;
df(x):=''(diff(f(x),x));

In Maxima, that would result in df(x) being assigned to  -2/(x+3)^3, hence df(2) evaluating.

In STACK, the differentiation is not performed, hence df(2) fails as I cannot differentiate with respect to 2.
I've also tried  ev(diff(f(x),x), nouns) which makes no difference.

(The reason for using functions is that an unsimplified f(2) displays nicely:  1/(2+3)^2  and if I do the same with variables I get the horrible (3+2)^-2  ! )

Tim

**Comment by shinuito** [comment]
This example seems to work in stack with `simp:true` at least. https://maxima.sourceforge.io/docs/manual/maxima_43.html#index-_0027_0027
```
(%i1) foo_1a (x) := ''(integrate (log (x), x));
(%o1)               foo_1a(x) := x log(x) - x
```
I just tested it in the send to the CAS page. I agree though that the df one seems to cause a problem.

I'm not sure I understand the difference between the two examples, other than f being a custom function and log not being user defined.

**Comment by sangwinc** [comment]
@aharjula this issue is still with us.  I've looked, and the way this interacts with %_E, etc, is going to be complex, especially as the '' operator changes the order of evaluation.  One option would be to add a filter to forbid the '' operator, which at least would alert users that STACK does not support this.  What do you think?

**Comment by aharjula** [comment]
@sangwinc  Might be necessary to disallow it. I have not looked at this too much, but my view is that this might be problematic from the point of view of the current logic rewriting things for the runtime security checker. It is more than likely that rewriting could not keep the order of evaluation the same, even if it had a special branch for that operator.

**Comment by sangwinc** [comment]
We've reviewed this issue and there is considerable complexity in supporting Maxima's double quote operator.  This is because of the way we check security and perform error trapping.  Since this is an edge case it is unlikely to be a priority to support, sorry.  However, the current behaviour is very poor and we will clarify the lack of support with a specific error message to help question authors find another solution.

**Comment by timhunt** [comment]
OK, so we have decided this, and put it in 4.7.0, but what should quesion authors be doing?

@timlowe's example seems like a reasonable thing to do in Question variables:

```
f(x):=1/(x+3)^2;
df(x):=''(diff(f(x),x));
```

I don't know much Maxima, but my attempts to find an alternative have so far failed:

```
(%i2) df(x):=ev(diff(f(x),x),diff,simp);
(%o2)               df(x) := ev(diff(f(x), x), diff, simp)
(%i3) Z=ev(diff(f(x),x),diff,simp);
                                         2
(%o3)                           Z = - --------
                                             3
                                      (x + 3)
(%i4) df(x):=Z;
(%o4)                             df(x) := Z
```

Is there a trick here that works?

**Comment by aharjula** [comment]
Well, in that particular case, I might do it like this:
```
f(x):=1/(x+3)^2;
_df: diff(f(x),x);
df(x):= ev(_df,x=x);
```
Basically, the evaluation bit that we don't want to happen inside the definition of a function should happen outside, and then we need to assign the argument assuming we want that function to do something. However, the function will reference a variable here, `_df`, which, if changed, will change the function, so one needs to be somewhat careful not to overwrite it.

**Comment by aharjula** [comment]
Given that extra complication with variables in many roles, I would rewrite my last example as, no need to use `x` as the function argument when we are doing an assignment to another `x`:
```
f(x):=1/(x+3)^2;
_df: diff(f(x),x);
df(_x):= ev(_df,x=_x);
```
Also, if the function is not being evaluated too often, i.e. performance is not an issue, one can always do things like this and keep the differentiation inside the function, but then it will be repeated during every call:
```
df(_x) := block([X,tmp],
 tmp: diff(f(X),X),
 ev(tmp,X=_x,simp=true)
);
```

**Comment by timhunt** [comment]
Thanks for the info @aharjula. That was very useful.

I have one slightly tricky case left to fix today. At least I hope I can fix it.

**Comment by timhunt** [comment]
While the above two suggestions work for defining the function, they confuse STACK's plot command. Some minimal exampls, in CAS chat both these give "Plot error: STACK does not currently support the following plot2d options: \( [[x,0,1]] \)"

```
_f:x^2;
f(_x):=ev(_f,x=_x);
fig:plot(f,[x,0,1]);
```

```
f(_x) := block([X,tmp],
 tmp:X^2,
 ev(tmp,X=_x,simp=true)
);
fig:plot(f,[x,0,1]);
```

(Obviously, there are easier ways to define f(x):=x^2;)

**Comment by timhunt** [comment]
Well, that is typical. As soon as I post I realise the answer. Just do 

```
fig:plot(_f,[x,0,1]);
```

In the first example.
