### ISSUE TITLE
How to changing line width for a function plot?

### ISSUE THREAD

**Issue by matias75R** [maths/moodle-qtype_stack#745]
Hi, 
I am writing questions for student in STACK and I would like to t change the thickness (or width) of the function's plot. 
I am using the following type of plotting code: 

{@plot([0.8*sin(0.5*x)+2, 0.8*sin(-0.5*x)+2, 0.8*sin(x), 0.8*sin(-x),0.8*sin(5*x/2)-2, 0.8*sin(-5*x/2)-2], [x, 0, 2*pi], [color, black, black, blue, blue, red, red],[axes,false], [box,false])@}

I have tried to use include [line_width, 10, 10, 20, 20, 30, 30] as an option  but it does not recognise it. 
I found the way to do it with Maxima using "draw" but it does not recognise it (or the environment I use is different, I don't know...)

I am writing the questions straight in the Moodle site. 

would anyone have an idea aobut how to change the the width for the line graph? And if it is not too much to ask, to change the size of the graph box?

Thank you
 Matias

**Comment by sangwinc** [comment]
Ok, 
We have to review all the options as we have a policy of only accepting specific options.  I'll look into line_width.

Draw is unsupported and will remain unsupported for a while I think.
Chris

**Comment by stebac** [comment]
Hi, as for the line_width issue `[style, [lines,1], [lines1], [lines,2], [lines, 2], [lines, 3], [lines 3]]` should do it. 
For the size of the box you can include `[size, 500,500]` or something like that.
Stephan

**Comment by sangwinc** [comment]
Thanks Stephan,
I've been talking with colleagues at the OU about the docs for plots.
https://docs.stack-assessment.org/en/CAS/Plots/
I just haven't had time to pull this apart and document every feature separately.

If you can create some examples we can improve the docs here.  Perhaps pulling apart the "A catalogue of plots" section and documenting this separately, including the example plots in the docs...

This is one area with which I'd really value some community input and help!

**Comment by stebac** [comment]
Hi Chris, 
Actually the docs are better than I thought with many examples already. But I agree, your suggestion would be an improvement. Would I just send examples to you?

**Comment by sangwinc** [comment]
The docs are all written in markdown.  Adding images is more a little more difficult. Now might be a good time to add in the example plots so colleagues can simply look for examples similar to things they need.  

I did document how to contribute to the STACK documentation (!!) here: https://docs.stack-assessment.org/en/Developer/Documentation/

You could edit the docs directly on github, but for more substantial changes (if you have the energy to contribute) then a pull request is ideal.   But I'm grateful for any contributions which more the project forward!

If you'd like to make some bigger changes I'm happy to have an online call and we can talk about the process.  Of course, email suggestions is fine and I'll sort them out.

**Comment by stebac** [comment]
Okay, thanks.

**Comment by matias75R** [comment]
It worked, 
Thank you very much Stephan and Chris!
Regarding the existing documents, they are good, I found them very useful and the examples are good. Perhaps I was being too picky about this option. 
Thanks again for your help!
Matias
