### ISSUE TITLE
Partial Fractions answer test question

### ISSUE THREAD

**Issue by shinuito** [maths/moodle-qtype_stack#747]
This might not be an actual issue, but could be a misunderstanding on my part on what the ATPartFrac test does.

In any case I have a question which asks students to give the partial fractions form of, for example,

`(9*y-8)/(y-4)^2`

of which one might expect them to input 

`9/(y-4)+28/(y-4)^2`

which would be marked correct by ATPartFrac as expected. The hints part of the documentation seem to suggest the same idea for partial fractions decomposition https://docs.stack-assessment.org/en/Authoring/Fact_sheets/#partial-fractions. 

Anyway just typing back in `(9*y-8)/(y-4)^2` also return true, although I don't exactly know why. I guess it passes all the tests when I look at the code, gcd between top and bottom is 1, the degree of the numerator is lower than the denominator and the denominator is a power of an irreducible factor, but it's not really in the form one would expect I would think.

I guess `irred_power_Qp` catches it if one input instead `(9*y-8)/(y^2-8*y+16)` which is why that returns false.

https://github.com/maths/moodle-qtype_stack/blob/bc5bb9e1dd56c99d66d8ec176cf2cf56cc2a7898/stack/maxima/stackmaxima.mac#L2361

In any case, is this something that one should just work around?

**Comment by sangwinc** [comment]
I'm really sorry about the delay in replying to this - I've been super busy with teaching here in Edinburgh.

So, you are suggesting that ATPartFrac should not accept `(9*y-8)/(y-4)^2` as correct partial fraction form? I'm very happy to reconsider what this test does and does not accept.  I do actually agree I'd expect students to write `(9*y)/(y-4)^2-8/(y-4)^2` in your example.

**Comment by sangwinc** [comment]
Sorry it has taken me so long to find time to fix this.  Let me know if you'd like the kind of feedback I've mentioned in https://github.com/maths/moodle-qtype_stack/commit/f3030a31791bd85801a3dbc2ffd8029e44bdcb6e putting into the answer test, in a similar way that the factored form answer test says "this term needs more work...".

**Comment by shinuito** [comment]
Thanks for having a look at it. It's no problem about the delay, it's at least a semester if not more before we see any STACK updates I would say, so delays are fine :)

> So, you are suggesting that ATPartFrac should not accept `(9*y-8)/(y-4)^2` as correct partial fraction form? I'm very happy to reconsider what this test does and does not accept. I do actually agree I'd expect students to write `(9*y)/(y-4)^2-8/(y-4)^2` in your example.

I think so, since it can separated out into terms like `A/(y-4)+B/(y-4)^2)`. I guess it's slightly complicated in general to know what to accept, since were the denominator irreducible like `(y+1)/(y^2+y+1)` it wouldn't be unreasonable to want to accept either of just that in itself and  `y/(y^2+y+1)+1/(y^2+y+1)`. In the example above, I suppose there's reason to give the students either of  `(9*y-8)/(y-4)^2` or  `(9*y-8)/(y^2-8*y+16)` depending on whether one want to make their life easier by omitting a factorisation step. But naturally the answer shoudn't be just a factorization if the idea is to compute a partial fraction. Similarly with just expanding when there is another partial fraction form possible.

The `poly_about_a(ex, v, a)` function sounds quite useful. I have taught students previously who found that method useful while others find it more confusing of course :) The feedback itself also looks quite useful, especially since the question I was using the test in was for a proficiency course, in order to assess/help the students catch up on some 1st year material.
