### ISSUE TITLE
Lisp error with ATAlgEquiv() and taylor()

### ISSUE THREAD

**Issue by NeilStrickland** [maths/moodle-qtype_stack#748]
In Maxima, `taylor(1/(1-x),x,0,1)`  returns `1+x`.  I have not tried to inspect the internal lisp representation of this, but I note that Maxima would typically write this expressions as `x+1`.  If I load `stackmaxima.mac` and try `ATAlgEquiv(1,taylor(1/(1-x),x,0,1))` then I get this error: 
```
Maxima encountered a Lisp error:
 The value
   #:X670
 is not of type
   LIST
Automatically continuing.
To enable the Lisp debugger set *debugger-hook* to nil.
```
On the other hand, `expand(taylor(1/(1-x),x,0,1))` gives `x+1` and `ATAlgEquiv(1,expand(taylor(1/(1-x),x,0,1)))` gives `[true,false,"",""]`, which is what I would expect.

I am using a modified version of STACK's Maxima code, but I do not believe that I have touched anything that could be relevant here.  If people tell me that they do not see this error in their versions of STACK then I will investigate further.

**Comment by sangwinc** [comment]
Thanks for such a helpful error report.
