### ISSUE TITLE
Basic Question Use Report combines distinct inputs

### ISSUE THREAD

**Issue by shinuito** [maths/moodle-qtype_stack#749]
I was looking at the "Basic question use report" page, and noticed that it combines some of the inputs together, that is sometimes it includes all the responses into one input under anothers heading as well as its own.

I think the case when this occurs is when one input name is a substring of another. Examples include `ans1` and `ans10`, so if one had ten inputs then in the basic question report, all the inputs for answer 10 will be shown under both `ans1` and `ans10`. Similarly if for some reason* you had inputs like `ans1`, `ans1b`, `ans1c` then all three would show up under `ans1` as well as showing up under their own headings.

I don't think it's a major issue, and I haven't really tried to understand the code, but I expect it's something to do with the use of `substr` :

https://github.com/maths/moodle-qtype_stack/blob/2657c7e427ca2312829b0810ad6804e4a8716882/questiontestreport.php#L148

*an example might be when you make a question and then someone asks you to add in extra inputs. Not wanting to edit and shift all the input names (although it can kind of be done with the tidy question tool, minus the prt answer notes), one might add in extra ones by tacking on a letter etc to the current input.

**Comment by sangwinc** [comment]
That is rather embarrassing, sorry!  I have to say this page is very basic indeed and any help in improving the way data is presented back would be much appreciated.  Please do make positive suggestions on how to improve this feature further.  It would be very welcome.
