### ISSUE TITLE
Handling of zero values in units input

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#750]
The attached question demonstrates a problem with unit input.

The last of the three "unit" inputs has model answer 0, which is given as trs*MPa both in the model solution of the input definition as in the tans field of the answer test. 

So if the student responds with 0, the answer test complains that the response must have units.

If the student responds with 0*MPa, the validation kicks in and complains that the answer should not have units.

What could I do if I still want to have response type units and allow for value zero of the result?

My feature request would be: If one of Tans or Sans is zero in a Units... Answer test, then unit match should not be tested, neither in the validation nor in the answer test. 

[quiz-T-B3-MB-TM2-TM2 03 02 Stress transformation Bug report-20211027-2213.zip](https://github.com/maths/moodle-qtype_stack/files/7429053/quiz-T-B3-MB-TM2-TM2.03.02.Stress.transformation.Bug.report-20211027-2213.zip)

**Comment by Famondir** [comment]
Hi all. I've stumbled about something related as I think. In my case it accepts `0*unit` as an input on the outer level. But if you do this inside a function or exponentiation it yields an error:
<img width="459" alt="image" src="https://github.com/maths/moodle-qtype_stack/assets/43599267/2e1e9db3-5f08-4093-b80f-ace3164fb520">

It is neither related on the imaginary number nor to a specific unit:
<img width="207" alt="image" src="https://github.com/maths/moodle-qtype_stack/assets/43599267/f32516c5-9d7e-4ebd-94e4-a3e3b6a2cfea">

It only works if the unit in the exponen is dropped. Also occurs when using functions like `sin`.

We are running Stack 4.6.
