### ISSUE TITLE
Wrong interpretation of sqrt(x)^5

### ISSUE THREAD

**Issue by marlag** [maths/moodle-qtype_stack#751]
Could you check/confirm if the interpretation of sqrt(x)^5 is wrong?

![Screenshot 2021-11-01 102018](https://user-images.githubusercontent.com/11375408/139650322-8df857e4-97a2-4fb5-a6cc-41823bc6e50f.png)

**Comment by sangwinc** [comment]
Sorry about this - it was a side effect of changing how exponents of functions are displayed.  A lot of people asked for sin^2(x), etc.  I'll fix this.
