### ISSUE TITLE
Answers to a question saved but not assessed

### ISSUE THREAD

**Issue by aacchhee** [maths/moodle-qtype_stack#753]
We had an exam-like quiz where students had to answer 4 questions within 1t30min. Just one of these questions has the following problem: answers seem to be registered, but not assessed -- no points are given. Applies just to this question, not the others.

The question is marked as "not answered", while attempt review after the quiz is finished manages to read the actual answers from the database.

The question is in XML (with 300 others, sorry). What students get is shown below (she answered 2 of 3 parts)
![Skjermbilde 2021-10-25 kl  14 11 19](https://user-images.githubusercontent.com/59649991/139671995-f522eca2-b0b7-4622-9588-c44c2f29020e.png)
[questions-BMA1010DCST1004-Standard for IMAG2021 2020V-20211101-1329.zip](https://github.com/maths/moodle-qtype_stack/files/7453238/questions-BMA1010DCST1004-Standard.for.IMAG2021.2020V-20211101-1329.zip)

**Comment by sangwinc** [comment]
Ok, I'll take a look but can you please just email me the one question?  There is a link to download a single STACK question from the question testing page!
Chris

**Comment by aacchhee** [comment]
Here is the single question. I forgot where was thaat download link hiding.

[questions-BMA1010DCST1004-antall tall relativt primsk-20211101-1449.zip](https://github.com/maths/moodle-qtype_stack/files/7453701/questions-BMA1010DCST1004-antall.tall.relativt.primsk-20211101-1449.zip)

**Comment by aacchhee** [comment]
Hi, we wonder if there was any progress here.

**Comment by aharjula** [comment]
Seems to work just fine, what is probably wrong or misunderstood is that there is just a single PRT checking those three inputs together. So it would only grade attempts that have all the inputs filled in. If you want to give points for answering just a part of the question and not the whole question you need to have separate PRTs for each of the subsets of the question that you deem worth grading.

The PRT logic is to and will always be such that it will only grade if all the inputs referenced by the PRT have valid values (that the student has seen/validated/submitted). One can have partial completion by either having PRTs that do not reference all the inputs or by having some (a PRT must have at least one input that is not like this) inputs that consider blank answers as valid and dealing with the issues that causes when grading the blank answers.

Also, I do wonder if the scoring of that PRT is correct, but that is a style issue better left for the user. Basically, where is `ans2` and why does only `ans1` affect the score?

**Comment by aacchhee** [comment]
Okey thanks.  I have redone it with 3 independent PRTs.

Indeed it was misunderstood that we need all three inputs present. There was a linear logic with giving 1.00 for the first and so stripping 0.33 for the second if wrong and 0.33 for the third if wrong.
