### ISSUE TITLE
stackCas_reserved_function missing from the language pack and unit tests.

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#755]
The string "stackCas_reserved_function" is missing from the language pack.

It only occurs in 998_security_filter.php, so we could also do with some examples of when this is triggered and why.

**Comment by aharjula** [comment]
It is the student-facing validation message for all sorts of evil things. Not specifying what exactly like for teachers as giving out that information might help reverse engineer identifiers used in the question (not that that would help for anything else than searching a dictionary of questions).

Essentially, the message should be "Don't use this identifier $id, like this, you should choose some other identifier." "Or $id is forbidden."

This is one of those cases where the actual trivial examples are attacks that could cause trouble for people that have not upgraded STACK so we do not have those tests in the public repository. And while that can be triggered with safe inputs we do not want to build tests around those as we aim to make the logic not trigger for safe inputs.
