### ISSUE TITLE
Stack int test with int() function 

### ISSUE THREAD

**Issue by shinuito** [maths/moodle-qtype_stack#757]
Another user asked me about a problem they had with the int test, and upon further testing I believe it has to do with their use of the `int` function within the prt node. It seems to be oddly specifically tied to the exponential function too.

In a simplified version, they store
question variables
 `f1:exp(-4*pi*x)`. 
`ta:int(f1,x)+c;`  

They had two nodes in a prt, the first comparing `ans1` with `ta` with the ATInt test just using the test options  `x`. Then the second node compared `ans1` with instead `int(f1,x)` for some reason using the ATInt test just with test options  `[x,NOCONST]`. The idea being that the first part would be false if missing an integration constant, and the second node would be true if it was missing but would award 0.8 of the marks.

It didn't cause any issues for other trig and polynomials but then this exponential function gives

![image](https://user-images.githubusercontent.com/26803867/141795210-3c6410f8-b9c5-4122-8a09-27e3873e32d0.png)

I don't understand where that extra `False` is coming from.

It doesn't show up if one just used instead `ta-c` for example as the teachers answer instead of directly using `int(f1,x)` or as mentioned other expressions with sines or polynomials. I haven't had a proper chance to look at the code though to figure it out myself.

In any case I'm aware the docs say:

"The test cannot cope with some situations. Please contact the developers when you find some of these. This test is already rather overloaded, so please don't expect every request to be accommodated! "

So I don't think it necessarily has to be fixed, just curious if this was a known case.

**Comment by sangwinc** [comment]
Your second argument int(f1,x) to the answer test is evaluated but not simplified. 

If you add a test case you can see what is going on inside the system much better.

ATInt(-(%e^-(4*%pi*x)/(4*%pi)), (-1)*(false*%e^(0+(-(4*%pi))*x))*(1/(4*log(%e)*%pi)), [x,NOCONST]) = [0, "ATInt_generic."];

To fix this, you need your second argument to be ev(int(f1,x),simp)
Then, this extra simplification means what really happens internally is this.

ATInt(%e^-(4*%pi*x)/(4*%pi), -(%e^-(4*%pi*x)/(4*%pi)), [x,NOCONST]) = [0, "ATInt_generic."];

The apparent inconsistency between questions is that only sometimes is the simplification needed.

Chris
