### ISSUE TITLE
Test script errors with Stack version 4.3.10

### ISSUE THREAD

**Issue by jmatikainen** [maths/moodle-qtype_stack#764]
Hi,

We are getting two test script errors using the latest Stack version 4.3.10 for Moodle 3.9+ (2021120900):

- answer test Power and roots: AlgEquiv (a^b)^c
- input test Trig functions: cos(x)^2)

Moodle is the latest 3.9 version. I also tested with another test environment and got the same errors.

With the earlier Stack version 4.3.8 for Moodle 3.5+ 2020120600 all tests are passed.

Our Maxima version is 5.38.1

Any idea why these two tests fail?

Regards,
Jukka Matikainen
![Stack-answer-test-error-4310](https://user-images.githubusercontent.com/97025405/147924718-cbaff343-a5d0-4d52-b481-21db9bf1d905.png)
![Stack-input-test-error-4310](https://user-images.githubusercontent.com/97025405/147924762-29a4ddf8-ba74-41f3-8911-f4cd5796daa0.png)

**Comment by sangwinc** [comment]
Sorry this didn't get attention until now.  We've moved on quite a few versions since this was raised.  If you get a similar issue with a more recent version please raise a new issue.
