### ISSUE TITLE
Add an option to resolve failing test cases

### ISSUE THREAD

**Issue by georgekinnear** [maths/moodle-qtype_stack#767]
After making some significant changes to a question's grading (e.g. adjusting the question-level penalty value, or reorganising PRTs), I'm often faced with multiple tests that fail for trivial reasons.

In this situation, it would be great to have:

1. a button under each failing test case saying something like "Make this test pass", that would set the expected values to the observed ones, and perhaps even

2. a button for the whole question (where there are failing tests) along the lines of "Make all my tests pass".

This would simplify the current workflow which is to go through each test and:

- click on "Edit this test case..."
- wait for the page to load
- click on "Fill in the rest of the form to make a passing test-case"
- wait for the page to load
- click on "Save changes"

Clearly authors could use this to be lazy and wrongly endorse tests that are genuinely failing, but I think in cases like I described where there's a tedious change, it would save a lot of clicking (which can itself be done quite mindlessly).

**Comment by timhunt** [comment]
I think this is a good idea.

If only the "Edit this test case..." buttons were acutally done as <a class="button"></a> beacause then there would be the work-around of doing Open in new tab on all of them, which would parallelise the waiting - but sadly it is not like that.
