### ISSUE TITLE
A very strange issue with complex numbers

### ISSUE THREAD

**Issue by impemic** [maths/moodle-qtype_stack#769]
Example: you ask the result of (1-3i)/(2-4i) in the form a+ib.
The correct answer is 7/10-i/10.
If you write 7/10-1/10*i, the answer is uncorrect.
I believe that is a bug, but I get it only if the numerator of the coefficient of the imaginary part is 1 (or -1).
![bug1](https://user-images.githubusercontent.com/56223576/151229384-fdcecf47-f2bf-4b57-a27d-ca202d4d5d98.jpg)
![bug2](https://user-images.githubusercontent.com/56223576/151229389-3d5bf363-8f6e-4aac-9eb4-7f655cb7730f.jpg)

**Comment by sangwinc** [comment]
This all depends on which test you are using.  

Notice that 1*x is not x under EqualsComAss: https://github.com/maths/moodle-qtype_stack/blob/master/tests/fixtures/answertestfixtures.class.php#L679

Similarly: https://github.com/maths/moodle-qtype_stack/blob/master/tests/fixtures/answertestfixtures.class.php#L663

So, I doubt this is a bug in STACK. It is probably a question authoring problem!  

I've authored this question, and you might like to look at this answer tests instead.
https://docs.stack-assessment.org/en/Authoring/Answer_tests_rules_based/

Adding in the "oneMul" rule will help establish 1/10*i is equivalent to i/10.  I'll close this issue.  If you can't get this fixed, email me and I'll update the docs.
