### ISSUE TITLE
Alt-text checking gives false-positives on STACK plots

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#770]
At least on our system, the HTML for STACK plots is

```html
<img src='!ploturl!stackplot-3852702702-79504506.svg' alt='The straight line with gradient -1/3 passing though the points (5,-5)' width='450' />
```

But the regex used is in the alt-text checking is

```php
$r2 = "/(alt|title|src)\s*=\s*(\"[^\"]*\")/i";
```

So you get false-positive warnings because ' does not match ".

I'll do a pull request.

**Comment by sangwinc** [comment]
This has all been merged into the main codebase.  Thanks @timhunt .
