### ISSUE TITLE
Error while upgrading plugin

### ISSUE THREAD

**Issue by andrewrowatt-masseyuni** [maths/moodle-qtype_stack#774]
Hi Team,

This is more of an FYI.  We received the error below during a recent update - on both pre-prod and production.  Retrying the upgrade enabled the process to continue.  We have received something similar in the past, but did not document it sufficiently.  This time we made sure we captured the details.

Thanks,
   Andrew

Moodle:
3.9.12

Plugin version:
From:
2020120600

To:
2021120900

-->qtype_stack
++ 2021010100: Success (0.07 seconds) ++
Default exception handler: stack_ast_container: tried to get the value from of an unevaluated casstring. Debug:
Error code: exceptionmessage
• line 202 of /question/type/stack/stack/cas/ast.container.class.php: stack_exception thrown
• line 452 of /question/type/stack/stack/cas/installhelper.class.php: call to stack_ast_container->get_value()
• line 889 of /question/type/stack/db/upgrade.php: call to stack_cas_configuration::create_auto_maxima_image()
• line 692 of /lib/upgradelib.php: call to xmldb_qtype_stack_upgrade()
• line 1917 of /lib/upgradelib.php: call to upgrade_plugins()
• line 193 of /admin/cli/upgrade.php: call to upgrade_noncore()
!!! stack_ast_container: tried to get the value from of an unevaluated casstring. !!!
!!
Error code: exceptionmessage !!
!! Stack trace: * line 202 of /question/type/stack/stack/cas/ast.container.class.php: stack_exception thrown
• line 452 of /question/type/stack/stack/cas/installhelper.class.php: call to stack_ast_container->get_value()
• line 889 of /question/type/stack/db/upgrade.php: call to stack_cas_configuration::create_auto_maxima_image()
• line 692 of /lib/upgradelib.php: call to xmldb_qtype_stack_upgrade()
• line 1917 of /lib/upgradelib.php: call to upgrade_plugins()
• line 193 of /admin/cli/upgrade.php: call to upgrade_noncore()
!!

**Comment by nadavkav** [comment]
Hi @sangwinc ,
I have similar issue while upgrading STACK 4.4.2 to 4.6
Any idea how to solve it?

**Comment by nadavkav** [comment]
OK, solved it by updating the castimeout (thanks! @sangwinc )
`php admin/cli/cfg.php --component=qtype_stack --name=castimeout --set=30`
