### ISSUE TITLE
Wrong equivalence of VA and W in casstring.units.class

### ISSUE THREAD

**Issue by jensfortmann** [maths/moodle-qtype_stack#775]
Wrong equivalence of VA and W in 
https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/casstring.units.class.php

VA (as apparent power) has an equivalence set to W (as 'real' or active power) - this is not correct.
        array('VA', '(kg*m^2)/(s^3)', 'VA', 'volt-ampere')

VA should only refer to itself
        array('VA', 'VA, 'VA', 'volt-ampere'),

Backgrond: The apparent power (unit VA) is defined as S = U*I. 
The apparent power consists of real power (P = S*cos(phi)) and the reactive power (Q = S*sin(phi)), 

with phi as angle between voltage and current for a given AC power system.
 
Consequence: 
- if voltage and currents are in phase, this is active power that can be used for motion, light, Energy,...
- if voltage and currents are not fully in phase, only the part in phase can be used, the rest (the reactive power) 'congests' the power line, (since the current is flowing and leads to losses) but does to contrtibute to active power

Consider a shaft that is connecting a motor to a load. if this shat starts swinigng (torsional swing), this swing does not lead to a faster operation of the load, but it still puts stress on the shaft.

**Comment by aharjula** [comment]
I really hate these units that need details of the context to function... Self-referencing is indeed a solution that turns it into a base unit that would not mix with any others. It also means that there is no method of automatic conversion to the other direction, not that it means anything when we have no access to context parameters i.e. that phase angle. And no this unit system will newer bring context definition into the system. If one wants to play with those one can simply do the maths with complex numbers and so on. When I said I saw no problems in #537 it was probably because at that point it had been 17 years since I did any calculations with reactive power, so I did not spot Chris setting `VA=W` being anyway wrong.

@sangwinc maybe you could switch that line in the code to a self-referential one...

**Comment by jensfortmann** [comment]
In case there are any questions I am happy to provide more information.
Our IT would implement the change directly, but only if it is accepted for the next release.

**Comment by sangwinc** [comment]
Ok, I'm really sorry I'm slow to the party on this one - it looks like an easy fix but I have to confess I don't understand the physics! 

Would you be willing to write up a brief note on why VA is not  (kg*m^2)/(s^3) for the docs?  This issue might re-open in the other direction by someone else making the same mistake as me!

Chris

**Comment by jensfortmann** [comment]
I will give it a try.
---
For DC systems (like a battery), in a steady state operating point voltages and currents are constant. The power can be calculated as P = U*I

For AC systems (like a synchronous generator), voltages and currents are given as sine waves with u(t) = u_magnitude * sin(omega *t + phi_u). For AC systems, in a steady state operating point, amplitude, frequency and phase angle are constant. 

The product of two sine functions sin(a)*sin(b) = ½ [cos(a-b)-cos(a+b)]. 
The calculation of power p(t) = u(t)*i(t) leads to p = U I cos(phi) – U I (cos(2*omega t-phi), 
with phi as the angle between voltage and current
The active or real power is described by the first term P = U I cos(phi), it consists of the component of voltage and current in phase. Its unit is W, this is equivalent to kg*m^2)/(s^3).

The second term Q = U I (cos(2*omega t-phi) is referred to as “reactive power”. It oscillates with twice the grid frequency, the integral over one line period is zero. The unit used is VA (sometimes also VAr or var). 

In AC systems, the apparent power S = U*I = P + Q consists of an active (real) part P and a reactive part Q. The unit used for the apparent power S is VA.

**Comment by sangwinc** [comment]
Thanks, that's clear now. And if anyone asks about why we changed this we have a record.  Sorry about this, the fix will be in the next release.

**Comment by sehomer** [comment]
Hi Chris,

this change was not committed to the v.4.3.11 Version, is there any chance that this will get into the official release?

Best regards
Sebastian

**Comment by sangwinc** [comment]
Sebastian,
That commit was into the dev branch and will be in the next major release (4.4). I have a couple more things to do before we enter the testing stages of this release.  I had to release v.4.3.11 urgently to unblock progress on a specific project who needed new JSXGraph code.
Chris

**Comment by sehomer** [comment]
Hi Chris, 

thank you for your fast reply.

Best regards
Sebastian
