### ISSUE TITLE
Suggestion: remove navigation and blocks from question test screen

### ISSUE THREAD

**Issue by gustavdelius** [maths/moodle-qtype_stack#78]
The question preview pop-up window does not show the moodle navigation and blocks but only the preview question. If one then clicks on "Question tests & deployed versions" the script moodle/question/type/stack/questiontestrun.php produces the header, blocks and footer of a standard moodle page, even though it is still displayed in the same small preview window where there is not really space for it. I suggest removing that.

**Comment by sangwinc** [comment]
Gustav,

I've been working back through all the various "issues" and re-read this one.  I've just noticed the suggestion to move the position of the question test results on the page.  I've moved these and I also prefer them.   Thanks for this suggestion and sorry it has taken so long to implement something so simple!

I'll leave it to you and Tim to battle out the navigation issue.....
