### ISSUE TITLE
"Required" indicator for Model answer, SAns and TAns fields

### ISSUE THREAD

**Issue by lassikor** [maths/moodle-qtype_stack#780]
Hi,
would it be possible to add the red exclamation mark '!' icon before the Model answer, SAns and TAns fields in the question editing form. See attached picture. 
![editform](https://user-images.githubusercontent.com/42375494/158552406-5244e596-f741-476e-9197-ca73982a4553.png)
These fields cannot be empty so I think they could be indicated as "Required". 
BR
Lassi Korhonen

**Comment by sangwinc** [comment]
Lassi,
Thanks for the helpful suggestion.  Yes, you are correct, but we documented the practical reason for not doing this here: https://github.com/maths/moodle-qtype_stack/blob/master/edit_stack_form.php#L371
Chris
