### ISSUE TITLE
-1*cm refused by "units" input

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#782]
In the attached question, there is a validation error with a useless message. Input type is "units" with no extra options.

![image](https://user-images.githubusercontent.com/12987918/160391402-a704b060-c220-4f66-a875-7e78d4833ef3.png)

[quiz-T-B5-MB-TM3-TM3 06 T02 Zentrale Rotation-20220328-1347.zip](https://github.com/maths/moodle-qtype_stack/files/8362349/quiz-T-B5-MB-TM3-TM3.06.T02.Zentrale.Rotation-20220328-1347.zip)

**Comment by aharjula** [comment]
Have to wonder if this has some connection to #779 in any case that minus has somehow ended up on the unit side of the stackunits-object and things break. 

Hmm could it be that `-1` is a special case. Maybe that is one of those cases like `0` where it is necessary to explicitly define the teachers answer using `stackunits(-1,cm)` or here `stackunits(xM,cm)`. `0` is special as the simplification would simply throw away the units, and I would guess `1` gets thrown away as well so we are left with the minus which will attach to the units as it has no coefficient to attach to. The automatic unit splitting logic should probably spot this and move the minus to the coefficient side.

@sangwinc Chris, everyone's favourite unary operator is again causing a mess, do you have an idea on what was done to it recently and if that could have affected this...

**Comment by mkraska** [comment]
Thank you, `stackunits` did the trick (in the "model answer" field of the input).

There was a similar problem with zero values. It was slightly different in that it did not raise a validation problem, but had to be solved on PRT level (use of `stackunits()` in teacher's answer).

I think I should hardwire in my mind that I must not simply multiply in order to attach units to numeric variables. Instead use `stackunits()` EVERYWHERE. Sorry for bothering you with problems caused by dirty authoring :(

I add that to my [checklist for validation problems](https://github.com/mkraska/meclib/wiki/Feedback-Overview).

**Comment by sangwinc** [comment]
Sorry, I can't reproduce this problem on the latest version of the development code.
![Screenshot_2022-05-03_15-57-45](https://user-images.githubusercontent.com/781615/166479117-21f9365d-3bb4-45da-9b14-09ee3094b997.png)

**Comment by mkraska** [comment]
I confirm that it works with 4.4.beta.
