### ISSUE TITLE
Provide an option for Maxima to display floating point numbers using "continental" comma for the decimal separator.

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#789]
With a growing list of users we need to support an option for Maxima to display floating point numbers using "continental" comma for the decimal separator with the existing tex() function.  This issue is confined to tex only,

1. Code to solve the problem, defining any options needed
2. many robust test cases!
3. documentation

If we can solve this issue we will deal with student input and "the teacher's answer is ...." kinds of output separately.

**Comment by aharjula** [comment]
Does this mean that we also get a "continental" list/argument separator for those outputs? Is it a semicolon?

What about number grouping? There are all sorts of conventions for that. Should the output logic do grouping or not if the input logic does not allow it...

Also if the formatting ever becomes the default for the whole question, those playing with JavaScript will still want means of getting float values as JavaScript floats.

**Comment by sangwinc** [comment]
Exactly Matti!  Lots more questions, and things to discuss.  For now, I'd like to see if I can get the tex() function to cooperate...

**Comment by sangwinc** [comment]
The very helpful folk in the Maxima community are discussing this - the feature would be helpful there as well.
E.g. https://sourceforge.net/p/maxima/mailman/message/37647279/
I think we should see how they get on with adding this option to the core of Maxima.

**Comment by Bjoern-Ge** [comment]
Thanks for this option to display the text output.

I tested it in a couple of questions, and it did change the dot in decimal fractions to comma.
 
The way the comma was displayed was in the way it is used in lists with a space behind the comma.
Example:
7.45 was displayed like 7, 45 and not like 7,45 

In the screenshot, 7.45 and 6.29 are stack variable displayed. 42,2 is the expression: \(42{,}2\)

![Screenshot](https://user-images.githubusercontent.com/93242256/182112942-47bda82c-0069-4067-a722-c26a72ba9324.png)

**Comment by Bjoern-Ge** [comment]
Concerning the space after the decimal separator, I tried to put "{,}" into the code instead of ",". 
This didn't work and only "(" was used as a "decimal separator". 
As it seems to be a mathjax problem, I found this:
https://github.com/mathjax/MathJax/issues/169 
solving the problem about the space after the comma.

`<script type="text/x-mathjax-config">
MathJax.Hub.Register.StartupHook("TeX Jax Ready",function () {
  MathJax.InputJax.TeX.Definitions.number =
    /^(?:[0-9]+(?:\{,\}[0-9]{3})*(?:\,[0-9]*)*|\,[0-9]+)/
});
</script>`

**Comment by Bjoern-Ge** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/gerss/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/gerss/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/gerss/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=DE style='tab-interval:35.4pt;word-wrap:break-word'>


<p class=MsoNormal><span lang=EN-GB style='mso-ansi-language:EN-GB'>Moving the decimal
separator, has the need to move the list separator.<o:p></o:p></span></p>



As it is | Continental option | Example as it is | Example continental
-- | -- | -- | --
. | , | 3.5 | 3,5
, | ; | [3,4.5] | [3;4,5]



<p class=MsoNormal><span lang=EN-GB style='mso-ansi-language:EN-GB'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span lang=EN-GB style='mso-ansi-language:EN-GB'>Is there a
Semicolon used by now? I never meet on in the input.<o:p></o:p></span></p>

<p class=MsoNormal><span lang=EN-GB style='mso-ansi-language:EN-GB'>To choose how
to display and input numbers it might be a good idea to have a option for this
in the Stack “Maths display options “.<o:p></o:p></span></p>


</body>

</html>

**Comment by sangwinc** [comment]
A fix to this issue is now in "dev" for release in the next version.  There are still some edge cases (matrix().matrix()) unresolved, but it's time to get this feature in use.
