### ISSUE TITLE
Longer term maintenance of JSX graph

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#796]
Could we rearrange matters to make STACK make use of the official JSXGraph plugin https://moodle.org/plugins/filter_jsxgraph

Could we make STACK depend on this plugin.  This would make it considerably easier to maintain STACK (we no longer serve up JSXGraph) and the JSXGraph people do not rely on us for updating JSXGraph within STACK.

**Comment by sangwinc** [comment]
@[alfredwassermann](https://github.com/alfredwassermann), do you have any comments on this?

**Comment by aharjula** [comment]
If we could get the Moodle JavaScript system to load up the filters JavaScript in a way we can link to it, that would lead to some extra limitations for the filter and how it delivers the JavaScript.
