### ISSUE TITLE
Using Maxima in Syntax hint for equivalence reasoning

### ISSUE THREAD

**Issue by Bjoern-Ge** [maths/moodle-qtype_stack#798]
When using equivalence reasoning, it can be useful to enter the first line of the equation as a teacher.

I found that it is possible to enter a Syntax hint. 

Is it possible to access the maxima equation with randomization for the Syntax hint?

**Comment by stebac** [comment]
You can just add `firstline` as the syntax hint.
Stephan

**Comment by Bjoern-Ge** [comment]
I only found that this can be added in the extra options box.
Thank's that was what I was looking for.
