### ISSUE TITLE
Hiding unnecessary input options

### ISSUE THREAD

**Issue by m-r-k** [maths/moodle-qtype_stack#799]
In the Options summary table (doc/en/Authoring/Inputs.md) one can see that no every input option is used by the different input types. Thus I suggest not showing them in this cases.

**Comment by m-r-k** [comment]
With the help of the moodle form lib i was able to do this.
See my patch in branch iss799

**Comment by m-r-k** [comment]
Additional information:
The used `hideIf` function is available since Moodle 3.4 and it is documented here:
https://docs.moodle.org/dev/lib/formslib.php_Form_Definition#hideIf

**Comment by sangwinc** [comment]
Thank you so much - this is a very helpful improvement and I'll merge this into the "dev" code for the next release.  When we develop "input 2" we should probably have a static function for the input class which decides whether the field is hidden rather than lists in the edit form.
