### ISSUE TITLE
Bulk testing

### ISSUE THREAD

**Issue by KZerva** [maths/moodle-qtype_stack#804]
This issue is something that most users won't notice because only site administrators can run the bulk tests.

When a course has questions stored in the "Quiz question bank" the bulk test on this course doesn't run the tests on these questions. These quizzes appear in the list of courses, and I can run the bulk test to each of them individually. I can see the benefit because it only takes a couple of minutes to run the test in 1 quiz that has 10-15 questions, in comparison with a whole course that has 1000 questions. 

The main problem is that I have multiple instances of these quizzes. These quizzes have the same name every year (it's the topic covered on this quiz) and we use some of them in 2 different courses, so I have the same quizz appearing 4 times on the list of courses. Since we'll keep using these quizzes (and changing the name doesn't seem an option) it gets more difficult to find which is the most recent one. My experince says that it's the one at the bottom of the list of courses.

My question is:
a) Is it possible to run the bulk test in a course, including the questions which are stored in the "Quizzes Question Banks"?
b) Or add a feature so that we can see the courses that have been added on the server on the last year?

**Comment by sangwinc** [comment]
Thanks for raising this Konstantina, I know this kind of thing occupies a lot of your time and that you don't have command line access for running more specific code.  This is related to this query

https://github.com/maths/moodle-qtype_stack/blob/master/stack/bulktester.class.php#L35

which is used to find the "contexts" which have a non-zero number of STACK questions.  I think it is time to develop a more subtle approach, perhaps with the "course" and listing the contexts within each course. I'm actually not sure how Moodle organises the question bank, so I'll have to look into this.

**Comment by timhunt** [comment]
This is an issue which affects us at the OU too - but basically we just live with it, becuase it only affects me and Anupama, the tester who works in my team.

Option a) would be nice. However, the structure of the question bank will be changing in Moodle 4.1, so I don't think that now is the best time to work on this.

**Comment by sangwinc** [comment]
Thanks Tim, yes I'm planning to work with Konstantina to get a better immediate workflow.  I think waiting for Moodle 4.1 is a sensible suggestion.

**Comment by georgekinnear** [comment]
Just to chip in on this, I would really like the ability to run the question tests on a given category in the question bank.

For my course with ~1000 questions in the overall bank, it's not feasible to run the full report very often, so I usually just do this once before the start of term. But if I could target just a single category, I could run the report on a more manageable batch of questions (e.g. on all the questions for a given topic), to double-check that I've fixed all the issues.

**Comment by KZerva** [comment]
One solution could be to move each category's questions into each "Quiz question bank" and then you could run the test on these quizzes.

Cons: i) you aren't able to see the categories/questions in the question bank ii) you end up having multiple instanses of the same quiz appearing in the test page.

**Comment by aharjula** [comment]
Tim? You know that little button at the bottom of the question bank that lets you execute an action "with selected". Is it possible to define new actions that it could do?  After all, a question can already define actions for that "actions/edit" dropdown, so could there be a way of defining an action that could receive a list of identifiers of the selected questions? Or maybe there already is a way but that interface is unknown to us?

![Screenshot_2022-06-24_07-32-29](https://user-images.githubusercontent.com/980957/175463032-3c179a18-8230-4a2c-a1cb-342583094a78.png)

**Comment by timhunt** [comment]
Basically yes - if you create a new qbank_ plugin. At the moment, this can't be done by qtype_ plugins, but that is quite reasonable.

**Comment by aharjula** [comment]
So we should build something like the ["bulkmove"](https://github.com/moodle/moodle/tree/master/question/bank/bulkmove) which implements ["bulk action base"](https://github.com/moodle/moodle/blob/master/question/classes/local/bank/bulk_action_base.php) if we were to use that "with selected" capability, but at this point, we would need to build a `qbank_` plugin to be installed separately and can not do it from within a `qtype_` plugin. Basically, adding a mode for the current bulk-tester to act on a list of questions coming from that `qbank_` plugin (which would basically only do the redirection to the existing logic) should not be too hard and installing a new plugin to a Moodle install to have this functionality is something that people can do.

**Comment by georgekinnear** [comment]
@KZerva - thanks for the suggested workaround, I'm using that now to run some tests!

@aharjula - I like this suggestion, though perhaps there is an issue with permissions? Currently it is only administrators who can access the bulk testing, so this change would presumably open it out to all teachers / users with appropriate question bank access. Maybe that's a good thing, though.

**Comment by sangwinc** [comment]
George,
The permissions issue is very easy to fix once we've decided what we
actually want to achieve!
Chris

**Comment by aharjula** [comment]
Chris, to me it seems safe to allow running unit tests for any question you can edit and any question you see in the question bank is probably a question you can edit, and if I understood correctly the bulk_action-interface even checks for that.

The bigger problem is the load issue, if every teacher may trigger unit testing of massive category trees at any time then there may be issues related to load. But that can probably be solved by making it so that you can only run one of these at a time, e.g. don't release the session after this bulk testing job starts. Those with more permissions can use the admin version of the bulk tester and start multiple parallel tests, but maybe general teachers should not be able to do that (maybe having some specific permission would release the session so that another request could start running).
