### ISSUE TITLE
STACK, moodle 4.0 and question tests

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#805]
We are testing STACK and Moodle 4, and the plugin works well so far.  The new question versions feature looks great, thank you!

When saving a question, the question tests get "left behind", and the new version ends up without any tests.  I would like to propose that when a new question version is created the question tests get copied over (just as the question is copied I think?).  

The question tests are a really important part of the question, and leaving these behind is significantly blocking progress with testing materials on Moodle 4.0.

**Comment by timhunt** [comment]
I agree with this proposal. We are planning to do something similar for qtype_pmatch.

**Comment by sangwinc** [comment]
Thanks Tim,
This issue, and the note in the development track, is really a reminder that we shouldn't use Moodle 4.0+ until this issue is fixed!  Any help would be appreciated.
Chris
