### ISSUE TITLE
Spurious newlines between AT feedback and PRT node feedback

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#807]
There are two spurious newlines (`<br><br>`) between the automatic feedback from the answer test and the custom feedback from a node in the same PRT.  Feedback style is set to `compact`.

This is a cosmetic issue, it just wastes screenspace and looks like something went wrong. I am quite sure that I didn't produce the newlines in the feedback function, because inspection of the page source shows that these newlines are actually outside the span with the custom feedback.

Issue found in STACK 4.3 and persists in 4.4b (at Aalto).
```

<p><span class="stackprtfeedback stackprtfeedback-MA"><span class="incorrect"><span style="font-size: 1.5em; color:red;">
<i class="fa fa-times"></i></span></span>
<span class="filter_mathjaxloader_equation">Die rot unterstrichenen Einträge sind falsch. <span class="filter_mathjaxloader_equation">
<span class="nolink"><span class="nolink">\[ \left[\begin{array}{c} -{F}_{1}\cdot a \\ {\color{red}{\underline{-2\cdot a^2\cdot q-2\cdot {F}_{1}\cdot a^2}}} \\ 2\cdot {F}_{2}\cdot a \end{array}\right]\]</span></span></span>
 <br>  <br>
<span class="nolink">\(y\)</span>: Pr&uuml;fen Sie den Term mit <span class="nolink">\(F_1\)</span>.<br>  </span></span></p>

```

![image](https://user-images.githubusercontent.com/12987918/171486109-20861086-6a7b-4407-911f-86cb37a03303.png)

Suppressing automatic feedback still looks weird (second screenshot below).  The two spurious newlines seem to persist even if nothing is to be separated by them.

![image](https://user-images.githubusercontent.com/12987918/171488044-663f0e55-039a-4637-947c-b949564586de.png)

[quiz-T-B1-MB-TM1-TM1 13 05 Resultierende Kraft und Resultierendes Moment-20220601-2101.zip](https://github.com/maths/moodle-qtype_stack/files/8818300/quiz-T-B1-MB-TM1-TM1.13.05.Resultierende.Kraft.und.Resultierendes.Moment-20220601-2101.zip)

**Comment by sangwinc** [comment]
You have two <br/> tags in the false branch feedback

```
{@fb_vars(S_MA[1,1], MA[1,1], [], "\\(x\\):")@}<br>
{@fb_vars(S_MA[2,1], MA[2,1], [q, F_1], "<br>\\(y\\):" )@}<br>
{@fb_vars(S_MA[3,1], MA[3,1], [], "<br>\\(z\\):")@}
```

Is the fb_vars function producing an empty string here?  If you remove this code from the PRT then the <br> tags get removed!

**Comment by mkraska** [comment]
You are absolutely right. The function fb_vars has been modified to not produce empty lines. Yet it can't do anything about the spurious `<br>` tags outside of it. 

This is correct.

    {@fb_vars(S_MA[1,1], MA[1,1], [], "\\(x\\):")@}
    {@fb_vars(S_MA[2,1], MA[2,1], [q, F_1], "<br>\\(y\\):" )@}
    {@fb_vars(S_MA[3,1], MA[3,1], [], "<br>\\(z\\):")@}

Still, the logics is not good, so I had to change `fb_vars` to issue line breaks at the end rather than at the start of non-empty return values.

Sorry, for bothering you with my own mistakes.
