### ISSUE TITLE
Failed CASText Validation. TIMEDOUT (%i4) The CAS timed out.

### ISSUE THREAD

**Issue by taraghi** [maths/moodle-qtype_stack#817]
Hi,

We have a problem with a stack question in a quiz, outputting:
`This question leads to an unexpected internal error. Please seek advice, e.g. from a lecturer` 
following the output bellow:
![Fehlermeldung Csurmann Frage 6](https://user-images.githubusercontent.com/204101/178771868-78d069fc-4459-41ed-a668-043291adc8e3.PNG)

Remarkably, the incidence occurs only to one student and we have not been able to reproduce it by ourselves.

Do you have any idea what the reason can be and what we can do to fix the problem?

**Comment by sangwinc** [comment]
This is almost certainly an issue with either the question itself, or the particular student's response.  Please email me the question at C.J.Sangwin@ed.ac.uk, and explain what the student typed an I'll take a look.  This is almost certainly not an issue for the plugin, so I'll close this issue.
