### ISSUE TITLE
Deprecated warnings: Required parameter follows optional parameter

### ISSUE THREAD

**Issue by voegii** [maths/moodle-qtype_stack#818]
Just installed version 4.4 on a testing environment with Moodle 3.11 and PHP 8.0.

Following messages appears:

```
Deprecated: Required parameter $options follows optional parameter $errors in /var/www/html/moodle/question/type/stack/stack/cas/castext2/block.interface.php on line 99

Deprecated: Required parameter $options follows optional parameter $errors in /var/www/html/moodle/question/type/stack/stack/cas/castext2/blocks/commonstring.block.php on line 121

Deprecated: Required parameter $options follows optional parameter $errors in /var/www/html/moodle/question/type/stack/stack/cas/castext2/blocks/textdownload.block.php on line 82

Deprecated: Required parameter $options follows optional parameter $errors in /var/www/html/moodle/question/type/stack/stack/cas/castext2/blocks/include.block.php on line 90
```

**Comment by timhunt** [comment]
Note, we hit these issues, and a fix for them in in the master branch here. Not sure if it has been released yet though.

**Comment by sangwinc** [comment]
Thanks very much for reporting this problem.

Tim, did you push changes to a fork of the code as I can't see any changes here: https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/castext2/block.interface.php

**Comment by timhunt** [comment]
Ah! I think I am confused. We are not running 4.4(pre-release) yet. We are still on STACK 4.3.x.

https://github.com/maths/moodle-qtype_stack/commit/aca0cbbd45be840a7ee42eb2859e97678fe55312 is a different PHP8 fix I did.

The "Required parameter ... follows optional parameter ..." fixes I remember doing were in CodeRunner.

So, these issues must be new in STACK 4.4 (casstring2). It needs to be fixed. (Normal fix is to just remove the default value for arguments which have other required arguments later in the function signature.

Sorry for the confusion.

**Comment by sangwinc** [comment]
Thanks Matti,
Chris
