### ISSUE TITLE
General feedback is missing

### ISSUE THREAD

**Issue by raedshorrosh** [maths/moodle-qtype_stack#819]
We installed STACK 4.4.  After testing the quizes, i found that the feedback is given only for each PRT but does not give the usual Moodle feedback ie corect, partially correct, or incorrect.  What is wrong ? did we miss something in the installation ?

**Comment by sangwinc** [comment]
Sorry about this.  Would you email me your question and I'll check out what is happening?  C.J.Sangwin@ed.ac.uk

**Comment by raedshorrosh** [comment]
Dear Chris
Thank you  for your reply.  I am attaching a simple example that has two
prt's.  I get feedback for each prt but not for the question a whole
thank you

Best regards,
Raed Shorrosh

**Comment by nadavkav** [comment]
@sangwinc , is there any news about this issue?
