### ISSUE TITLE
Question editing form - "Options" has become "Opt"

### ISSUE THREAD

**Issue by georgekinnear** [maths/moodle-qtype_stack#820]
Since our server was upgraded to version 2022071300 of STACK, I've noticed the "Options" section on the question editing form is now called "Opt":
![image](https://user-images.githubusercontent.com/30723394/180795252-c9733f47-f267-43ee-b945-9abe8fc57d5f.png)

I guess this is just an error rather than something intentional?

I did search the repo for "Opt" to see where this was coming from, but couldn't figure it out. I guess if you know your way around the code, this will be an easy fix!

**Comment by timhunt** [comment]
All UI text in Moodle comes from from the language file.

Looks like Chris changed this, thinking it only affected something else: https://github.com/maths/moodle-qtype_stack/blame/master/lang/en/qtype_stack.php#L646
