### ISSUE TITLE
Unit Tests UnitsRelativ with test option 0

### ISSUE THREAD

**Issue by Bjoern-Ge** [maths/moodle-qtype_stack#825]
When trying to use the answer test UnitsRelativ with the test option 0, I expected to get true for:

ATUnitsRelative(102.9*mm^3, stackunits(0.1029,cm^3), 0.0) = [0, "ATUnits_compatible_units m^3."];

But the result was false.

When the test option was set to 0.001 the result was true:

ATUnitsRelative(102.9*mm^3, stackunits(0.1029,cm^3), 0.001) = [1, "ATUnits_compatible_units m^3."];

Is this a bug, or did I misunderstand the answer test?

**Comment by sangwinc** [comment]
This is almost certainly an internal rounding error in converting 102.9*mm^3 to 0.1029*cm^3.  Maxima uses binary representations of floats, so many terminating decimals end up a recurring binary floats, and so we get rounding errors propagating.  This makes "0.0" a dangerous tolerance, although it is not clear this would be the case.

**Comment by Bjoern-Ge** [comment]
Thanks, then I will set a slightly larger number than 0.0 as option.
