### ISSUE TITLE
matrix() protected against ev() ?

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#830]
In a question with matrix values I observe a difference between standard maxima and STACK 4.4 (should have worked in 4.3 but I can't prove that any more).

the code is
```
y: a*sin(2*%pi*x/L);

dy: diff(y,x);
ddy: diff(y,x,2);

aa: rand( [0.3, 0.4, 0.5, 0.6, 0.7, 0.8] );  
LL: rand( [3,4,5] ); 
XX: rand( [0.2, 0.35, 0.6, 0.1] ) *LL;
vv: rand_with_step(2, 9, 1);

kappa:float(ev(ddy/(1+dy^2)^(3/2), a=aa, L=LL, x=XX));
an: abs(kappa)*vv^2;

et: float(ev( matrix(  [1/sqrt(1+dy^2)],[dy/sqrt(1+dy^2)] ), a=aa, L=LL, x=XX));
en: float(ev( abs(kappa)/kappa*matrix(  [-dy/sqrt(1+dy^2)],[1/sqrt(1+dy^2)] ), a=aa, L=LL, x=XX));
```
Maxima results (no sandbox, just pure maxima, rand() replaced by fixed values)

![image](https://user-images.githubusercontent.com/12987918/183065107-219edcd9-67a5-47d0-b114-689d74221020.png)

When injecting the values using these commands:
 ```
{@en@}

{@float(ev( matrix(  [1/sqrt(1+dy^2)],[dy/sqrt(1+dy^2)] ), a=aa, L=LL, x=XX))@}

{@float(ev( matrix(  [1/sqrt(1+dy^2)],[dy/sqrt(1+dy^2)] )[1,1], a=aa, L=LL, x=XX))@}
```
I get this display:

![image](https://user-images.githubusercontent.com/12987918/183065442-39b30562-db58-4ef3-90e6-973b0ab5510b.png)

Observation:
-  The wrapping ev() for the matrix expression only works for individual elements. 
- If the whole matrix is under ev(), then the substitutions fail, no matter if a storage variable was used or the expression was directly injected.

Same happens when using variables en and et as teachers answer, so the PRT fails.

[quiz-T-B5-MB-TM3-TM3 02 03 Sinus (Bug)-20220805-1312.zip](https://github.com/maths/moodle-qtype_stack/files/9268055/quiz-T-B5-MB-TM3-TM3.02.03.Sinus.Bug.-20220805-1312.zip)

BTW, the question test shows the correct values:

![image](https://user-images.githubusercontent.com/12987918/183066790-061bb48c-f68a-4c06-8c57-2aa858e325c1.png)

**Comment by aharjula** [comment]
Probably same as #824. Try `ev()` -> `at()`.

**Comment by mkraska** [comment]
You are right, at() helps. However, at() needs the replacement equations being in a list, whereas ev() just has arbitrary number of arguments. 

I missed that in the beginning. The editor refused to save the question, framed the question variables in red and the error message was "no error".

This might be an issue of it's own.

**Comment by sangwinc** [comment]
Can we document all this please?!

**Comment by aharjula** [comment]
Chris,

Document what? If this is an issue we should probably solve it if possible. Using `at` just seems to be a workaround that works. I have only spent four days trying to figure this out after George had this same issue in #824 and even there the oddity is that all the evaluations seem to happen for the question test page listing but not in the actual places where they are used, e.g. in CASText and answer tests and that does not really make sense.

Beyond that, there are two different problems with `ev` in play the first one that is probably going to require the use of `at` is having the substitutions come directly from a function call and the second one is with the target being a function-call bot would point to the new security system but neither makes clear sense. I am starting to run out of ideas, maybe you could push those expressions through the runtime check filter and see how the resulting wrapped version evaluates and whether it would need some extra processing to behave well.

If it is not the new security system, then its CASText2 + the new security system, or maybe one of the bits that does unwrapping inside stack_disp.

`at` working when `ev` does not seems to point to evaluation order related issues, but again there should not be differences with the evaluation order. In any case, this needs to be figured out as `ev` is quite widely used and we are also rewriting evaluation-flags to `ev`. And we cannot simply use `at` for everything as it does not exactly do the same thing, it just overlaps for the most common task people do.
