### ISSUE TITLE
unable to get in to Tidy STACK question tool

### ISSUE THREAD

**Issue by uziharush** [maths/moodle-qtype_stack#835]
Hi,
When one of the input defined as Drop down list I cant enter Tidy STACK question tool.
![r](https://user-images.githubusercontent.com/33420471/184117011-774648d4-7677-433f-bea4-1eb959536880.PNG)

**Comment by sangwinc** [comment]
Sorry about this - thanks for reporting the problem.

**Comment by uziharush** [comment]
Thank you!
I took your correction manually and it work properly.
