### ISSUE TITLE
Matrix is read from right to left

### ISSUE THREAD

**Issue by toolmathmoodle** [maths/moodle-qtype_stack#837]
Hi,
I not sure that it is a bug, but I think it is fixable.
My moodle site is in Hebrew, Hebrew is weird language that is written from right to left which cause problems when we need to integrate between Hebrew and math (like in latex). Moolde and STACK deal with it nicelly without any bugs except one:
If the input is "Matrix" or "Matrix of variable size" it is also read from right to left (see figure). If it is hard fix I will use Algebraic input with hint for the syntax which bypass the problem.

Thanks :-) 

![image](https://user-images.githubusercontent.com/111237208/184544515-9af8fe62-d962-42f8-8052-bef22b1c2d90.png)

**Comment by sangwinc** [comment]
Oh dear!  That really does need to be fixed.

I suspect, this could be a relatively easy CSS fix.  But, I'm no expert in either CSS, or how Moodle packages up CSS and hence the order in which styles are applied.  The STACK CSS, and the var matrix in particular, is defined here

https://github.com/maths/moodle-qtype_stack/blob/master/styles.css#L840

Is it as simple as adding in

 direction: ltr;

to this CSS I wonder?

**Comment by sangwinc** [comment]
Ok, I'm planning a new release (minor bug fix) at the end of this month. If you can hot-fix your CSS file and test this before then it would be much appreciated.

**Comment by toolmathmoodle** [comment]
Thanks,
It solved the problem only in "Matrix of variable size" which now the text box of the input is read from left to right as it should be, but in input Matrix the problem is still relevant (see figure).

Other issue (minor one) which appears regardless of language, the input box of "Matrix" and "Matrix of variable size" is not centralize like algebraic input, in Englsh the input box appears in left without centralize  - I can open new issue on it.

![image](https://user-images.githubusercontent.com/111237208/184582252-4499468e-7003-4c32-a06f-c7ad0bf606c2.png)

**Comment by sangwinc** [comment]
Glad to hear we've made progress.  Can I ask for your continued help?  Please could you load up these sample questions
https://github.com/maths/moodle-qtype_stack/blob/master/samplequestions/input-sample-questions.xml
(import the .xml into the normal Moodle question bank).  This should contain a comprehensive selection of samples for all the input types.  If you are able to test them all, then we can compile a complete list of all the inputs for which rlt/ltr is an issue.

**Comment by toolmathmoodle** [comment]
Sure,
first I will comment that I got a error when I tried to import the .xml file from the link, it is version problem (my STACK version is 4.3.10) so I took the file that packed in v4.3.10.

See summary below
![image](https://user-images.githubusercontent.com/111237208/184597009-d8a0fa31-e180-48b6-a5ba-8246fd65f95b.png)

![image](https://user-images.githubusercontent.com/111237208/184597232-720f1e34-9cc4-4424-a56c-c5e72d9bc5e7.png)

**Comment by sangwinc** [comment]
Thanks for that.  I think I have a fix for this which I'll push when I've run the unit tests. I'm struggling to reproduce the dropdown problem.  Could I ask you to author a question from scratch which replicated the problem in a minimal way?

Also, I'm fascinated (sorry for my ignorance here) about how mathematics is embedded into text.  Reading an equation isn't a linear LTR or RTL process, but just to confirm you _do_ expect the equations to be written in the same way in both languages?

**Comment by toolmathmoodle** [comment]
Thanks,
Yes, any mathematical expression should written similar in both languages.
About the dropdown I suspect that it is moodle issue, there is some problems when I write mathematical expression in equation editor. See also the PRT but the student dont see it so I dont care (I move to English when I write the PRT).
If it is can help the question file is attached.

Any way it is huge progress for me.

![image](https://user-images.githubusercontent.com/111237208/185453192-234129df-83d4-4e9c-9dbb-c40e0cc6ccab.png)
[dropdown_question1.zip](https://github.com/maths/moodle-qtype_stack/files/9376124/dropdown_question1.zip)

**Comment by sangwinc** [comment]
I hope this fixes everything except, perhaps, the dropdown.  Happy to work on this further.  I'm planning a release on Monday 29th.

**Comment by toolmathmoodle** [comment]
Hi, 
Thanks, I took your changes and they work well except, the dropdown as you suspect.
But I know how to bypass it in the dropdown, if the list will be someting like "ta:[[-2*x,true,"2x-"],[x,false,"x-"]];" so moodle will try to write 2x- which will show -2x.

Thanks again.
