### ISSUE TITLE
Add seed numbers to headings in the "basic question use report"

### ISSUE THREAD

**Issue by georgekinnear** [maths/moodle-qtype_stack#840]
I think the latest update has changed the content of the sub-headings under "Raw inputs and PRT answer notes by variant" on the basic question use report page. They now look like this:

![image](https://user-images.githubusercontent.com/30723394/185607690-9d7661c1-1353-4a71-aca7-4fa2020135ea.png)

I like that it now shows the question note, but I think it would be useful to keep the seed number there too, so that it's easier to search for a particular one. And sometimes the question notes are not that easy to follow!

**Comment by sangwinc** [comment]
Ok, they can be put back as well....
