### ISSUE TITLE
Simplify presentation on the question tests page

### ISSUE THREAD

**Issue by georgekinnear** [maths/moodle-qtype_stack#847]
I'm finding the question tests page quite cluttered now, with all the `<pre>` tags showing the code for each PRT.

(As a side issue, I'm not sure how I'm supposed to use that information....)

I wonder if the gory details could be hidden away with a `<details>`/`<summary>` combo?  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

Looks like the key line is here:
https://github.com/maths/moodle-qtype_stack/blob/03e884213df8e4f2d65813562d26e76814fd7b71/questiontestrun.php#L521

I'm not sure how to edit that in the proper style, but the goal would be to take those two parts and arrange them as follows:

```
<details>
<summary> s($state->answernote) </summary>
html_writer::tag('pre', implode('', $prtinputs) . $state->trace)
</details>
```

Here's what it would look like applied to prt1 in this example:

![image](https://user-images.githubusercontent.com/30723394/187211048-55ef35f3-5ead-4696-b55e-0c0cd991c191.png)

The whole of the triangle and "prt1-1-T" text can be clicked to expand the details.

**Comment by sangwinc** [comment]
Interesting suggestion George - thanks for this.  I've added your suggestion to the dev branch. I use this information an awful lot, so this will involve a lot of extra clicks.  I might revert this particular use, but I didn't know about this html, which is very useful elsewhere.  Thanks!
