### ISSUE TITLE
Lambda functions not allowed in CASText?

### ISSUE THREAD

**Issue by georgekinnear** [maths/moodle-qtype_stack#848]
Since our server was updated to the latest version, this question (among others) is now broken: 
[questions-FAC 22-23-3.3.3 Expand binomial - (2x-1)^4 type-20220905-0807.zip](https://github.com/maths/moodle-qtype_stack/files/9487757/questions-FAC.22-23-3.3.3.Expand.binomial.-.2x-1.4.type-20220905-0807.zip)

I'm seeing the following error message after the worked solution when I try to save the question:
> This function call _tmp_996 does not appear to have an easily visible function name. Due to security reasons you may need to simplify the call so that the validator can see the function name.

The issue seems to be my use of `lambda` functions within the CASText.

## Minimal example

Take a working question and put the following into the question text:
```
{@maplist(lambda([ex], x^ex), [1,2,3,4])@}
```
I get the same `_tmp_996` message.

## Workaround

The same code is allowed in the question variables, e.g.
```
working1: maplist(lambda([ex], x^ex), [1,2,3,4])
```

You can also give the lambda function a name before calling it:
```
{@(myfunction: lambda([ex], x^ex), maplist(myfunction, [1,2,3,4]))@}
```

## Resolution?

I will have to patch my broken questions for now, but it would be good if the original use of lambda functions could be allowed again.

**Comment by aharjula** [comment]
Seems like the old security system attacks the new one's solution to #824. I guess we need to strip out that part of the old system sooner than expected. I was planning to excise it but was hoping to think things through for a somewhat longer time just in case something evil would become possible.

**Comment by georgekinnear** [comment]
Thanks, at least there is a workaround for now!

**Comment by KZerva** [comment]
I was ready to come here and post exaclty the same issue! Thanks for providing a workarrond George, it works in my questions for now.
