### ISSUE TITLE
Over-picky complaints on variables in user input

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#855]
I know that names used in the question variables are forbidden as part of algebraic input by default.

Yet I am surprised that this seems to apply to local variables in block() statements also. And what is also surprising, that this seems to apply to subparts of variables like the `v` in `A_v`.

The following question exhibits the problem: It has a link to a maxima macro file on github in it. In the preview, insert the correct solution and press Check.

Then you get a complaint on a forbidden variable in the input: 

![image](https://user-images.githubusercontent.com/12987918/189539654-cd0f9f0f-c62f-4410-97f7-b519998759b2.png)

Deleting the force A_v (by doubleclick on it) and pressing Check again, you see that the culprit in the internal input is indeed the variable `A_v`

[quiz-MMM-FBD demo (ll)-20220911-1849.zip](https://github.com/maths/moodle-qtype_stack/files/9543110/quiz-MMM-FBD.demo.ll.-20220911-1849.zip)

Another observation is that if you copy the macro to the question variables and change the following function definition by replacing `v` by `%_v` then the problem is gone.

```
/* https://github.com/mkraska/meclib/wiki/direction%28%29 */
direction(o):=block([v, a0, le, r1, r2, a1],
  if member(o[1], ["bar", "force", "dashpot", "springt", "springc"]) then return(o[4]-o[3]),
  if member(o[1], ["fix1"]) then return([-sin(o[4]*%pi/180), cos(o[4]*%pi/180)]),
  if member(o[1], ["fix13"]) then return([cos(o[4]*%pi/180), sin(o[4]*%pi/180)]),
  if member(o[1], ["q"]) then (
    v: o[5]-o[4], le: cabs(v[1]+%i*v[2]), a0: carg(v[1]+%i*v[2]),
    return([cos(a0+o[8]*pi/180), sin(a0+o[8]*pi/180)]) 
    ),
  if member(o[1], ["rope"]) then (
    /* same math as in meclib */
    v: o[5]-o[3], le: cabs(v[1]+%i*v[2]), a0: carg(v[1]+%i*v[2]),
    r1: o[4], r2: o[6], a1: acos((r1-r2)/le),
    return(float(v+[(r2-r1)*cos(a0-a1), (r2-r1)*sin(a0-a1)]))
    )
);

```
Here is the same question with local definitions and the mentioned modification:

[quiz-MMM-FBD demo (l, %_v)-20220911-1849.zip](https://github.com/maths/moodle-qtype_stack/files/9543119/quiz-MMM-FBD.demo.l._v.-20220911-1849.zip)

Everything could be clear by now, but I failed to produce a minimum working example:

Using `f(x):=block([v], v: x, return(x));` in the question variables doesn't trigger the complaint when using `v` or `f_v` as input.

[quiz-MMM-forbidden variable demo-20220911-1849.zip](https://github.com/maths/moodle-qtype_stack/files/9543125/quiz-MMM-forbidden.variable.demo-20220911-1849.zip)

So I must admit that I didn't nail down the problem even though I seem to have a workaround.

Should I really mask all my local variables (and perhaps also the function arguments) to avoid such problems? I saw Matti using such coding style...

**Comment by mkraska** [comment]
The online version of the feedback macros has been fixed with the workaround v--> %_v, therefore the following question with external links works now:

[quiz-MMM-FBD demo (ll)-20220911-1849.zip](https://github.com/maths/moodle-qtype_stack/files/9552049/quiz-MMM-FBD.demo.ll.-20220911-1849.zip)

The original problem can be reproduced with this question, where the content is local:

[quiz-MMM-FBD demo (l, v)-20220912-2354.zip](https://github.com/maths/moodle-qtype_stack/files/9552062/quiz-MMM-FBD.demo.l.v.-20220912-2354.zip)

**Comment by sangwinc** [comment]
Yes, this happens here
https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/parsingrules/998_security.filter.php#L486

We did this to prevent possible construction of nefarious function calls.  This may be too cautious (@aharjula are we being too cautious here?).

The fix to this issue is to include `A_v` in the allowed words for that input.  

I accept we are probably being a little cautious here.

**Comment by mkraska** [comment]
In my case, it is part of the task to provide reasonable names for user-created entities like forces and moments. So, adding whatever students could think of to the allowed words is probably a hopeless endeavour.

Yet I see the priority of security.
