### ISSUE TITLE
test_confirm_induced_timeout needs a better task..

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#859]
Lately had some trouble with this particular unit test:
https://github.com/maths/moodle-qtype_stack/blob/29f077be3a11c8de632d418bb7018fde03e6bc0e/tests/cassession2_test.php#L2273-L2287

It does not quite behave the same way on all LISPs, for example, on SBCL one can get this result basically immediately:
```
Maxima restarted.
(%i7) p1:2^(2^100)-1;

Maxima encountered a Lisp error:

 can't represent result of left shift

Automatically continuing.
```
And on GCL, one typically runs out of memory quite fast or segfaults if one is unlucky. Neither of these leads to actual timeouts. It would be nice to have some other type of task that would not eat all the memory in the world but which would take enough time.

Does anyone have any great ideas for slow tasks that would not eat all the memory? Or should we simply write a loop and hope that Maxima does not figure out that it can optimise the loop away if we don't include sensible content for it?

```
for i:1 thru 2^100 do true;
```

**Comment by sangwinc** [comment]
Oh!  Sorry, I think I wrote that test and didn't think carefully about the difference between "time" and "space".   I also didn't realise that different maxima/lisp combinations would throw different kinds of errors.

What about something a bit less easy to optimise away without some thought?

```
p:1;
for i:1 thru 2^100 do p:p+(-1)^i;
```

I think 2^100 should be enough for now.  (And it would be nice to know when this isn't big enough any longer!)

**Comment by aharjula** [comment]
`2^30` is something one can expect to complete in a few hours on pretty much any machine, but `2^100` won't happen in our lifetimes without separate parallelism with any machine working with low GHz speeds... In any case, for us, all that matters is that it takes longer than the timeout we use in testing.

Your example will work just fine as it is indeed something that a compiler would not figure out., nor would any compiler logic we might add to the STACK side of CAS preprocessing.

**Comment by aharjula** [comment]
Ok. Now that tests times out, I'll add another test to confirm that the tests are being executed on the correct STACK-maxima version, as that is another issue that caused some trouble for me as I use MaximaPool in testing and sometimes forget things. That test can only test the version number of those scripts, so it won't catch all the issues we can have in `dev`. Maybe at some point, we could start using hashes of the scripts as an additional identifier that people externalising Maxima execution could use.
