### ISSUE TITLE
Update version of jsxgraph

### ISSUE THREAD

**Issue by smborio** [maths/moodle-qtype_stack#861]
Hi,

Version 1.4.6 of jsxgraph was released last week. My STACK installation is running jsxgraph v1.4.4 and in order to complete some interactive questions I need the changes made for v1.4.6. Is there a way to specify what version of jsxgraph to use or should I update the relevant file in here, create a PR and wait for the next release?

Many thanks,

Santiago

**Comment by aharjula** [comment]
Eventually, a new version will be bundled with STACK again, but I was waiting for the [JSXGraph conference](https://jsxgraph.org/conf2022/) to find out when and what is coming out.

Before that, you can always replace your own installation JSXGraph script with the released version and make [a small change in it](https://github.com/maths/moodle-qtype_stack/issues/690#issuecomment-781424153) to make it work in Moodles module system. It will likely work, but naturally, do test it and check the bindings. A pull request would be nice but I am already planning to include an update in 4.4.2.

**Comment by sangwinc** [comment]
We're certainly going to update JSXGraph as it is released.
