### ISSUE TITLE
Please simplify the input options

### ISSUE THREAD

**Issue by angelrios97** [maths/moodle-qtype_stack#862]
In the new version I noticed that only the required options are now available for the inputs.
Is it possible to simplify this further by hiding the advance options?

**Comment by sangwinc** [comment]
Ángel,
Thanks, this is a very sensible suggestion.  Can you make a specific proposal about (i) the order of the options, and (ii) which you think should be in the "advanced" list and we can discuss it further.
Chris

**Comment by aharjula** [comment]
Interesting idea and would simplify any future where we would have more options. But I hope that there would be some way to have a user-specific option for toggling the behaviour of this. We already need to "open" those inputs to see the options, and I, for one, would not want to then have to "open" a second level of hidden things to see everything. I would want to have some form of "expert" mode which would display all the options all the time by default. I wonder if it is possible to have such a plugin-specific user-level option in Moodle? Probably it is, but I have no idea how.
