### ISSUE TITLE
How to get the input "0*MPa" filled in as correct response?

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#868]
This might be related to #750.

Setting:
- input type units
- randomized question, where the correct value happens to be zero

Problem: Button `fill in correct responses` doesn't actually fill in any unit.
Correct answer would be `0*unit` but actually inserted is only 0. 

I tried these notations for model answer:
- value*unit (this perhaps simplifies to 0 if value is 0)
- stackunits(value, unit) as is used in the PRT

Typing 0*unit actually works and is accepted by the PRT. But still this is a glitch of the `fill in` function.

<img width="708" alt="image" src="https://user-images.githubusercontent.com/12987918/195987347-b7cf9406-1f9f-4c69-ace0-1f68e43e1f10.png">

**Comment by sangwinc** [comment]
Oh dear, sorry about this.
It is another result of a single call to the CAS.  You can avoid the problem if you set simp:false at the question level but that will, no doubt, break other things in your question. I'm working on a fix for the next release.
Chris
