### ISSUE TITLE
Give a validation warning about ln*x

### ISSUE THREAD

**Issue by georgekinnear** [maths/moodle-qtype_stack#874]
I'm getting a trickle of messages from students who have typed `ln*x` instead of `ln(x)` in their answers - and I would like a way to prevent them doing this through the validation feedback.

If they try to do the same thing using `log` it is flagged as invalid:
![ajcokknpeinfgkfj](https://user-images.githubusercontent.com/30723394/199300265-b300d708-a1a7-41e8-a7b0-4ebe2f24ee59.png)

However, they are shown reasonable looking output when typing `ln*x`:
![ckaigmfhdbgbnpek](https://user-images.githubusercontent.com/30723394/199300259-b68f86ae-899f-4213-b59b-abe7a4533c16.png)
(`ln` appearing in the list of variables is the only sign that anything is amiss here, which is quite subtle)

Is there any way I can cause this to show as invalid to students?

I can at least point out the error after the fact, by adding a check to the PRT for `length(intersect({ln,log},setify(listofvars(ans1)))) == 0` - though as further wrinkle, I cannot add a test case to confirm this!
![glmbppgllclodpgc](https://user-images.githubusercontent.com/30723394/199300261-884801c4-ab25-4b79-b5fb-d229ac8d33c9.png)

**Comment by georgekinnear** [comment]
Thanks!

Just to check - will this also pick up more complicated expressions, e.g. `ln*(2*x)` ?

**Comment by sangwinc** [comment]
Yes, that is also now rejected.  You can't use function names as variables.
Chris

**Comment by georgekinnear** [comment]
Great, I've tried out the dev version and it seems to work much as I would expect - thanks.

One odd thing I noticed:
![image](https://user-images.githubusercontent.com/30723394/199692265-ec6a1db3-5ef3-4296-848d-7e7f1edbbf6b.png)

The suggestion to insert the "missing" * is somewhat unhelpful here!

And in fact, it makes me wonder how useful the validation message will be to students in the case I had in mind:
![image](https://user-images.githubusercontent.com/30723394/199692780-13999537-a358-4ced-9350-3cdf56c7657d.png)

This might be read as "you're not allowed to use `ln` here" when in fact the message should be more like "you need to provide an input for `ln`" or "you have used the function name `ln` but have not specified an input value".

**Comment by aharjula** [comment]
Ahh, the joy of using the same identifier as both a variable and a function... and the way that mixes with all the other filters we apply...

If I recall correctly, we have that one insert-stars rule (406) that will assume that there are no functions with the same names as variables and expects that multiplication sign. Now maybe that one should have an alternative operation mode where it would not do the insert stars that gets either silently through or produces that error but instead would generate its specific error if we are doing things in no-fixes (starts or spaces) mode(999). Of course, if it is the same filter, we need to make it parametric and let it know about the future filter chain members. Will be tricky to define what are the behaviours for all the possible combinations of acceptable fixes and so on...
