### ISSUE TITLE
Getting error "Too many arguments supplied to ct2_latex(%_val,%_mode); found: [{[Q,4]},"i",_ct2_simp] "

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#882]
[Four cards.xml.txt](https://github.com/maths/moodle-qtype_stack/files/10023106/Four.cards.xml.txt)

The attached question is giving ther error

Rendering of text content failed: this question is broken. Please contact your teacher.
* Too many arguments supplied to ct2_latex(%_val,%_mode); found: [{[A,3]},"i",_ct2_simp] 

repeatedly when running the question tests.

ct2_latex seems to be something deep in the Maxima code which I don't understand. Is this a bug or an authoring issue? (I can edit and save the question with no errors.)

**Comment by timhunt** [comment]
Another different question with the same symptoms.

[CR-Int-10-basic-1.b.xml.txt](https://github.com/maths/moodle-qtype_stack/files/10023621/CR-Int-10-basic-1.b.xml.txt)

**Comment by aharjula** [comment]
Well, you did quite a large merge recently, are you sure you remembered to update the Maxima images and scripts in your test setup? That function got its third argument some months ago, and if you are calling it with three it means that you are running PHP code that expects it to have those arguments while your Maxima version does not have that third one.

**Comment by timhunt** [comment]
I just checked the healthcheck page to verify I had not forgotten, and I have not. We are using the right version of Maxima for our version of STACK.

(Unless ... perhaps there was a change in stackmaxima.mac, and someone forgot to update stackmaximaversion. I will need to look through git history carefully, and work it out.)

Thanks for pointing me in the right direction. (Also, I recently noticed your new PHPunit test to verify that you weren't running the unit tests with the wrong maxima_optimised. That was a great idea.)

**Comment by timhunt** [comment]
So,

* we are running 29f077be3a11c8de632d418bb7018fde03e6bc0e, which is basicallly v4.4.1 tag, plus a few extra commits of docs improvements.
* In those changes, there were no alterations in the stack/maxima directory.
* It was the v4.4.1 commit where Chris updated the stackmaximaversion to 2022082900.
* Our healthchech script shows that we are running 2022082900

I'm continuing to investigate.

**Comment by timhunt** [comment]
Eureka! I think I found the missing comma: 

Should there be a comma between $mode and $simp here stack/cas/castext2/blocks/latex.block.php ?

I will test that when I am out of this meeting.

**Comment by timhunt** [comment]
No, becuase $simp is defined with a , prepended to the real value. Drat!

**Comment by timhunt** [comment]
Confirmed. That must be what happened. I will close this now. Thanks for pointing me in the right direction.

For the future, we might think about storing stackmaximaversion in the CAS cache DB table, so we can auto-purge/ignore old entries which are no longer required. (I think we do if STACK version in version.php changes, but that does not always change when stackmaximaversion changes.)

**Comment by aharjula** [comment]
Would probably be better if we would not cache things coming from the wrong version at all. More straightforward to know at the moment of calling what is the expected version and check the returned version to see if it matches... Just needs to ensure that all sessions include the version number in the response, and that is cheap. If we did this the upgrade script clearing the cache would clean things nicely and the cache would not get polluted before the versions start matching.

And yes, that sequence of events is a common thing with MaximaPool and GoeMaxima installs. Leading to the general guidance of clearing the CAS cache after the image is in place and clearing again after you remember to actually reload the servlet and the image is actually running.

**Comment by timhunt** [comment]
Yes, once I have finished my current panic over questions we have that are about to break (my fault for not checking sooner) I will look at coding something.

As you say:
* After calling the CAS, if stackmaximaversion does not match, do not cache. (And ensure something is written to the server error log.)
* Also, when loading a value from the cache, if stackmaximaversion does not match, delete this cache entry, and then call the CAS.
