### ISSUE TITLE
Strange behaviour with polarform

### ISSUE THREAD

**Issue by georgekinnear** [maths/moodle-qtype_stack#884]
The behaviour of `ev(polarform(%i+1), simp)` seems to have changed recently.

I use something like that as a teacher answer in a test case, and it's now being reduced to cartesian form (i.e. the answer being used in the test ends up being `%i+1`). When I wrote the question some years ago, I'm pretty sure it was kept in polar form as `sqrt(2)*%e^((%i*%pi)/4)`. (I was using the simp because sometimes the modulus/argument were messy unsimplified expressions.)

If I run `ev(polarform(%i+1), simp)` on my desktop maxima installtion, I get the polar form.

While trying to investigate what's going on, I've noticed some weirdness on the CAS chat page too:

![1YgjDcYEsVtPnqyK](https://user-images.githubusercontent.com/30723394/202443441-b899f777-b4c4-4b16-91c2-e5fd63bf8e2d.png)

This shows the (unexpected) simplification from polar form to cartesian being done. Turning off the auto-simplify will keep pf0 in polar form.

But weirdly, adding a simp:false; in the middle of the question variables (with auto-simplify turned on) changes the behaviour in a way I would not have predicted:

![h8cgScoWjLstRdap](https://user-images.githubusercontent.com/30723394/202443510-06799e1f-2866-42fd-9de1-4b4b8054c5cc.png)

**Comment by KZerva** [comment]
Just to follow up on this issue, I try to debug a similar question and whatever simplification settings I may use I  only get the complex number in the Cartesian form.  
What perplexes me most is that in the  "Question variables values" I see that "polarz" is in the polar form while it previews in the Catressian form!!! (The expression in the red box, the correct polar form that appears next is manually crafted to show what is expected).

![image](https://github.com/maths/moodle-qtype_stack/assets/79198720/bbc3515e-7f05-4b55-857a-691d40225cc6)

**Comment by sangwinc** [comment]
The problem arises because the PHP->Maxima connection assumes that `ev(...,simp)` is idempotent. 

In the case of `polarform` it isn't!  Here is a minimal example.
```
simp:false;
q0:ev(polarform(%i+1),simp);
q1:ev(q0,simp); 
```
We'll have to ask the Maxima community about this, and for their suggestions about how to fix it.

**Comment by sangwinc** [comment]
Another example happens with factor.
```
p0:ev(factor(12),simp);
p1:ev(p0,simp);
```
Of course, you don't really _need_ the simplification in defining `p0` so this issue never arises.  With `polarform` we do want to simplify the r and theta which come back, but not to re-simplify the whole expression.

**Comment by sangwinc** [comment]
We have two options to fix this immediately.

1. Introduce a new "inert form" like `disp_complex` (see https://docs.stack-assessment.org/en/CAS/Complex_numbers/ ) perhaps call this `disp_polar`.
2. Write our own function `polarform_disp` which simplifies the modulus and argument.  Then the return value will be a simple maxima expression, with no problematic inert forms but will require `simp:false` in the question to prevent further simplification happening elsewhere.

I propose we adopt 2.

**Comment by KZerva** [comment]
Here is the simplified version of the code (no rand).
`varphi:pi/3;`
`x:cos(varphi);`
`y:sin(varphi);`
`r:2;`
`z:r*(x+y*%i);`
`simp:false;`
`polarz:ev(polarform(z),simp);`
`ta1:expand(z);`
