### ISSUE TITLE
Fatal error: Nesting level too deep - recursive dependency? in MP_classes.php on line 908

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#885]
When I try to run the question tests, or preview, the attached question, I am getting:

Fatal error: Nesting level too deep - recursive dependency? in /var/www/html/moodle/question/type/stack/stack/maximaparser/MP_classes.php on line 908

That line of code is https://github.com/maths/moodle-qtype_stack/blob/3528f4a691bf076825b9f68eefa3202487933bc5/stack/maximaparser/MP_classes.php#L908 where it is doing a nested array search.

This Stackoverflow answer seems to give some information about what is going on: https://stackoverflow.com/a/19097159/1292707

The suggested fix there, making the array search strict, makes the symptoms go away, but I don't understand enough to know if it breaks the code. That is, changing line 908 to

```php
                    if (array_search(array_search($prev, $i->arguments), $indices, true) !== false) {
```

makes teh error go away.

Any thoughts about this?

[parsing-error.xml.txt](https://github.com/maths/moodle-qtype_stack/files/10067267/parsing-error.xml.txt)

**Comment by aharjula** [comment]
Before we go too deep into this does the call trace that ends up in that fatal error include a call to `identify_identifier_values` i.e. the old static analysis based security validation, which no longer takes place and could probably be removed from the whole code base with its companion functions?

That old logic led to potentially infinite nesting as it wrote open references. No natural question code has been seen generating enough depth for the AST to trigger any nesting issues.

**Comment by aharjula** [comment]
But yes, if we need to specially care about comparing recursive objects, then we need to, as most of those nodes have been populated with a link to the parent node and can circle back through it.

Could be that some order of operation has changed, as earlier, we did not populate the link to parent during all operations, but now it is something we do as the operations happen more in bulk, and that access to parent is important for many filters.

Anyway, that bit of code is important as it is used to identify variables that are not present in the global scope and can thus be ignored when checking access issues.

**Comment by timhunt** [comment]
Thanks for the speedy response Matti.

Unforunately, there is no stack track. PHP fatal errors like out-of-memory and this just give you the single line number, which is unhelpful. ... Ah! but, since I know where it is crashing, I can put in a print statement just before that to get the stack trace. It is:

-     line 908 of \question\type\stack\stack\maximaparser\MP_classes.php: call to debugging()
-     line 855 of \question\type\stack\stack\maximaparser\MP_classes.php: call to MP_Identifier->is_global()
-     line 190 of \question\type\stack\stack\cas\parsingrules\998_security.filter.php: call to MP_Identifier->is_being_written_to()
-     line 35 of \question\type\stack\stack\cas\parsingrules\pipeline.class.php: call to stack_ast_filter_998_security->filter()
-     line 342 of \question\type\stack\stack\cas\keyval.class.php: call to stack_ast_filter_pipeline->filter()
-     line 1728 of \question\type\stack\question.php: call to stack_cas_keyval->compile()
-     line 1614 of \question\type\stack\question.php: call to qtype_stack_question::compile()
-     line 330 of \question\type\stack\question.php: call to qtype_stack_question->get_cached()
-     line 321 of \question\type\stack\question.php: call to qtype_stack_question->initialise_question_from_seed()
-     line 364 of \question\behaviour\behaviourbase.php: call to qtype_stack_question->start_attempt()
-     line 135 of \question\behaviour\adaptivemultipart\behaviour.php: call to question_behaviour->init_first_step()
-     line 1064 of \question\engine\questionattempt.php: call to qbehaviour_adaptivemultipart->init_first_step()
-     line 565 of \question\engine\questionusage.php: call to question_attempt->start()
-     line 121 of \question\type\stack\questiontestrun.php: call to question_usage_by_activity->start_question()

Still not really understanding what is going on, I tried changing all the array_search calls to use 'strict' and then ran all the tests. That does not cause any unit tests to fail: https://github.com/timhunt/moodle-qtype_stack/actions/runs/3523899774/jobs/5908614958 - how good is our Unit test coverage?

I did not just edit the code. I was looking at what each call did, and it seems like we are walking an existing tree structure, so perhaps it is OK. This is the change I ran the tests on https://github.com/timhunt/moodle-qtype_stack/commit/ba0079501fc4c5e5d4f3c61d5ac65b5aaa2338ae.

If doing this is not OK, it would be nice to add a unit test that fails because of it.

**Comment by aharjula** [comment]
After testing against my secret set of theoretical attacks, I can say that exact matches of objects are fine here. We do not have similar objects in play due to it being impossible from the point of view of the parser, so doing a strict equal is fine, especially as we are doing it inside that same object graph.

The reason why this might not have unit test coverage is due to this being one of those paths one could attack through and was thus a somewhat silent addition. Safe to say that now, though, as the security system is now quite far forward on that attack path and has been, for quite some time, not going to tell how to use that against a vulnerable installation as I estimate there still being some. To ease your mind, this is an attack path impossible for students to use.

Have to wonder if this was triggered due to some PHP version behaviour change, but that does not really matter.

**Comment by aharjula** [comment]
Yes.
