### ISSUE TITLE
Function call in TAns no longer works

### ISSUE THREAD

**Issue by dibevan** [maths/moodle-qtype_stack#886]
A question that used to work, with "std1([ans1,ans2,ans3])" as the TAns, now generates the following error (with sample data):

apply: second argument must be a list; found: ([654,654,654]-(654+654+654)/3)^2 apply: found %_TMP evaluates to 0 where an array was expected.

This looks like a failure of the internal execuation of std1.

Moving the calculation to the Feedback variables box resolves the issue.

Is this the result of a deliberate change of behaviour? If so, a more informative error message would be appreciated.

**Comment by sangwinc** [comment]
David,
Sorry about the delay in replying - I don't know why this issue got overlooked.  Please could you email me your question (Edinburgh) and I'll look into it?
Chris
