### ISSUE TITLE
Result as number

### ISSUE THREAD

**Issue by topse** [maths/moodle-qtype_stack#889]
Hi,
sorry, I feel it is a beginners question, but I don't find a hint in documentation and also not a forum to ask :-/

I have the following:

```
a: 5+rand_with_step(0, 8, 1);
b: 1+rand_with_step(0, 2, 1);
c: 5+rand_with_step(0, 8, 1);

n_raw: ((4*{a}+2*{c}+3*{b})/10)

n: round(n_raw)
n_falsch_gerundet: floor(n_raw)
```

When I use {@n@} in the text, I get:

![grafik](https://user-images.githubusercontent.com/893695/206676005-7e331b65-85f5-4f52-aae9-53b533d8156b.png)

... but I want the calcutation result as a "number".

I really would appreciate any hint on this.

Thanks and Best Regards,
Tobias

**Comment by georgekinnear** [comment]
I think the issue here is that you should not use `{` and `}` as brackets in the definition of `n_raw` - they must be `(` and `)` for maxima to recognise those, since the curly brackets are reserved for defining sets.
