### ISSUE TITLE
Bulk test a selected category within a context

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#896]
From a user on the Moodle forum:  I am wondering if it might be useful/possible to have the STACK bulk test script adapted so that the bulk test can be run on a selected category within a [context](https://moodle.org/mod/glossary/showentry.php?eid=9984&displayformat=dictionary) not on the all the STACK questions in a context.

https://moodle.org/mod/forum/discuss.php?d=441624

Yes, it is!  We'll try to sort this out.

Chris

**Comment by sangwinc** [comment]
Just an update: I think Coderunner has already solved this issue in that question type.  Is this the case @trampgeek?

**Comment by trampgeek** [comment]
CodeRunner lets you tests all questions in a given context within a given course. It's not the greatest UI in the world but it usually lets you select a sufficiently small subset of questions to test. See the screenshot, which has had one small course, COSC401, expanded.
![Screenshot from 2023-02-23 17-59-41](https://user-images.githubusercontent.com/1101142/220824954-ecdb2c13-57b7-4735-adc0-54ed21bc9689.png)

**Comment by sangwinc** [comment]
This is now fixed.  Thanks @trampgeek for your help with this!
