### ISSUE TITLE
Feature request: update an existing question by importing external Moodle .xml

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#898]
A relatively common request is to replace an existing question in the database from an external Moodle XML. Typically, user emails a question to somebody else for advice or support and needs to replace the old version in a live quiz with the new improved version.

Clearly this is a Moodle issue and not a STACK issue, since we want to be able to do this with any question type. The new question bank features in Moodle 4 good makes this potentially much easier to implement than in the past. I'm raising a separate issue here because this is related to issue #897, but it would be very valuable to have this as independent functionality.

**Comment by timhunt** [comment]
I think https://tracker.moodle.org/browse/MDL-74070 is the Moodle feature request which covers this.

**Comment by sangwinc** [comment]
Thanks Tim,
Not surprised, and thank you for the link!

**Comment by sangwinc** [comment]
That's great, thanks!  I've installed this on my dev machine, and so far it works really well.

**Comment by sangwinc** [comment]
This is not a "STACK" issue, and a fix has been started....
