### ISSUE TITLE
Links in Deployed variants are sometimes not working 

### ISSUE THREAD

**Issue by Bjoern-Ge** [maths/moodle-qtype_stack#901]
Using Stack 4.4.1 (2022082900) with Moodle 3.9+

A question is stored in a subcategory of "system" instead of a course.

When running the bulk-test and clicking on the link, the question will open in the "Question tests & deployed variants" mode.

In this case, the links "See this question in the question bank" and "Edit this question" do not work.

Moodle gives the error "Need to provide courseid or cmid to print_question."

This might be considered also for #896

**Comment by sangwinc** [comment]
Oh dear, sorry this is where my knowledge of the edge cases of Moodle starts to get a little thin!

@timhunt, what is the correct thing to do here?

Chris

**Comment by timhunt** [comment]
I think the issue is here: https://github.com/maths/moodle-qtype_stack/blob/master/locallib.php#L232 where we don't set `$urlparams['courseid']` in the 'else' block.

I think we need something like:

```php
if ($context->contextlevel == CONTEXT_MODULE) {
    $urlparams['cmid'] = $context->instanceid;
} else if ($context->contextlevel == CONTEXT_COURSE) {
    $urlparams['courseid'] = $context->instanceid;
} else {
    $urlparams['courseid'] = SITEID;
}
```

At the end of the else. Sorry, I have not tested that.

**Comment by sangwinc** [comment]
Thanks so much Tim!  I had reproduced the issue, but had no idea how to fix it.  I've applied your suggestion, and I can no longer reproduce the issue on my test system.

**Comment by Bjoern-Ge** [comment]
Thanks, that was a quick
