### ISSUE TITLE
STACK Units and JXG: converting numbers in scientific represenation

### ISSUE THREAD

**Issue by Famondir** [maths/moodle-qtype_stack#902]
Hi everyone,
I struggle with a little task. Maybe there already is a solution I'm not aware of. This is what I'm trying to do:

I want to show the students in the feedback what their answer would imply in a graph. E. g. a velocity-time graph. Therefore, I access the numerical value of students answer via stack_units_num(). I found out that I can use stack_unit_si_to_si_base() to get the following behaviour:

f(3 km/h) = 0.833
f( 0.3 mm/s) = 3 e-4
and
f(3 m/s) = 3

The JXG draws the lines for first and third value. But when the value gets to small it refuses to draw a line. Here's the error:

```
Error: Parse error on line 1:
...ion (t) { return 3.5e-4; };
```

I could print the number without scientific notation via stackfltfmt:"~f"; But that does not solve the internal problem.

Sincerely Simon

**Comment by Famondir** [comment]
I found a workaround:
First I used in feedback variable area:
```
fv:stack_units_nums(stack_unit_si_to_si_base(ans5));
```
and in JS
```
var fv= board.jc.snippet('{#fv#}', true, 't', true);
board.create('functiongraph', [fv,0,t_1]);
```
which gives the error above.

Now I just use JS only:
```
var Sans = {#stack_units_nums(stack_unit_si_to_si_base(ans5))#};
var fv= board.create('functiongraph', [function(t) {return Sans}, t_1,zeit-t_1]);
```
instead which works fine.

**Comment by sangwinc** [comment]
Thanks for figuring this out - the solution should have been better documented in the first place.  Sorry about that.  Please do make suggestions and additions to the docs.  Keeping this up to date isn't easy and I really appreciate any help with this.
