### ISSUE TITLE
Placeholder matrix syntax hint

### ISSUE THREAD

**Issue by malthefogsporring** [maths/moodle-qtype_stack#904]
It is currently not possible to have placeholder syntax hints in any matrix input type. Regardless of "Hint attribute" tag, the syntax hint is always taken as "value". This is maybe niche, but if it is an easy fix, it would be appreciated!

**Comment by mkraska** [comment]
I support this proposal because I am using hints in all input fields. In matrix fields this is not possible now, so the user experience isn't consistent.

BTW: How about localization of the hints?

**Comment by aharjula** [comment]
Localisation waits for the "input 2"-system which would allow us to have CASText-values for the options and thus localisation through that using the `[[lang]]`-block.
