### ISSUE TITLE
4.4.2 `[[lang]]`-block broken

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#905]
This is an informational issue for those having trouble with 4.4.2 and newer CASText features. If you are using the `[[lang]]`-block, things simply won't work, but you may ask your admins to do a small hotfix of two characters to fix this:
https://github.com/maths/moodle-qtype_stack/commit/6b5c2c3e3b444a587dd8c13036c16f0b5c0a66ba

Those going there and using the inline castext feature with empty strings can either start writing empty strings as just strings or `castext("") => ""` or add this fix to their system:
https://github.com/maths/moodle-qtype_stack/commit/ef4de44c1e0cbded3f07116bd333e9dba39b9669

This issue has been handled and will get closed after the next release....

**Comment by sangwinc** [comment]
Thanks Matti!
