### ISSUE TITLE
Tidy up the teacher view of a question - link to a "dashboard"?

### ISSUE THREAD

**Issue by georgekinnear** [maths/moodle-qtype_stack#908]
Currently when teachers view a STACK question they see two links in the top-right corner:
![image](https://user-images.githubusercontent.com/30723394/212129078-9811f201-e73b-49d3-8413-ae142f8054e8.png)

Could these perhaps be consolidated into a single link, something like "STACK question dashboard", with the link the "tidy" tool added to the list of action links that appear at the top of the "question tests & deployed variants" page?

This is a tentative suggestion - I rarely use the "tidy" tool so having an extra click would not bother me. 

But since the "question tests & deployed variants" page now has links to quite a lot of extra functionality (e.g. exporting the question, viewing the response data, etc) it might be clearer to view it as a single one-stop-shop for authors to manage the question.

(As a side benefit, it might look a bit cleaner when people show screenshots of their questions!)

**Comment by timhunt** [comment]
So, when we first added those links to STACK, there was no other way to get a link to those pages. But, just shoving the links in there is basically a hack.

Now, we have a better place for those links. When you are in the question bank, there is the 'Edit' menu for each question, and those links appear in that menu.

So, we could get rid of those links in the rendererd question. Hoewever, if we did that, you would no longer  be able to jump straight to those pages for places like a quiz attempt review, or a question preview. Would that be a pain?

(Something I would love to do in future, when I have time: At the moment, when you are viewing a question, there is the Edit question link - but that is just one of the actions you can perform on a question. I would love to replace that with the whole of the edit menu you get in the question bank, with all the actions.

**Comment by georgekinnear** [comment]
I like the sound of that action menu!

But I do think it's useful having the link quite prominent and easily accessible for teachers/authors - it would indeed be a pain to have to use the Edit menu from the question bank, since you'd first have to locate the question in the question bank.

**Comment by sangwinc** [comment]
Thanks George, 

This is a simple and helpful suggestion: funny when you're used to things how you develop "blind spots" to some otherwise simple improvements.  I've updated "coulomb.maths.ed.ac.uk/m39" with the code above.  Please confirm this is what you're asking for.

I'd like to add in a link from the question menu and weed out that link from the preview.  It was always a workaround.  Tim, is a "question dashboard" something which every question could have? 

Anyway, consolidating all STACK-specific things into a single dashboard is the right approach.
Chris

**Comment by georgekinnear** [comment]
Thanks, that's looking good on coulomb.

For the options at the top of the page, how about using Bootstrap styles and FontAwesome icons to make it a bit cleaner?

![image](https://user-images.githubusercontent.com/30723394/212729763-3ddc2585-f0b1-4804-8dda-4fb48c46ae56.png)
--->
![image](https://user-images.githubusercontent.com/30723394/212729821-13985b7b-9e1b-48b5-a7dc-972a381f4945.png)

This includes some suggested renaming of the options, and I also dropped the "send to CAS" since I think that actually makes more sense in the original location, next to the preview at the bottom of the page showing what you'll be sending.

This was just playing around in the browser to edit the HTML code, something like the following:

```
<nav class="nav">
  <a class="nav-link" href="#"><i class="fa fa-pencil"></i> Edit question</a>
  <a class="nav-link" href="#"><i class="fa fa-list-alt"></i> Show in question bank</a>
  <a class="nav-link" href="#"><i class="fa fa-download"></i> Export as Moodle XML</a>
  <a class="nav-link" href="#"><i class="fa fa-sort-amount-asc"></i> Tidy inputs and PRTs</a>
  <a class="nav-link" href="#"><i class="fa fa-bar-chart"></i> Response summary</a>
</nav>
```

Some stray thoughts:

- An alternative for the "show in question bank" icon could be the crosshairs `<i class="fa fa-crosshairs"></i>`
- Perhaps "Response summary" should be "Analyze responses" to match the "start with a verb" pattern.

**Comment by sangwinc** [comment]
George,
Those are all very sensible suggestions, thanks.  Can you take another look at coulomb and let me know what you think?
Chris

**Comment by georgekinnear** [comment]
That's already looking better, thanks!

I suggest also using the `<nav>` element and styles rather than separating the links with "|" - I think you should just need to:
- add `array('class' => 'nav-link')` as a 3rd argument to each of the `html_writer::link` calls, and
- change `html_writer::tag('p', implode(' | ', $links));` to `html_writer::tag('nav', implode(' ', $links));`

Also I'm not sure about "Edit general feedback" - I think it's potentially misleading, as any "edits" are not saved. My vote would be to return that to being a button at the end of the page, and stick with the original wording.

**Comment by sangwinc** [comment]
Thanks George,
I'm not sure this is what you have in mind?
![Screenshot_2023-01-16_10-11-44](https://user-images.githubusercontent.com/781615/212977130-5b4e048b-8389-438e-8d1e-6915b9f3f36a.png)

**Comment by sangwinc** [comment]
Ok, I've merged the suggested fixes we discussed into the "dev" branch and this will be available in the next release.  Any further suggestions need a new issue!

**Comment by georgekinnear** [comment]
Sorry this was languishing on my todo list - I think it was just that I forgot that the top <nav> tag needs `class="nav"` for the proper styling to be applied.

I've tried to implement that here, but haven't been able to test it!

https://github.com/maths/moodle-qtype_stack/pull/927

**Comment by sangwinc** [comment]
Thanks George, I've added that pull request to the dev branch.
