### ISSUE TITLE
Missing argument in the test UnitsStrictAbsolute

### ISSUE THREAD

**Issue by lassikor** [maths/moodle-qtype_stack#909]
Hi,
I bumped into problems when trying to apply answer test UnitsStrictAbsolute. The documentation says that the only required additional argument (test option) is the acceptable absolute error but this seems not to be the case. Using this test leads to an error as shown in the pictures below:  
![image](https://user-images.githubusercontent.com/42375494/212274555-e3801e08-8be1-4a53-95b3-c76aa8aec380.png)
![image](https://user-images.githubusercontent.com/42375494/212274683-5fe1d3cf-7e40-4db7-9a5c-71023c85ca54.png)

I was not able to find a way to add the demanded "SR" argument for the test.
The tests/screenshots are from Abacus Moodle.

BR Lassi Korhonen

**Comment by sangwinc** [comment]
Lassi,
That appears to be a rather embarrassing internal mistake on my part. I'm really sorry about that!
Chris
