### ISSUE TITLE
Equivalence reasoning problem with +

### ISSUE THREAD

**Issue by thofkens** [maths/moodle-qtype_stack#910]
If you enter the following in an equivalence reasoning question, stack says it is not equivalent

binomial(n,k)+binomial(n,k-1)
=n!/((k-1)!*(n-k+1)!)+n!/(k!*(n-k)!)
=n!*k/(k!*(n-k+1)!)+n!*(n-k+1)/(k!*(n-k+1)!)
=n!*k/(k!*(n-k+1)!)+n!/(k!*(n-k)!)
=((n-k+1)*n!+k*n!)/(k!*(n-k+1)!)
=((n+1)*n!)/(k!*(n-k+1)!)

If you enter both terms separately, stack says it is equivalent:

n!/((k-1)!*(n-k+1)!)
=n!*k/(k!*(n-k+1)!)

and

n!/(k!*(n-k)!)
=n!*(n-k+1)/(k!*(n-k+1)!)

**Comment by sangwinc** [comment]
Just to note, this is about the sum of two binomial quantities.  

```
p1:n!/((k-1)!*(n-k+1)!)+n!/(k!*(n-k)!);
p2:n!*k/(k!*(n-k+1)!)+n!*(n-k+1)/(k!*(n-k+1)!);
algebraic_equivalence(p1,p2);
```
gives false as well.

**Comment by sangwinc** [comment]
I think I've found a fix for this involving the `sumsplitfact` option to Maxima's `factcomb` function, which I didn't know about before.

Thanks for reporting this.  It is a rather subtle problem of which order you do "simplification" in, and I think this will be a genuine improvement.  The test cases are also really appreciated and I've added these into the unit tests for future reference.
