### ISSUE TITLE
Export/import changes default mark of a question

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#911]
Problem:

The attached question was created under STACK 4.4.2. After export (this state is attached) and import into another server running 4.4.1. the question has a modified default mark (original: 1, after import: 0). This leads to complaints when including this question in a test. After manual edit of the default mark the test works.

This could be related to the fact that the question doesn't contain any input. It just has PRTs based on maxima expressions in the question variables and in the feedback variables. The purpose is a unit test for functions written in Maxima.

[questions-Meclib-QA 01 fb_unit unit test-20230114-1634.zip](https://github.com/maths/moodle-qtype_stack/files/10417949/questions-Meclib-QA.01.fb_unit.unit.test-20230114-1634.zip)

**Comment by sangwinc** [comment]
This is odd - I've just imported the question you attached back into STACK 4.4.2 and I get the original mark 1, which is in the raw XML if you look.  I don't have a server with 4.4.1 to hand.   Can you create a minimal example with this problem?

**Comment by mkraska** [comment]
I can't reproduce it either. Sorry for raising this. Most likely, I lost control when moving questions between servers and tests. Once the same pattern occured two times I suspected an issue...
