### ISSUE TITLE
rounding, avoid Bankers' Rounding

### ISSUE THREAD

**Issue by speedyjwc** [maths/moodle-qtype_stack#913]
Hi,

When I use decimalplaces(x, n), I found it applies Bankers' rounding when it comes the ending digital is 5, is there a way to avoid that and always round up?

Thanks!

**Comment by sangwinc** [comment]
Yes, Maxima implements Bankers' Rounding. This is a design decision from Maxima, 
https://docs.stack-assessment.org/en/CAS/Numbers/#notes-about-numerical-rounding
We don't have an alternative option, sorry.
Chris

**Comment by speedyjwc** [comment]
OK. Thanks!
