### ISSUE TITLE
Error writing to database led to a lot of lost work

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#914]
I was editing a question for almost 30 minutes, adding some parts to it, and when I finally got to the point where it was possible to save the question, I got an error message saying that there was an error writing to the database. After that I was redirected to a page which only contained this error message:

![Skärmbild från 2023-01-20 08-25-45](https://user-images.githubusercontent.com/1645276/213631896-c7a6e396-346f-4561-bd91-8c0a38d9c922.png)

Now it seems like all my edits are lost. :(

**Edit:** Using the browser's back button, I was able to recover most of the edits, so I only lost perhaps 10 minutes of work. But the experience was nevertheless rather shocking. Fortunately, I did not get any error messages as I saved the question the second time.

**Comment by sangwinc** [comment]
Yes, this is very annoying.  Do you know what led to the DB error?  The failure to recover from a DB error like this is really a Moodle issue and is not something we can fix as part of the STACK plugin generally.   If you know what caused the error we might be able to add in some checks before attempting to write to the DB.

**Comment by alcarola** [comment]
Unfortunately, I really have no idea. I was just working as usual and did not notice anything out of the ordinary. I did also not do anything to make saving work either; I just used the back button of the browser, redid the latest work, and then saving was successful. 

I close this, since you determined that it is a moodle issue rather than a stack issue.
