### ISSUE TITLE
input field not updated when JSXGraph slider is moved to 0

### ISSUE THREAD

**Issue by geoo89** [maths/moodle-qtype_stack#920]
Create a slider in JSXGraph and use stack_jxg.bind_slider.
When the corresponding input field is not empty (i.e. the slider has been moved at least once before), the input field will NOT be updated when the slider is moved to 0.

Here is a minimal working example (in Moodle XML format, rename .txt to .xml): [Slider bug.txt](https://github.com/maths/moodle-qtype_stack/files/10537166/Slider.bug.txt)

I believe the culprit is here:
https://github.com/maths/moodle-qtype_stack/blob/0c96a9d6b50eef187c54f4726265df01d856a6f2/amd/src/jsxgraph.js#L503
Specifically in the line `if (initialValue != slider.Value()) {`, as initialValue is set to `false` after the first moving of the slider, and `false == 0` in javascript, the if condition evaluates to false and the update is skipped.

**Comment by aharjula** [comment]
Well tracked. Luckily the new implementation of those bindings, when it eventually gets to the release, should have this under control:
https://github.com/maths/moodle-qtype_stack/blob/18b9cbe028785f1cd9cd24382f12179c32786f48/amd/src/jsxgraph.js#L153

**Comment by sangwinc** [comment]
Thanks for confirming this is now working @geoo89 .
