### ISSUE TITLE
Support for plot2d option `adapt_depth`

### ISSUE THREAD

**Issue by dmca-glasgow** [maths/moodle-qtype_stack#921]
Hi there,

I'm looking at solutions for making Maxima plots a bit more accessible to students with colour blindness, by adding symbols to the lines via the plot2d [`style`](https://maxima.sourceforge.io/docs/manual/maxima_65.html#style) option.

In the plots I'm working with, I've found I need to disable adaptive sampling via the [`adapt_depth`](https://maxima.sourceforge.io/docs/manual/maxima_65.html#adapt_depth) option for the best result:

![Screenshot 2023-02-03 at 09 10 41](https://user-images.githubusercontent.com/59647327/216559327-13e72d96-e1d3-4963-b675-7fb32d71a40e.png)

But I've found this option isn't supported by STACK at the moment:

![Screenshot 2023-02-03 at 09 01 57](https://user-images.githubusercontent.com/59647327/216559389-f6ddfcc9-336f-4c35-a45f-67023a692a88.png)

This is what the plot looks like on Moodle without it:

![Screenshot 2023-02-03 at 09 02 31](https://user-images.githubusercontent.com/59647327/216559460-11ca5846-3fb8-4c6b-a1a4-3f9fd2f7e5f3.png)

Is it possible to add support for this option?  Thanks.

**Comment by sangwinc** [comment]
David,
Thank you very much indeed for suggesting this - accessibility is important and this is a very sensible practical suggestion.

I've done some investigation this morning.  I don't think adapt_depth is really the correct approach.  It is also fragile to different versions of Maxima.  I think we need support for the gnuplot option pointinterval: http://www.gnuplotting.org/manpage-gnuplot-4-6/#x1-84000II

The chain of events is

1. STACK "plot" sends the request to Maxima.
2. Maxima sends the request to gnuplot
3. Gnuplot creates the SVG and puts is somewhere a user can download through the browser, and the URL ends up no a user's page.

This is not an option I can add in the STACK codebase, and it will require the following changes to Maxima:
https://sourceforge.net/u/sangwincsf/maxima/ci/fdbd4c67aee840ec5bb436bb4398ecf7695fba21/

If the maxima community accept this proposal, it will end up in a future release and hence on our servers.  Not an immediate fix, sorry!

Chris

**Comment by sangwinc** [comment]
All that said, I've reviewed adapt_depth and see no reason to forbid it now.  It may have some genuine uses.

**Comment by dmca-glasgow** [comment]
Hi @sangwinc,

Thanks very much for looking into this and your incredibly quick response!

Following your 2nd comment and commit, has the change now been made to STACK, or is it in review?  

Is there anything I need to follow up on at my end, ie. should I ask the Glasgow University Moodle team to update STACK to the latest release?

Just hoping to understand the process so I can feedback to my team.

Thanks again.

**Comment by sangwinc** [comment]
Duncan,
The Maxima changes won't end up in STACK by default until Maxima is released and packaged up - that could be a year.  The adapt_depth fix might work for you, but I'm worried how fragile it is!  Could you email me at Edinburgh and we can discuss how best to get these changes onto your system, especially if they are urgent?  
Chris

**Comment by sangwinc** [comment]
The Maxima merge request is here: https://sourceforge.net/p/maxima/code/merge-requests/35/
