### ISSUE TITLE
Sets in NumRelative tests not working if containing "0"

### ISSUE THREAD

**Issue by troemax** [maths/moodle-qtype_stack#922]
Using the test "NumRelative" and a set containing the number 0 as the teacher answer (for example {0,1,2}) then entering the same set as the student answer states (again {0,1,2}) the answer as wrong.

I had a look at the source code in the file moodle-qtype_stack/stack/maxima/numericaltest.mac. Changing the "<" to an "<=" in line 150 should solve the problem (so "if is(f2<=0)"). Some lines above we see that the function numrelativep (which is responsible for checking numbers) uses a "<=", but the equal sign is missing in the said line which is responsible for checking sets.

**Comment by sangwinc** [comment]
Sorry about that - thanks for finding the fix. Much appreciated.
Chris
