### ISSUE TITLE
`cartesian_product` function broken in maxima 5.43 and after

### ISSUE THREAD

**Issue by Lennart-Kramer** [maths/moodle-qtype_stack#924]
In maxima commit `c02a5b182`, the maxima function `cartesian_product_list` is introduced. To avoid code duplication with the existing `cartesian_product` function, a `cartesian-product` lisp function was written.

When it was introduced, the lisp function of the name was removed from the `logic` package, since the new `cartesian-product` function seems to be able to deal both with maxima lists and lisp lists. However, stackmaxima still contains an old `cartesian-product` implementation in `stack_logic.lisp` that does not work on maxima lists and therefore breaks the `cartesian_product` maxima function if used with maxima version >5.43.

Maybe the definition of `cartesian-product` in `stack_logic.lisp` could be guarded by an `(unless (fboundp 'cartesian-product) ..)` or checking the maxima version through `*autoconf-version*`?

**Comment by sangwinc** [comment]
Thanks very much for raising this - such are the joys of maintaining parallel code over many years!

I think the suggestion of `(unless (fboundp 'cartesian-product) ..)` is very sensible.  Are you able to test any code and send me a pull request?  If not, I'll do my best.

Chris

**Comment by Lennart-Kramer** [comment]
> Are you able to test any code and send me a pull request?
Sure, I'll do it later today.
