### ISSUE TITLE
Wrong total points after deleting PRT

### ISSUE THREAD

**Issue by geoo89** [maths/moodle-qtype_stack#930]
It appears that when deleting a PRT, its question value still contributes to the total of the question, making it impossible to get a full score on that question.
Note: When previewing the question, we use "Deferred feedback" in the preview options.

Steps to reproduce:
1. Create a new question with 2 input fields and 2 PRTs.
2. Save the question
3. Delete one of the PRTs and the corresponding input field
4. Save the question again.
5. Preview the question and submit the correct answer for the remaining input field. You will score only partial points, see (left-hand side):
![image](https://user-images.githubusercontent.com/678199/223093561-dea81682-01fd-4602-b486-9b86dffaf29c.png)

Workarounds:
- Making a copy of the question and previewing the copy fixes the issue (this, however, is not an available option when the question has already been deployed in a quiz).
- Moving the PRT (or one of the PRTs, in case there are multiple remaining) from the question text to the specific feedback (or vice versa), saving the question, and then moving it back, seems to fix the issue, and allows for regrading of the question with the updated version.

Moodle version: 4.0.3 (20220822)
STACK version: 4.4.0 (2022071300)

**Comment by sangwinc** [comment]
Really sorry this has taken so long to get my attention!  Let's get this fixed...

**Comment by sangwinc** [comment]
Thanks for your help tracking this down @geoo89.
