### ISSUE TITLE
(%i2) (%i3) Field ""Question Text"" generated the following error: TIMEDOUT Field ""Question Variables"" generated the following error: TIMEDOUT

### ISSUE THREAD

**Issue by MecatronickB** [maths/moodle-qtype_stack#941]
When i run the healthcheck script or another test, i get this error:

(%i2) (%i3) Field ""Question Text"" generated the following error: TIMEDOUT Field ""Question Variables"" generated the following error: TIMEDOUT

can anyone could help me?

**Comment by sangwinc** [comment]
This is probably an install error.  Please email be at Edinburgh and I'll see what I can do.  But this almost certainly isn't a bug in STACK itself so this isn't the place to report it.  Please don't post your healthcheck results here!

Chris Sangwin
