### ISSUE TITLE
Correct answers not validating and valid responses not passing to score

### ISSUE THREAD

**Issue by alexanderwilliams091** [maths/moodle-qtype_stack#943]
Hi all,

I am presently supporting a higher ed institution in diagnosing why --- with a particular STACK question --- correct student answers are being marked as incorrect and the input status of student answers do not show with a SCORE status such to execute the relevant PRT.  

The university is using v2022082900(4.4.1 for Moodle 3.9+) of the STACK qtype plugin on Moodle 4.0.6. The university has also authorised with the authoring academic the sharing of this problematic question which is attached/described below. My technical support and mathematical acumen doesn't really compass the expertise needed to instinctively know what might be wrong here, so please forgive me if I explain this poorly or have missed something super evident. I am hoping someone might know what might be going on and can explain this sufficiently for me to pass back to the instructing academic to rectify. 

This question has three parts, prt1 being a checkbox type and the other two standard numerical input types. Question text and variables as follows:

VARIABLES: 

`/*display variables in the way you want*/
dispm:dispsf(m,3);
dispv:dispsf(v,3);
dispv2:dispsf(v2,3);
dispt:dispsf(t,3);

/*do the calculations*/
v1:v
V:(m*v1+m*v2)/(2*m);
Ki:1/2*m*(v1^2+v2^2);
Kf:m*V^2;
DeltaK:Kf-Ki;
Favg1:(m*V-m*v1)/t;

/* Answers */
Tans1: [[1,true," When the lumps of clay collide, momentum is conserved."],[2,true," External forces are negligible while the lumps of clay collide."],[3,false," When the lumps of clay collide, mechanical energy is conserved."],[4,false," Non-conservative forces are doing no work as the lumps of clay collide."],[5,false," This is an elastic collision."],[6,true," This is a perfectly inelastic collision."]];
Tans2: significantfigures(V,3); /*m/s*/
Tans3: significantfigures(DeltaK,3); /*J*/
Tans4: significantfigures(DeltaK,3); /*J*/
Tans5: significantfigures(Favg1,3); /*N*/`

QTEXT: 

```
Two lumps of clay, each with mass \(m={@dispm@}\text{ kg}\), move along the \(x\)-axis. They collide and stick together. Before the collision, one has a velocity \(v_1 = {@dispv@}\text{ m/s}\) while the other has a velocity \(v_2={@dispv2@}\text{ m/s}\).

Part 1)

Which of the statements below are true?

[[input:ans1]][[validation:ans1]][[feedback:prt1]]

Part 2)

What is the final velocity of the combined lump of clay?
![Screenshot 2023-04-18 at 4 55 37 pm](https://user-images.githubusercontent.com/90909802/232702987-1060fda0-5673-4d48-82b0-a72362dc4094.png)

\(V = \) [[input:ans2]] \(\text{m/s}\) in the \(x\) direction. [[validation:ans2]][[feedback:prt2]]

Part 3)

What is the change in kinetic energy of the system consisting of the lumps of clay during the collision?

\(\Delta K = \) [[input:ans3]] \(\text{J}\) [[validation:ans3]][[feedback:prt3]] 
```

prt1 expects Tans[1,2,6], prt2 has a 10% tolerance on answers where velocity must be expressed to 3 sigfigs and prt3 a 3% tolerance on whatever the student solves for delta k. I will also note that prt1 seems to be working fine score-wise, but prt2 and prt3 seem to be the root of the issue here. Their part logic is as follows: 

![Screenshot 2023-04-18 at 4 55 25 pm](https://user-images.githubusercontent.com/90909802/232704374-e6bc8954-4f95-4cd2-96b9-0d90839447ba.png)

![Screenshot 2023-04-18 at 4 55 37 pm](https://user-images.githubusercontent.com/90909802/232704422-10afeb2f-7f11-47b2-9ca6-60495afcc08c.png)

So in the case of an example student, they were provided with this version of the question: 

![Screenshot 2023-04-18 at 4 43 40 pm](https://user-images.githubusercontent.com/90909802/232700193-d6440f50-87bb-4426-9d32-90a118ebd32b.png)

however when their answers for parts 2 and 3 (which seems to be correct) were checked, the response state recognises them as valid, but does not pass them to score: 

![Screenshot 2023-04-18 at 4 41 23 pm](https://user-images.githubusercontent.com/90909802/232700939-18436971-a4e1-4d73-9dc7-24272fa80a34.png)

I have not been able to gain clarity on what the exclamation symbol means (presumably it means null) and replication of the problem has not been consistently observed. In every case I have investigated --- including my own single case of validation for this issue --- the failure to append a grade occurs where at least one part response -- either prt2 or 3 --- in the overall question  does not have a SCORE status listed for the checked answer. It seems that ans2_val and ans3_val are somehow different from the expected inputs required to trigger a score state. 

In investigating this, apart from attempting to replicate,  I came across a number of discussions stemming from https://github.com/maths/moodle-qtype_stack/issues/195 around input states. The best guess I have here is that what we are seeing here must be expected function based on the setup of the question. I would appreciate any pointers or any assistance with this. Thanks in advance. 

Regards,
Alex

[Question 3.xml.zip](https://github.com/maths/moodle-qtype_stack/files/11258337/Question.3.xml.zip)

**Comment by sangwinc** [comment]
Alex,

Thanks for contacting me.  

The ! means the PRT did not execute.  

I can't replicate this problem immediately.  One thought is that the - sign is a unicode symbol.  Is this relayed to issue #868 ?  Is there any way you could check that?

Just as a side note, please add test cases and deployed variants to your questions!
https://docs.stack-assessment.org/en/Authoring/Testing/

Chris

**Comment by alexanderwilliams091** [comment]
Hi Chris,

Thanks for taking the time to respond. In this case, are you suggesting the use of the minus sign in TAns for prt3 is the issue or the student responses including them might be causing issues? 

I looked at #868 and #750 which it refers to but both seem to be related to the handling/validation of zero values, not negative values exactly. Not sure of the association here so if you could clarify what I might best be changing or looking into, I'd appreciate the assistance.

Regards,
Alex

**Comment by sangwinc** [comment]
Is it possible the student's answer contains a unicode character which looks like - but isn't?

Sorry, my mistake above.  The issue is #860 (not 868), and one list of alternatives is here:  https://jkorpela.fi/dashes.html  As you can see there are lots of dashes.  Some software, e.g. Wolfram Alpha, returns expressions with these and not the minus sign we expect.  In the current version, this will not validate.

**Comment by alexanderwilliams091** [comment]
Hi Chris, 

Thanks for the update and corrections. That looks promising.  I am presently attempting to obtain more information if possible around the specifics of the users who attempted this question (e.g what devices used or if answer engines like Wolfram induced the problem). 

I'll update accordingly when I find out more. 

Thanks,
Alex

**Comment by alexanderwilliams091** [comment]
Hi Chris, 

I am informed that the users in this case did not use mobile devices or Wolfram Alpha. These tests were conducted in a first year physics lab, on iMac devices with the Moodle Safe Exam Browser enabled. All other websites and browsers were blocked from use. 

Thanks,
Alex

**Comment by sangwinc** [comment]
@alexanderwilliams091 I'm really sorry we didn't get to the bottom of this issue.  I'm reviewing old/stale issues.  I'm going to close this issue today.  If the problem reoccurs, please open a new issue and we will investigate further.
