### ISSUE TITLE
Convenience functions for working with GeoGebra

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#944]
When using the new geogebra input type the point inputs return a Maxima list, e.g. `[1.23,-0.32]`.  We need some convenience functions for question authors.  For example, we need a "distance" function, for example `distance(A,B)` which measures the distance between A and B.  Yes, such functions are relatively trivial Maxima code, but it would be helpful to have these as core supported features so question authors can author/think in terms of mathematical properties (distance between) and not always in code (`sqrt((A[0]-B[0])^2+A[1]-B[1])^2)`).

What other functions do we need?

**Comment by guidopinkernell** [comment]
angle(A,B,C) would be another...
Actually, we could think of defining functions in STACK along existing GeoGebra functions for measuring (lengths, areas, ...) or other GeoGebra functions. If we do this, could we make sure that we use the same names?

**Comment by sangwinc** [comment]
Using the same names as in GeoGebra is a very suggestion sensible, thanks!

We can also do some calculations in GeoGebra before sending the information back.  That option should also be in considered...

**Comment by aharjula** [comment]
Remember that these are also directly usable for us JSXGraph people. So if points are similar lists in both systems and if we define vectors as lists of points, they will be exactly the same for both systems. So having tools like `distance` ready for use would benefit us all. Also, having a well-defined `angle(A,B,C)` with direction and all predefined would probably cut down the number of implementation bugs significantly. The next step is to have a full Maxima library for turning polygons into areas and checking other properties related to polygons.

**Comment by sangwinc** [comment]
@aharjula, is this an opportunity to develop a template for Maxima functions containing documentation and tests?  If so, and you can provide an example, I'll make a start on the substance of this issue.

**Comment by aharjula** [comment]
Something like this:
```
/**
 * Euclidean distance between points represented as lists.
 * If one of the lists is shorter, assume the same value for missing dimensions.
 *
 * @param[list] v1 list of values 
 * @param[list] v2 list of values
 * @return[scalar expression] the Euclidean distance between two vectors as an expression.
 */
distance(v1,v2) := block([simp,_i],
  simp:true,
  sqrt(apply("+",makelist((v1[_i]-v2[_i])^2,_i,1,min(length(v1),length(v2)))))
)$

s_test_case(simp) := is(sqrt(2) = distance([0,0] , [1,1]))$
s_test_case(simp) := is(1 = distance([0,0] , [1,0]))$
s_test_case(simp) := is(0 = distance([0,0] , [0,0,0,0]))$
s_test_case(simp) := is(sqrt((y_1-y_2)^2+(x_1-x_2)^2) = distance([x_1,y_1], [x_2,y_2]))$
```

Do note that we want our geometry functions to work in mixed 2D-3D cases when working with graph libraries that might use extra dimensions for things and might sometimes return values with those extra dimensions. This is why this works with arbitrary lengths and mixed lengths. It might be necessary to have a dedicated 2D version that would always only use the two first dimensions when working with source materials with excess dimensions on both sides.

Now for more documentation, we might have keywords describing what this is and for what. But I would prefer that this would simply reside in a directory with the name of "geometry". Maybe some crosslinking with keywords to bring up that this is useful for graphing tools.

**Comment by sangwinc** [comment]
We still need to define the angle function in STACK.

**Comment by guidopinkernell** [comment]
For an angle function two cases need to be discussed:

(A) angle(ABC) = 2pi - angle(CBA)

In this case the angle ABC is oriented, commonly counterclockwise.
Values of angles are from [0,2pi].
Geogebra does this, and usually school math does this too.

(B) angle(ABC) = angle(CBA)

In this case the angle is not oriented, values are from [0,pi].
This is - as far as I know - common in mathematics and SI.

For (B), I would suggest using the dotproduct * of vectors.
I.e. for the angle ABC between rays BA and BC define angle(ABC) = arccos((vec(BA)*vec(BC))/(distance(BA)*distance(BC)). This returns a value from [0,pi]

For (A), there could be various ways. Since Geogebra does this it might be worthwhile to have a look at their code.

**Comment by sangwinc** [comment]
GGB code is here, I think, https://github.com/geogebra/geogebra/blob/master/common/src/main/java/org/geogebra/common/kernel/algos/AlgoAnglePoints.java

**Comment by sangwinc** [comment]
Maxima's atan2 function runs from -%pi to %pi, not from 0 to 2*%pi.  I suggest we don't fight against Maxima here!
