### ISSUE TITLE
Feature proposal: teachers specify a predicate for validation

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#945]
Allow teachers to give the name of a maxima "validator" functionfor bespoke validation.  

For example, we could then check a student's answer is a "list of lists", of a "list of equations".

Not sure how this would give meaningful feedback, and especially how such feedback would be localised.....

**Comment by aharjula** [comment]
#870 is my proposition for this. The function returns either `true` for valid or inline-CASText for the error message.
