### ISSUE TITLE
Functions random_subset and random_subset_n forbidden

### ISSUE THREAD

**Issue by AdrianDoM** [maths/moodle-qtype_stack#950]
Hi. Whenever I try to use the Maxima functions `random_subset` or `random_subset_n` provided by STACK in the Question variables section of a question, I get the error `Forbidden function: random_subset_n`. I realise I can avoid these functions by using `rand_selection` instead, but since they are in the docs I thought it was bringing this up.

These functions are documented [here](https://stack-demo.maths.ed.ac.uk/demo/question/type/stack/doc/doc.php/CAS/Random.md).

STACK version: 2023010400

**Comment by sangwinc** [comment]
Sorry about that, and thanks for reporting it. It will be fixed in the next release.
