### ISSUE TITLE
stack_jxg.bind_list_of

### ISSUE THREAD

**Issue by Famondir** [maths/moodle-qtype_stack#951]
Hello all,
we are running STACK-Version 2023010400 and in our documentation there is mentioned the function `stack_jxg.bind_list_of`. Unfortunately I get an error (in the console in developer view) that says there is no such a function. The fuction `stack_jxg.bind_point` works just fine.

Do you have any clue what could be the reason or can you advice me what further information I can provide you / things I could try?

Best regards
Simon

**Comment by sangwinc** [comment]
Very sorry about this.  It will be fixed in the next (imminent) release.
