### ISSUE TITLE
Suppress model answers (feature request)

### ISSUE THREAD

**Issue by hgeorgsch** [maths/moodle-qtype_stack#954]
Using JSXGraph, it is sometimes necessary to insert dummy inputs to share variables between the client-side JS code and server-side STACK.  The only solution we have found is to make student answer fields which are hidden from the student.  They only appear to the student in the feedback giving model answers which are often meaningless.

Is it possible to make the feedback more configurable, and suppress the model answers?  I imagine a simple checkbox for each student input to display/suppress model answer for that field.

**Comment by hgeorgsch** [comment]
It seems that this is configurable in the quiz activity; sorry I missed that before posting. 
I suppose this makes it hard to fix in a question type, even if I find the feedback to be an integral part of question design.

**Comment by timhunt** [comment]
The content of the feedback (if feedback should be visible) is part of the question.

The policy about whether the feedback for this quiz should be visible at this time, is part of the settings for the quiz where the question is used (including the setting How questions behave - and the question behaviour selected there.)

That separation increases the flexibility of the system.

**Comment by sangwinc** [comment]
Have you considered using the input extra option: `hideanswer` which is documented here: https://docs.stack-assessment.org/en/Authoring/Inputs/

**Comment by hgeorgsch** [comment]
Thank you @sangwinc .  That's the option I was looking for, but did not find when searching.

**Comment by sangwinc** [comment]
No problem, it's a very sensible feature request!
