### ISSUE TITLE
Using newer materials on older systems: user left in un-editable state.

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#959]
The AuthOMath branch introduces the "geogebra" block.  When testing 4.4.3 on a dev server with some AuthOMath questions on it, containing "geogebra" blocks, we have an exception thrown on _any_ interaction with a question,

```
Exception - Return value of stack_cas_castext2_special_root::make() must be an instance of stack_cas_castext2_block, instance of stdClass returned

Stack trace:

    line 224 of /question/type/stack/stack/cas/castext2/blocks/root.specialblock.php: TypeError thrown
    line 173 of /question/type/stack/stack/cas/castext2/blocks/root.specialblock.php: call to stack_cas_castext2_special_root::make()
    ...
```

This is because we are trying to create castext with a non-existent block.  It's fine to throw exceptions, but this situation could arise if I send a colleague running an older version a question containing a new feature.  We therefore need an error, not an exception, so the user can at least edit the question and understand why they can't use it!

This exception also halts the bulk-testing script.

I propose we add an "unknown_block" block in this case.  Any castext containing an unknown block will show a dire warning message to users, and the bulk tester can flag "unknown" blocks.  Is this the right way to proceed?

**Comment by sangwinc** [comment]
Suggested fix.
1. Create a new "unknown_block" block.
2. Rather than return `null` here: https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/castext2/block.factory.php#L30 we return the "unknown_block" which contains a reference to the `$type` of (missing) block requested.

**Comment by aharjula** [comment]
Implemented, roughly as suggested. Now it does not say anything when editing. It could give validation messages, but then it would not be possible to save. Feel free to add a wrapper `[[unknown]]` to the output if you feel like it, but to me it seems to make sense to try to output the original block as far as possible. Trying to figure out what to output for the internals of the block is obviously impossible, as we do not have the block so I just placed an error message there. Replicating the original code at that point of logic is also difficult as the original CASText has been processed quite far at the point when the block sees it.

Again one of those cases where warnings, as opposed to errors, make sense.

**Comment by sangwinc** [comment]
Thanks Matti,
I was just trying to write this myself and had written almost identical code!  I'd like this block to always be invalid - leave this with me.

**Comment by aharjula** [comment]
"Always invalid to block saving, but to allow editing", so basically, just return the error message in the `validate()` of the block. No need to do anything at all elsewhere in the block.

**Comment by sangwinc** [comment]
Yes, Matti, that's what my draft code did, based on the comment block.  I'm now struggling getting the error messages into a sensible place.  I'll work on this.

**Comment by sangwinc** [comment]
Thanks for your help @aharjula with this.

This change took me a while to figure out!
https://github.com/maths/moodle-qtype_stack/commit/43073edabcbadb83a2960cb17123bc4a9a545bfe#diff-0b3cb3015c3560e17b7948cb6f2d9821b4a6a68ac9840076624b37a32046a7cfL155-L159

**Comment by aharjula** [comment]
Well, that L155-L159 was an interesting omission. Now we should finally see some errors. Unlike, me you actually remembered that our validation errors are no longer strings, instead they are now objects of a configurable class.
