### ISSUE TITLE
Editing an existing question does not allow new response tree (rpt) -> Exception

### ISSUE THREAD

**Issue by FelixDiLenarda** [maths/moodle-qtype_stack#963]
**Description**: 
Once an existing, already saved question is edited and an attempt is made to add an additional response tree (RPT), Moodle throws an exception:
`Exception - property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given'`

**Stack trace:**

    line 85 of /question/type/stack/stack/prt.class.php: TypeError thrown
    line 85 of /question/type/stack/stack/prt.class.php: call to property_exists()
    line 509 of /question/type/stack/questiontype.php: call to stack_potentialresponse_tree_lite->__construct()
    line 965 of /question/type/questiontypebase.php: call to qtype_stack->initialise_question_instance()
    line 288 of /question/engine/bank.php: call to question_type->make_question()
    line 278 of /question/engine/bank.php: call to question_bank::make_question()
    line 217 of /question/bank/editquestion/question.php: call to question_bank::load_question()

**Reproduction**:

    Create a question with one response tree (rpt1)
    Save the question
    Open the form to edit the question
    Add another response tree (rpt2)
    Try to save the question
    => Exception is thrown

**Comment by sangwinc** [comment]
Thanks for reporting this.  I'm very sorry about that issue.  We fixed this a year ago here
https://github.com/maths/moodle-qtype_stack/blob/master/stack/prt.class.php#L85
I've just tried to recreate the problem and I can't in the latest code.   I think you are using an older version, and you should upgrade.
