### ISSUE TITLE
Exception: Call to a member function is_flat() on null

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#966]
I upgraded to the latest version of STACK, and am now doing the question bulk tests.

In one of my courses, the bulk testing ended with the following exception:

Call to a member function is_flat() on null

What should I do?

STACK version 2023052400

**Comment by sangwinc** [comment]
Please could you email me (1) the whole error message (it has line numbers in the code) and (2) the question .xml which generated it?

**Comment by sangwinc** [comment]
I'd like to fix this in parallel with issue #965 and release a bug-fix version with both issues closed.  Can you help me recreate this one as well please @alcarola ?

**Comment by sangwinc** [comment]
Mikael, (@alcarola) I'm about to push a new version with this fix.  Please could you email me the question which caused this problem?  I'd like to add a unit test as I'm concerned our current test coverage did not spot this problem in advance of the last release.  I'd like to improve our test coverage in this area!

**Comment by sangwinc** [comment]
This is fixed in STACK 4.4.4.

**Comment by alcarola** [comment]
Yes, I would have liked to track down which question it was that caused it, but I could not, because the question bank did not display the questions properly -- see above.

I'll just try git pulling the last version of STACK at some point soon and see if the issue has been fixed.

**Comment by sangwinc** [comment]
Ok, then I really hope we've fixed the issue.  We can't have a user backed into a position of not being able to load a question!
