### ISSUE TITLE
Proposal: Floating Save Button

### ISSUE THREAD

**Issue by m-r-k** [maths/moodle-qtype_stack#967]
I would like to propose an additional floating save button.
This way we avoid the need for the tedious scrolling down, every time you make changes.

**Comment by m-r-k** [comment]
Here is a quick implementation: 1898cdd766abd673f1185280f27dcb883b2eca03

Of course, we still need to discuss on how the button should look like and where exactly it will be placed.

**Comment by m-r-k** [comment]
1. I agree having that for every edit_form would be great.

2. How should the z-index be computed? When I take a look e.g. at the boost theme, I see many hardcoded z-index numbers.

**Comment by sangwinc** [comment]
This is now reported as fixed.  Thanks @m-r-k for suggesting this.
