### ISSUE TITLE
Proposal: Question block: hint

### ISSUE THREAD

**Issue by m-r-k** [maths/moodle-qtype_stack#968]
Some users would like to be able to provide hints in their tasks at the click of a button.
I therefore suggest that we introduce a new question block for hints.
Various implementations are conceivable, I myself once showed one at one of the STACK conferences.

**Comment by m-r-k** [comment]
Here is a sample implementation: bdcd9261d54c7b2e97e18f27ef49436633f84525
I also added some minimal doc.

Some questions about the fact sheets, which are called "hints" in the documentation (Authoring/Fact_sheets/):
* These are just readymade fact sheets, perhaps the heading of the page should be renamed?
* Isn't a fact sheet also a question block and should therefore be moved to the corresponding subfolder?

**Comment by aharjula** [comment]
Well, I do remember stating at some point that mapping the `[[facts:...]]` IO-block to "common strings" would be a nice little training exercise on the way CASText2 is being processed. One might even do it in many ways. The important thing is just to use the logic of the common string block and only pass the key for the language string to the CAS and resolve it only after the processing.

Whether one would change the syntax at all is another matter. After all the CASText2 parser already detects all those input/validation and feedback IO-blocks so no need to turn facts into full blocks if one wants to keep their original syntax.

**Comment by sangwinc** [comment]
Thanks, this is a very nice use of the summary/details tags.  I didn't know you could just style the summary as a button.  That had me fooled for quite a while!  Anyway, I really like this.  I'd like to chat about the style (padding) before we merge this back into the dev branch and close the issue, but we can sort that out in person.
