### ISSUE TITLE
Create `stack_include_contrib()` function to load contributed maxima libraries

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qtype_stack#971]
I propose we have a new `stack_include_contrib()` function to load contributed maxima libraries from
https://github.com/maths/moodle-qtype_stack/tree/master/stack/maxima/contrib

This has a number of advantages

1. It's use is much shorter (and less error prone) than `stack_include()`  Compare
       stack_include("https://raw.githubusercontent.com/maths/moodle-qtype_stack/master/stack/maxima/contrib/validators.mac");
       stack_include_contrib("validators.mac");
2. Site admins are more likely to condone  `stack_include_contrib()` than arbitrary includes.
3. Encourages people to contribute their code in a sensible public place.
4. Links into the sandbox for offline testing.

**Comment by aharjula** [comment]
Makes sense. Some thoughts:
 1. Do we run validation and security checks on these? Or are all things that have ended up as part of the master branch considered safe?
 2. Will this actually load from Github, or will these come from the locally installed version? Number 4. implies local, which is fine and preferred.
 3. This will cause some issues for Maxima images, and including code through actual Maxima `load()` statements (which would be nice) mean that those scripts need to be locally accessible, and Maxima must have the rights to cache the compilation results, which may be a bit of a problem for MeximaPool etc.
 4. Although we might not be using actual `load()` statements, especially if these libraries contain CASText2 or any other compiled features, we really want them to be able to contain those features. On the other hand, these could be compiled during "parser2" style compiling of the core libraries and then use `load()` to be included. For performance reasons, it would be nice to precompile these.
 5. Will there be equivalent CASText `[[include_contrib src="helm-graph.txt"/]]` to share common templates? Or will that go too far and lead to too many conflicts of styles and interests?

**Comment by sangwinc** [comment]
I think we just treat this exactly the same as `stack_include` and load from github.  The only difference is we add a fixed URL.  This means people can push contributions to github, we can review and accept the pull request, and they can use this code immediately in their materials.  No need to update their STACK version.  I'm really trying to make it easier for other people to contribute small improvements, e.g. the "Vector Calculus" materials that Luke pushed today.

No idea about (5) yet!

I'll push a proposal to a branch and you can comment on the specifics!
