### ISSUE TITLE
Change "Question note" 

### ISSUE THREAD

**Issue by m-r-k** [maths/moodle-qtype_stack#973]
Change the type of the input field for the question note from "textarea" to "editor".

**Comment by georgeionutionita** [comment]
That would be indeed helpful.

**Comment by MeikeAkveld** [comment]
I agree, this would be a very useful feature for us to have

**Comment by aharjula** [comment]
My view is as it was [two weeks ago](https://github.com/maths/moodle-qtype_stack/commit/71d0cb9b6d3fdfedd83ade88b2464401a86aa0a3) when this almost happened, but as CPU cycles are not expensive and the price is mainly paid only while deploying it really does not matter. Just do not start attaching pictures to it.

In any case, at least the length of that field should no longer be an issue. Oh, the olden times when you could only have 255 characters in your question note...

**Comment by sangwinc** [comment]
Yes, I'll do this.  It requires a non-trivial database change.  I think it's too close to the release of 4.4.4 to implement that now, as I'd like to keep the "dev" and "master" quite free of irreversible changes to make any (hopefully no) bug-fix releases clean and easy.  This is especially important in 2023 with the move to Moodle 4.x and the other changes there.  

The changes are not difficult. So, it should be in the next major release (Dec 23?).
Chris

**Comment by sangwinc** [comment]
@EJMFarrow Please compare the "questionnote" with the "questiondescription" fields.  We need to add in the counterpart of "questiondescriptionformat" to the "questionnote" throughout, e.g. including the DB 

https://github.com/maths/moodle-qtype_stack/blob/master/db/install.xml#L15

end in the edit form
https://github.com/maths/moodle-qtype_stack/blob/master/edit_stack_form.php#L256

This provide pointers to a previous example.....
https://github.com/maths/moodle-qtype_stack/commit/064a3afd1eb1fd3940d58d72c944b3c3d14b728a

**Comment by aharjula** [comment]
One thing I am starting to worry about is what happens if someone tries to import XML that has been exported in a system running older STACK. Will this explode if the questionnote is not a formatted field in the XML? Will it identify that and know how to read it as default HTML-format or some such?

This might be a major issue as those XMLs are all around in various backups of courses and restoring one after an upgrade to the new format might be somewhat tricky if the thing explodes.

**Comment by sangwinc** [comment]
Thanks @aharjula, yes that's something we need to test for and accommodate.
Chris

**Comment by EJMFarrow** [comment]
Good point. Seems to be fine with Moodle XML files - questionnote defaults to HTML (although I'm not sure why that as opposed to anything else as I've currently got DB defaulting to Moodle format). I will keep checking!

**Comment by EJMFarrow** [comment]
In the changes question note format is set it up to default to the format of the questiontext when importing a question where the format has not been set. Questions already in the DB will default to moodle_auto_format when the STACK update is applied (to match previous format column additions but that does not have to be the case - we could use plain text instead).

**Comment by sangwinc** [comment]
Thanks @EJMFarrow, I've merged your pull request into dev.  One last task before we close this issue.

Please would you add a unit test of an _old_ .xml file (without the new file format) being imported?   Either a behat test, or a straight unit test.  That way we might see in the future if imports throw an error or a note.

**Comment by EJMFarrow** [comment]
I've added in a test loading an old XML question to xml_import.feature (in with the other Behat additions I've been doing). https://github.com/maths/moodle-qtype_stack/pull/1163
