### ISSUE TITLE
"found TIMEDOUT" error under Question variables text field when "Save changes and continue editing" clicked during new Question adding process

### ISSUE THREAD

**Issue by otatarintseva** [maths/moodle-qtype_stack#977]
Hi,

I receives the "found TIMEDOUT" error under Question variables text field when "Save changes and continue editing" clicked during new Question adding process.

Additional information:
qtype_stack version is 2023060500
qbehaviour_adaptivemultipart version is 2022092200
qbehaviour_dfexplicitvaildate version is 2022092200
qbehaviour_dfcbmexplicitvaildate version is 2022092200
Moodle version is 2022112802.00 ($release  = '4.1.2 (Build: 20230313)')

Just tried to test the plugin according to this instruction: https://www.youtube.com/watch?v=GyHuD7YQub0
When I click "Save changes and continue editing" first time it focus on Question variables text field and shows the "found" error under it.
Then I try to input "x" for example in this field and click "Save changes and continue editing" again and then it focus on Question variables text field and shows the "found TIMEDOUT" error under it.

**Comment by sangwinc** [comment]
This is almost certainly an installation problem.  If you email me in Edinburgh I'll try to help.  Since this is highly unlikely to be a general plugin problem I'll close this issue.
