### ISSUE TITLE
Logarithms and matrices

### ISSUE THREAD

**Issue by GraphZahlCounts** [maths/moodle-qtype_stack#994]
Hi,

I've got a problem concerning the input of logarithms in a matix of variable size. I ask fo the hessian matrix of a function and if the input type is a fixed matrix, everything is fine, if I switch to a matrix of variable type, which I would really like to do for jacobian matrices, my answer is always invalid. I am not sure if this issue is resolved in a more recent release, we are still running on the january version.

Best regards 
Hendrikje

**Comment by GraphZahlCounts** [comment]
xml-Export:
http://www.mathematik.uni-kassel.de/~heschmpo/

**Comment by sangwinc** [comment]
Very sorry about that.  There will be a fix in the next release.
