### ISSUE TITLE
Validation doesn't accept a correct solution

### ISSUE THREAD

**Issue by mkraska** [maths/moodle-qtype_stack#996]
In the attached question, the validation rejects the correct answer.  There seems to happen some simplification/mess-up before displaying the validation, which turns the expression from a correct one to an incorrect one. Then the validation complains about units not matching.

![image](https://github.com/maths/moodle-qtype_stack/assets/12987918/31d369a7-b5cc-41a2-a6ad-f9deacb2c9f7)

How to reproduce: 

- import the attached question
- open preview
- insert correct solution. Here the above behaviour is observed. 

I'd expect the expression to be displayed as it was input.

[quiz-MMM-TM1 14 05 Welle - Minimum Working Example-20230718-2206.zip](https://github.com/maths/moodle-qtype_stack/files/12088732/quiz-MMM-TM1.14.05.Welle.-.Minimum.Working.Example-20230718-2206.zip)

**Comment by sangwinc** [comment]
The units input makes the assumption that the students' answer is a number with units, rather than a very complex expression.  I haven't downloaded your question (sorry) but that's likely to be the problem.  That's why it is not picking up the units.

**Comment by sangwinc** [comment]
The design goal of the units inputs was to validate an answer of the form number*units.  The answer in your image requires significant reorganisation to get to this form. So I'm not really surprised the input did not accept it.  We could probably improve the docs to make clear what our intentions are.

**Comment by sangwinc** [comment]
I think you are asking for a perfectly reasonable thing here.  However, this just isn't what the current unit input is designed to support.  We could adapt the input, but some people are of course relying on the current behaviour.  I'm open to suggestions for improving the feedback.

**Comment by mkraska** [comment]
I am ok with such restrictions but would expect the validator to reject expressions which don't match the assumptions under which further processing is made. On user level one could forbid + and -. We need to allow for *, / and ^ because we may have compound units in the answer.

An error message of forbidden "-" would clearly say how to fix the situation for the student, while message in the example in the TO post does not.
